#!/bin/bash

# Set the serf name
surfname="installphpmyadmin"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This installs phpMyAdmin at sql.vipURI/DIRECTORY
EOU
)"

# Available flags
optSerf="n:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[n]="Directory"
optDesc[n]="URL folder under sql.vipURI"
optName[u]="Database user"
optDesc[u]="MariaDB boss user; autogenerated if omitted"
optName[p]="Database password"
optDesc[p]="MariaDB password; autogenerated if omitted"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  n)
    isazAZ09lines "${OPTARG}" "${optName[n]}"
    SOn="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-n ${optName[n]}: ${optDesc[n]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

if [ -z "${SOn}" ]; then
  /bin/echo "${optName[n]} option must be set."; inkFail
fi

success_message="phpMyAdmin installed at https://sql.\${vipURI}/${SOn}"
fail_message="phpMyAdmin failed to install."

serfcommand="${Serfs}/${surfname} ${SOn} ${SOu} ${SOp}"

. $InkRun
