#!/bin/bash

# Alias: ink install pw99 → installwinston99
surfname="installwinston99"

. ${InkSet}
. ${iDir}/ink.functions

aboutMsg="$(cat <<EOU
Alias of ink install winston99 (was PinkWrite 99 / pw99)
EOU
)"

optSerf="d:b:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[d]="Domain"
optDesc[d]="The hosted domain or subdomain"
optName[b]="Database"
optDesc[b]="MariaDB database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="MariaDB user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="MariaDB password; autogenerated if omitted"

while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  d) isDomain "${OPTARG}" "${optName[d]}"; SOd="${OPTARG}" ;;
  b) isSQLDatabasename "${OPTARG}" "${optName[b]}"; SOb="${OPTARG}" ;;
  u) isSQLDatabasename "${OPTARG}" "${optName[u]}"; SOu="${OPTARG}" ;;
  p) isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"; SOp="${OPTARG}" ;;
  c) SOcli="true" ;;
  v) SOverbose="true" ;;
  h) SOh="true" ;;
  r) richtext="true" ;;
  *) inkFail ;;
 esac
done

if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}
Use: ink install winston99 -d domain.tld
"
  exit 0
fi
if [ -z "${SOd}" ]; then
  /bin/echo "${optName[d]} option must be set."; inkFail
fi

success_message="Winston 99 installed on ${SOd}. Finish at https://${SOd}/install.php"
fail_message="Winston 99 failed to install on ${SOd}."
serfcommand="${Serfs}/${surfname} ${SOd} ${SOb} ${SOu} ${SOp}"
. $InkRun
