#!/bin/bash

# Set the serf name
surfname="installinkmail"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This installs the Go inkMail control panel on po.emailURI.
Agnostic: Maddy or Postfix via ink mail. Roundcube stays webmail.
EOU
)"

# Available flags
optSerf="p:hrcv"
declare -A optName
declare -A optDesc
optName[p]="Path"
optDesc[p]="URL folder under po.emailURI (autogenerated if omitted)"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  p)
    isazAZ09lines "${OPTARG}" "${optName[p]}"
    SOp="${OPTARG}"
  ;;
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

# Check requirements or defaults
## Help
if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

## Required flags & defaults


# Message prep
success_message="This installs the Go inkMail control panel on po.emailURI."
fail_message="Command failed."

# Prepare command
serfcommand="${Serfs}/${surfname} ${SOp}"

# Run the ink
. $InkRun
