#!/bin/bash

# Set the serf name
surfname="installpdtnews"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This downloads and installs pdt-news as a vapp on a hosted domain
pdt-news resides in www/vapps/pdtnews.DOMAIN.TLD; Nginx proxies to a localhost Go binary
EOU
)"

# Available flags
optSerf="d:b:u:p:m:hrcv"
declare -A optName
declare -A optDesc
optName[d]="Domain"
optDesc[d]="The hosted domain or subdomain to install pdt-news on"
optName[b]="Database"
optDesc[b]="PostgreSQL database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="PostgreSQL user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="PostgreSQL password; autogenerated if omitted"
optName[m]="Mode"
optDesc[m]="single (one blog at the host) or network (paper plus /handle author blogs)"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  d)
    isDomain "${OPTARG}" "${optName[d]}"
    SOd="${OPTARG}"
  ;;
  b)
    isSQLDatabasename "${OPTARG}" "${optName[b]}"
    SOb="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  m)
    isChoice "${OPTARG}" "single network" "${optName[m]}"
    SOm="${OPTARG}"
  ;;
  # Standard flags
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

# Check requirements or defaults
## Help
if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-d ${optName[d]}: ${optDesc[d]}
-m ${optName[m]}: ${optDesc[m]}
-b ${optName[b]}: ${optDesc[b]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

## Required flags & defaults
if [ -z "${SOd}" ]; then
  /bin/echo "${optName[d]} option must be set."; inkFail
fi

# Message prep
success_message="pdt-news installed on ${SOd}. Finish at https://${SOd}/install"
fail_message="pdt-news failed to install on ${SOd}."

# Prepare command (mode is sequential arg 2 so omitted db flags do not steal it)
serfcommand="${Serfs}/${surfname} ${SOd} ${SOm} ${SOb} ${SOu} ${SOp}"

# Run the ink
. $InkRun
