#!/bin/bash

# Alias: ink install pdt → installwinstonpress
surfname="installwinstonpress"

. ${InkSet}
. ${iDir}/ink.functions

aboutMsg="$(cat <<EOU
Alias of ink install winstonpress (was pdt-news)
EOU
)"

optSerf="d:b:u:p:m:hrcv"
declare -A optName
declare -A optDesc
optName[d]="Domain"
optDesc[d]="The hosted domain or subdomain"
optName[b]="Database"
optDesc[b]="PostgreSQL database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="PostgreSQL user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="PostgreSQL password; autogenerated if omitted"
optName[m]="Mode"
optDesc[m]="single or network"

while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  d) isDomain "${OPTARG}" "${optName[d]}"; SOd="${OPTARG}" ;;
  b) isSQLDatabasename "${OPTARG}" "${optName[b]}"; SOb="${OPTARG}" ;;
  u) isSQLDatabasename "${OPTARG}" "${optName[u]}"; SOu="${OPTARG}" ;;
  p) isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"; SOp="${OPTARG}" ;;
  m) isChoice "${OPTARG}" "single network" "${optName[m]}"; SOm="${OPTARG}" ;;
  c) SOcli="true" ;;
  v) SOverbose="true" ;;
  h) SOh="true" ;;
  r) richtext="true" ;;
  *) inkFail ;;
 esac
done

if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}
Use: ink install winstonpress -d domain.tld
"
  exit 0
fi
if [ -z "${SOd}" ]; then
  /bin/echo "${optName[d]} option must be set."; inkFail
fi

success_message="Winston Press installed on ${SOd}. Finish at https://${SOd}/install"
fail_message="Winston Press failed to install on ${SOd}."
serfcommand="${Serfs}/${surfname} ${SOd} ${SOm} ${SOb} ${SOu} ${SOp}"
. $InkRun
