#!/bin/bash

# Set the serf name
surfname="installnextcloud"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This downloads and installs Nextcloud on kit.blueURI (or cloud.blueURI with -s cloud)
EOU
)"

# Available flags
optSerf="s:b:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[s]="Subdomain"
optDesc[s]="kit (default) or cloud"
optName[b]="Database"
optDesc[b]="MariaDB database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="MariaDB user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="MariaDB password; autogenerated if omitted"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  s)
    isChoice "${OPTARG}" "kit cloud" "${optName[s]}"
    SOs="${OPTARG}"
  ;;
  b)
    isSQLDatabasename "${OPTARG}" "${optName[b]}"
    SOb="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-s ${optName[s]}: ${optDesc[s]}
-b ${optName[b]}: ${optDesc[b]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

if [ -z "${SOs}" ]; then
  SOs="kit"
fi

success_message="Nextcloud installed. Finish at https://${SOs}.blueURI/"
fail_message="Nextcloud failed to install."

serfcommand="${Serfs}/${surfname} ${SOs} ${SOb} ${SOu} ${SOp}"

. $InkRun
