#!/bin/bash

# Set the serf name
surfname="installbadad"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This downloads and installs badAd as a vapp on a hosted domain
badAd resides in www/vapps/badad.DOMAIN.TLD; web at DOMAIN, API at api.DOMAIN
EOU
)"

# Available flags
optSerf="d:b:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[d]="Domain"
optDesc[d]="The hosted domain or subdomain to install badAd on"
optName[b]="Database"
optDesc[b]="PostgreSQL database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="PostgreSQL user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="PostgreSQL password; autogenerated if omitted"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  d)
    isDomain "${OPTARG}" "${optName[d]}"
    SOd="${OPTARG}"
  ;;
  b)
    isSQLDatabasename "${OPTARG}" "${optName[b]}"
    SOb="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  # Standard flags
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

# Check requirements or defaults
## Help
if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-d ${optName[d]}: ${optDesc[d]}
-b ${optName[b]}: ${optDesc[b]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

## Required flags & defaults
if [ -z "${SOd}" ]; then
  /bin/echo "${optName[d]} option must be set."; inkFail
fi

# Message prep
success_message="badAd installed on ${SOd}. Open https://${SOd}/ and https://api.${SOd}/"
fail_message="badAd failed to install on ${SOd}."

# Prepare command (sequential args, same as serfs/installbadad)
serfcommand="${Serfs}/${surfname} ${SOd} ${SOb} ${SOu} ${SOp}"

# Run the ink
. $InkRun
