#!/bin/bash

# Set the serf name
surfname="installpw99"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This downloads and installs PinkWrite 99 as a vapp on a hosted domain
PinkWrite 99 resides in www/vapps/pw99.DOMAIN.TLD; front-facing host is 99.DOMAIN.TLD
-d 99.DOMAIN.TLD is the same public host (not 99.99.DOMAIN.TLD)
EOU
)"

# Available flags
optSerf="d:b:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[d]="Domain"
optDesc[d]="The hosted domain or subdomain to install PinkWrite 99 on"
optName[b]="Database"
optDesc[b]="MariaDB database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="MariaDB user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="MariaDB password; autogenerated if omitted"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  d)
    isDomain "${OPTARG}" "${optName[d]}"
    SOd="${OPTARG}"
  ;;
  b)
    isSQLDatabasename "${OPTARG}" "${optName[b]}"
    SOb="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  # Standard flags
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

# Check requirements or defaults
## Help
if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-d ${optName[d]}: ${optDesc[d]}
-b ${optName[b]}: ${optDesc[b]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

## Required flags & defaults
if [ -z "${SOd}" ]; then
  /bin/echo "${optName[d]} option must be set."; inkFail
fi

# Message prep
pw99apex="${SOd}"
[[ "${pw99apex}" == 99.* ]] && pw99apex="${pw99apex#99.}"
success_message="PinkWrite 99 installed on 99.${pw99apex}. Finish at https://99.${pw99apex}/install.php"
fail_message="PinkWrite 99 failed to install on ${SOd}."

# Prepare command (sequential args, same as serfs/installpw99)
serfcommand="${Serfs}/${surfname} ${SOd} ${SOb} ${SOu} ${SOp}"

# Run the ink
. $InkRun
