#!/bin/bash

# Set the serf name
surfname="installsuitecrm"

# Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# About message
aboutMsg="$(cat <<EOU
This downloads and installs SuiteCRM on crm.redURI
EOU
)"

# Available flags
optSerf="b:u:p:hrcv"
declare -A optName
declare -A optDesc
optName[b]="Database"
optDesc[b]="MariaDB database name; autogenerated if omitted"
optName[u]="Database user"
optDesc[u]="MariaDB user; defaults to the database name"
optName[p]="Database password"
optDesc[p]="MariaDB password; autogenerated if omitted"

# Check the variables
while getopts "${optSerf}" Flag; do
 case "${Flag}" in
  b)
    isSQLDatabasename "${OPTARG}" "${optName[b]}"
    SOb="${OPTARG}"
  ;;
  u)
    isSQLDatabasename "${OPTARG}" "${optName[u]}"
    SOu="${OPTARG}"
  ;;
  p)
    isSQLDatabasename "${OPTARG}" "${optName[p]}" "n"
    SOp="${OPTARG}"
  ;;
  c)
    SOcli="true"
  ;;
  v)
    SOverbose="true"
  ;;
  h)
    SOh="true"
  ;;
  r)
    richtext="true"
  ;;
  *)
    inkFail
  ;;
 esac
done

if [ "${SOh}" = "true" ]; then
  /bin/echo "
${aboutMsg}"
  /bin/echo "
Available flags:
-h This help message
-b ${optName[b]}: ${optDesc[b]}
-u ${optName[u]}: ${optDesc[u]}
-p ${optName[p]}: ${optDesc[p]}
"
  exit 0
fi

success_message="SuiteCRM installed. Finish at https://crm.\${redURI}/"
fail_message="SuiteCRM failed to install."

serfcommand="${Serfs}/${surfname} ${SOb} ${SOu} ${SOp}"

. $InkRun
