#!/bin/bash
#inkVerbSerf! verb.ink
# This adds a new domain, complete with OpenDKIM profiles and keys and inkCert Letsencrypt cli-ini entries and Apache/Nginx configs and folders in www/domains that link to www/html
## This also creates a folder for the domain in www/domains which an ftpvip can access
## This also creates an inkDNS zone file, complete with mail records

# How to use:
## ./adddomain [ newdomain.tld ] [ multi/wild - optional for auto-inkCert when ready ]

## Eg:
## ./adddomain inkisaverb.com
## ./adddomain inkisaverb.com multi # automatically run inkcertdole for specified domain only; addsubdomain won't work for this domain after using this option
## ./adddomain inkisaverb.com wild # automatically run inkcertdocb with wildcard certs

usagenotes="This adds a new domain, complete with inkDKIM OpenDKIM profiles and keys, inkDNS DNS zone record, inkCert Letsencrypt cli-ini entries, and Apache/Nginx configs and folders in www/domains/ that link to www/html/"
usageformat="adddomain [ newdomain.tld ] [ auto/wild - optional for auto-inkCert when ready ]"
usageexample="adddomain inkisaverb.com
adddomain inkisaverb.com multi # will automatically run inkcertdole for specified domain only; addsubdomain won't work for this domain after using this option
adddomain inkisaverb.com wild # will automatically run inkcertdocb with wildcard certs"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "Auto-cert" )
vopttypes=( "string_match" )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( newdomainshell ensitenginx ensiteapache )
useconfigs=( inkcertstatus inkdnsconf servermailpath servernameip servertype )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/adddomain.replace" ]; then . /opt/verb/mods/adddomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/adddomain.before" ]; then . /opt/verb/mods/adddomain.before; fi # Precedes this script


# Dependencies same as newdomainshell
if ! /bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if /bin/grep -q 'EmailAllowed="YES"' /opt/verb/conf/servernameip && ! /bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi
if ! /bin/grep -q 'DomHostAllowed="YES"' /opt/verb/conf/servernameip; then
  /usr/bin/echo "Domain hosting not allowed, I quit."; exit 8
fi

# Include settings
. /opt/verb/conf/servernameip
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

newdomain=$1

# Check if it already exists
if [ ${ServerType} = "lemp" ]; then
  if [ -f /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf ]; then
    /opt/verb/serfs/ensitenginx -r ${newdomain}
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
elif [ ${ServerType} = "lamp" ]; then
  if [ -f /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf ]; then
    /opt/verb/serfs/ensiteapache -r ${newdomain}
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
elif [ ${ServerType} = "laemp" ]; then
  if [ -f /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf ]; then
    /opt/verb/serfs/ensitenginx -r ${newdomain}
    siteon=true
  fi
  if [ -f /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf ]; then
    /opt/verb/serfs/ensiteapache -r ${newdomain}
    siteon=true
  fi
  if [ "$siteon" = "true" ]; then
    /bin/echo "Site already exists, server restarted."
    exit 0
  fi
fi

# Check the domain shell
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${newdomain}" ] || [ ! -f "/opt/verb/conf/inkcert/cli-ini/cli.${newdomain}.ini" ]; then
  /bin/echo "The shell for ${newdomain} does not exist yet. Creating it..."
  /opt/verb/serfs/newdomainshell ${newdomain}; wait
fi

# Server config files
## Web directory
if [ ! -d /srv/www/domains/${newdomain} ]; then
  /usr/bin/cp -rf /opt/verb/conf/site-files/newdomain.tld /srv/www/domains/${newdomain}
fi
/bin/ln -sfn /srv/www/domains/${newdomain} /srv/www/html/
/bin/chown -R www:www /srv/www/html/${newdomain}
/bin/chown -R www:www /srv/www/domains/${newdomain}
/bin/chmod -R 750 /srv/www/domains/${newdomain}
## Copy
if [ ${ServerType} = "lemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxdomain.tld.conf /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf
  /bin/sed -i "s/newdomain.tld/${newdomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf
  ## Server
  /opt/verb/serfs/ensitenginx -r ${newdomain}
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf
  /bin/sed -i "s/newdomain.tld/${newdomain}/g" /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${newdomain}
elif [ ${ServerType} = "laemp" ]; then
  /usr/bin/cp /opt/verb/conf/site-files/conf/newdomain.tld.conf /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newrpnginxdomainhttps.tld.conf /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf
  /bin/sed -i "s/newdomain.tld/${newdomain}/g" /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf
  /bin/sed -i "s/newdomain.tld/${newdomain}/g" /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf
  ## Server
  /opt/verb/serfs/ensiteapache -r ${newdomain}
  /opt/verb/serfs/ensitenginx -r ${newdomain}
fi

# Auto-inkCert when DNS is populated?
if [ -n "$2" ] && [ "$2" = "multi" ]; then
  /usr/bin/echo '*/5 * * * * root /opt/verb/donjon/digdomain.sh' "${newdomain} multi" > /etc/cron.d/digdomain-${newdomain}
  /usr/bin/chmod 0644 /etc/cron.d/digdomain-${newdomain}
elif [ -n "$2" ] && [ "$2" = "wild" ]; then
  /usr/bin/echo '*/5 * * * * root /opt/verb/donjon/digdomain.sh' "${newdomain} wild" > /etc/cron.d/digdomain-${newdomain}
  /usr/bin/chmod 0644 /etc/cron.d/digdomain-${newdomain}
fi

# Finish
/bin/echo "Great! With no error messages, you are ready to run inkCert for ${newdomain}, unless you want to add subdomains."




if [ -e "/opt/verb/mods/adddomain.after" ]; then . /opt/verb/mods/adddomain.after; fi # Follows this script
