#!/bin/bash
#inkVerbSerf! verb.ink

# This restores a backup .vbak file from an inkVerb app backed-up using backup

# Prereq: The app may already be installed, but will be totally replaced, no symlink from the html/tld.app folder to the vapps/APP folder is needed

# Instructions:
## The file can have any name, even if you changed it from the original, as long as it ends in .vbak
## The file MUST be uploaded to the "www/vip" folder, which can be done with vsftp installed and an ftpvip

# How to use:
## ./backuprestore [app namespace] [filename]

## This uses the same app namespace as installAPPNAME and vapp.APPNAME configs
## This does not work for ghost sites
## For WordPress installed to a domain, the namespace follows the format: wp-DOMAIN.TLD or wp-SUB.DOMAIN.TLD

# Eg:
## ./backuprestore orangehrm verb.orangehrm.sF52.vbak
## ./backuprestore wp.inkisaverb.com verb.wp.inkisaverb.com.ftU8.vbak


appName=$1
filename=$2

# Include the site config
. /opt/verb/conf/servernameip

# Backup and remove whatever the original status is
if [ -e "/opt/verb/conf/vapps/vapp.${appName}" ]; then
. /opt/verb/conf/vapps/vapp.${appName}
cd /srv/www/vapps/${appName}/ || exit 6
/opt/verb/serfs/mysqlvappex vapp.${appName}; wait
/bin/mv /opt/verb/conf/vapps/vapp.${appName} .
cd /srv/www/vapps/ || exit 6
/opt/verb/serfs/vtxzin ${appName}
/bin/mv ${appName}.txz verb.${appName}.restore-originalbackedup.vbak
/bin/mv verb.${appName}.restore-originalbackedup.vbak /srv/www/vip/
/opt/verb/serfs/mysqlkilldb ${appDBase}; wait
/opt/verb/serfs/mysqlkilluser ${appDDBUsr}; wait
/bin/rm -rf ${appName}
fi

# Unpack the file
cd /srv/www/vip || exit 6
/bin/mv ${filename} ${appName}.txz
/opt/verb/serfs/vtxzout ${appName}; wait
/bin/mv ${appName} /srv/www/vapps/

# Set up the vapp symlink
/opt/verb/serfs/setvapplinkon ${appName}

# Restore and include the app config
/bin/mv /srv/www/vapps/${appName}/vapp.${appName} /opt/verb/conf/vapps/
###DEV one-time migration to Arch
/usr/bin/sed -i "s/APPDBASE/appDBase/g" /opt/verb/conf/vapps/vapp.${appName}
/usr/bin/sed -i "s/APPDDBUSR/appDDBUsr/g" /opt/verb/conf/vapps/vapp.${appName}
/usr/bin/sed -i "s/APPDDBPAS/appDDBPass/g" /opt/verb/conf/vapps/vapp.${appName}
###DEV
. /opt/verb/conf/vapps/vapp.${appName}

# Create the SQL database
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE ${appDBase} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON ${appDBase}.* TO '${appDDBUsr}'@'localhost' IDENTIFIED BY '${appDDBPass}';
FLUSH PRIVILEGES;"

# Restore the database
cd /srv/www/vapps/${appName} || exit 6
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf ${appDBase} < /srv/www/vapps/${appName}/${appDBase}.sql; wait
#/bin/rm -f ${appDBase}.sql
/usr/bin/mv ${appDBase}.sql /srv/vip/sql/ ###DEV one-time migration to Arch
/bin/rm -f /srv/www/vapps/${appName}/servernameip*

# Own
/bin/chown -R www:www /srv/www/vapps/${appName}

# Finish
/bin/echo "${appName} has been restored and all its backup files removed from this server.

A backup of the previous ${appName} on this server has been saved in the vip folder just in case.
"




if [ -e "/opt/verb/mods/backuprestore.after" ]; then . /opt/verb/mods/backuprestore.after; fi # Follows this script
