#!/bin/bash
#inkVerbSerf! verb.ink

# This backs up an installed webapp by exporting the database, app folder, and siteconfig file into one downloadable vbak file in the "vip" folder and symlinked to the main site domain.

# How to use:
## ./backup [ app namespace ] [ securename 0-9, a-z, and A-Z only, optional ] [ -nl for no link, optional dep ]

## This uses the same app namespace as installAPPNAME and vapp.APPNAME configs
## This does not work for ghost sites
## For WordPress installed to a domain, the namespace follows the format: wp-DOMAIN.TLD or wp-SUB.DOMAIN.TLD

# Eg:
## ./backup suitecrm
## ./backup orangehrm 583
## ./backup wp.inkisaverb.com 7aJk -nl
## ./backup wpinkblog b


usagenotes="This backs up an installed webapp by exporting the database, app folder, and siteconfig file into one downloadable vbak file in the \"vip\" folder and symlinked to the main site domain."
usageformat="backup [ app namespace ] [ securename 0-9, a-z, and A-Z only, optional ] [ -nl for no link, optional dep ]"
usageexample="backup suitecrm
backup orangehrm 583
backup wp.inkisaverb.com 7aJk -nl
backup wpinkblog b"
hierarchy=( secondary )
vsetnames=( "App namespace" )
vsettypes=( isazAZ09lines )
voptnames=( "Securename 0-9, a-z, and A-Z only, optional" "-nl for no link, optional dep" )
vopttypes=( isazAZ09lines isazAZ09lines )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( wpvappbackupall )
useserfs=( mysqlvappex vtxzin )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/backup.replace" ]; then . /opt/verb/mods/backup.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/backup.before" ]; then . /opt/verb/mods/backup.before; fi # Precedes this script


appName=$1
if [ -z "$2" ]; then
secName=$(/usr/bin/pwgen -s -1 12)
else
secName=$2
fi

# Check if installed
if [ -z "/opt/verb/conf/vapps/vapp.${appName}" ]; then
/bin/echo "${appName} not installed. Nothing to backup."
exit 0; fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/vapps/vapp.${appName}

# Export the database
cd /srv/www/vapps/${appName}/ || exit 6
/opt/verb/serfs/mysqlvappex vapp.${appName}; wait
/bin/cp /srv/vip/sql/${appDBase}.sql /srv/www/vapps/${appName}/ || exit 4

# Backup the config
/bin/cp /opt/verb/conf/vapps/vapp.${appName} /srv/www/vapps/${appName}/

# Space: include inkDrive /mnt/{h|s}dd trees (du -L). Fail if nothing has room.
. /opt/verb/donjon/vbak.sh
vbakNeed=$(vbak_need_kb "$(vbak_tree_kb /srv/www/vapps/${appName})")
vbakDest=$(vbak_dest "${vbakNeed}")
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Pack onto the dest disk (tar -h follows wp-content bind/symlink as real dirs)
cd /srv/www/vapps || exit 6
/opt/verb/serfs/vtxzin ${appName} "${vbakDest}/verb.${appName}.${secName}.vbak"
e="$?"; [[ "$e" = "0" ]] || exit "$e"
vbak_linkvip "${vbakDest}/verb.${appName}.${secName}.vbak"

# Finish
if [ "$3" = "-nl" ]; then
/bin/echo "${appName} has been backed up to the 'vip' folder.

Note that the app remains live.
"
exit 0
fi

. /opt/verb/donjon/servedl.sh
serveURL=$(servedl_put "/srv/www/vip/verb.${appName}.${secName}.vbak")
/bin/echo "${appName} has been backed up to the 'vip' folder and can also be downloaded at:

${serveURL}

Note that the app remains live.
"




if [ -e "/opt/verb/mods/backup.after" ]; then . /opt/verb/mods/backup.after; fi # Follows this script
