#!/bin/bash
#inkVerbSerf! verb.ink

# This backs up an installed webapp by exporting the database, app folder, and siteconfig file into one downloadable vbak file in the "vip" folder and symlinked to the main site domain.

# How to use:
## ./backup [app namespace] [securename 0-9, a-z, and A-Z only, optional] [-nl for no link, optional dep]

## This uses the same app namespace as installAPPNAME and vapp.APPNAME configs
## This does not work for ghost sites
## For WordPress installed to a domain, the namespace follows the format: wp-DOMAIN.TLD or wp-SUB.DOMAIN.TLD

# Eg:
## ./backup suitecrm
## ./backup orangehrm 583
## ./backup wp.inkisaverb.com 7aJk -nl
## ./backup wpinkblog b


appName=$1
if [ -z "$2" ]; then
SECNAME=$(/usr/bin/pwgen -s -1 12)
else
SECNAME=$2
fi

# Check if installed
if [ -z "/opt/verb/conf/vapp.${appName}" ]; then
/bin/echo "${appName} not installed. Nothing to backup."
exit 0; fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/vapp.${appName}

# Export the database
cd /srv/www/vapps/${appName}/ || exit 6
/opt/verb/serfs/mysqlvappex vapp.${appName}; wait
/bin/cp /srv/vip/sql/${appDBase}.sql /srv/www/vapps/${appName}/ || exit 4

# Backup the config
/bin/cp /opt/verb/conf/vapp.${appName} /srv/www/vapps/${appName}/

# Pack the directory
cd /srv/www/vapps || exit 6
/opt/verb/serfs/vtxzin ${appName}
/bin/mv ${appName}.txz verb.${appName}.${SECNAME}.vbak
/bin/mv verb.${appName}.${SECNAME}.vbak /srv/www/vip/

# Finish
if [ "$3" = "-nl" ]; then
/bin/echo "${appName} has been backed up to the 'vip' folder.

Note that the app remains live.
"
exit 0
fi

/bin/ln -sfn /srv/www/vip/verb.${appName}.${SECNAME}.vbak /srv/www/html/${ServerServeTLD}.serve/${ServerServeDir}/
/bin/chown -R www:www /srv/www/html/${ServerServeTLD}.serve/${ServerServeDir}/verb.${appName}.${SECNAME}.vbak
/bin/echo "${appName} has been backed up to the 'vip' folder and can also be downloaded at:

http://${ServerServePath}/verb.${appName}.${SECNAME}.vbak

Note that the app remains live.
"




if [ -e "/opt/verb/mods/backup.after" ]; then . /opt/verb/mods/backup.after; fi # Follows this script
