#!/bin/bash
#inkVerbSerf! verb.ink

# This backs up the entire email server, including folders and database

# How to use:
## ./backupinkvmail [securename 0-9, a-z, and A-Z only, optional] [-nl for no link, optional dep]

# Eg:
## ./backupinkvmail VERB-NAMESPACE
## ./backupinkvmail 583-NAME
## ./backupinkvmail aF9 -nl

if [ -z "$1" ]; then
secName=$(/usr/bin/pwgen -s -1 12)
else
secName=$1
fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Export the database
cd /srv/vmail || exit 6
/opt/verb/serfs/mysqlex mail; wait

# Copy the config
/bin/cp /opt/verb/conf/servermailpath /srv/vmail/servermailpath-old
/bin/cp /opt/verb/conf/servermailpass /srv/vmail/servermailpass-old
/bin/cp /opt/verb/conf/servernameip /srv/vmail/servernameip-old

# Zip the directory
cd /var || exit 6
/opt/verb/serfs/vtxzin inkvmail
/bin/mv inkvmail.txz verb.inkvmail.${secName}.vbak

# Move to web-download area
/bin/mv /var/verb.inkvmail.${secName}.vbak /srv/www/vip/

if [ "$2" = "-nl" ]; then
/bin/echo "The email server data has been backed up to the 'vip' folder.
Note that the email server remains live."
exit 0
fi

/bin/ln -sfn /srv/www/vip/verb.inkvmail.${secName}.vbak /srv/www/html/${ServerServeTLD}.serve/${ServerServeDir}/
/bin/chown -R www:www /srv/www/html/${ServerServeTLD}.serve/${ServerServeDir}/verb.inkvmail.${secName}.vbak
/bin/echo "The email server data has been backed up to the 'vip' folder and can also be downloaded at

http://${ServerServePath}/verb.inkvmail.${secName}.vbak

Note that the email server remains live.
"




if [ -e "/opt/verb/mods/backupinkvmail.after" ]; then . /opt/verb/mods/backupinkvmail.after; fi # Follows this script
