#!/bin/bash
#inkVerbSerf! verb.ink

# This backs up the installed Nextcloud webapp data folder by exporting the database, and siteconfig file into one downloadable vbak file in the "vip" folder and symlinked to the main site domain.
## This is separate from other backups because Nextcloud's developers make exporting difficult by more or less "welding" the app to the server. But, the export file is also smaller.
## This mainly backs up the user files and database, not the app itself.

# How to use:
## ./backupnextcloud [ securename 0-9, a-z, and A-Z only, optional ] [ -nl for no link, optional dep ]

# Eg:
## ./backupnextcloud 583
## ./backupnextcloud 7aJk -nl
## ./backupnextcloud b


usagenotes="This backs up the installed Nextcloud webapp data folder by exporting the database, and siteconfig file into one downloadable vbak file in the \"vip\" folder and symlinked to the main site domain."
usageformat="backupnextcloud [ securename 0-9, a-z, and A-Z only, optional ] [ -nl for no link, optional dep ]"
usageexample="backupnextcloud 583
backupnextcloud 7aJk -nl
backupnextcloud b"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "Securename 0-9, a-z, and A-Z only, optional" "-nl for no link, optional dep" )
vopttypes=( isazAZ09lines isazAZ09lines )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( mysqlvappex vtxzin )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/backupnextcloud.replace" ]; then . /opt/verb/mods/backupnextcloud.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/backupnextcloud.before" ]; then . /opt/verb/mods/backupnextcloud.before; fi # Precedes this script


if [ -z "$1" ]; then
secName=$(/usr/bin/pwgen -s -1 12)
else
secName=$1
fi

# Check if installed
if [ -z "/opt/verb/conf/vapps/vapp.nextcloud" ]; then
/bin/echo "Nextcloud not installed. Nothing to backup."
exit 0; fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/vapps/vapp.nextcloud

# Export the database
cd /srv/www/vapps/nextcloud/data || exit 6
/opt/verb/serfs/mysqlvappex vapp.nextcloud; wait

# Backup the config
/bin/cp /opt/verb/conf/vapps/vapp.nextcloud /srv/www/vapps/nextcloud/data/

. /opt/verb/donjon/vbak.sh
vbakNeed=$(vbak_need_kb "$(vbak_tree_kb /srv/www/vapps/nextcloud/data)")
vbakDest=$(vbak_dest "${vbakNeed}")
e="$?"; [[ "$e" = "0" ]] || exit "$e"

cd /srv/www/vapps/nextcloud || exit 6
/opt/verb/serfs/vtxzin data "${vbakDest}/verb.nextcloud.${secName}.vbak"
e="$?"; [[ "$e" = "0" ]] || exit "$e"
vbak_linkvip "${vbakDest}/verb.nextcloud.${secName}.vbak"

# Finish
if [ "$2" = "-nl" ]; then
/bin/echo "nextcloud has been backed up to the 'vip' folder.

Note that the app remains live.
"
exit 0
fi

. /opt/verb/donjon/servedl.sh
serveURL=$(servedl_put "/srv/www/vip/verb.nextcloud.${secName}.vbak")
/bin/echo "Nextcloud has been backed up to the 'vip' folder and can also be downloaded at:

${serveURL}

Note that the app remains live.
"




if [ -e "/opt/verb/mods/backupnextcloud.after" ]; then . /opt/verb/mods/backupnextcloud.after; fi # Follows this script
