#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert-Certbot Apache/Nginx credentials for a given domain, including inkVerb namespace domains
## Prerequesite: inkcertreqcb
## This is intended as a subscript of inkcertdocbsingle or to add certs to specific server configs as they are installed after the fact, such as in updates.

# How to use:
## ./inkcertaddcbsingle [ domain.tld or sub.domain.tld ]

# Eg:
## ./inkcertaddcbsingle NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddcbsingle blog.NAME.verb.ink
## ./inkcertaddcbsingle inkisaverb.com
## ./inkcertaddcbsingle sub.inkisaverb.com

usagenotes="This installs inkCert-Certbot Apache/Nginx credentials for a given domain, including inkVerb namespace domains"
usageformat="inkcertaddcbsingle [ domain.tld or sub.domain.tld ] [ DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld ]"
usageexample="inkcertaddcbsingle NAME.verb.ink (will apply ONLY to NAME.verb.ink)
inkcertaddcbsingle blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallcb NAME.verb.ink')
inkcertaddcbsingle blog.NAME.verb.ink NAME.verb.ink
inkcertaddcbsingle inkisaverb.com
inkcertaddcbsingle sub.inkisaverb.com (BAD NEWS: this won't work!! sub.inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallcb inkisaverb.com')
inkcertaddcbsingle sub.inkisaverb.com inkisaverb.com
inkcertaddcbsingle poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)"
hierarchy=( secondary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall inkcertreqcbsingle )
usedby=( inkcertdocbsingle installghostinkblog installghostsite installnextcloud installnextcloudpac )
useserfs=(  )
useconfigs=( servernameip siteurilist servertype inkcertstatus )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddcbsingle.replace" ]; then . /opt/verb/mods/inkcertaddcbsingle.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertaddcbsingle.before" ]; then . /opt/verb/mods/inkcertaddcbsingle.before; fi # Precedes this script


sitedomain=$1

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi


# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -e "/etc/inkcert/le/live/${sitedomain}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${sitedomain}/chain.pem" ] || [ ! -e "/etc/inkcert/le/live/${sitedomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/le/live/${sitedomain}/privkey.pem" ]; then
  if [ "${ServerIPv4}" != "NOIP4" ] && [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="A ${ServerIPv4} and AAAA ${ServerIPv6}"
  ## IP4?
  elif [ "${ServerIPv4}" != "NOIP4" ]; then
    ipAddrBlock="A ${ServerIPv4}"
  ## IP6?
  elif [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="AAAA ${ServerIPv6}"
  fi
/bin/echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${sitedomain} because the ${sitedomain} certs don't exist. Common problems can include:
  - DNS records: ${sitedomain} should point to ${ipAddrBlock}
  - DNS for ${sitedomain} may need a \"wildcard\" * CNAME record that points to ${sitedomain} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqcb
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, inkisaverb.com, etc.
  - The verb/conf/inkcert/cli-ini/ file for ${sitedomain} may not be intended for the domain you are using.
"
exit 8
fi

if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CBSINGLE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=MAIL" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "inkCert certs not needed for mail certs: ${sitedomain}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Check if the certs exist
  if [ ! -e "/etc/inkcert/le/live/${certdomain}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${certdomain}/privkey.pem" ] || [ ! -e "/etc/inkcert/le/live/${certdomain}/chain.pem" ]; then
    /usr/bin/echo "Certs don't exist. I quit."
    exit 8
  fi

  ## Stop Nginx
  /bin/systemctl stop nginx; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CB\n  ssl_certificate\t\/etc\/inkcert\/le\/live\/${sitedomain}\/fullchain\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/le\/live\/${sitedomain}\/privkey\.pem;\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddCB}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddCB=\"NOT_YET\"/FirstInkCertAddCB=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertcble.log

  ## Start Nginx
  /bin/systemctl start nginx; wait

elif [ ${ServerType} = "lamp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CBSINGLE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=MAIL" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "inkCert certs not needed for mail certs: ${sitedomain}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Check if the certs exist
  if [ ! -e "/etc/inkcert/le/live/${certdomain}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${certdomain}/privkey.pem" ] || [ ! -e "/etc/inkcert/le/live/${certdomain}/chain.pem" ]; then
    /usr/bin/echo "Certs don't exist. I quit."
    exit 8
  fi

  ## Stop Apache
  /bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf
  /bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CB\n  SSLCertificateFile\t\/etc\/inkcert\/le\/live\/${sitedomain}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${sitedomain}\/privkey\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${sitedomain}\/chain\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddCB}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddCB=\"NOT_YET\"/FirstInkCertAddCB=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertcble.log

  ## Start Apache
  /bin/systemctl start httpd; wait

fi

# inkCert mail certs
if [ "${certdomain}" = "${nameURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${certdomain} inkvmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
elif [ "${certdomain}" != "${emailURI}" ] && [ "${certdomain}" != "${oneURI}" ] && [ "${certdomain}" != "${inkURI}" ] && [ "${certdomain}" != "${blueURI}" ] && [ "${certdomain}" != "${vipURI}" ] && [ "${certdomain}" != "${kiwiURI}" ] && [ "${certdomain}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${certdomain}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Finish
/bin/echo "
${sitedomain} certs installed.
"




if [ -e "/opt/verb/mods/inkcertaddcbsingle.after" ]; then . /opt/verb/mods/inkcertaddcbsingle.after; fi # Follows this script
