#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert-Letsencrypt Apache/Nginx credentials for a given domain, including inkVerb namespace domains
## Prerequesite: inkcertreqle
## This is intended as a subscript of inkcertdole or to add certs to specific server configs as they are installed after the fact, such as in updates.

# How to use:
## ./inkcertaddle [ domain.tld or sub.domain.tld ] [ DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld ]

# Eg:
## ./inkcertaddle NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddle blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallle NAME.verb.ink')
## ./inkcertaddle blog.NAME.verb.ink NAME.verb.ink
## ./inkcertaddle sub.inkisaverb.com (BAD NEWS: this won't work!! inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallle inkisaverb.com')
## ./inkcertaddle sub.inkisaverb.com inkisaverb.com
## ./inkcertaddle poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)

usagenotes="This installs inkCert-Certbot Apache/Nginx credentials for a given domain, including inkVerb namespace domains"
usageformat="inkcertaddle [ domain.tld or sub.domain.tld ] [ DOMAIN OF CERTIFICATE IF DIFFERENT, ie: domain.tld ]"
usageexample="inkcertaddle NAME.verb.ink (will apply ONLY to NAME.verb.ink)
inkcertaddle blog.NAME.verb.ink (BAD NEWS: this won't work!! blog.NAME.verb.ink does not have a certificate by itself, use: 'inkcertaddallle NAME.verb.ink')
inkcertaddle blog.NAME.verb.ink NAME.verb.ink
inkcertaddle inkisaverb.com
inkcertaddle sub.inkisaverb.com (BAD NEWS: this won't work!! sub.inkisaverb.com does not have a certificate by itself, use: 'inkcertaddallle inkisaverb.com')
inkcertaddle sub.inkisaverb.com inkisaverb.com
inkcertaddle poetryiscode.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)"
hierarchy=( tertiary inkcertdole )	# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall inkcertreqle )
usedby=( inkcertaddallle installghostinkblog installghostsite installnextcloud installnextcloudpac installpfa )
useserfs=(  )
useconfigs=( servernameip siteurilist servertype inkcertstatus )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddle.replace" ]; then . /opt/verb/mods/inkcertaddle.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertaddle.before" ]; then . /opt/verb/mods/inkcertaddle.before; fi # Precedes this script


SITEDOMAIN=$1
CERTDOMAIN=$2

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
CERTDOMAIN=$1
fi

# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -e "/etc/inkcert/le/live/${CERTDOMAIN}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${CERTDOMAIN}/chain.pem" ] || [ ! -e "/etc/inkcert/le/live/${CERTDOMAIN}/fullchain.pem" ] || [ ! -e "/etc/inkcert/le/live/${CERTDOMAIN}/privkey.pem" ]; then
  if [ "${ServerIPv4}" != "NOIP4" ] && [ "${ServerIPv6}" != "NOIP6" ]; then
    IPADDRBLOCK="A ${ServerIPv4} and AAAA ${ServerIPv6}"
  ## IP4?
  elif [ "${ServerIPv4}" != "NOIP4" ]; then
    IPADDRBLOCK="A ${ServerIPv4}"
  ## IP6?
  elif [ "${ServerIPv6}" != "NOIP6" ]; then
    IPADDRBLOCK="AAAA ${ServerIPv6}"
  fi
/bin/echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${SITEDOMAIN} because the ${CERTDOMAIN} certs don't exist. Common problems can include:
  - DNS records: ${SITEDOMAIN} should point to ${IPADDRBLOCK}
  - DNS for ${SITEDOMAIN} may need a \"wildcard\" * CNAME record that points to ${SITEDOMAIN} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqle
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, inkisaverb.com, etc.
  - The verb/conf/inkcert/cli-ini/ file for ${CERTDOMAIN} may not contain the subdomain you are using.
"
exit 8
fi

if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CBSINGLE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Nginx
  /bin/systemctl stop nginx; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_LE\n  ssl_certificate\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/fullchain\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem;\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/nginx/${SITEDOMAIN}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddLE}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddLE=\"NOT_YET\"/FirstInkCertAddLE=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /bin/echo '2 2 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertcble.log

  ## Start Nginx
  /bin/systemctl start nginx; wait

elif [ ${ServerType} = "lamp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Setting inkCert configs for ${SITEDOMAIN}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CBSINGLE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${SITEDOMAIN}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${SITEDOMAIN}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${SITEDOMAIN}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Apache
  /bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf
  /bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_LE\n  SSLCertificateFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/privkey\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${CERTDOMAIN}\/chain\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/httpd/${SITEDOMAIN}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddLE}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddLE=\"NOT_YET\"/FirstInkCertAddLE=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /bin/echo '2 2 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertcble.log

  ## Start Apache
  /bin/systemctl start httpd; wait

fi

# inkCert mail certs
if [ "${CERTDOMAIN}" = "${nameURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${CERTDOMAIN} inkvmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
elif [ "${CERTDOMAIN}" != "${emailURI}" ] && [ "${CERTDOMAIN}" != "${oneURI}" ] && [ "${CERTDOMAIN}" != "${inkURI}" ] && [ "${CERTDOMAIN}" != "${blueURI}" ] && [ "${CERTDOMAIN}" != "${vipURI}" ] && [ "${CERTDOMAIN}" != "${kiwiURI}" ] && [ "${CERTDOMAIN}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${CERTDOMAIN}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Finish
/bin/echo "
${SITEDOMAIN} certs installed.
"




if [ -e "/opt/verb/mods/inkcertaddle.after" ]; then . /opt/verb/mods/inkcertaddle.after; fi # Follows this script
