#!/bin/bash
#inkVerbSerf! verb.ink

# This creates one-time ssl certs for inkCertSC (Self-Cert)
## Prerequesite: inkcertinstallsc
## DEV: This has not been tested and may still need inkcertdosc, inkcertaddsc, inkcdertaddallsc to be written
## DEV: This has not been tested and is useful in theory only, such as for private networks

# How to use:
## ./inkcertsc FULLDOMAIN

# Eg:
## ./inkcertsc inkisaverb.com
## ./inkcertsc somesub.inkisaverb.com


domain="${1}"

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertldstatus
. /opt/verb/conf/inkcertstatus

if [ "${INKCERTSCINSTALLED}" != "DONE" ]; then
/bin/echo "inkCert-SC must be installed first, run: inkcertinstallsc"
exit 0; fi

# CA #

# Create the CA root key
## Note: omitting options like "-aes256" or "-des3" because they instruct openssl to encrypt the key with a passphrase, causing a prompt
cd /etc/inkcert/sc/ca || exit 6
/usr/bin/openssl genrsa -out priv/ca.${domain}.key.pem 4096
/bin/chmod 400 priv/ca.${domain}.key.pem

# CA Subject details:
country="US"
state="Ink"
locality="Cyberspace City"
organization="inkVerb Verber @ ${nameURI}"
organizationalunit="inkCert Self-Cert"
email="certmaster@${nameURI}"
companyname="This is an autocert, not from another company."
commonname="${nameURI}"

# Create the CA root cert
## Note: "-nodes" means there will be no password prompt
cd /etc/inkcert/sc/ca || exit 6
/usr/bin/openssl req -config /opt/verb/conf/inkcert/sc-ca-openssl.cnf \
	-key priv/ca.${domain}.key.pem \
	-new -nodes -x509 -days 3650 -sha256 -extensions v3_ca \
	-out certs/ca.${domain}.cert.pem
	-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email/unstructuredName=$companyname/"
/bin/chmod 444 certs/ca.cert.pem

# Intermediate CA #

# Create the intermediate key
## Note: omitting options like "-aes256" or "-des3" because they instruct openssl to encrypt the key with a passphrase, causing a prompt
cd /etc/inkcert/sc/intrm || exit 6
/usr/bin/openssl genrsa -out priv/intrm.${domain}.key.pem 4096
/bin/chmod 400 priv/intrm.${domain}.key.pem

# Intermediate Subject details:
country="US"
state="Ink"
locality="Cyberspace City"
organization="inkVerb Verber @ ${nameURI}"
organizationalunit="inkCert Self-Cert"
email="certmaster@${nameURI}"
companyname="This is an autocert, not from another company."
commonname="serve.${nameURI}"

# Create the intermediate cert CSR
cd /etc/inkcert/sc/intrm || exit 6
/usr/bin/openssl req -config /opt/verb/conf/inkcert/sc-intrm-openssl.cnf \
	-key priv/intrm.${domain}.key.pem \
	-new -nodes -sha256
	-out csr/intrm.${domain}.csr.pem
	-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email/unstructuredName=$companyname/"

# Sign the intermediate cert
## Note: "CA" & "CAkey" override the "certificate" & "private_key" settings in the .cnf file
cd /etc/inkcert/sc/ca || exit 6
/usr/bin/openssl ca -config /opt/verb/conf/inkcert/sc-ca-openssl.cnf \
	-extensions v3_intermediate_ca \
	-CA /etc/inkcert/sc/ca/certs/ca.${domain}.cert.pem \
	-CAkey /etc/inkcert/sc/ca/priv/ca.${domain}.key.pem \
	-days 3650 -notext -md sha256 \
	-in /etc/inkcert/sc/intrm/csr/intrm.${domain}.csr.pem \
	-out /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem
/bin/chmod 444 /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem

# Verify the signed intermediate cert
/usr/bin/openssl verify -CAfile /etc/inkcert/sc/ca/certs/ca.cert.pem /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem

# Create the intermediate chain
/bin/cat /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem /etc/inkcert/sc/ca/certs/ca.${domain}.cert.pem > /etc/inkcert/sc/intrm/certs/ca-intrm.${domain}.chain.cert.pem
/bin/chmod 444 /etc/inkcert/sc/intrm/certs/ca-intrm.${domain}.chain.cert.pem

# Client #

# Create the client key
## Note: omitting options like "-aes256" or "-des3" because they instruct openssl to encrypt the key with a passphrase, causing a prompt
cd /etc/inkcert/sc/cli || exit 6
/usr/bin/openssl genrsa -out priv/${domain}.key.pem 2048
/bin/chmod 400 priv/${domain}.key.pem

# Client Subject details:
country="US"
state="Ink"
locality="Cyberspace City"
organization="inkVerb Verber @ ${nameURI}"
organizationalunit="inkCert Self-Cert"
email="certmaster@${nameURI}"
companyname="This is an autocert, not from another company."
commonname="${domain}"

# Create the client CSR
cd /etc/inkcert/sc/cli || exit 6
/usr/bin/openssl req -config /opt/verb/conf/inkcert/sc-intrm-openssl.cnf \
	-key priv/cli.${domain}.key.pem \
	-new -sha256 \
	-out csr/cli.${domain}.csr.pem \
	-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email/unstructuredName=$companyname/"

# Sign the client cert
cd /etc/inkcert/sc/intrm || exit 6
/usr/bin/openssl ca -config /opt/verb/conf/inkcert/sc-intrm-openssl.cnf \
	-extensions server_cert \
	-CA /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem \
	-CAkey /etc/inkcert/sc/intrm/priv/intrm.${domain}.key.pem \
	-days 3650 -notext -md sha256 \
	-in /etc/inkcert/sc/cli/csr/cli.${domain}.csr.pem \
	-out /etc/inkcert/sc/cli/certs/cli.${domain}.cert.pem
/bin/chmod 444 /etc/inkcert/sc/cli/certs/cli.${domain}.cert.pem

# Verify the signed intermediate cert
/usr/bin/openssl verify -CAfile /etc/inkcert/sc/intrm/certs/ca-intrm.${domain}.chain.cert.pem /etc/inkcert/sc/cli/certs/cli.${domain}.cert.pem

# Create the full chain (CA - Intrm - Cli)
/bin/cat /etc/inkcert/sc/cli/certs/cli.${domain}.cert.pem /etc/inkcert/sc/intrm/certs/ca-intrm.${domain}.chain.cert.pem > /etc/inkcert/sc/cli/certs/full.${domain}.chain.cert.pem
/bin/chmod 444 /etc/inkcert/sc/cli/certs/full.${domain}.chain.cert.pem

# Delete the roots
/bin/rm /etc/inkcert/sc/ca/priv/ca.${domain}.key.pem
/bin/rm /etc/inkcert/sc/intrm/priv/intrm.${domain}.key.pem
/bin/rm /etc/inkcert/sc/intrm/certs/intrm.${domain}.cert.pem

# Publish the root cert
/bin/mv /etc/inkcert/sc/ca/certs/ca.${domain}.cert.pem /etc/inkcert/sc/rcinst/${domain}.rootcert.pem

# Deploy to the server
/bin/mv /etc/inkcert/sc/intrm/certs/ca-intrm.${domain}.chain.cert.pem /etc/inkcert/sc/pub/${domain}.chain.cert.pem
/bin/mv /etc/inkcert/sc/cli/certs/full.${domain}.chain.cert.pem /etc/inkcert/sc/pub/${domain}.fullchain.cert.pem
/bin/mv /etc/inkcert/sc/cli/certs/cli.${domain}.cert.pem /etc/inkcert/sc/pub/${domain}.cert.pem
/bin/mv /etc/inkcert/sc/cli/priv/cli.${domain}.key.pem /etc/inkcert/sc/keys/${domain}.key.pem
/bin/mkdir -p /etc/inkcert/sc/live/${domain}
/bin/ln -sfn /etc/inkcert/sc/pub/${domain}.fullchain.cert.pem /etc/inkcert/sc/live/${domain}/fullchain.cert.pem
/bin/ln -sfn /etc/inkcert/sc/pub/${domain}.chain.cert.pem /etc/inkcert/sc/live/${domain}/chain.cert.pem
/bin/ln -sfn /etc/inkcert/sc/pub/${domain}.cert.pem /etc/inkcert/sc/live/${domain}/cert.pem
/bin/ln -sfn /etc/inkcert/sc/keys/${domain}.key.pem /etc/inkcert/sc/live/${domain}/key.pem




if [ -e "/opt/verb/mods/inkcertsc.after" ]; then . /opt/verb/mods/inkcertsc.after; fi # Follows this script
