#!/bin/bash
#inkVerbSerf! verb.ink

# This unpacks the certificates from the CA and moves files where they need to go
## The .ict file produced by inkCert's Intermediate CA should be uploaded to /etc/inkcert/req/. Links to this folder are in verb/req and vip/req for convenience.
## In case you did not get your certificate from inkCert, the .ict file contains a DOMAIN folder and it's contents look like this:
### DOMAIN/DOMAIN.cert.pem
### DOMAIN/interm.inkcert.cert.pem
### DOMAIN/ca.inkcert.cert.pem
## (rename CA files to look like this, above, it won't change the CA's information, but will allow the certs to work on the site)
## Only .pem files are acceptable

# How to use:
## ./inkcertaddkeyset [domain.tld] [req.domain.tld.filename.ict]

domain=$1
ICTFILENAME=$2

# Unpack the file
cd /etc/inkcert || exit 6
/bin/mv ${ICTFILENAME} ${domain}.txz
/opt/verb/serfs/vtxzout ${domain}
/bin/mv ${domain} req/

# Move files in place
/bin/mkdir /etc/inkcert/live/${domain}
/bin/cp csr/${domain}/${domain}.key.pem /etc/inkcert/live/${domain}/
/bin/chmod 600 /etc/inkcert/live/${domain}/${domain}.key.pem
/bin/cp req/${domain}/${domain}.cert.pem /etc/inkcert/live/${domain}/
/bin/cp req/${domain}/ca-chain.cert.pem /etc/inkcert/live/${domain}/
shred -f -x req/${domain}/${domain}.cert.pem
shred -f -x req/${domain}/interm.inkcert.cert.pem
shred -f -x req/${domain}/ca.inkcert.cert.pem
shred -f -x req/${domain}/${domain}.chain.pem
shred -f -x csr/${domain}/${domain}.key.pem
/bin/rm -f req/${domain}.csr.pem





if [ -e "/opt/verb/mods/inkcertaddkeyset.after" ]; then . /opt/verb/mods/inkcertaddkeyset.after; fi # Follows this script
