#!/bin/bash
#inkVerbSerf! verb.ink

# This batch runs inkCert-Certbot request and install scripts for a given domain, including inkVerb namespace domains
## It DOES NOT apply to subdomains for that domain, CB is done on a per-domain basis
## Prereqesite: inkcertinstall

# How to use:
## ./inkcertdocb [ domain.tld NO SUBDOMAINS ]

#Eg:
## ./inkcertdocb inkisaverb.com
## ./inkcertdocb inkisaverb.com r
## ./inkcertdocb YOURNAME.verb.blue

usagenotes="This batch runs inkCert-Certbot request and install scripts for a given domain, including inkVerb namespace domains"
usageformat="inkcertdocb [ domain.tld NO SUBDOMAINS ]"
usageexample="inkcertdocb inkisaverb.com
inkcertdocb inkisaverb.com r
inkcertdocb YOURNAME.verb.one"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=( r )
voptflagpurpose=( "Refresh if already done (required for domains with certs already installed)" )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall )
usedby=( inkcertdo-all-verbs inknetmakeca )
useserfs=( inkcertreqcb inkcertaddcb inkcertcheck setinkcertmailcerts )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertdocb.replace" ]; then . /opt/verb/mods/inkcertdocb.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertdocb.before" ]; then . /opt/verb/mods/inkcertdocb.before; fi # Precedes this script


domain=$1

# Refresh option
if [ -n "$2" ] && [ "$2" = "r" ]; then
  suffix=" r"
else
  suffix=""
fi

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z "${1}" ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertreqcb ${domain}${suffix}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Install the certs
if /bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
  if [ -e "/etc/inkcert/le/live/${domain}" ]; then
    /opt/verb/serfs/inkcertaddallcb ${domain}
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
  fi
fi

# Check if installed
/opt/verb/serfs/inkcertcheck ${domain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Domain check for mail certs
. /opt/verb/conf/siteurilist
if [ "${domain}" = "${nameURI}" ]; then
  opt/verb/serfs/setinkcertmailcerts ${domain} inkmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
elif [ "${domain}" != "${emailTLD}" ] && [ "${domain}" != "${hostURI}" ] && [ "${domain}" != "${serveURI}" ] && [ "${domain}" != "${emailTLDURI}" ] && [ "${domain}" != "${emailURI}" ] && [ "${domain}" != "${oneURI}" ] && [ "${domain}" != "${inkURI}" ] && [ "${domain}" != "${blueURI}" ] && [ "${domain}" != "${vipURI}" ] && [ "${domain}" != "${kiwiURI}" ] && [ "${domain}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${domain}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Check if the certs exist
if [ ! -e "/etc/inkcert/le/live/${domain}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${domain}/privkey.pem" ] || [ ! -e "/etc/inkcert/le/live/${domain}/chain.pem" ]; then
  /usr/bin/echo "Certs don't exist. I quit."
  exit 8
fi

# Update the inkCert-DOMAIN config file, fail silently (eg. when used on subdomains)
/bin/sed -i "s/InkCerted=.*/InkCerted=DONE_CB/" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain} 2> /dev/null

# Finish
/bin/echo "
Excellent!

Now, ${domain} and all subdomains are now live with inkCert Letsencrypt certificates.
"




if [ -e "/opt/verb/mods/inkcertdocb.after" ]; then . /opt/verb/mods/inkcertdocb.after; fi # Follows this script
