#!/bin/bash
#inkVerbSerf! verb.ink

# This batch runs a revoke and uninstall of inkCert Self-Cert certs for a domain and replaces the Snakeoil certificate
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertdosc (or both subscripts thereof: inkcertreqsc, inkcertaddsc)

# Dev NOTE:
## The portion of this script that calls the CA to revoke the cert has not been written yet.

# How to use:
## ./inkcertundosc [ domain.tld or sub.domain.tld ]

usagenotes="This batch runs a revoke and uninstall of inkCert Self-Cert certs for a domain and replaces the Snakeoil certificate"
usageformat="inkcertundosc [ domain.tld or sub.domain.tld ]"
usageexample="inkcertundosc inkisaverb.com
inkcertundosc YOURNAME.verb.one
inkcertundosc owncloud.YOURNAME.verb.blue"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( inkcertrevokesc inkcertremovesc )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertundosc.replace" ]; then . /opt/verb/mods/inkcertundosc.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertundosc.before" ]; then . /opt/verb/mods/inkcertundosc.before; fi # Precedes this script


#Eg:
## ./inkcertundosc inkisaverb.com
## ./inkcertundosc YOURNAME.verb.one
## ./inkcertundosc owncloud.YOURNAME.verb.blue


domain=$1

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertrevokesc ${domain}

# Install the certs
/opt/verb/serfs/inkcertremovesc ${domain}

# Remove mail certs
/usr/bin/rm -f /etc/ssl/server/mail/${domain}.crt
/usr/bin/rm -f /etc/ssl/server/mail/${domain}.key




if [ -e "/opt/verb/mods/inkcertundosc.after" ]; then . /opt/verb/mods/inkcertundosc.after; fi # Follows this script
