#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert Self-Cert Apache/Nginx credentials for a given domain, including inkVerb namespace domains
## It applies only to one domain/subdomain at a time
## Prerequesite: inkcertreqsc
## This is intended as a subscript of inkcertdosc
## Nginx (LAEMP/LEMP) or Apache (LAMP) should be stopped before this script and started after, all outside this script
### This script has a failsafe check for status of the Nginx/Apache running status in the event this is run by itself
### The isssue is that we don't want restarts with each subdomain because it causes a "too many restarts" type of systemctl error if it stops and starts with each subdomain when run through inkcertaddall*

# How to use:
## ./inkcertaddsc [ domain.tld or sub.domain.tld ]

usagenotes="This installs inkCert Self-Cert Apache/Nginx credentials for a given domain, including inkVerb namespace domains"
usageformat="inkcertaddsc [ domain.tld or sub.domain.tld ]"
usageexample="inkcertaddsc inkisaverb.com
inkcertaddsc blog.inkisaverb.com inkisaverb.com
inkcertaddsc YOURNAME.verb.one
inkcertaddsc owncloud.YOURNAME.verb.blue
inkcertaddsc smtp.YOURNAME.verb.email"
hierarchy=( tertiary inkcertdosc )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inkcertdosc installampache installghostinkblog installghostsite installnextcloud installorangehrm installowncloud installpydio installsuitecrm )
useserfs=(  )
useconfigs=( servernameip siteurilist servertype inkcertstatus )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddsc.replace" ]; then . /opt/verb/mods/inkcertaddsc.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertaddsc.before" ]; then . /opt/verb/mods/inkcertaddsc.before; fi # Precedes this script


#Eg:
## ./inkcertaddsc inkisaverb.com
## ./inkcertaddsc blog.inkisaverb.com inkisaverb.com
## ./inkcertaddsc YOURNAME.verb.one
## ./inkcertaddsc owncloud.YOURNAME.verb.blue
## ./inkcertaddsc smtp.YOURNAME.verb.email


sitedomain=$1
# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
  certdomain=$1
else
  certdomain=$2
fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
certdomain=$1
fi

# Certs should already be in place from inkcertreq
## This is a test for the inkcert directories:
if [ ! -e "/etc/inkcert/sc/live/${certdomain}/cert.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/chain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/privkey.pem" ]; then
  if [ "${ServerIPv4}" != "NOIP4" ] && [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="A ${ServerIPv4} and AAAA ${ServerIPv6}"
  ## IP4?
  elif [ "${ServerIPv4}" != "NOIP4" ]; then
    ipAddrBlock="A ${ServerIPv4}"
  ## IP6?
  elif [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="AAAA ${ServerIPv6}"
  fi
/bin/echo "Something's wrong...

inkCert certs are not installed. Common problems can include:
  - DNS records: ${sitedomain} should point to ${ipAddrBlock}
  - DNS for ${sitedomain} may need a \"wildcard\" * CNAME record that points to ${sitedomain} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreq
  - Do not run for individual subdomains with a shared certificate, but only for: ${blueURI}, inkisaverb.com, etc.
"
exit 8
fi

if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf" ]; then
    /usr/bin/echo "Site config does not exist."
    exit 0
  fi

  ## Check config status
  if /usr/bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-CBSINGLE: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=MAIL" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /usr/bin/echo "inkCert certs not needed for mail certs: ${sitedomain}. Moving on..."
   exit 0
  else
   /usr/bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Check if the certs exist
  if [ ! -e "/etc/inkcert/sc/live/${certdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/key.pem" ]; then
    /usr/bin/echo "Certs don't exist. I quit."
    exit 8
  fi

  ## Check Nginx status
  if /usr/bin/systemctl is-active --quiet nginx; then
    NginxStatus=true
  fi

  ## Stop Nginx
  [[ -n $NginxStaus ]] && /usr/bin/systemctl stop nginx

  ## Comment the Snakeoil certs
  /usr/bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## Insert the inkCert certs
  /usr/bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_SC\n  ssl_certificate\t\/etc\/inkcert\/sc\/live\/${certdomain}\/fullchain\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/sc\/live\/${certdomain}\/key\.pem;\n\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAdd}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /usr/bin/sed -i "s/FirstInkCertAdd=\"NOT_YET\"/FirstInkCertAdd=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /usr/bin/echo '3 3 * * * root /opt/verb/donjon/inkcert-renew-allsc.sh' > /etc/cron.d/inkcertrenewcronsc
    /usr/bin/chmod 0644 /etc/cron.d/inkcertrenewcronsc
  fi

  ## Create the inkCert log file
  /usr/bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Nginx
  /usr/bin/systemctl start nginx; wait

elif [ ${ServerType} = "lamp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf" ]; then
    /usr/bin/echo "Site config does not exist."
    exit 0
  fi

  ## Check config status
  if /usr/bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-CBSINGLE: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  elif /usr/bin/grep -Fq "#INKVERB-INKCERT=MAIL" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /usr/bin/echo "inkCert certs not needed for mail certs: ${sitedomain}. Moving on..."
   exit 0
  else
   /usr/bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Check if the certs exist
  if [ ! -e "/etc/inkcert/sc/live/${certdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/sc/live/${certdomain}/key.pem" ]; then
    /usr/bin/echo "Certs don't exist. I quit."
    exit 8
  fi

  ## Check Apache status
    if /usr/bin/systemctl is-active --quiet httpd; then
    ApacheStatus=true
  fi

  ## Stop Apache
  [[ -n $ApacheStatus ]] && /usr/bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /usr/bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf
  /usr/bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## Insert the inkCert certs
  /usr/bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_SC\n  SSLCertificateFile\t\/etc\/inkcert\/sc\/live\/${certdomain}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/sc\/live\/${certdomain}\/key\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/sc\/live\/${certdomain}\/chain\.cert\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAdd}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /usr/bin/sed -i "s/FirstInkCertAdd=\"NOT_YET\"/FirstInkCertAdd=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add inkCertLE's auto updater to the cron
    /usr/bin/echo '3 3 * * * root /opt/verb/donjon/inkcert-renew-allsc.sh' > /etc/cron.d/inkcertrenewcronsc
    /usr/bin/chmod 0644 /etc/cron.d/inkcertrenewcronsc
  fi

  ## Create the inkCert log file
  /usr/bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Apache
  [[ -n $ApacheStatus ]] && /usr/bin/systemctl start httpd; wait

fi

# Finish
/bin/echo "
${sitedomain} certs installed.
"




if [ -e "/opt/verb/mods/inkcertaddsc.after" ]; then . /opt/verb/mods/inkcertaddsc.after; fi # Follows this script
