#!/bin/bash
#inkVerbSerf! verb.ink

# This installs inkCert-Certbot Apache/Nginx credentials for a given domain with wildcard subdomains
## Prerequesite: inkcertreqcbsingle
## This is intended as a subscript of inkcertdocbsingle or to add certs to specific server configs as they are installed after the fact, such as in updates.

# How to use:
## ./inkcertaddcb [ domain.tld or sub.domain.tld ] [ DOMAIN OF PARENT, ie: domain.tld ]

# Eg:
## ./inkcertaddcb NAME.verb.ink (will apply ONLY to NAME.verb.ink)
## ./inkcertaddcb inkisaverb.com
## ./inkcertaddcb sub.inkisaverb.com inkisaverb.com (this wildcard feature shouldn't be necessary if used correctly)

usagenotes="This installs inkCert-Certbot Apache/Nginx credentials for a given domain with wildcard subdomains"
usageformat="inkcertaddcb [ domain.tld or sub.domain.tld ] [ DOMAIN OF PARENT, ie: domain.tld ]"
usageexample="inkcertaddcb NAME.verb.ink
inkcertaddcb inkisaverb.com
inkcertaddcb sub.inkisaverb.com inkisaverb.com (this wildcard feature shouldn't be necessary if used correctly)"
hierarchy=( tertiary inkcertdocb )	# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )  # purpose for each optional flag
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall inkcertreqcb )
usedby=( inkcertaddallcb )
useserfs=(  )
useconfigs=( servernameip siteurilist servertype inkcertstatus )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddcb.replace" ]; then . /opt/verb/mods/inkcertaddcb.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertaddcb.before" ]; then . /opt/verb/mods/inkcertaddcb.before; fi # Precedes this script


sitedomain=$1
parentdomain=$2

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/inkcertstatus

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
parentdomain=$1
fi

# Certs should already be in place from inkcertreqle
## This is a test for the inkcert directories:
if [ ! -e "/etc/inkcert/le/live/${parentdomain}/cert.pem" ] || [ ! -e "/etc/inkcert/le/live/${parentdomain}/chain.pem" ] || [ ! -e "/etc/inkcert/le/live/${parentdomain}/fullchain.pem" ] || [ ! -e "/etc/inkcert/le/live/${parentdomain}/privkey.pem" ]; then
  if [ "${ServerIPv4}" != "NOIP4" ] && [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="A ${ServerIPv4} and AAAA ${ServerIPv6}"
  ## IP4?
  elif [ "${ServerIPv4}" != "NOIP4" ]; then
    ipAddrBlock="A ${ServerIPv4}"
  ## IP6?
  elif [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="AAAA ${ServerIPv6}"
  fi
/bin/echo "Something's wrong...

inkCert-Letsencrypt certs were not installed for ${sitedomain} because the ${parentdomain} certs don't exist. Common problems can include:
  - DNS records: ${sitedomain} should point to ${ipAddrBlock}
  - DNS for ${sitedomain} may need a \"wildcard\" * CNAME record that points to ${sitedomain} as the \"hostname\"
  - DNS records can take about 4 hours to have effect
  - You need to first run: inkcertreqcbsingle
  - Do not run inkcertreqle for individual subdomains with a shared certificate, but only for: ${blueURI}, inkisaverb.com, etc.
  - The verb/conf/inkcert/cli-ini/ file for ${parentdomain} may not contain the subdomain you are using.
"
exit 8
fi

if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CBSINGLE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Nginx
  /bin/systemctl stop nginx; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/ssl_certificate/#INKVERB-INKCERT-COMMENT-ssl_certificate/g" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CBSINGLE\n  ssl_certificate\t\/etc\/inkcert\/le\/live\/${parentdomain}\/fullchain\.pem;\n  ssl_certificate_key\t\/etc\/inkcert\/le\/live\/${parentdomain}\/privkey\.pem;\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/nginx/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddCBSINGLE}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddCBSINGLE=\"NOT_YET\"/FirstInkCertAddCBSINGLE=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertle.log

  ## Start Nginx
  /bin/systemctl start nginx; wait

elif [ ${ServerType} = "lamp" ]; then
  ## Check if config file exists
  if [ ! -f "/opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf" ]; then
    /bin/echo "Site config does not exist."
    exit 0
  fi
  ## Check Apache config status
  if /bin/grep -Fq "#INKVERB-INKCERT=INK_NO" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
    /bin/echo "Setting inkCert configs for ${sitedomain}..."
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CBSINGLE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
    /bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
    exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_CB" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-CB: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_LE" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-LE: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=DONE_SC" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "Already certified by inkCert-SC: ${sitedomain}. Moving on..."
   exit 0
  elif /bin/grep -Fq "#INKVERB-INKCERT=NA" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf ; then
   /bin/echo "inkCert certs do not apply here: ${sitedomain}. Moving on..."
   exit 0
  else
   /bin/echo "Something's really wrong with ${sitedomain}. No inkCert, no non-inkCert either. I quit here."
   exit 6
  fi

  ## Stop Apache
  /bin/systemctl stop httpd; wait

  ## Comment the Snakeoil certs
  /bin/sed -i "s/SSLCertificateFile/#INKVERB-INKCERT-COMMENT-SSLCertificateFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf
  /bin/sed -i "s/SSLCertificateKeyFile/#INKVERB-INKCERT-COMMENT-SSLCertificateKeyFile/g" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## Insert the inkCert certs
  /bin/sed -i "s/#INKVERB-INKCERT=INK_.*/#INKVERB-INKCERT=DONE_CBSINGLE\n  SSLCertificateFile\t\/etc\/inkcert\/le\/live\/${parentdomain}\/cert\.pem\n  SSLCertificateKeyFile\t\/etc\/inkcert\/le\/live\/${parentdomain}\/privkey\.pem\n  SSLCertificateChainFile\t\/etc\/inkcert\/le\/live\/${parentdomain}\/chain\.pem\n  #INKVERB-INKCERT-stop/" /opt/verb/conf/webserver/sites-available/httpd/${sitedomain}.conf

  ## inkCert status & exit
  if [ "${FirstInkCertAddCBSINGLE}" = "NOT_YET" ]; then
    ### Config status: first inkCert done
    /bin/sed -i "s/FirstInkCertAddCBSINGLE=\"NOT_YET\"/FirstInkCertAddCBSINGLE=\"DONE\"/g" /opt/verb/conf/inkcertstatus
    ### Create the cron job
    #### Add CB's auto updater to the cron
    /bin/echo '4 4 * * * root /opt/verb/donjon/inkcertcble-renew-all.sh' > /etc/cron.d/inkcertrenewcblecron
    /bin/chmod 0644 /etc/cron.d/inkcertrenewcblecron
  fi

  ## Create the inkCert log file
  /bin/mkdir -p /var/log/inkcert/
  /usr/bin/touch /var/log/inkcert/inkcertcble.log

  ## Start Apache
  /bin/systemctl start httpd; wait

fi

# inkCert mail certs
if [ "${certdomain}" = "${nameURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${certdomain} inkvmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
elif [ "${certdomain}" != "${emailURI}" ] && [ "${certdomain}" != "${oneURI}" ] && [ "${certdomain}" != "${inkURI}" ] && [ "${certdomain}" != "${blueURI}" ] && [ "${certdomain}" != "${vipURI}" ] && [ "${certdomain}" != "${kiwiURI}" ] && [ "${certdomain}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${certdomain}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Finish
/bin/echo "
${sitedomain} certs installed.
"




if [ -e "/opt/verb/mods/inkcertaddcb.after" ]; then . /opt/verb/mods/inkcertaddcb.after; fi # Follows this script
