#!/bin/bash
#inkVerbSerf! verb.ink

# This batch runs inkCert Self-Cert creation and install scripts for a given domain, including inkVerb namespace domains
## It also applies to all subdomains for that domain
## Prereqesite: inkcertinstall

# How to use:
## ./inkcertdosc [domain.tld NO SUBDOMAINS]

#Eg:
## ./inkcertdosc inkisaverb.com
## ./inkcertdosc YOURNAME.verb.blue


DOMAIN=$1

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Request and get the certs
/opt/verb/serfs/inkcertsc ${domain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Install the certs
if /bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
  if [ -e "/etc/inkcert/le/live/${domain}" ]; then
    /opt/verb/serfs/inkcertaddsc ${domain}
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
  fi
fi

# Domain check for mail certs
. /opt/verb/conf/siteurilist
if [ "${domain}" = "${nameURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${domain} inkvmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
elif [ "${domain}" != "${emailTLD}" ] && [ "${domain}" != "${hostURI}" ] && [ "${domain}" != "${serveURI}" ] && [ "${domain}" != "${emailTLDURI}" ] && [ "${domain}" != "${emailURI}" ] && [ "${domain}" != "${oneURI}" ] && [ "${domain}" != "${inkURI}" ] && [ "${domain}" != "${blueURI}" ] && [ "${domain}" != "${vipURI}" ] && [ "${domain}" != "${kiwiURI}" ] && [ "${domain}" != "${redURI}" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${domain}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Update the inkCert-DOMAIN config file, fail silently (eg. when used on subdomains)
/bin/sed -i "s/InkCerted=.*/InkCerted=DONE_SC/" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain} 2> /dev/null

# Finish
/bin/echo "
Excellent!
Verify above exits - IMPORTANT NOTES: ... - Congratulations!

If so, then ${domain} and all subdomains are now live with inkCert Letsencrypt certificates.
"




if [ -e "/opt/verb/mods/inkcertdosc.after" ]; then . /opt/verb/mods/inkcertdosc.after; fi # Follows this script
