#!/bin/bash
#inkVerbSerf! verb.ink

# This runs inkcertaddcb for a domain and all of its subdomains
## Prerequesite: inkcertreqcb

# NOTE: This is intended to be run by inkcertdocbsingle, but can be run separately, such as for updates
# NOTE: If your domain and subdomains have the same certificate then run this only for the main domain

# How to use:
## ./inkcertaddallcb [ domain.tld for root wildcard domain ]

# Eg:
## ./inkcertaddallcb NAME.verb.ink (will apply to all subdomains of NAME.verb.ink)
## ./inkcertaddallcb inkisaverb.com (will apply to all subdomains of inkisaverb.com)

usagenotes="This runs inkcertaddcb for a domain and all of its subdomains"
usageformat="inkcertaddallcb [ domain.tld or sub.domain.tld ] [ DOMAIN OF CERTIFICATE IF PARENT, ie: domain.tld ]"
usageexample="inkcertaddallcb NAME.verb.ink (will apply to all subdomains of NAME.verb.ink)
inkcertaddallcb inkisaverb.com (will apply to all subdomains of inkisaverb.com)
inkcertaddallcb subdomain.inkisaverb.com inkisaverb.com (if the SSL cert for poetryiscode.com is included in the CN of the certificate for inkisaverb.com)"
hierarchy=( tertiary inkcertdocb )	# Choose: primary (works by itself, may use secondaries or tertiaries); secondary (can work by itself, but not normally, may use other secondaries or tertiaries); tertiary (cannot run by itself, must be run by a secondary or primary);oversight (uses primaries)
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "Domain of cert, if different" )
vopttypes=( isDomain )	# Value types for options in # Validity check functions, must be in order of options
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkcertinstall )
prerequesite=( inkcertinstall inkcertreqcb )
usedby=( inkcertdocb )
useserfs=( inkcertaddcb )
useconfigs=(  )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertaddallcb.replace" ]; then . /opt/verb/mods/inkcertaddallcb.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertaddallcb.before" ]; then . /opt/verb/mods/inkcertaddallcb.before; fi # Precedes this script


sitedomain=$1
# Set variable for same certificate as domain (most all scenarios)
if [ -z ${2} ]; then
  certdomain=$1
else
  certdomain=$2
fi

# Include the config
. /opt/verb/conf/servertype

# Check inkCert installed
if [ "${InkCertInstalled}" = "NOT_YET" ]; then
/usr/bin/echo "inkCert not yet installed.

First run inkcertinstall
"
exit 0
fi

# Check variables
if [ -z ${1} ]; then
/bin/echo "You need to specify a domain. Read the instructions."; exit 0
fi

# Stop web server
if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl stop nginx; wait
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/systemctl stop httpd; wait
fi 

# Get each subdomain from the cli-ini file that the domain-subdomain structure was based on from adddomain and newdomainshell
domainlist=$(/usr/bin/grep 'domains = ' /opt/verb/conf/inkcert/cli-ini/cli.${certdomain}.ini | /usr/bin/sed 's/domains = //')
for eachsite in ${domainlist//,/ }; do
## Run inkCertAddCB per site config
 /opt/verb/serfs/inkcertaddcb ${eachsite} ${certdomain}
 e="$?"; [[ "$e" = "0" ]] || exit "$e"
done

# Start web server
if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl start nginx; wait
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/systemctl start httpd; wait
fi 

# Finish
/bin/echo "
Done. ${sitedomain} certs installed for ${sitedomain}.
"




if [ -e "/opt/verb/mods/inkcertaddallcb.after" ]; then . /opt/verb/mods/inkcertaddallcb.after; fi # Follows this script
