#!/bin/bash
#inkVerbSerf! verb.ink

# This communicates with the inkCert CA Inker to send the csr and retrieve the cert package
## This runs a file remotely on the Inker server

# How to use:
## ./inkcertgetcert-verber [ name of info profile ] [ domain ]

# Eg:
## ./inkcertgetcert-verber picprofile poetryiscode.com
## ./inkcertgetcert-verber inkVerbProfile mysub.inkisaverb.com


usagenotes="This communicates with the inkCert CA Inker to send the csr and retrieve the cert package"
usageformat="inkcertgetcert-verber [ name of info profile ] [ domain ]"
usageexample="inkcertgetcert-verber picprofile poetryiscode.com
inkcertgetcert-verber inkVerbProfile mysub.inkisaverb.com"
hierarchy=( primary )
vsetnames=( "File" "Domain" )
vsettypes=( isFilename isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkcertgetcert-verber.replace" ]; then . /opt/verb/mods/inkcertgetcert-verber.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkcertgetcert-verber.before" ]; then . /opt/verb/mods/inkcertgetcert-verber.before; fi # Precedes this script


INFPROFILE=$1
domain=$2

# Verify that the domain is installed
if [ ! -f /opt/verb/conf/inkcert/cli-ini/siteinkcert-${domain} ]; then
/bin/echo "Sorry, Bucko. ${domain} is not installed yet.

Do that first, then get back to me.
"; exit 0
fi

# Verify that the csr exists


# Push the csr to the inkCert server


# Tell the inkCert Server to do its job
# inkNet run on Inker: verber-inkcertreceivecsr





if [ -e "/opt/verb/mods/inkcertgetcert-verber.after" ]; then . /opt/verb/mods/inkcertgetcert-verber.after; fi # Follows this script
