#!/bin/bash
#inkVerbKnight! verb.ink

# This checks whether a domain points to this server and returns STDOUT regardless, but with exit 4 if it does not
## This is intended to check DNS nameserver readiness for installing inkCert SSL certs for a hosted domain
## Any new system or domain recently added with adddomain will set a cron task with this to loop this command until ready, then automatically run inkCert

# How to use:
## ./inkdnsdig [ domain.tld ] [ mail - option to only for mail domains (smtp, imap, pop3, mail) ]

# Eg:
## ./inkdnsdig inkisaverb.com
## ./inkdnsdig v.inkisaverb.com
## ./inkdnsdig inkisaverb.com mail

usagenotes="This checks whether a domain points to this server and returns STDOUT regardless, but with exit 4 if it does not"
usageformat="inkdnsdig [ domain.tld ] [ mail - option to only for mail domains (smtp, imap, pop3, mail) ]"
usageexample="inkdnsdig inkisaverb.com
inkdnsdig v.inkisaverb.com
inkdnsdig inkisaverb.com mail"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=( isDomain )
voptnames=( "Check also for mail domains" )
vopttypes=( "string_match" )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsdigverbs "adddomain - via donjon/digdomain.sh" )
useserfs=(  )
useconfigs=( inkdnsconf servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsdig.replace" ]; then . /opt/verb/mods/inkdnsdig.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsdig.before" ]; then . /opt/verb/mods/inkdnsdig.before; fi # Precedes this script


# Config check
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi

# Include the configs
. /opt/verb/conf/inkdnsconf
. /opt/verb/conf/servernameip

# Argument check
if [ -z "$1" ]; then
  /bin/echo "Must specify a domain, I quit."; exit 5
fi

# Don't interrupt
if [ -f "/opt/verb/dig/.digging" ]; then exit 0; fi

# Prep
/usr/bin/mkdir -p /opt/verb/dig
/usr/bin/touch /opt/verb/dig/.digging

# Domain
domain="$1"
output="/opt/verb/dig/digverbs-${domain}-$(date +'%Y-%m-%d_%H:%M:%S')"
outraw="${output}-raw"

# Check for inkCert and OpenDKIM frameworks
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini" ] || [ -d "/etc/opendkim/keys/${domain}" ]; then
  /usr/bin/echo "Domain framework for '${domain}' does not exist! Nothing to do."
  exit 0
fi

# Dig basic domain entries
/usr/bin/dig @${ServerNS1DNS} ${domain} ns | /usr/bin/tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
/usr/bin/dig @${ServerNS1DNS} ${domain} ns | /usr/bin/tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
/usr/bin/dig @${ServerNS1DNS} ${domain} mx | /usr/bin/tee -a ${outraw} | /usr/bin/grep MX | /usr/bin/tee -a ${output} | /usr/bin/grep "mail.${domain}." >> ${output} 2>&1 || ( /usr/bin/echo "No MX record for ${domain}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
/usr/bin/dig @${ServerNS1DNS} inkdkim._domainkey.${outraw} txt | /usr/bin/tee -a ${output} | /usr/bin/grep TXT | /usr/bin/tee -a ${output} | /usr/bin/grep "inkdkim" >> ${output} 2>&1 || ( /usr/bin/echo "No TXT record for DKIM" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1

# Loop through each to-certify domain based on cli-ini files
domains="$(/usr/bin/grep 'domains = ' /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini | /usr/bin/sed 's/domains = //')"
for digdom in ${domains}; do
  digdom="$(/usr/bin/echo ${digdom} | /usr/bin/sed 's/,//')"
  ## dig the domain
  /usr/bin/dig @${ServerNS1DNS} ${digdom} a | /usr/bin/tee -a ${outraw} | /usr/bin/grep A | /usr/bin/tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${digdom} aaaa | /usr/bin/tee -a ${outraw} | /usr/bin/grep AAAA | /usr/bin/tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6}" && /usr/bin/rm -f /opt/verb/dig/.digging && exit 4 ) >> ${output} 2>&1
  ## Verify the server files
  if [ ${ServerType} = "lemp" ]; then
    if [ ! -f /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf ] || [ ! -e /opt/verb/conf/webserver/sites-enabled/nginx/${newdomain}.conf ]; then
      /usr/bin/echo "No site config fils on the server! Something is wrong."
      exit 6
    fi
  elif [ ${ServerType} = "lamp" ]; then
    if [ ! -f /opt/verb/conf/webserver/sites-available/httpd/${newdomain}.conf ] || [ ! -f /opt/verb/conf/webserver/sites-enabled/httpd/${newdomain}.conf ]; then
      /usr/bin/echo "No site config file on the server! Something is wrong."
      exit 6
    fi
  elif [ ${ServerType} = "laemp" ]; then
    if [ ! -f /opt/verb/conf/webserver/sites-available/nginx/${newdomain}.conf ] || [ ! -e /opt/verb/conf/webserver/sites-enabled/nginx/${newdomain}.conf ]; then
      /usr/bin/echo "No site config file on the server! Something is wrong."
      exit 6
    fi
  fi  
done

# Cleanup
/usr/bin/rm -rf /opt/verb/dig

if [ -e "/opt/verb/mods/inkdnsdig.after" ]; then . /opt/verb/mods/inkdnsdig.after; fi # Follows this script
