#!/bin/bash
#inkVerbKnight! verb.ink

# This checks whether a domain points to this server and returns STDOUT regardless, but with exit 4 if it does not
## This is intended to check DNS nameserver readiness for installing inkCert SSL certs for a hosted domain
## Any new system or domain recently added with adddomain will set a cron task with this to loop this command until ready, then automatically run inkCert

# How to use:
## ./inkdnsdig [ domain.tld ] [ mail - option to only for mail domains (smtp, imap, pop3, mail) ]

# Eg:
## ./inkdnsdig inkisaverb.com
## ./inkdnsdig v.inkisaverb.com
## ./inkdnsdig inkisaverb.com mail

usagenotes="This checks whether a domain points to this server and returns STDOUT regardless, but with exit 4 if it does not"
usageformat="inkdnsdig [ domain.tld ] [ mail - option to only for mail domains (smtp, imap, pop3, mail) ]"
usageexample="inkdnsdig inkisaverb.com
inkdnsdig v.inkisaverb.com
inkdnsdig inkisaverb.com mail"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=( isDomain )
voptnames=( "Check also for mail domains" )
vopttypes=( "string_match" )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsdigverbs "adddomain - via donjon/digdomain.sh" )
useserfs=(  )
useconfigs=( inkdnsconf servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsdig.replace" ]; then . /opt/verb/mods/inkdnsdig.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsdig.before" ]; then . /opt/verb/mods/inkdnsdig.before; fi # Precedes this script


# Config check
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi

# Include the configs
. /opt/verb/conf/inkdnsconf
. /opt/verb/conf/servernameip

# Argument check
if [ -z "$1" ]; then
  /bin/echo "Must specify a domain, I quit."; exit 5
fi

# Domain
domain="$1"
output="/opt/verb/dig/digverbs-${domain}-$(date +'%Y-%m-%d_%H:%M:%S')"
outraw="${output}-raw"

# Check mail?
if [ -n "$2" ] && [ "$2" = "mail" ]; then
  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} mx | tee -a ${outraw} | /usr/bin/grep MX | tee -a ${output} | /usr/bin/grep "mail.${domain}." >> ${output} 2>&1 || ( /usr/bin/echo "No MX record for ${domain}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} inkdkim._domainkey.${outraw} txt | tee -a ${output} | /usr/bin/grep TXT | tee -a ${output} | /usr/bin/grep "inkdkim" >> ${output} 2>&1 || ( /usr/bin/echo "No TXT record for DKIM" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} mail.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A mail record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} mail.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA mail record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A smtp record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} smtp.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA smtp record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} imap.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A imap record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} imap.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA imap record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A pop3 record for ${ServerIPv4}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} pop3.${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA pop3 record for ${ServerIPv6}" && exit 4 ) >> ${output} 2>&1
else
  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS1DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS1DNS}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} ns | tee -a ${outraw} | /usr/bin/grep "${ServerNS2DNS}" >> ${output} 2>&1 || ( /usr/bin/echo "No NS record for ${ServerNS2DNS}" && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} a | tee -a ${outraw} | /usr/bin/grep A | tee -a ${output} | /usr/bin/grep "${ServerIPv4}" >> ${output} 2>&1 || ( /usr/bin/echo "No A record for ${ServerIPv4} " && exit 4 ) >> ${output} 2>&1
  /usr/bin/dig @${ServerNS1DNS} ${domain} aaaa | tee -a ${outraw} | /usr/bin/grep AAAA | tee -a ${output} | /usr/bin/grep "${ServerIPv6}" >> ${output} 2>&1 || ( /usr/bin/echo "No AAAA record for ${ServerIPv6} " && exit 4 ) >> ${output} 2>&1
fi


if [ -e "/opt/verb/mods/inkdnsdig.after" ]; then . /opt/verb/mods/inkdnsdig.after; fi # Follows this script
