#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server

# How to use:
## ./inkdnsaddinkdkim [ domain.tld ]

usagenotes="This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server"
usageformat="inkdnsaddinkdkim [ domain.tld ]"
usageexample="inkdnsaddinkdkim inkisaverb.com"
hierarchy=( tertiary adddomain )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=( newinkdkim )
usedby=( newdomainshell installinkvmail )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.replace" ]; then . /opt/verb/mods/inkdnsaddinkdkim.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.before" ]; then . /opt/verb/mods/inkdnsaddinkdkim.before; fi # Precedes this script


DNsdnsDomainAIN="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  ZONEDIR="inkzones"
else
  ZONEDIR="zones"
fi

# Include the configs
. /opt/verb/conf/servernameip

# Check if already added
if /biusr/binn/grep -Fq "; inkDKIM key" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}; then
/usr/bin/echo "The inkDKIM key for ${DNsdnsDomainAIN} has already been added. Use killinkdnsinkdkim to remove it."
exit 0; fi
if /bin/grep -Fq "dkim._domainkey" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}; then
/usr/bin/echo "The ${DNsdnsDomainAIN} zone file seems to have been tampered with. It should say nothing about DKIM keys at this point, but it does. Fix that first."
exit 7; fi

# Echo the key
## Remove any existing entries
/usr/bin/sed -i "/inkdkim\._domainkey/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
/usr/bin/sed -i "/; inkDKIM key ${DNsdnsDomainAIN}/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
/usr/bin/sed -i "/;; End inkDKIM key ${DNsdnsDomainAIN}/d" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
## Add the entry
/usr/bin/echo "; inkDKIM key ${DNsdnsDomainAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
/usr/bin/echo $(/usr/bin/cat /etc/opendkim/keys/${DNsdnsDomainAIN}/inkdkim.txt | /usr/bin/sed -z -E 's/"\s+"//') >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
/usr/bin/echo ";; End inkDKIM key ${DNsdnsDomainAIN}" >> /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}
## Append the domain to the record host name
/usr/bin/sed -i "s/inkdkim\._domainkey/inkdkim\._domainkey\.${DNsdnsDomainAIN}\./" /opt/verb/conf/inkdns/${ZONEDIR}/db.${DNsdnsDomainAIN}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${DNsdnsDomainAIN} verber

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/usr/bin/echo "The inkDKIM key has been added to the ${DNsdnsDomainAIN} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddinkdkim.after" ]; then . /opt/verb/mods/inkdnsaddinkdkim.after; fi # Follows this script
