#!/usr/bin/bash
#inkVerbSerf! verb.ink

# This resets a complete list of local inkDNS domains in the Bind config file: /var/named/named.conf.verb after copying inkDNS db. files to /var/named/zones/db.*

# How to use:
## ./inkdnsrefreshbind

usagenotes="This installs the inkDNS Bind package for managing DNS records on the server"
usageformat="inkdnsrefreshbind"
usageexample="inkdnsrefreshbind"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsadddomain inkdnsaddinkdkim inkdnsaddmail inkdnsaddonesub inkdnsaddslave inkdnsaddsub inkdnsaddvipsub inkdnsinstall inkdnssetns1 inkdnssetns2 killinkdnsdomain killinkdnsinkdkim killinkdnsmail killinkdnsonesub killinkdnsslavedns killinkdnssub killinkdnsvipsub setipv4update setipv6update )
useserfs=(  )
useconfigs=( servernameip siteurilist inkdnsconf )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsrefreshbind.replace" ]; then . /opt/verb/mods/inkdnsrefreshbind.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsrefreshbind.before" ]; then . /opt/verb/mods/inkdnsrefreshbind.before; fi # Precedes this script


# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/inkdnsconf

if [ "${InkDNSStat}" = "INSTALLED" ]; then

  # Stop Bind
  /usr/bin/systemctl stop named

  # Create the directories and configs
  /usr/bin/rm -rf /var/named/zones
  /usr/bin/cp -rf /opt/verb/conf/inkdns/zones /var/named/
  ## Parked domains don't have priority #NOTE: On "proper" Linux distros, an -n option that is needed will exit 1, though on Manjaro it will exit 0; we use `|| true` to ensure we don't get an error code when we don't need one
  [[ -n "$(/usr/bin/ls -A /opt/verb/conf/inkdns/parked/db.* 2> /dev/null)" ]] && /usr/bin/cp -n /opt/verb/conf/inkdns/parked/db.* /var/named/zones/ || true
  [[ -n "$(/usr/bin/ls -A /opt/verb/conf/inkdns/parked/nv.* 2> /dev/null)" ]] && /usr/bin/cp -n /opt/verb/conf/inkdns/parked/nv.* /var/named/zones/ || true
  /usr/bin/cp -f /opt/verb/conf/inkdns/inkzones/db.* /var/named/zones/
  /usr/bin/cp -f /opt/verb/conf/inkdns/inkzones/nv.* /var/named/zones/
  /usr/bin/chown -R root:named /var/named/zones
  /usr/bin/chmod -R 755 /var/named/zones

  # inkDNS domain list file
  /usr/bin/rm -f /var/named/named.conf.verb
  /usr/bin/echo '// inkVerb-inkDNS domain list file, managed automatically, edits will likely be deleted' > /var/named/named.conf.verb
  /usr/bin/chown root:named /var/named/named.conf.verb
  /usr/bin/chmod 644 /var/named/named.conf.verb
  ## TSGI key (for Letsencrypt's' certbot --preferred-challenges=dns)
  /usr/bin/tsig-keygen inkcert >> /var/named/named.conf.verb
  # Refresh global inkDNS rDNS config & zone files
  ## rDNS config
  /usr/bin/rm -f /var/named/named.conf.rdns
  /usr/bin/echo "// Created by inkDNS, managed automatically, edits will likely be deleted
zone \"${ServerARPAIPv6}\" { type master; allow-transfer { ${ServerNS1IPv6}; ${ServerNS1IPv4}; ${ServerNS2IPv6}; ${ServerNS2IPv4}; }; file \"nv.verber\"; allow-query { any; }; };
zone \"${ServerARPAIPv4}\" { type master; allow-transfer { ${ServerNS1IPv6}; ${ServerNS1IPv4}; ${ServerNS2IPv6}; ${ServerNS2IPv4}; }; file \"nv.verber\"; allow-query { any; }; };
" > /var/named/named.conf.rdns
  ### Permissions
  /usr/bin/chown root:named /var/named/named.conf.rdns
  /usr/bin/chmod 644 /var/named/named.conf.rdns
  ## rDNS zone file
  /usr/bin/rm -f /var/named/nv.verber
  /usr/bin/cat <<EOF > /var/named/nv.verber
\$TTL    86400
@		IN  SOA		${ServerNS1DNS}. dns.inkisaverb.com. (
0000000001		; Serial No
10800			; Refresh
3600			; Retry
604800			; Expire
1800 )			; Minimum TTL

; Nameserver Defaults
@		IN  NS		${ServerNS1DNS}.
@		IN  NS		${ServerNS2DNS}.

; Hosted Domains
EOF
  /usr/bin/chown root:named /var/named/nv.verber
  /usr/bin/chmod 644 /var/named/nv.verber
  ## rDNS zone file entries
  cd /var/named/zones/ || exit 6
  for inkZoneDB in db.*; do
    inkZone="$(/usr/bin/echo ${inkZoneDB} | /usr/bin/sed 's/db\.//' )"
    if [ "${inkZone}" = '*' ]; then continue; fi
      # We don't use 'allow-update { none; };' because 'update-policy' will ignore 'allow-update'
      # Only one domain can fit the rDNS PTR record anyway, which should probably be the FQDN, but it just needs to resolve
      /usr/bin/echo "zone \"${inkZone}\" { type master; allow-transfer { ${ServerNS1IPv6}; ${ServerNS1IPv4}; ${ServerNS2IPv6}; ${ServerNS2IPv4}; }; file \"zones/db.${inkZone}\"; update-policy { grant inkcert. name _acme-challenge.${inkZone}. TXT; grant inkcert. name _acme-challenge.*.${inkZone}. TXT; }; };" >> /var/named/named.conf.verb
      #/usr/bin/echo "\$INCLUDE \"/var/named/zones/nv.${inkZone}\";" >> /var/named/nv.verber #DEV at this point of interwebs dev, only one PRT record; we may uncomment this in the future if multiple records are allowed
  done

  ## Slave DNS server?
  if [ -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
    . /opt/verb/conf/inkdns/sdns/dnshost
    ### Create the zone files
    sDNSdateStamp="$(date '+%Y%m%d')"
    sDNSSerialNum="${sDNSdateStamp}00"
    #### DNS
    /usr/bin/rm -f /var/named/db.slavedns
    /usr/bin/cat <<EOF > /var/named/db.slavedns
\$TTL    86400
@		IN  SOA		${DNSSlave}. dns.inkisaverb.com. (
${sDNSSerialNum}		; Serial No
10800			; Refresh
3600			; Retry
604800			; Expire
1800 )			; Minimum TTL

; Nameserver Defaults
@		IN  NS		${ServerNS1DNS}.
@		IN  NS		${ServerNS2DNS}.

; Hosted Domains
EOF
    /usr/bin/chown root:named /var/named/db.slavedns
    /usr/bin/chmod 644 /var/named/db.slavedns
    #### rDNS
    /usr/bin/rm -f /var/named/nv.slavedns
    /usr/bin/cat <<EOF > /var/named/nv.slavedns
; PTR Domain
${ServerARPAIPv4}		IN  PTR  ${DNSSlave}.
${ServerARPAIPv6}		IN  PTR  ${DNSSlave}.
EOF
    /usr/bin/chown root:named /var/named/nv.slavedns
    /usr/bin/chmod 644 /var/named/nv.slavedns
    ### If this is set as the tertiary DNS server
    if [ "${DNSSlave}" = "${ServerNS2DNS}" ]; then
      /usr/bin/echo "zone \"${DNSSlave}\" { type master; allow-transfer { ${ServerNS1IPv6}; ${ServerNS1IPv4}; }; file \"db.slavedns\"; };" >> /var/named/named.conf.verb
    ### If this is set as the secondary DNS server
    elif [ "${DNSSlave}" = "${ServerNS1DNS}" ]; then
      /usr/bin/echo "zone \"${DNSSlave}\" { type master; allow-transfer { ${ServerNS2IPv6}; ${ServerNS2IPv4}; }; file \"db.slavedns\"; };" >> /var/named/named.conf.verb
    ### If this is not set as the secondary or tertiary DNS server
    else
      /usr/bin/echo "zone \"${DNSSlave}\" { type master; allow-transfer { ${ServerNS1IPv6}; ${ServerNS1IPv4}; ${ServerNS2IPv6}; ${ServerNS2IPv4}; }; update-policy { grant inkcert. name _acme-challenge.${inkZone}. TXT; grant inkcert. name _acme-challenge.*.${inkZone}. TXT; }; file \"db.slavedns\"; };" >> /var/named/named.conf.verb
    fi
    /usr/bin/echo "\$INCLUDE \"/var/named/nv.slavedns\";" >> /var/named/nv.verber
    ### Served slave records
    if [ -d "/opt/verb/conf/inkdns/sdns" ] && [ -d "/srv/sns" ]; then
      for snsverber in /srv/sns/*; do
        #### Proper directory structure?
        if [ ! -d "${snsverber}/domains" ]; then continue; fi
        #### rDNS slave listing (host only, which populates individual items through the named interchagne system)
        . "${snsverber}/conf"
        /usr/bin/echo "zone \"${VerbARPAIPv4}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv4.${VerbHostID}.${VerbName}.${VerbTLD}\"; };" >> /var/named/named.conf.rdns
        /usr/bin/echo "zone \"${VerbARPAIPv6}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv6.${VerbHostID}.${VerbName}.${VerbTLD}\"; };" >> /var/named/named.conf.rdns
        #### DNS slave listings in domains/ folder of the served verber in /srv/sns/VERBER
        ##### Parked
        for slv in "${snsverber}/domains/parked/"*; do
          if [ "${slv}" = ${snsverber}/domains/parked/'*' ]; then continue; fi
          sDomain=$(/usr/bin/echo ${slv} | /usr/bin/sed "s:^${snsverber}/domains/parked/::")
          ##### Config for this domain
          . ${slv}
          ##### Validate file properly lists itself?
          if [ ! -f "${snsverber}/domains/parked/${sdnsDomain}" ]; then continue; fi
          #### # Served domains have priority
          if [ -f "${snsverber}/domains/served/${sdnsDomain}" ]; then continue; fi
          ##### No duplicates
          if /usr/bin/grep -q "db.${sdnsDomain}" /var/named/named.conf.verb; then
            /usr/bin/echo "$(date +'%Y-%m-%d %H:%M:%S') - Duplicate ${sdnsDomain} found on ${snsverber}" >> /opt/verb/rinkcon/log/nsduplicates
            continue
          fi
          ##### DNS entry
          /usr/bin/echo "zone \"${sdnsDomain}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"db.${sdnsDomain}\"; };" >> /var/named/named.conf.verb
          ##### rDNS, pointing to PRT records listed in named/nv.verber on the master, but only if grep doesn't find the ARPA IP doesn't already exist
          /usr/bin/grep -q "${sdnsIPv4ARPA}" /var/named/named.conf.rdns || /usr/bin/echo "zone \"${sdnsIPv4ARPA}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv4.${sdnsDomain}\"; };" >> /var/named/named.conf.rdns
          /usr/bin/grep -q "${sdnsIPv6ARPA}" /var/named/named.conf.rdns || /usr/bin/echo "zone \"${sdnsIPv6ARPA}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv6.${sdnsDomain}\"; };" >> /var/named/named.conf.rdns
          ##### Fresh?
          if [ -f "${snsverber}/domains/fresh/.${sDomain}" ]; then
            /usr/bin/rm -f "/var/named/db.${sDomain}"
            /usr/bin/rm -f "${snsverber}/domains/fresh/.${sDomain}"
          fi
        done
        ##### Served
        for slv in "${snsverber}/domains/served/"*; do
          if [ "${slv}" = ${snsverber}/domains/served/'*' ]; then continue; fi
          sDomain=$(/usr/bin/echo ${slv} | /usr/bin/sed "s:^${snsverber}/domains/served/::")
          ##### Config for this domain
          . ${slv}
          ##### Validate file properly lists itself?
          if [ ! -f "${snsverber}/domains/served/${sdnsDomain}" ]; then continue; fi
          ##### No duplicates
          if /usr/bin/grep -q "db.${sdnsDomain}" /var/named/named.conf.verb; then
            /usr/bin/echo "Duplicate ${sdnsDomain} found on ${snsverber}" >> /opt/verb/rinkcon/log/nsduplicates
            continue
          fi
          ##### DNS entry
          /usr/bin/echo "zone \"${sdnsDomain}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"db.${sdnsDomain}\"; };" >> /var/named/named.conf.verb
          ##### rDNS, pointing to PRT records listed in named/nv.verber on the master, but only if grep doesn't find the ARPA IP doesn't already exist
          /usr/bin/grep -q "${sdnsIPv4ARPA}" /var/named/named.conf.rdns || /usr/bin/echo "zone \"${sdnsIPv4ARPA}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv4.${sdnsDomain}\"; };" >> /var/named/named.conf.rdns
          /usr/bin/grep -q "${sdnsIPv6ARPA}" /var/named/named.conf.rdns || /usr/bin/echo "zone \"${sdnsIPv6ARPA}\" { type slave; masters { ${VerbIPv6}; ${VerbIPv4}; }; allow-transfer { none; }; file \"nv6.${sdnsDomain}\"; };" >> /var/named/named.conf.rdns
          ##### Fresh?
          if [ -f "${snsverber}/domains/fresh/.${sDomain}" ]; then
            /usr/bin/rm -f "/var/named/db.${sDomain}"
            /usr/bin/rm -f "${snsverber}/domains/fresh/.${sDomain}"
            echo "deleted ${sDomain} ::"
            ls -l "/var/named/db.${sDomain}"
          fi
        done
        ##### Killed
        if [ -d "${snsverber}/domains/killed/fresh" ]; then
          cd ${snsverber}/domains/killed/fresh
          for sDomain in *; do
            if [ "${sDomain}" = '*' ]; then continue; fi
            /usr/bin/rm -f "/var/named/db.${sDomain}"
            /usr/bin/mv /domains/killed/fresh/${sDomain} /domains/killed/
          done
          cd ..
          /usr/bin/rm -rf ${snsverber}/domains/killed/fresh
        fi
        ## Delete the fresh folder
        #/usr/bin/rm -rf "${snsverber}/domains/fresh"
      done
    fi
  fi # End Slave DNS

  ## Set the new serial (code imported from inkdnsserial)
  ### Create the datestamp
  dateStamp="$(date '+%Y%m%d')"
  ### Set the increment for today
  if [ ! -f "/opt/verb/conf/inkdns/serial" ]; then
    oldSerial="0"
  else
    oldSerial="$(/usr/bin/cat /opt/verb/conf/inkdns/serial)"
  fi
  #### Keep it to two digits
  if [ -z "${oldSerial}" ] || [ "${oldSerial}" = "" ] || [ "${oldSerial}" -gt "98" ]; then
  oldSerial="0"; fi
  #### Keep the digits double
  newSerial=$(expr ${oldSerial} + 1)
  if [ "${newSerial}" -le "9" ]; then
  newSerial="0${newSerial}"; fi
  #### Record the serial
  /usr/bin/echo "${newSerial}" > /opt/verb/conf/inkdns/serial
  ### Create a datestamp-based serial number to the second (how inkVerb does it)
  serialNum="${dateStamp}${newSerial}\t\t; Serial No"
  ### Set it in the file
  /usr/bin/sed -i "/; Serial No/c ${serialNum}" /var/named/nv.verber

  # Restart Bind
  /usr/bin/systemctl start named || /usr/bin/systemctl restart named

else /usr/bin/echo "inkDNS not installed, run inkdnsinstall first."; exit 0
fi




if [ -e "/opt/verb/mods/inkdnsrefreshbind.after" ]; then . /opt/verb/mods/inkdnsrefreshbind.after; fi # Follows this script
