#!/bin/bash
#inkVerbSerf! verb.ink
# This sets a default for installnextcloud to automatically mount the data folder to a mounted drive
## The drive must be added first, if none is specified, then hdd or ssd defaults will be used in that order of preference

# How to use:
## ./inkdrivenc [ on/off ] [ drive name - optional ]

# Eg:
## ./inkdrivenc on myssd
## ./inkdrivenc on
## ./inkdrivenc off


usagenotes="This sets a default for installnextcloud to automatically mount the data folder to a mounted drive"
usageformat="inkdrivenc [ on/off ] [ drive name - optional ]"
usageexample="inkdrivenc on myssd
inkdrivenc on
inkdrivenc off"
hierarchy=( primary )
vsetnames=( "Drive name" "on/off" )
vsettypes=( isChoice isExists )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdriveadd )
usedby=(  )
useserfs=(  )
useconfigs=( inkdrive/inkdriveinfo )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdrivenc.replace" ]; then . /opt/verb/mods/inkdrivenc.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdrivenc.before" ]; then . /opt/verb/mods/inkdrivenc.before; fi # Precedes this script

# Check if installed
if [ ! -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  /usr/bin/echo "inkDrive not installed. Nothing to show."
fi

OnOff="$1"
Mnt="$2"

if [ "${OnOff}" != "on" ] && [ "${OnOff}" != "off" ]; then
  /usr/bin/echo "WP must be set to 'on' or 'off', see usage."
  exit 5
fi

# Config check
if [ ! -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  /usr/bin/echo "No drives installed; do that first."
  exit 8
else
  . /opt/verb/conf/inkdrive/inkdriveinfo
fi

# Defaults (prefer HDD)
Vapp="$1"
if [ -n "$2" ]; then
  Mnt="$2"
elif [ -n "${HDDdefault}" ]; then
  Mnt=${HDDdefault}
elif [ -n "${SSDdefault}" ]; then
  Mnt=${SSDdefault}
else
  /usr/bin/echo "There is no default drive. Something is very wrong."
  exit 6
fi

# Redundancy
if [ -n "${InkDriveNC}" ] && [ "${InkDriveNC}" = "${OnOff}" ]; then
  /usr/bin/echo "Nextcloud inkDrive is already set to '${InkDriveNC}'; nothing to do."
  exit 0
fi

# Setting
if [ "${OnOff}" = "on" ]; then
  OnOff="${Mnt}"
fi

# Check mount
if [ ! -d "/mnt/${Mnt}" ] && [ -n "$2" ]; then
  /usr/bin/echo "That drive is not mounted on the system. Choose a drive that exists."
  echo 8
elif [ ! -d "/mnt/${Mnt}" ]; then
  /usr/bin/echo "Default drive is not mounted. Something is very wrong."
  echo 6
fi

# Set
if [ -n "${InkDriveNC}" ]; then
  /usr/bin/sed -i "s/InkDriveNC=.*/InkDriveNC=\"${OnOff}\"/" /opt/verb/conf/inkdrive/inkdriveinfo
else
  /usr/bin/echo "InkDriveNC=\"${OnOff}\"" >> /opt/verb/conf/inkdrive/inkdriveinfo
fi

# Finish
if [ "$?" = 0 ]; then
  /usr/bin/echo "Automatic inkDrive for Nextcloud is set to '${OnOff}'\""
fi

if [ -e "/opt/verb/mods/inkdrivenc.after" ]; then . /opt/verb/mods/inkdrivenc.after; fi # Follows this script
