#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the mail subdomain A & AAAA records in the inkDNS zone file on the server

# How to use:
## ./inkdnsaddmail [ domain.tld ]
## ./inkdnsaddmail [ domain.tld ] verber

usagenotes="This adds the mail subdomain A & AAAA records in the inkDNS zone file on the server"
usageformat="inkdnsaddmail [ domain.tld ] verber"
usageexample="inkdnsaddmail inkisaverb.com
inkdnsaddmail myself.verb.blue verber"
hierarchy=( tertiary newdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "verber" )
vopttypes=( string_match )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( newdomainshell )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddmail.replace" ]; then . /opt/verb/mods/inkdnsaddmail.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsaddmail.before" ]; then . /opt/verb/mods/inkdnsaddmail.before; fi # Precedes this script


dnsDomain="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  zonedir="inkzones"
else
  zonedir="zones"
fi

# Include the configs
. /opt/verb/conf/servernameip

# Check if already added
if /bin/grep -Fq "; Hostname Mail Record Defaults" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}; then
/bin/echo "Mail Record Defaults already added to ${dnsDomain}. Use killinkdnsmail to remove them."
exit 0; fi

# Echo the records
## db.DOM
/bin/echo "; Hostname Mail Record Defaults
email.${dnsDomain}. IN  CNAME	mail.${dnsDomain}.
${dnsDomain}.       IN  MX 50	mail.${dnsDomain}.
mail.${dnsDomain}.  IN  A    	${ServerIPv4}
smtp.${dnsDomain}.  IN  A    	${ServerIPv4}
imap.${dnsDomain}.  IN  A    	${ServerIPv4}
pop3.${dnsDomain}.  IN  A    	${ServerIPv4}
pop2.${dnsDomain}.  IN  A    	${ServerIPv4}
pop.${dnsDomain}.   IN  A    	${ServerIPv4}
mail.${dnsDomain}.  IN  AAAA 	${ServerIPv6}
smtp.${dnsDomain}.  IN  AAAA 	${ServerIPv6}
imap.${dnsDomain}.  IN  AAAA 	${ServerIPv6}
pop3.${dnsDomain}.  IN  AAAA 	${ServerIPv6}
pop2.${dnsDomain}.  IN  AAAA 	${ServerIPv6}
pop.${dnsDomain}.   IN  AAAA 	${ServerIPv6}
;; End Mail Defaults" >> /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
/bin/sed -i "s/; Text Record Defaults/; Text Record Defaults\n${dnsDomain}.	\tIN  TXT	\t\"v=spf1 a mx a:${dnsDomain} ip4:${ServerIPv4} ip6:${ServerIPv6} -all\"\n_dmarc.${dnsDomain}.	\tIN  TXT	\t\"v=DMABOX1; p=reject; fo=0; aspf=r; adkim=r; pct=100; ri=86400; rua=mailto:dmark@${dnsDomain};\"/" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}

## nv.DOM
/bin/echo "; PTR Hostname Mail Record Defaults
${ServerARPAIPv4}		IN  PTR  mail.${dnsDomain}.
${ServerARPAIPv4}		IN  PTR  smtp.${dnsDomain}.
${ServerARPAIPv4}		IN  PTR  imap.${dnsDomain}.
${ServerARPAIPv4}		IN  PTR  pop3.${dnsDomain}.
${ServerARPAIPv4}		IN  PTR  pop2.${dnsDomain}.
${ServerARPAIPv4}		IN  PTR   pop.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR  mail.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR  smtp.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR  imap.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR  pop3.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR  pop2.${dnsDomain}.
${ServerARPAIPv6}		IN  PTR   pop.${dnsDomain}.
;; End Mail Defaults" >> /opt/verb/conf/inkdns/${zonedir}/nv.${dnsDomain}

# Set the Serial No
if [ "${zonedir}" = "inkzones" ]; then
  /opt/verb/serfs/inkdnsserial ${dnsDomain} verber
elif [ "${zonedir}" = "zones" ]; then
  /opt/verb/serfs/inkdnsserial ${dnsDomain}
fi

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The Mail Record Defaults have been added to the ${dnsDomain} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddmail.after" ]; then . /opt/verb/mods/inkdnsaddmail.after; fi # Follows this script
