#!/bin/bash
#inkVerbSerf! verb.ink

# This sets a new serial number for an existing DNS record in the inkDNS zone file on the server

# How to use:
## ./inkdnsserial [ domain.tld ]
## ./inkdnsserial [ domain.tld ] [ verber|parked - must specify if a verb or parked domain ]

usagenotes="This sets a new serial number for an existing DNS record in the inkDNS zone file on the server"
usageformat="inkdnsserial [ domain.tld ] [ verber|parked - must specify if a verb or parked domain ]"
usageexample="inkdnsserial inkisaverb.com
inkdnsserial myself.verb.blue verber
inkdnsserial parkeddomain.tld parked"
hierarchy=( secondary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "verber" )
vopttypes=( string_match )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( inkdnsinstall inkdnsadddomain inkdnsaddinkdkim inkdnsaddmail inkdnsaddonesub inkdnsaddsub inkdnsaddvipsub inkdnsrefreshbind killinkdnsinkdkim killinkdnsmail killinkdnsonesub killinkdnssub killinkdnsvipsub setserve )
useserfs=(  )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsserial.replace" ]; then . /opt/verb/mods/inkdnsserial.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsserial.before" ]; then . /opt/verb/mods/inkdnsserial.before; fi # Precedes this script


dnsDomain="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  zonedir="inkzones"
elif [ -n $2 ] && [ "$2" = "parked" ]; then
  zonedir="parked"
else
  zonedir="zones"
fi

# Check if the zone file exists
if [ ! -f "/opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}" ]; then
/usr/bin/echo "The domain \"${dnsDomain}\" has no DNS zone file. That comes first."
exit 8; fi

# Set the new serial
## Create the datestamp
datestamp="$(date '+%Y%m%d')"
## Set the increment for today
### Make sure we have a count file
if [ ! -f "/opt/verb/conf/inkdns/serial" ]; then
/usr/bin/echo "0" > /opt/verb/conf/inkdns/serial; fi
oldSerial="$(/bin/cat /opt/verb/conf/inkdns/serial)"
### Keep it to two digits
if [ "${oldSerial}" -gt "98" ]; then
oldSerial="0"; fi
### Keep the digits double
newSerial=$(expr ${oldSerial} + 1)
if [ "${newSerial}" -le "9" ]; then
newSerial="0${newSerial}"; fi
### Record the serial
/usr/bin/echo "${newSerial}" > /opt/verb/conf/inkdns/serial
## Create a datestamp-based serial number to the second (how inkVerb does it)
serno="${datestamp}${newSerial}\t\t; Serial No"
## Set it in the files
/usr/bin/sed -i "/; Serial No/c ${serno}" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"
exit 0



if [ -e "/opt/verb/mods/inkdnsserial.after" ]; then . /opt/verb/mods/inkdnsserial.after; fi # Follows this script
