#!/bin/bash
#inkVerbSerf! verb.ink
#DEV This is depreciated and kept for reference only. It worked once, but is fully achieved with larger implementations in inkdrivemove
# This restores a service directory from an inkDrive mounted with inkdriveadd, such as www/ vmail/ mysql/

# How to use:
## ./inkdrivesvcoff [ service ]

# Eg:
## ./inkdrivesvcoff www
## ./inkdrivesvcoff mysql


usagenotes="This relocates a service directory to an inkDrive mounted with inkdriveadd, such as www/ vmail/ mysql/"
usageformat="inkdrivesvcoff [ service ] [ mount dir - optional ]"
usageexample="inkdrivesvcoff www hdd
inkdrivesvcoff mysql"
hierarchy=( primary )
vsetnames=( "Service name" )
vsettypes=( isChoice )
voptnames=( "Drive name" )
vopttypes=( isExists )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdriveadd )
usedby=(  )
useserfs=(  )
useconfigs=( inkdrive/inkdriveinfo )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdrivesvcoff.replace" ]; then . /opt/verb/mods/inkdrivesvcoff.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdrivesvcoff.before" ]; then . /opt/verb/mods/inkdrivesvcoff.before; fi # Precedes this script

if [ -z "${1}" ]; then
  /usr/bin/echo "Must desegnate a service."
  exit 5
fi

# Config check
if [ ! -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  /usr/bin/echo "No drives installed; do that first."
  exit 8
else
  . /opt/verb/conf/inkdrive/inkdriveinfo
fi

Svc="${1}"

# Service
case $Svc in
  www) SrcPath="/srv/www"; Owner="www:www" ;;
  mysql) SrcPath="/var/lib/mysql"; Owner="mysql:mysql" ;;
  postgres) SrcPath="/var/lib/postgres"; Owner="postgres:postgres" ;;
  vmail) SrcPath="/srv/vmail"; Owner="vmail:vmail" ;;
esac

# Check service is indeed drive hosted and linked
if [ -d "${SrcPath}" ]; then
  /usr/bin/echo "${Svc} is not hosted on a drive, but resides on the verber itself. Nothing to do."
  exit 0
fi

# Drive Origin
driveOrigin="$(/usr/bin/readlink ${SrcPath})"

# Space
SpaceAvail="$(/usr/bin/df -k "/" | /usr/bin/awk 'NR==2 { print $4 }')"
SpaceNeed="$(/usr/bin/du -s "${driveOrigin}" | /usr/bin/awk '{ print $1 }')"
if [ "${SpaceNeed}" -gt "${SpaceAvail}" ]; then
  SpaceAvailH="$(/usr/bin/df -h "/" | /usr/bin/awk 'NR==2 { print $4 }')"
  SpaceNeedH="$(/usr/bin/du -sh "${driveOrigin}" | /usr/bin/awk '{ print $1 }')"
  echo "Not enough space. ${SpaceNeedH} needed, but only ${SpaceAvailH} available."
  exit 4
fi

# Stop services
case $Svc in
  www)
    /usr/bin/systemctl stop php-fpm
    if [ ${ServerType} = "laemp" ]; then
      /usr/bin/systemctl stop nginx httpd
    elif [ ${ServerType} = "lemp" ]; then
      /usr/bin/systemctl stop nginx
    elif [ ${ServerType} = "lamp" ]; then
      /usr/bin/systemctl stop httpd
    fi
  ;;
  mysql) /usr/bin/systemctl stop postfix dovecot mariadb ;;
  postgres) /usr/bin/systemctl stop postgres ;;
  vmail) /usr/bin/systemctl stop postfix dovecot mariadb ;;
esac

# Remove link & relocate
## fstab entry
/usr/bin/sed -i "/ #inkdrive-${Svc}/d" /etc/fstab
## Reload fstab entries
/usr/bin/umount ${SrcPath}
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/systemctl daemon-reload
## Restore original file structure
/usr/bin/rm -f ${SrcPath}
if [ -e "${SrcPath}" ]; then
  /usr/bin/echo "${Svc} could not be properly prepared to relocate. Something is very wrong."
  exit 6
fi
/usr/bin/mv "${driveOrigin}" "${SrcPath}"
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/chown -R ${Owner} "${SrcPath}"
## Conf for vmail
if [ "${Svc}" = "vmail" ]; then
  confOrigin="$(/usr/bin/readlink /opt/verb/conf/servermailpass)"
  /usr/bin/rm -f /opt/verb/conf/servermailpass
  if [ -e "/opt/verb/conf/servermailpass" ]; then
    /usr/bin/echo "${Svc} pass config could not be properly prepared to relocate. Something is very wrong."
    exit 6
  fi
  /usr/bin/mv "${confOrigin}" /opt/verb/conf/servermailpass
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  confOrigin="$(/usr/bin/readlink /opt/verb/conf/servermailpath)"
  /usr/bin/rm -f /opt/verb/conf/servermailpath
  if [ -e "/opt/verb/conf/servermailpath" ]; then
    /usr/bin/echo "${Svc} path config could not be properly prepared to relocate. Something is very wrong."
    exit 6
  fi
  /usr/bin/mv "${confOrigin}" /opt/verb/conf/servermailpath
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  ### Legacy for vmail
  /usr/bin/ln -sfn /srv/vmail /var/vmail
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
## Conf for mysql
elif [ "${Svc}" = "mysql" ]; then
  confOrigin="$(/usr/bin/readlink /opt/verb/conf/sql/mysqlrootpassword)"
  /usr/bin/rm -f /opt/verb/conf/sql/mysqlrootpassword
  if [ -e "/opt/verb/conf/sql/mysqlrootpassword" ]; then
    /usr/bin/echo "${Svc} config could not be properly prepared to relocate. Something is very wrong."
    exit 6
  fi
  /usr/bin/mv "${confOrigin}" /opt/verb/conf/sql/mysqlrootpassword
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
## Conf for postgres
elif [ "${Svc}" = "postgres" ]; then
  confOrigin="$(/usr/bin/readlink /opt/verb/conf/sql/postgresrootpassword)"
  /usr/bin/rm -f /opt/verb/conf/sql/postgresrootpassword
  if [ -e "/opt/verb/conf/sql/postgresrootpassword" ]; then
    /usr/bin/echo "${Svc} config could not be properly prepared to relocate. Something is very wrong."
    exit 6
  fi
  /usr/bin/mv "${confOrigin}" /opt/verb/conf/sql/postgresrootpassword
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
## Conf for www
elif [ "${Svc}" = "www" ]; then
  confOrigin="$(/usr/bin/readlink /opt/verb/conf/vapps)"
  /usr/bin/rm -f /opt/verb/conf/vapps
  if [ -e "/opt/verb/conf/vapps" ]; then
    /usr/bin/echo "${Svc} config could not be properly prepared to relocate. Something is very wrong."
    exit 6
  fi
  /usr/bin/mv "${confOrigin}" /opt/verb/conf/vapps
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Start services
case $Svc in
  www)
    /usr/bin/systemctl start php-fpm
    if [ ${ServerType} = "laemp" ]; then
      /usr/bin/systemctl start nginx httpd
    elif [ ${ServerType} = "lemp" ]; then
      /usr/bin/systemctl start nginx
    elif [ ${ServerType} = "lamp" ]; then
      /usr/bin/systemctl start httpd
    fi
  ;;
  mysql) /usr/bin/systemctl start postfix dovecot mariadb ;;
  postgres) /usr/bin/systemctl start postgres ;;
  vmail) /usr/bin/systemctl start postfix dovecot mariadb ;;
esac

# Finish
if [ -d "${SrcPath}" ]; then
  /usr/bin/echo "${Svc} folder successfully restored to original location."
else
  /usr/bin/echo "${Svc} folder is not where it should be. Something is very wrong."
  exit 6
fi


if [ -e "/opt/verb/mods/inkdrivesvcoff.after" ]; then . /opt/verb/mods/inkdrivesvcoff.after; fi # Follows this script
