#!/bin/bash
#inkVerbSerf! verb.ink

# This adds (or updates) the BIMI TXT record on an existing DNS zone
## Logo lives at https://${emailTLDURI}/domain.tld/bimi.svg
## TXT: default._bimi IN TXT "v=BIMI1; l=https://${emailTLDURI}/domain.tld/bimi.svg;"
## File is /srv/www/email/bimi/domain.tld/bimi.svg (setbimi / updatehtmlverbs)

# How to use:
## ./inkdnsaddbimi [ domain.tld ]
## ./inkdnsaddbimi [ domain.tld ] verber

usagenotes="This adds the BIMI TXT record to an existing DNS zone file on the server"
usageformat="inkdnsaddbimi [ domain.tld ]"
usageexample="inkdnsaddbimi inkisaverb.com
inkdnsaddbimi NAME.verb.email verber"
hierarchy=( tertiary adddomain )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=( "verber" )
vopttypes=( string_match )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=( inkdnsadddomain )
usedby=( newdomainshell setbimi )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddbimi.replace" ]; then . /opt/verb/mods/inkdnsaddbimi.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsaddbimi.before" ]; then . /opt/verb/mods/inkdnsaddbimi.before; fi # Precedes this script


dnsDomain="$1"
if [ -n "$2" ] && [ "$2" = "verber" ]; then
  zonedir="inkzones"
  verberny=" verber"
else
  zonedir="zones"
fi

. /opt/verb/conf/siteurilist
bimiURL="https://${emailTLDURI}/${dnsDomain}/bimi.svg"
txtLine="default._bimi.${dnsDomain}.	IN  TXT	\"v=BIMI1; l=${bimiURL};\""

zonefile="/opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}"
if [ ! -f "${zonefile}" ]; then
  /usr/bin/echo "No zone file for ${dnsDomain}."
  exit 8
fi

# Update an existing record to the emailTLDURI URL
if /usr/bin/grep -Fq "; BIMI ${dnsDomain}" "${zonefile}"; then
  /usr/bin/sed -i "s|default._bimi.${dnsDomain}.*|${txtLine}|" "${zonefile}"
  /opt/verb/serfs/inkdnsserial ${dnsDomain}${verberny}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  if [ -f "/opt/verb/conf/inkdnsconf" ]; then
    . /opt/verb/conf/inkdnsconf
    if [ "${InkDNSStat}" = "INSTALLED" ]; then
      /opt/verb/serfs/inkdnsrefreshbind
      e="$?"; [[ "$e" = "0" ]] || exit "$e"
    fi
  fi
  /usr/bin/echo "The BIMI record for ${dnsDomain} was updated to ${bimiURL}."
  if [ -e "/opt/verb/mods/inkdnsaddbimi.after" ]; then . /opt/verb/mods/inkdnsaddbimi.after; fi
  exit 0
fi
if /bin/grep -Fq "default._bimi" "${zonefile}"; then
  /usr/bin/echo "The ${dnsDomain} zone file already mentions BIMI. Fix that first or use killinkdnsbimi."
  exit 7
fi

# Add the entry
/usr/bin/echo "; BIMI ${dnsDomain}" >> "${zonefile}"
/usr/bin/echo "${txtLine}" >> "${zonefile}"
/usr/bin/echo ";; End BIMI ${dnsDomain}" >> "${zonefile}"

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${dnsDomain}${verberny}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
    /opt/verb/serfs/inkdnsrefreshbind
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
  fi
fi

# Finish
/usr/bin/echo "The BIMI record has been added to the ${dnsDomain} DNS zone file (${bimiURL})."




if [ -e "/opt/verb/mods/inkdnsaddbimi.after" ]; then . /opt/verb/mods/inkdnsaddbimi.after; fi # Follows this script
