#!/bin/bash
#inkVerbSerf! verb.ink

# This adds a subdomain A & AAAA records to an existing DNS record in the inkDNS zone file on the server
## This automatically detects a parked domain and adds the subdomain there first

# How to use:
## ./inkdnsaddsub [ subdomain ] [ domain.tld ]

usagenotes="This adds a subdomain A & AAAA records to an existing ONE DNS record in the inkDNS zone file on the server; parked domain detection is automatic and given preference"
usageformat="inkdnsaddsub [ subdomain ] [ domain.tld ]"
usageexample="inkdnsaddsub subdomain"
hierarchy=( tertiary addsubdomain )
vsetnames=( "Subdomain" "Domain" )
vsettypes=( isDomainPart isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=(  )
usedby=( addsubdomain )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( inkcertstatus inkdnsconf servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddsub.replace" ]; then . /opt/verb/mods/inkdnsaddsub.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsaddsub.before" ]; then . /opt/verb/mods/inkdnsaddsub.before; fi # Precedes this script


# Dependencies
if ! /bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if /bin/grep -q 'EmailAllowed="YES"' /opt/verb/conf/servernameip && ! /bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath && ! /bin/grep -q 'ServerMailStatus="MADDY_EMAIL_SERVER"' /opt/verb/conf/servermailpath; then
  /usr/bin/echo "Install either Maddy Email or Postfix Vmail first, I quit."; exit 8
fi

dnsSubDom="$1"
dnsDomain="$2"

# Include the configs
. /opt/verb/conf/servernameip

# Check if zone exists & which directory
if [ -e "/opt/verb/conf/inkdns/parked/db.${dnsDomain}" ]; then
  zonedir="parked"
elif [ -e "/opt/verb/conf/inkdns/zones/db.${dnsDomain}" ]; then
  zonedir="zones"
elif [ ! -f "/opt/verb/conf/inkdns/zones/db.${dnsDomain}" ]; then
  /bin/echo "DNS zone file for domain ${dnsDomain} does not exist. Add the domain first."
  exit 8
fi

# Check if already added
if /bin/grep -Fq "${dnsSubDom}.${dnsDomain}" /opt/verb/conf/inkdns/zones/db.${dnsDomain}; then
/bin/echo "The subdomain ${dnsSubDom} has already been added to ${dnsDomain}. Use killinkdnssub to remove it."
exit 0; fi

# Echo the records
## db.DOM
/bin/echo "; Subdomain Records Added by inkDNS ${dnsSubDom}.${dnsDomain}" >> /opt/verb/conf/inkdns/zones/db.${dnsDomain}
### IP4?
if [ "${ServerIPv4}" != "NOIP4" ]; then
  /bin/echo "${dnsSubDom}.${dnsDomain}.   IN  A    ${ServerIPv4}" >> /opt/verb/conf/inkdns/zones/db.${dnsDomain}
fi
### IP6?
if [ "${ServerIPv6}" != "NOIP6" ]; then
  /bin/echo "${dnsSubDom}.${dnsDomain}.   IN  AAAA   ${ServerIPv6}" >> /opt/verb/conf/inkdns/zones/db.${dnsDomain}
fi
## nv.DOM
/bin/echo "; PTR Subdomain Records Added by inkDNS ${dnsSubDom}.${dnsDomain}" >> /opt/verb/conf/inkdns/zones/nv.${dnsDomain}
### IP4?
if [ "${ServerIPv4}" != "NOIP4" ]; then
  /bin/echo "${ServerARPAIPv4}		IN  PTR  ${dnsSubDom}.${dnsDomain}." >> /opt/verb/conf/inkdns/zones/nv.${dnsDomain}
fi
### IP6?
if [ "${ServerIPv6}" != "NOIP6" ]; then
  /bin/echo "${ServerARPAIPv6}		IN  PTR  ${dnsSubDom}.${dnsDomain}." >> /opt/verb/conf/inkdns/zones/nv.${dnsDomain}
fi

# Set the Serial No
#DEV redundant from inkdnsrefreshbind
#/opt/verb/serfs/inkdnsserial ${dnsDomain}

# Refresh zones
/opt/verb/serfs/inkdnsrefreshbind

# Finish
/bin/echo "The subdomain ${dnsSubDom} has been added to the ${dnsDomain} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddsub.after" ]; then . /opt/verb/mods/inkdnsaddsub.after; fi # Follows this script
