#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server

# How to use:
## ./inkdnsaddinkdkim [ domain.tld ]

usagenotes="This adds the inkDKIM key to an existing DNS TXT record in the inkDNS zone file on the server"
usageformat="inkdnsaddinkdkim [ domain.tld ]"
usageexample="inkdnsaddinkdkim inkisaverb.com"
hierarchy=( tertiary adddomain )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall )
prerequesite=( newinkdkim )
usedby=( newdomainshell installinkvmail )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.replace" ]; then . /opt/verb/mods/inkdnsaddinkdkim.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdnsaddinkdkim.before" ]; then . /opt/verb/mods/inkdnsaddinkdkim.before; fi # Precedes this script


dnsDomain="$1"
if [ -n $2 ] && [ "$2" = "verber" ]; then
  zonedir="inkzones"
  verberny=" verber"
else
  zonedir="zones"
fi

# Include the configs
. /opt/verb/conf/servernameip

# Check if already added
if /usr/bin/grep -Fq "; inkDKIM key" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}; then
/usr/bin/echo "The inkDKIM key for ${dnsDomain} has already been added. Use killinkdnsinkdkim to remove it."
exit 0; fi
if /bin/grep -Fq "dkim._domainkey" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}; then
/usr/bin/echo "The ${dnsDomain} zone file seems to have been tampered with. It should say nothing about DKIM keys at this point, but it does. Fix that first."
exit 7; fi

# Echo the key
## Remove any existing entries
/usr/bin/sed -i "/inkdkim\._domainkey/d" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/sed -i "/; inkDKIM key ${dnsDomain}/d" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/sed -i "/;; End inkDKIM key ${dnsDomain}/d" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"
## Add the entry
/usr/bin/echo "; inkDKIM key ${dnsDomain}" >> /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
/usr/bin/echo $(/usr/bin/cat /etc/opendkim/keys/${dnsDomain}/inkdkim.txt | /usr/bin/sed -z -E 's/"\s+"//') >> /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
/usr/bin/echo ";; End inkDKIM key ${dnsDomain}" >> /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
## Append the domain to the record host name
/usr/bin/sed -i "s/inkdkim\._domainkey/inkdkim\._domainkey\.${dnsDomain}\./" /opt/verb/conf/inkdns/${zonedir}/db.${dnsDomain}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${dnsDomain}${verberny}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
    /opt/verb/serfs/inkdnsrefreshbind
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
  fi
fi

# Finish
/usr/bin/echo "The inkDKIM key has been added to the ${dnsDomain} DNS zone file."




if [ -e "/opt/verb/mods/inkdnsaddinkdkim.after" ]; then . /opt/verb/mods/inkdnsaddinkdkim.after; fi # Follows this script
