#!/bin/bash
#inkVerbSerf! verb.ink
# This relocates an vapp's media folder to an inkDrive mounted with inkdriveadd
## This does not relocate the entire vapp's folder
## This is not for ghost, owncloud, or other /srv/cloud/ apps
## This is designed on a per-vapp basis
## Pydio note: supporting multiple data directories, pydio can take arguments as pydio (same as pydio1), pydio1, pydio2, pydio3, and pydio4
### But, those other pydio "data sources" must already be enabled in the Pydio admin before running this

# How to use:
## ./inkdriveapp [ vapp ] [ drive name - optional ]

# Eg:
## ./inkdriveapp wp.inkisaverb.com mydrive 
## ./inkdriveapp nextcloud


usagenotes="This relocates an vapp's media folder to an inkDrive mounted with inkdriveadd; not for ghost, owncloud, or other /srv/cloud/ apps"
usageformat="inkdriveapp [ vapp ] [ drive name - optional ]"
usageexample="inkdriveapp wp.inkisaverb.com mydrive
inkdriveapp nextcloud"
hierarchy=( primary )
vsetnames=( "Vapp name" )
vsettypes=( isInstalledVapp )
voptnames=( "Drive name" )
vopttypes=( isExists )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdriveadd )
usedby=( installwp )
useserfs=(  )
useconfigs=( inkdrive/inkdriveinfo )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkdriveapp.replace" ]; then . /opt/verb/mods/inkdriveapp.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkdriveapp.before" ]; then . /opt/verb/mods/inkdriveapp.before; fi # Precedes this script

# Config check
if [ ! -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  /usr/bin/echo "No drives installed; do that first."
  exit 8
else
  . /opt/verb/conf/inkdrive/inkdriveinfo
fi

# Defaults (prefer SSD)
Vapp="${1}"
if [ -n "${2}" ]; then
  Mnt="${2}"
elif [ -n "${SSDdefault}" ]; then
  Mnt=${SSDdefault}
elif [ -n "${HDDdefault}" ]; then
  Mnt=${HDDdefault}
else
  /usr/bin/echo "There is no default drive. Something is very wrong."
  exit 6
fi

# Check mount
if [ ! -d "/mnt/${Mnt}" ] && [ -n "${2}" ]; then
  /usr/bin/echo "That drive is not mounted on the system. Choose a drive that exists."
  echo 8
elif [ ! -d "/mnt/${Mnt}" ]; then
  /usr/bin/echo "Default drive is not mounted. Something is very wrong."
  echo 6
fi

# Check vapp
if [ ! -f "/opt/verb/conf/vapps/vapp.${Vapp}" ]; then
  /usr/bin/echo "That vapp is not installed; nothing to do."
  exit 8
fi
if [ ! -d "/srv/www/vapps/${Vapp}" ]; then
  /usr/bin/echo "That vapp has a config, but is not installed. Something is very wrong."
  exit 6
fi
if [[ "${Vapp}" =~ ^wp.* ]] && [ -e "/srv/www/vapps/${Vapp}/wp-content" ]; then
  VappType="WordPress"
  VappData="/srv/www/vapps/${Vapp}/wp-content"
  DataDir="wp-content"
  UserGroup="www:www"
elif [ "${Vapp}" = "maddy" ] && [ -e "/srv/email/maddy/messages" ]; then
  VappType="Maddy"
  VappData="/srv/email/maddy/messages"
  DataDir="messages"
  UserGroup="maddy:maddy"
elif [ "${Vapp}" = "owncloud" ] && [ -e "/srv/cloud/ocis" ]; then
  VappType="ownCloud"
  VappData="/srv/cloud/ocis"
  DataDir="ocis"
  UserGroup="ocis:ocis"
elif [ "${Vapp}" = "nextcloud" ] && [ -e "/srv/www/vapps/nextcloud/data" ]; then
  VappType="Nextcloud"
  VappData="/srv/www/vapps/nextcloud/data"
  DataDir="data"
  UserGroup="www:www"
elif [ "${Vapp}" = "pydio" ] && [ -e "/srv/cloud/pydio/data/pydiods1" ]; then
  VappType="Pydio"
  VappData="/srv/cloud/pydio/data/pydiods1"
  DataDir="pydiods1"
  UserGroup="pydio:pydio"
elif [ "${Vapp}" = "pydio1" ] && [ -e "/srv/cloud/pydio/data/pydiods1" ]; then
  VappType="Pydio"
  VappData="/srv/cloud/pydio/data/pydiods1"
  DataDir="pydiods1"
  UserGroup="pydio:pydio"
elif [ "${Vapp}" = "pydio2" ] && [ -e "/srv/cloud/pydio/data/pydiods2" ]; then
  VappType="Pydio"
  VappData="/srv/cloud/pydio/data/pydiods2"
  DataDir="pydiods2"
  UserGroup="pydio:pydio"
elif [ "${Vapp}" = "pydio3" ] && [ -e "/srv/cloud/pydio/data/pydiods3" ]; then
  VappType="Pydio"
  VappData="/srv/cloud/pydio/data/pydiods3"
  DataDir="pydiods3"
  UserGroup="pydio:pydio"
elif [ "${Vapp}" = "pydio4" ] && [ -e "/srv/cloud/pydio/data/pydiods4" ]; then
  VappType="Pydio"
  VappData="/srv/cloud/pydio/data/pydiods3"
  DataDir="pydiods4"
  UserGroup="pydio:pydio"
else
  /usr/bin/echo "${Vapp} is not a vapp that can be mounted to a drive."
  exit 5
fi
## Check against its VappDrive setting, which is set to Mnt at the end of this script
. "/opt/verb/conf/vapps/vapp.${Vapp}"
if [ -d "/mnt/${Mnt}/vapps/${Vapp}" ] && [ -n "${VappDrive}" ] && [ "${VappDrive}" = "${Mnt}" ]; then
  /usr/bin/echo "That vapp is already mounted to that drive."
  exit 0
elif [ -n "${VappDrive}" ] && [ -d "/mnt/${VappDrive}/vapps/${Vapp}" ]; then
  /usr/bin/echo "That vapp is already mounted to another drive."
  exit 7
elif [ -e "/mnt/${Mnt}/vapps/${Vapp}" ]; then
  /usr/bin/echo "A vapp by that name is already on that drive, but shouldn't be. Something is very wrong."
  exit 6
elif [ -n "${VappDrive}" ]; then
  /usr/bin/echo "The vapp indicates that it is mounted, but is not."
  exit 6
fi

# Space
SpaceAvail="$(/usr/bin/df -k "/mnt/${Mnt}" | /usr/bin/awk 'NR==2 { print $4 }')"
SpaceNeed="$(/usr/bin/du -s "${VappData}" | /usr/bin/awk '{ print $1 }')"
if [ "${SpaceNeed}" -gt "${SpaceAvail}" ]; then
  SpaceAvailH="$(/usr/bin/df -h "/mnt/${Mnt}" | /usr/bin/awk 'NR==2 { print $4 }')"
  SpaceNeedH="$(/usr/bin/du -sh "${VappData}" | /usr/bin/awk '{ print $1 }')"
  echo "Not enough space. ${SpaceNeedH} needed, but only ${SpaceAvailH} available."
  exit 4
fi

# Move & link
if [ ! -d "${VappData}" ]; then
  /usr/bin/echo "That vapp is already linked somewhere it shouldn't be: $(/usr/bin/ls -l "${VappData}")"
  exit 6
else
  /usr/bin/mkdir -p "/mnt/${Mnt}/vapps/${Vapp}"
  /usr/bin/mv "${VappData}" "/mnt/${Mnt}/vapps/${Vapp}/"
  /usr/bin/mkdir -p "${VappData}" # fstab needs something to mount to
  #/usr/bin/ln -sfn "/mnt/${Mnt}/vapps/${Vapp}/${DataDir}" "${VappData}" #DEV the blind mount in fstab is better
  ## fstab
  /usr/bin/echo "/mnt/${Mnt}/vapps/${Vapp}/${DataDir}  ${VappData}  none  bind  0  0 #${Vapp}" >> /etc/fstab # Remove with: sed -i "/#${Vapp}/d" /etc/fstab
  /usr/bin/systemctl daemon-reload
  /usr/bin/mount -a
  ## Own
  /usr/bin/chown -R ${UserGroup} "${VappData}"
  /usr/bin/chown -R ${UserGroup} "/mnt/${Mnt}/vapps/${Vapp}/${DataDir}"
fi
if [ "$?" != 0 ]; then
  /usr/bin/echo "Vapp's data folder could not be mounted. Something is very wrong."
  exit 6
fi

# Finish
if [ -d "/mnt/${Mnt}/vapps/${Vapp}" ] && [ -e "${VappData}" ]; then
  /usr/bin/sed -i "s/VappDrive=.*/VappDrive=\"${Mnt}\"/" "/opt/verb/conf/vapps/vapp.${Vapp}"
  /usr/bin/echo "${VappType} successfully mounted to '${Mnt}'."
fi


if [ -e "/opt/verb/mods/inkdriveapp.after" ]; then . /opt/verb/mods/inkdriveapp.after; fi # Follows this script
