#!/bin/bash
#inkVerbSerf! verb.ink

# This sets and resets the base email addresses used by all other domains on the Maddy email server

# How to use:
## ./inkemailbaseaddrs

usagenotes="This sets and resets the base email addresses used by all other domains on the Postfix vmail server"
usageformat="inkemailbaseaddrs"
usageexample="inkemailbaseaddrs"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installmaddymail )
prerequesite=(  )
usedby=( installmaddymail ) # backupinkemailrestore?
useserfs=( inkemailalias )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailbaseaddrs.replace" ]; then . /opt/verb/mods/inkemailbaseaddrs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailbaseaddrs.before" ]; then . /opt/verb/mods/inkemailbaseaddrs.before; fi # Precedes this script



# Include the config
. /opt/verb/conf/siteurilist

# Set the variables
verberdomain="$nameURI"
rawPassword=$(/usr/bin/pwgen -s 15)
hashedPassword="$(/opt/verb/serfs/inkemailpasshash c "$rawPassword")"
/usr/bin/echo "$rawPassword" > "/srv/email/pass/${emailUser}-${domain}"
passwordMessage="recorded at email/pass/${emailUser}-${domain}; shred after viewing with: 'shred -uf /srv/email/pass/${emailUser}-${domain}'"
adminemail="admin@$nameURI"

# Run the Maddy entry
/usr/bin/sudo -u maddy maddyctl creds create --hash "$adminemail" <<< "$hashedPassword"
/opt/verb/serfs/inkemailalias abuse $nameURI $adminemail
/opt/verb/serfs/inkemailalias hostmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias postmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias webmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias dmark $nameURI $adminemail

if [ -e "/opt/verb/mods/inkemailbaseaddrs.after" ]; then . /opt/verb/mods/inkemailbaseaddrs.after; fi # Follows this script
