#!/bin/bash
#inkVerbSerf! verb.ink

# This creates or resets the Nextcloud smtp user for inkemail, such as is used by php to send emails
## This also creates a cron task to run itself regularly; this is the proper workflor for creating that cron task, creating it the first time run and resetting it

# How to use:
## ./inkemailsyspydio

usagenotes="This creates or resets the Nextcloud smtp user for inkemail, such as is used by php to send emails"
usageformat="inkemailsyspydio"
usageexample="inkemailsyspydio"
hierarchy=( tertiary installpydio )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=(  )
usedby=( installpydio )
useserfs=( setsecure )
useconfigs=( servermailpath servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailsyspydio.replace" ]; then . /opt/verb/mods/inkemailsyspydio.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailsyspydio.before" ]; then . /opt/verb/mods/inkemailsyspydio.before; fi # Precedes this script


# Check to see if inkemail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /bin/echo "Maddy email not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/sysmail.pydio" ]; then
  . /opt/verb/conf/sysmail.pydio
  oldusername="${username}"
fi

# Prep all vairables
Password=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/sysmail.pydio
Password="${Password}"
user="pdy_${randomuser}"
username="pdy_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="Pydio ${blueURI}"
EOF
. /opt/verb/conf/sysmail.pydio

# Security check
/opt/verb/serfs/setsecure; wait

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh pydio; wait
if [ "$?" != 0 ]; then
  echo "Error updating new Pydio mail user in databse"
  exit 6;
fi

# Update Maddy
if [ -n "$oldusername" ] && [ "$oldusername" != "$username" ]; then /usr/bin/sudo -u maddy maddyctl creds remove "$oldusername"; fi

# Set up sysmails cron
## Pydio background jobs (manage the crontab files directly)
/bin/echo '44 * * * * root /opt/verb/serfs/inkemailsyspydio' > /etc/cron.d/sysmailpydio
## Permissions
/bin/chmod 0644 /etc/cron.d/sysmailpydio

# Mail config
if [ -f "/srv/cloud/pydio/pydio.json" ]; then
  /usr/bin/systemctl stop pydio
  /usr/bin/jq ".configs.\"pydio.grpc.mailer\".SMTP_USER = \"pyd_${randomuser}@${nameURI}\" | .configs.\"pydio.grpc.mailer\".SMTP_PASSWORD = \"${Password}\"" /srv/cloud/pydio/pydio.json > /srv/cloud/pydio/tmp.json && /usr/bin/mv /srv/cloud/pydio/tmp.json /srv/cloud/pydio/pydio.json && /usr/bin/rm -f /srv/cloud/pydio/tmp.json
  /usr/bin/chown pydio:pydio /srv/cloud/pydio/pydio.json
  /usr/bin/chmod 600 /srv/cloud/pydio/pydio.json
  /usr/bin/systemctl start pydio
fi




if [ -e "/opt/verb/mods/inkemailsyspydio.after" ]; then . /opt/verb/mods/inkemailsyspydio.after; fi # Follows this script
