#!/bin/bash
#inkVerbSerf! verb.ink

# This adds a domain to Maddy inkemail

# How to use:
## ./inkemaildomain [ domain ]

# Eg:
## ./inkemaildomain inkisaverb.com

usagenotes="This adds a domain to Maddy inkemail"
usageformat="inkemaildomain [ domain ]"
usageexample="inkemaildomain inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=(  )
usedby=( newdomainshell )
useserfs=(  )
useconfigs=( siteurilist servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemaildomain.replace" ]; then . /opt/verb/mods/inkemaildomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemaildomain.before" ]; then . /opt/verb/mods/inkemaildomain.before; fi # Precedes this script


# Include the config files
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath

# Check to see if inkemail is installed
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "Maddy email not installed, not adding $domain"
  exit 0; fi

domain="$1"
if [[ -z "${domain}" ]]; then
  /usr/bin/echo "Domain not specified, not adding"
  exit 0; fi

# Domain already added
if /usr/bin/grep -q "${domain}" /etc/maddy/conf.d/domains.conf || [[ "${domain}" = "${nameURI}" ]]; then
  /usr/bin/echo "The domain $domain already added, doing nothing"
  exit 0; fi

# Make the entry
/usr/bin/sed -i "/extra_domains/ s/$/ ${domain}/" /etc/maddy/conf.d/domains.conf

# Restart Maddy
/usr/bin/systemctl restart maddy.service

# Finish
/usr/bin/echo "Domain $domain added to inkemail"






if [ -e "/opt/verb/mods/inkemaildomain.after" ]; then . /opt/verb/mods/inkemaildomain.after; fi # Follows this script
