#!/bin/bash
#inkVerbSerf! verb.ink

# This removes an unsubscription request email address for a domain
## This removes an entry added in response to the List-Unsubscribe header email generated in Postfix by /etc/postfix/header_checks and /etc/postfix/smtp_header_checks
## The unsubscription file is located at /srv/vip/email/unsubscribe/DOMAIN based on Dovecot-run scipts in /srv/vip/email/nativescripts


# How to use:
## ./inkemailunsubscriberemove [ unsubscribe domain ] [ email address ]

usagenotes="This removes an unsubscription request email address for a domain"
usageformat="inkemailunsubscriberemove [ unsubscribe domain ] [ email address ]"
usageexample="inkemailunsubscriberemove inkisaverb.com johndoe@example.tld"
hierarchy=( primary )
vsetnames=( "Domain to unsubscribe" "Email address to remove" )
vsettypes=( isDomain isEmail )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newdomainshell )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailunsubscriberemove.replace" ]; then . /opt/verb/mods/inkemailunsubscriberemove.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailunsubscriberemove.before" ]; then . /opt/verb/mods/inkemailunsubscriberemove.before; fi # Precedes this script



domain="$1"
email="$2"

# Check the domain shell
if [ ! -f "/opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}" ] || [ ! -f "/opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini" ]; then
  /usr/bin/echo "The shell for ${domain} does not exist. No unsubscriptions to check."
  exit 8
fi

# Check
if [ ! -f "/srv/vip/email/unsubscribe/${domain}" ]; then
  /usr/bin/echo "Domain ${domain} has no unsubscriptions yet."
  exit 0
fi
if ! /usr/bin/grep -q "${email}" "/srv/vip/email/unsubscribe/${domain}"; then
  /usr/bin/echo "Domain ${domain} has no unsubscription request from ${email}"
  exit 0
fi

# Remove
/usr/bin/sed -i "/^${email}$/d" "/srv/vip/email/unsubscribe/${domain}"

# Finish
if ! /usr/bin/grep -q "${email}" "/srv/vip/email/unsubscribe/${domain}"; then
  /usr/bin/echo "${email} request removed from ${domain}"
  exit 0
else
  /usr/bin/echo "Cloud not remove ${email} request from ${domain}, something is wrong!"
  exit 6
fi




if [ -e "/opt/verb/mods/inkemailunsubscriberemove.after" ]; then . /opt/verb/mods/inkemailunsubscriberemove.after; fi # Follows this script
