#!/bin/bash
#inkVerbSerf! verb.ink

# This sets and resets the base email addresses used by all other domains on the Maddy email server

# How to use:
## ./inkemailbaseaddrs

usagenotes="This sets and resets the base email addresses used by all other domains on the Postfix vmail server"
usageformat="inkemailbaseaddrs"
usageexample="inkemailbaseaddrs"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installmaddymail )
prerequesite=(  )
usedby=( installmaddymail ) # backupinkemailrestore?
useserfs=( inkemailalias )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailbaseaddrs.replace" ]; then . /opt/verb/mods/inkemailbaseaddrs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailbaseaddrs.before" ]; then . /opt/verb/mods/inkemailbaseaddrs.before; fi # Precedes this script



# Include the config
. /opt/verb/conf/siteurilist

# Set the variables
emailUser="admin"
adminemail="${emailUser}@${nameURI}"
rawPassword=$(/usr/bin/pwgen -s 15)
#DEV hashedPassword="$(/opt/verb/serfs/inkemailpasshash c "$rawPassword")" # the hash is too long for CLI input with this tool
/usr/bin/echo "$rawPassword" > "/srv/email/pass/${emailUser}-${nameURI}"
passwordMessage="recorded at email/pass/${emailUser}-${nameURI}; shred after viewing with: 'shred -uf /srv/email/pass/${emailUser}-${nameURI}'"

# Run the Maddy entry
#DEV /usr/bin/sudo -u maddy maddy creds create $adminemail --hash <<< "$hashedPassword" # not with the other #DEV line commented-out
/usr/bin/sudo -u maddy maddy creds create -password "$rawPassword" $adminemail
/opt/verb/serfs/inkemailalias abuse $nameURI $adminemail
/opt/verb/serfs/inkemailalias hostmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias postmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias webmaster $nameURI $adminemail
/opt/verb/serfs/inkemailalias dmark $nameURI $adminemail

# Run the Blacklist script now (ensuring all folders exist)
/opt/verb/donjon/sync-blacklist.sh


if [ -e "/opt/verb/mods/inkemailbaseaddrs.after" ]; then . /opt/verb/mods/inkemailbaseaddrs.after; fi # Follows this script
