#!/bin/bash
#inkVerbSerf! verb.ink

# This adds an emaail recipient script filter to domain
## The script must exist at: vip/email/customscripts/emailuser-domain-tld  (only letters & numbers, @ and . replaced with hyphen -)

# How to use:
## ./inkemailaddscriptfilter [ emailuser ] [ domain ]

# Eg:
## ./inkemailaddscriptfilter john inkisaverb.com

usagenotes="This adds an email recipient script filter to domain; the script must exist at: vip/vmail/customscripts/emailuserdomaintld (only letters & numbers); if using unsubscribe@domain.tld and no custom script exists, then a default unsubscribe script will be created"
usageformat="inkemailaddscriptfilter [ emailuser ] [ domain ]"
usageexample="inkemailaddscriptfilter john inkisaverb.com"
hierarchy=( secondary )
vsetnames=( "Email user" "Domain" )
vsettypes=( isDomainPart isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=( inkemaildomain )
usedby=( installmaddymail newdomainshell )
useserfs=(  )
useconfigs=( servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailaddscriptfilter.replace" ]; then . /opt/verb/mods/inkemailaddscriptfilter.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailaddscriptfilter.before" ]; then . /opt/verb/mods/inkemailaddscriptfilter.before; fi # Precedes this script


# Include the config files
. /opt/verb/conf/servermailpath

# Check to see if inkemail is installed
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "Maddy email not installed, not adding $domain"
  exit 0; fi

# Check credentials
if [ -z "$2" ]; then
  /usr/bin/echo "Must enter emailuser and domain as separate arguments"
  exit 5; fi

emailuser="$1"
domain="$2"
emailaddress="${emailuser}@${domain}"
scriptname="${emailuser}-$(/usr/bin/echo ${domain} | /usr/bin/sed "s/[^[:alnum:]]/-/g")"

# Check script
if [ ! -f "/srv/vip/email/customscripts/${scriptname}" ] && [ "${emailuser}" != "unsubscribe" ]; then
  /usr/bin/echo "The necessary script \"${scriptname}\" was not fount in vip/email/customscripts/${scriptname}; I quit"
  exit 8
elif [ "${emailuser}" = "unsubscribe" ]; then
  ## Already added?
  if /usr/bin/grep -q "${scriptname}" /etc/maddy/conf.d/unsubscribe.conf; then
    /usr/bin/echo "The unsubscribe script for ${domain} is already entered. Nothing more to do."
    exit 7
  fi
  scriptpath="/srv/vip/email/nativescripts/${scriptname}"
  /usr/bin/echo "destination ${emailaddress} { check { command ${scriptpath} {sender} } deliver_to dummy }" >> /etc/maddy/conf.d/unsubscribe.conf
  /usr/bin/echo '#!/bin/bash' > "${scriptpath}"
  /usr/bin/echo '/usr/bin/echo "$1" | sed '\''s/^From: //; s/.*<\([^>]*\)>.*/\1/; s/[<>\" ]//g'\'' >> /srv/vip/email/unsubscribe/'"${scriptname}" >> "${scriptpath}"
  /usr/bin/chmod 750 "${scriptpath}"
else
  ## Already added?
  if /usr/bin/grep -q "${scriptname}" /etc/maddy/conf.d/customscripts.conf; then
    /usr/bin/echo "The script \"${scriptname}\" is already entered. Nothing more to do."
    exit 7
  fi
  scriptpath="/srv/vip/email/customscripts/${scriptname}"
  /usr/bin/echo "destination ${emailaddress} { check { command ${scriptpath} {sender} } deliver_to dummy }" >> /etc/maddy/conf.d/customscripts.conf
  /usr/bin/chmod 750 ${scriptpath} # Ensure proper permissions for the pre-existing script
fi

# Restart Maddy
/usr/bin/systemctl restart maddy.service

# Finish
/bin/echo "Mail filter for ${emailaddress} entered."




if [ -e "/opt/verb/mods/inkemailaddscriptfilter.after" ]; then . /opt/verb/mods/inkemailaddscriptfilter.after; fi # Follows this script
