#!/bin/bash
#inkVerbSerf! verb.ink

# This shows all inkemail domains

# How to use:
## ./inkemailshowdomains

usagenotes="This shows all inkemail domains"
usageformat="inkemailshowdomains"
usageexample="inkemailshowdomains"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailshowdomains.replace" ]; then . /opt/verb/mods/inkemailshowdomains.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailshowdomains.before" ]; then . /opt/verb/mods/inkemailshowdomains.before; fi # Precedes this script


# Check to see if inkemail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "Maddy email not installed, not adding $domain"
  exit 0; fi

# Run the query
domainlist="$(/usr/bin/grep "(extra_domains) =" /etc/maddy/conf.d/domains.conf | /usr/bin/sed 's/$(extra_domains) =//' )"

# Show the results
for dom in $domainlist; do
  echo $dom
done




if [ -e "/opt/verb/mods/inkemailshowdomains.after" ]; then . /opt/verb/mods/inkemailshowdomains.after; fi # Follows this script
