#!/bin/bash
#inkVerbSerf! verb.ink

# This creates or resets the system smtp user for inkemail, such as is used by PHP for php to send emails
## This uses msmtp specifically, which requires the msmtp package, not installed by default
## This also creates a cron task to run itself regularly; this is the proper workflor for creating that cron task, creating it the first time run and resetting it

# How to use:
## ./inkemailsysmailboxmsmtp

usagenotes="This creates or resets the system smtp user for inkemail, such as is used by PHP for php to send emails"
usageformat="inkemailsysmailboxmsmtp"
usageexample="inkemailsysmailboxmsmtp"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=(  )
usedby=(  )
useserfs=( setsecure )
useconfigs=( servermailpath servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailsysmailboxmsmtp.replace" ]; then . /opt/verb/mods/inkemailsysmailboxmsmtp.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailsysmailboxmsmtp.before" ]; then . /opt/verb/mods/inkemailsysmailboxmsmtp.before; fi # Precedes this script


# Check to see if inkemail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /bin/echo "Maddy email not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/sysmail.msmtp" ]; then
  . /opt/verb/conf/sysmail.msmtp
  oldusername="${username}"
fi

# Prep all vairables
Password=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/sysmail.msmtp
Password="${Password}"
user="sys_${randomuser}"
username="sys_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="System"
EOF
. /opt/verb/conf/sysmail.msmtp

# Security check
/opt/verb/serfs/setsecure; wait

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh msmtp; wait
if [ "$?" != 0 ]; then
  echo "Error updating new System mail user in databse"
  exit 6;
fi

# Update Maddy
if [ -n "$oldusername" ] && [ "$oldusername" != "$username" ]; then /usr/bin/sudo -u maddy maddy creds remove "$oldusername"; fi

# Set up cron
## MSMTP background jobs (manage the crontab files directly)
/bin/echo '22 * * * * root /opt/verb/serfs/inkemailsysmailboxmsmtp' > /etc/cron.d/sysmailmsmtp
## Permissions
/bin/chmod 0644 /etc/cron.d/sysmailmsmtp




if [ -e "/opt/verb/mods/inkemailsysmailboxmsmtp.after" ]; then . /opt/verb/mods/inkemailsysmailboxmsmtp.after; fi # Follows this script
