#!/bin/bash
#inkVerbSerf! verb.ink

# This removes an email recipient filter to domain

# How to use:
## ./inkemailkillscriptfilter [ emailuser ] [ domain ]

# Eg:
## ./inkemailkillscriptfilter john inkisaverb.com

usagenotes="This adds an email recipient filter to domain"
usageformat="inkemailkillscriptfilter [ emailuser ] [ domain ]"
usageexample="inkemailkillscriptfilter john inkisaverb.com"
hierarchy=( secondary )
vsetnames=( "Email user" "Domain" )
vsettypes=( isDomainPart isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=( inkemaildomain inkemailaddscriptfilter )
usedby=( killdomainshell )
useserfs=(  )
useconfigs=( servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailkillscriptfilter.replace" ]; then . /opt/verb/mods/inkemailkillscriptfilter.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailkillscriptfilter.before" ]; then . /opt/verb/mods/inkemailkillscriptfilter.before; fi # Precedes this script


# Include the config files
. /opt/verb/conf/servermailpath

# Check to see if inkemail is installed
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "Maddy email not installed, not adding $domain"
  exit 0; fi

# Check credentials
if [ -z "$2" ]; then
  /usr/bin/echo "Must enter emailuser and domain as separate arguments"
  exit 5; fi

emailuser="$1"
domain="$2"
emailaddress="${emailuser}@${domain}"
scriptname="${emailuser}-$(/usr/bin/echo ${domain} | /usr/bin/sed "s/[^[:alnum:]]/-/g")"

# Check script
if [ ! -f "/srv/vip/email/customscripts/${scriptname}" ] && [ "${emailuser}" != "unsubscribe" ]; then
  /usr/bin/echo "The necessary script \"${scriptname}\" was not fount in vip/email/customscripts/${scriptname}; attempting to purge anyway..."
fi

# Remove by type
if [ "${emailuser}" = "unsubscribe" ]; then
  scriptpath="/srv/vip/email/nativescripts/${scriptname}"
  /usr/bin/sed -i "\:${scriptpath}:d" /etc/maddy/conf.d/unsubscribe.conf # Colon because $scriptpath contains slash /
  /usr/bin/rm -f ${scriptpath}
else
  scriptpath="/srv/vip/email/customscripts/${scriptname}"
  /usr/bin/sed -i "\:${scriptpath}:d" /etc/maddy/conf.d/customscripts.conf # Colon because $scriptpath contains slash /
fi

# Restart Maddy
/usr/bin/systemctl restart maddy.service

# Finish
/usr/bin/echo "Mail filter for ${emailaddress} is gone."




if [ -e "/opt/verb/mods/inkemailkillscriptfilter.after" ]; then . /opt/verb/mods/inkemailkillscriptfilter.after; fi # Follows this script
