#!/bin/bash
#inkVerbSerf! verb.ink

# This purges (deletes) the inkemail directory of an email box from the inkemail server
##DEV this is not tested yet, waiting to confirm directory structure and whether this is necessary after maddyctl creds remove

# How to use:
## ./inkemailpurgebox [ emailuser (no domain) ] [ domain ]


usagenotes="This purges (deletes) the inkemail directory of an email box from the inkemail server"
usageformat="inkemailpurgebox [ emailuser (no domain) ] [ domain ]"
usageexample="inkemailpurgebox james inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email username" "Domain" )
vsettypes=( isaz09lines isDomian )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkemail )
prerequesite=( inkemailbox )
usedby=(  )
useserfs=(  )
useconfigs=( servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkemailpurgebox.replace" ]; then . /opt/verb/mods/inkemailpurgebox.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkemailpurgebox.before" ]; then . /opt/verb/mods/inkemailpurgebox.before; fi # Precedes this script


# Check to see if inkemail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "Maddy email not installed. Do that first."
  exit 0; fi

# Variables
emailUser="$1"
domain="$2"
inkemaildirectory="$domain/$emailUser/"
emailaddress="$domain@$emailUser"

## May be redundant from *emaildel*

# Delete from Maddy
 /usr/bin/sudo -u maddy maddyctl creds remove "$emailaddress"

# Delete files
/usr/bin/rm -rf /srv/email/maddy/messages/$inkemaildirectory

# Finish
/usr/bin/echo "Email box $address purged from server"




if [ -e "/opt/verb/mods/inkemailpurgebox.after" ]; then . /opt/verb/mods/inkemailpurgebox.after; fi # Follows this script
