#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads an app from the site-wide ink repo

# How to use:
## ./inkget [ app repo name ]

# Eg:
## ./inkget mediawiki
## ./inkget owncloud
## ./inkget wpbb


usagenotes="This downloads an app from the site-wide ink repo"
usageformat="inkget [ app repo name ]"
usageexample="inkget owncloud
inkget wpbb"
hierarchy=( tertiary )
vsetnames=( "app repo name" )
vsettypes=( isInkgetRepo )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( setup )
usedby=( install* )
useserfs=(  )
useconfigs=( servertype servernameip siteurilist servermailpass servermailpath )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkget.replace" ]; then . /opt/verb/mods/inkget.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkget.before" ]; then . /opt/verb/mods/inkget.before; fi # Precedes this script


appName=$1

# Include the config file
. /opt/verb/conf/serverinkget

if [ "${InkGet_Repo}" = "NOT_SET" ]; then
  /usr/bin/echo "inkNet is not setup, so no repo is available. Can't download the necessary package."
exit 8; fi

# zjz
if [ $InkGet_Method = "ZJZ" ]; then
  /opt/verb/donjon/repoupdate/${appName}.updaterepo
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  ## Check repo for failed DL
  if [ "$2" = "check" ] && [ -f "/opt/verb/donjon/repoupdate/${appName}.failed" ]; then
  exit 4; fi
  ## Continue
  /bin/echo "Retrieved from repo."
fi

# wget
if [ $InkGet_Method = "USE_WGET" ]; then
  /usr/bin/wget https://${InkGet_Repo}/repo/${appName}.txz --no-check-certificate
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# rink
if [ $InkGet_Method = "RINK_CP" ]; then
  /usr/bin/cp /opt/ink/repo/${appName}.txz .
  if [ $InkGet_Repo = "TEMP" ]; then
    /usr/bin/rm /opt/verb/repo/${appName}.txz
    /usr/bin/echo "Temp repo files cleaned-up."
  else
    /usr/bin/echo "Repo files kept."
    # Exit if failed
    if [ ! -f /opt/verb/repo/${appName}.txz ]; then
      /usr/bin/echo "Couldn't get the file! I quit."
    exit 4; fi
  fi
fi

## DEV NOTE: Other secure methods are planned in the roadmap
# SSH




if [ -e "/opt/verb/mods/inkget.after" ]; then . /opt/verb/mods/inkget.after; fi # Follows this script
