#!/bin/bash
#inkVerbSerf! verb.ink

# This puts the login credentials into the right place for a Verber
## This assumes that the key has been already uploaded to the CA, signed, downloaded from the CA, and put on the server in the www/vip folder

# How to use:
## ./inknetaddca2vpkg [CA2 Host/Name] [sec path code from CA Verber - optional, will prompt if not entered here]

iCA2v=$1
ca2vName="$(/bin/echo ${iCA2v} | /usr/bin/sed 's/\./_/g')"
ca2vHost="$(/bin/echo ${iCA2v} | /usr/bin/sed 's/\_/./g')"
secpath=$2

# Include the config
. /opt/verb/conf/inknet/2cav.${ca2vName}.cnf

# Verify working home directory
cd ~/ || exit 6

# If sec path not specified in command line
if [ -z ${2} ]; then
/bin/echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read secpath
fi
if [ -z "$secpath" ]; then
/bin/echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read secpath
fi
if [ -z "$secpath" ]; then
/bin/echo "You aren't entering the path. I quit."; exit 5; fi

# Download the package
/usr/bin/wget -q https://${caVerberHost}/inknet/${secpath}/${clientName}.ink --no-check-certificate

# Unpack
/bin/mv ${clientName}.ink ${clientName}.txz
/opt/verb/serfs/vtxzout ${clientName}
/bin/rm -f ${clientName}.txz
. ~/${clientName}/verbername
/bin/cp ~/${clientName}/client.verber.${clientName}.cnf /opt/verb/conf/inknet/client.${VerberName}.rink.login.cnf
/bin/rm -rf ${clientName}

# Finish
/bin/echo "The CA-signed cert for this Verber has been installed. This Verber may now use inkNet to connect to the Inker for other services, such as inkCert."





if [ -e "/opt/verb/mods/inknetaddca2vpkg.after" ]; then . /opt/verb/mods/inknetaddca2vpkg.after; fi # Follows this script
