#!/bin/bash
#inkVerbSerf! verb.ink

# This deletes a Verber Client's profile and kills the inkNet JailKit user

# How to use:
## ./inknetkillverberclient [verb host]


killHost=$1
KILLVERBCLIENT="$(/bin/echo ${killHost} | /usr/bin/sed 's/\./_/g')"

# Chek if it exists
if [ ! -e "/opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf" ]; then
/bin/echo "That Verber Client doesn't exist here."
exit 8; fi

# Include the Client's config
. /opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf

# Kill the inkNet ivApp user
userdel -r ${clientUsername}
/bin/rm -rf /opt/ivapp/inknet/verber/${clientUsername}

# Remove directories
/bin/rm -f /opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf

# Remove the SSH authorized_key file
/bin/rm -f /etc/ssh/authorized_keys/${clientUsername}

# Finish
/bin/echo "Done. ${killHost} pushed overboard and fed to the sharks."





if [ -e "/opt/verb/mods/inknetkillverberclient.after" ]; then . /opt/verb/mods/inknetkillverberclient.after; fi # Follows this script
