#!/bin/bash
# inkVerb serf/surfer, verb.ink

# This creates an Verber Client key to be signed by a CA Verber that will be used to sign into the CA Verber
## Prerequisite: inknetmakeverberclient

# How to use:
## ./inknetnewverber2clientkey [ CA2 Host/Name ]

# Eg:
## ./inknetnewverber2clientkey joeyca2_joeyca_verb_ink
## ./inknetnewverber2clientkey joeyca2.joeyca.verb.ink
## ./inknetnewverber2clientkey joey_joey_verb_email
## ./inknetnewverber2clientkey joey.joey.verb.email


usagenotes="This creates an Verber Client key to be signed by a CA Verber that will be used to sign into the CA Verber"
usageformat="inknetnewverber2clientkey [ CA2 Host/Name ]"
usageexample="inknetnewverber2clientkey joeyca2_joeyca_verb_ink
inknetnewverber2clientkey joeyca2.joeyca.verb.ink
inknetnewverber2clientkey joey_joey_verb_email
inknetnewverber2clientkey joey.joey.verb.email"
hierarchy=( primary )
vsetnames=( "CA2 Host/Name" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( showinknetclientinfo showinknetverberclientkey )
useconfigs=( inknet/2cav. )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inknetnewverber2clientkey.replace" ]; then . /opt/verb/mods/inknetnewverber2clientkey.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inknetnewverber2clientkey.before" ]; then . /opt/verb/mods/inknetnewverber2clientkey.before; fi # Precedes this script


ICASEC=$1
CA2NAME="$(/bin/echo ${ICASEC} | /usr/bin/sed 's/\./_/g')"

# Check the config
if [ ! -f /opt/verb/conf/inknet/2cav.${CA2NAME}.cnf ]; then
/bin/echo "Out of order. This is not a Client yet.

First run inknetaddsecondarycaverber
"
exit 8; fi

# Include the config
. /opt/verb/conf/inknet/2cav.${CA2NAME}.cnf

# Generate the keys
runuser -l ${clientSailor} -c "ssh-keygen -t rsa -N '' -f /opt/ivapp/inknet/sailor/${clientSailor}/.ssh/in_cli_${clientName}_key"

# Finish
/bin/echo "Ready for the next step...
"
/opt/verb/serfs/showinknetclientinfo
wait
/opt/verb/serfs/showinknetverberclientkey
wait





if [ -e "/opt/verb/mods/inknetnewverber2clientkey.after" ]; then . /opt/verb/mods/inknetnewverber2clientkey.after; fi # Follows this script
