#!/bin/bash
#IVapp installer! verb.ink

# This adds an IVapp user with settings for inkNet

# Usertype options are: sail vrb vrk

# How to use:
## ./inknetivappadduser [user] [password] [usertype]


ADDINIVuser=$1
ADDINIVPASS=$2
ADDINIVConf=$3

# Check if installed
if [ ! -d "/opt/ivapp/inknet" ]; then
/bin/echo "ivApp is not instlled yet. I quit."; exit 8; fi

# Add the user
/opt/verb/donjon/ivapp/ivappadduser ${addInivUser} ${ADDINIVPASS} /opt/verb/conf/inknet/ivinknet-${ADDINIVConf}.conf
wait

# Include the user type config
. /opt/verb/conf/inknet/ivinknet-${ADDINIVConf}.conf

# Create the inkNet Client tool links
/bin/rm -rf /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/tools
/bin/ln -sfn /opt/verb/tools/${IvappGroupDir} /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/tools
/bin/mkdir -p /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/.ssh
/bin/chown -R ${addInivUser}:${addInivUser} /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}





if [ -e "/opt/verb/mods/inknetivappadduser.after" ]; then . /opt/verb/mods/inknetivappadduser.after; fi # Follows this script
