#!/bin/bash
#inkVerbSerf! verb.ink

# This puts the login credentials into the right place for a Verber
## This assumes that the key has been already uploaded to the CA, signed, downloaded from the CA, and put on the server in the www/vip folder

# How to use:
## ./inknetaddcavpkg [sec path code from CA Verber - optional, will prompt if not entered here]


secpath=$1

# Include the config
. /opt/verb/conf/inknet/rink.client.cnf

# Verify working home directory
cd ~/ || exit 6

# If sec path not specified in command line
if [ -z ${1} ]; then
/bin/echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read SECPATH
fi
if [ -z "${secpath}" ]; then
/bin/echo "Please copy-paste the code the CA Verber gave you, then press Enter."
read SECPATH
fi
if [ -z "${secpath}" ]; then
/bin/echo "You aren't entering the path. I quit."; exit 5; fi

# Download the package
/usr/bin/wget -q https://${CAVERBERHOST}/inknet/${secpath}/${clientName}.ink --no-check-certificate

# Unpack
/bin/mv ${clientName}.ink ${clientName}.txz
/opt/verb/serfs/vtxzout ${clientName}
/bin/rm -f ${clientName}.txz
. ~/${clientName}/verbername
/bin/cp ~/${clientName}/client.verber.${clientName}.cnf /opt/verb/conf/inknet/client.${VERBERNAME}.rink.login.cnf
/bin/rm -rf ${clientName}

# Finish
/bin/echo "The CA-signed cert for this Verber has been installed. This Verber may now use inkNet to connect to the Inker for other services, such as inkCert."





if [ -e "/opt/verb/mods/inknetaddcavpkg.after" ]; then . /opt/verb/mods/inknetaddcavpkg.after; fi # Follows this script
