#!/bin/bash
#IVapp installer! verb.ink

# This adds an IVapp user with settings for inkNet

# Usertype options are: sail vrb vrk

# How to use:
## ./inknetivappadduser [ user ] [ password ] [ usertype ]


usagenotes="This adds an IVapp user with settings for inkNet"
usageformat="inknetivappadduser [ user ] [ password ] [ usertype ]"
usageexample="inknetivappadduser
inknetivappadduser [ user ] [ password ] [ usertype ]"
hierarchy=( tertiary inknetaddverberclient )
vsetnames=( "Username" "Password" "Username" )
vsettypes=( isUsername isPassword isUsername )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inknetaddverberclient inknetaddvrkclient )
useserfs=(  )
useconfigs=( inknet/ivinknet- )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inknetivappadduser.replace" ]; then . /opt/verb/mods/inknetivappadduser.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inknetivappadduser.before" ]; then . /opt/verb/mods/inknetivappadduser.before; fi # Precedes this script


ADDINIVuser=$1
ADDINIVPASS=$2
addInivConf=$3

# Check if installed
if [ ! -d "/opt/ivapp/inknet" ]; then
/bin/echo "ivApp is not instlled yet. I quit."; exit 8; fi

# Add the user
/opt/verb/donjon/ivapp/ivappadduser ${addInivUser} ${ADDINIVPASS} /opt/verb/conf/inknet/ivinknet-${addInivConf}.conf
wait

# Include the user type config
. /opt/verb/conf/inknet/ivinknet-${addInivConf}.conf

# Create the inkNet Client tool links
/bin/rm -rf /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/tools
/bin/ln -sfn /opt/verb/tools/${IvappGroupDir} /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/tools
/bin/mkdir -p /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}/.ssh
/bin/chown -R ${addInivUser}:${addInivUser} /opt/ivapp/inknet/${IvappGroupDir}/${addInivUser}





if [ -e "/opt/verb/mods/inknetivappadduser.after" ]; then . /opt/verb/mods/inknetivappadduser.after; fi # Follows this script
