#!/bin/bash
#inkVerbSerf! verb.ink

# This deletes a Verber Client's profile and kills the inkNet JailKit user

# How to use:
## ./inknetkillverberclient [ verb host ]


usagenotes="This deletes a Verber Client's profile and kills the inkNet JailKit user"
usageformat="inknetkillverberclient [ verb host ]"
usageexample="inknetkillverberclient
inknetkillverberclient [ verb host ]"
hierarchy=( primary )
vsetnames=( "Verb host" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( inknet/verber/client.verber. )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inknetkillverberclient.replace" ]; then . /opt/verb/mods/inknetkillverberclient.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inknetkillverberclient.before" ]; then . /opt/verb/mods/inknetkillverberclient.before; fi # Precedes this script


killHost=$1
KILLVERBCLIENT="$(/bin/echo ${killHost} | /usr/bin/sed 's/\./_/g')"

# Chek if it exists
if [ ! -e "/opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf" ]; then
/bin/echo "That Verber Client doesn't exist here."
exit 8; fi

# Include the Client's config
. /opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf

# Kill the inkNet ivApp user
userdel -r ${clientUsername}
/bin/rm -rf /opt/ivapp/inknet/verber/${clientUsername}

# Remove directories
/bin/rm -f /opt/verb/conf/inknet/verber/client.verber.${KILLVERBCLIENT}.cnf

# Remove the SSH authorized_key file
/bin/rm -f /etc/ssh/authorized_keys/${clientUsername}

# Finish
/bin/echo "Done. ${killHost} pushed overboard and fed to the sharks."





if [ -e "/opt/verb/mods/inknetkillverberclient.after" ]; then . /opt/verb/mods/inknetkillverberclient.after; fi # Follows this script
