#!/bin/bash
#IVapp installer! verb.ink

# This adds an IVapp user with settings for an inkNet Sailor


# How to use:
## ./inknetivappaddsailor [ user ]


usagenotes="This adds an IVapp user with settings for an inkNet Sailor"
usageformat="inknetivappaddsailor [ user ]"
usageexample="inknetivappaddsailor
inknetivappaddsailor [ user ]"
hierarchy=( tertiary inknetivappnewclientsailor )
vsetnames=( "Username" )
vsettypes=( isUsername )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inknetivappnewclientsailor )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inknetivappaddsailor.replace" ]; then . /opt/verb/mods/inknetivappaddsailor.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inknetivappaddsailor.before" ]; then . /opt/verb/mods/inknetivappaddsailor.before; fi # Precedes this script


addInivSailor=$1

# Add the user
/opt/verb/donjon/ivapp/ivappaddsailor ${addInivSailor} /opt/verb/conf/inknet/ivinknet-sail.conf
wait

# Create the inkNet Client tool links
/bin/rm -rf /opt/ivapp/inknet/sailor/${addInivSailor}/tools
/bin/ln -sfn /opt/verb/tools/sailor /opt/ivapp/inknet/sailor/${addInivSailor}/tools
/bin/mkdir -p /opt/ivapp/inknet/sailor/${addInivSailor}/.ssh
/bin/chown -R ${addInivSailor}:${addInivSailor} /opt/ivapp/inknet/sailor/${addInivSailor}





if [ -e "/opt/verb/mods/inknetivappaddsailor.after" ]; then . /opt/verb/mods/inknetivappaddsailor.after; fi # Follows this script
