#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a temporary link for downloading the inkVPN client profile file
## This is run automatically by inkvpninstall and inkvpnclientkey, but can be run separately

# How to use:
## ./inkvpnclientdl


usagenotes="This creates a temporary link for downloading the inkVPN client profile file"
usageformat="inkvpnclientdl"
usageexample="inkvpnclientdl"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inkvpnclientkey inkvpnport )
useserfs=(  )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvpnclientdl.replace" ]; then . /opt/verb/mods/inkvpnclientdl.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkvpnclientdl.before" ]; then . /opt/verb/mods/inkvpnclientdl.before; fi # Precedes this script


# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Set the link names
cdir="$(/usr/bin/pwgen -s -1 128)"
. /opt/verb/donjon/servedl.sh
serveURL=$(servedl_put /opt/openvpn/certificates/clients/client.ovpn "${cdir}" "${ServerName}-${ServerTLD}-client.ovpn")

# Finish
/bin/echo "The client OVPN profile is ready for download.
Get it here: ${serveURL}
This download link will expire in at least 30 minutes."




if [ -e "/opt/verb/mods/inkvpnclientdl.after" ]; then . /opt/verb/mods/inkvpnclientdl.after; fi # Follows this script
