#!/bin/bash
#inkVerbSerf! verb.ink

# This creates or resets the Nextcloud smtp user for inkvmail, such as is used by php to send emails
## This also creates a cron task to run itself regularly; this is the proper workflor for creating that cron task, creating it the first time run and resetting it

# How to use:
## ./inkvmailsysowncloud

usagenotes="This creates or resets the Nextcloud smtp user for inkvmail, such as is used by php to send emails"
usageformat="inkvmailsysowncloud"
usageexample="inkvmailsysowncloud"
hierarchy=( tertiary installowncloud )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkvmail )
prerequesite=(  )
usedby=( installnextcloud )
useserfs=( setsecure )
useconfigs=( servermailpath servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailsysowncloud.replace" ]; then . /opt/verb/mods/inkvmailsysowncloud.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkvmailsysowncloud.before" ]; then . /opt/verb/mods/inkvmailsysowncloud.before; fi # Precedes this script


# Check to see if inkvmail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed. Do that first."
  exit 0; fi

# Include the config
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Cleanup previous entries
if [ -f "/opt/verb/conf/vsysmail.owncloud" ]; then
  . /opt/verb/conf/vsysmail.owncloud
  /usr/bin/rm -rf /srv/vmail/${inkvmaildirectory}
  oldusername="${username}"
fi

# Prep all vairables
Password=$(/usr/bin/pwgen -s1 24)
randomuser=$(/usr/bin/pwgen -s1A 5)
/usr/bin/cat <<EOF > /opt/verb/conf/vsysmail.owncloud
Password="${Password}"
user="ons_${randomuser}"
username="ons_${randomuser}@${nameURI}"
maildomain="${nameURI}"
name="Nextcloud ${blueURI}"
inkvmaildirectory="${nameURI}/ons_${randomuser}/"
mailboxsize="1048576" # 1MB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000
EOF

# Security check
/opt/verb/serfs/setsecure; wait

# Disable the old entry in the database
if [ -n "${oldusername}" ]; then
  password="$(/bin/echo $Password | /usr/bin/openssl passwd -1 -stdin)"
  /usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqldb.vmail.cnf -e "UPDATE mailbox
  SET username = 'ons_${randomuser}@${nameURI}', password = '${password}', name = 'System', maildir = '${nameURI}/ons_${randomuser}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE username = '${oldusername}';
  UPDATE alias
  SET address = 'ons_${randomuser}@${nameURI}', goto = 'ons_${randomuser}@${nameURI}', domain = '${nameURI}', modified = CURRENT_TIMESTAMP, active = 1
  WHERE address = '${oldusername}';"
fi

# Run it quick to create the account
/opt/verb/donjon/sysmails.sh nextcloud; wait
if [ "$?" != 0 ]; then
  echo "Error updating new Nextcloud mail user in databse"
  exit 6;
fi

# Set up sysmails cron
## Nextcloud background jobs (manage the crontab files directly)
/usr/bin/echo '49 * * * * root /opt/verb/serfs/inkvmailsysowncloud' > /etc/cron.d/sysmailowncloud
## Permissions
/usr/bin/chmod 0644 /etc/cron.d/sysmailowncloud

# Mail config
## Be safe
/usr/bin/touch /srv/cloud/ocis/config/notifications.yaml
## notifications.yaml option for system email settings in a separate file
/usr/bin/cat <<EOF > /srv/cloud/ocis/config/notifications.yaml
smtp:
  host: "mail.${nameURI}"
  port: 587
  sender: "ons_${randomuser}@${nameURI}"
  username: "ons_${randomuser}@${nameURI}"
  password: "${Password}"
  authentication: "login"
  encryption: "starttls"
EOF
## Permissions
/usr/bin/chmod 600 /srv/cloud/ocis/config/notifications.yaml
/usr/bin/chown ocis:ocis /srv/cloud/ocis/config/notifications.yaml




if [ -e "/opt/verb/mods/inkvmailsysowncloud.after" ]; then . /opt/verb/mods/inkvmailsysowncloud.after; fi # Follows this script
