#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the inkVPN client and server email address
## This is used by inkvpninstall but can also be used by itself
## If the email is not set in the first argument, the default will be used by the Verber's nameURI

# How to use:
## ./inkvpnemail [ new email - optional ]


usagenotes="This sets the inkVPN client and server email address"
usageformat="inkvpnemail [ new email - optional ]"
usageexample="inkvpnemail"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "Email" )
vopttypes=( isEmail )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inkvpninstall )
useserfs=(  )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvpnemail.replace" ]; then . /opt/verb/mods/inkvpnemail.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkvpnemail.before" ]; then . /opt/verb/mods/inkvpnemail.before; fi # Precedes this script


# Include the config
. /opt/verb/conf/siteurilist

# Set the email variable
if [ -z "$1" ]; then
 /bin/echo "Option not specified, OK, using default..."
 newEmailAddr="vpn@${nameURI}"
else
 newEmailAddr="$1"
fi

# Do it
/bin/sed -i "s/InkVPNClientEmail=.*/InkVPNClientEmail=${newEmailAddr}/" /opt/verb/conf/inkvpn/inkvpnstatus

#Finish
/bin/echo "inkVPN email now set to: ${newEmailAddr}"




if [ -e "/opt/verb/mods/inkvpnemail.after" ]; then . /opt/verb/mods/inkvpnemail.after; fi # Follows this script
