#!/bin/bash
#inkVerbSerf! verb.ink

# This sets and resets the base email addresses used by all other domains on the Postfix vmail server

# How to use:
## ./inkvmailbaseaddrs

usagenotes="This sets and resets the base email addresses used by all other domains on the Postfix vmail server"
usageformat="inkvmailbaseaddrs"
usageexample="inkvmailbaseaddrs"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installpostfixvmail )
prerequesite=(  )
usedby=( installpostfixvmail backupinkvmailrestore )
useserfs=(  )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailbaseaddrs.replace" ]; then . /opt/verb/mods/inkvmailbaseaddrs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkvmailbaseaddrs.before" ]; then . /opt/verb/mods/inkvmailbaseaddrs.before; fi # Precedes this script



# Include the config
. /opt/verb/conf/siteurilist

# Set the variables
verberdomain="$nameURI"
PASSWORD=$(/usr/bin/pwgen -s -1 20)
password="$(/bin/echo $PASSWORD | /usr/bin/openssl passwd -1 -stdin)"
username="verberadmin@$nameURI"
name="Change Me Dont Delete Me"
inkvmaildirectory="$nameURI/verberadmin/"
mailboxsize="524288000" # 0.5GB, 2GB=2097152000, 1GB=1048576000, 5GB=5242880000

# Run the database query, IGNORE if key already exists, FYI PRIMARY KEY is username.mail and address.alias
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/mysqldb.vmail.cnf -e "INSERT IGNORE INTO domain (domain, description, aliases, mailboxes, maxquota, quota, transport, backupmx, created, modified, active) VALUES ('$verberdomain', '$verberdomain', '1000', '1000', '10000', '2048', 'virtual', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO mailbox (username, password, name, maildir, quota, local_part, domain, created, modified, active) VALUES ('$username', '$password', '$name', '$inkvmaildirectory', '$mailboxsize', 'verberadmin', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('$username', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('abuse@$nameURI', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('hostmaster@$nameURI', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('postmaster@$nameURI', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('webmaster@$nameURI', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT IGNORE INTO alias (address, goto, domain, created, modified, active) VALUES ('dmark@$nameURI', '$username', '$nameURI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);"

if [ -e "/opt/verb/mods/inkvmailbaseaddrs.after" ]; then . /opt/verb/mods/inkvmailbaseaddrs.after; fi # Follows this script
