#!/bin/bash
#inkVerbSerf! verb.ink

# This sets an email box to 'active' in the inkvmail database

# How to use:
## ./inkvmailonbox [ emal address ]

usagenotes="This sets an email box to 'active' in the inkvmail database"
usageformat="inkvmailonbox [ emal address ]"
usageexample="inkvmailonbox john@inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Email" )
vsettypes=( isEmail )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( installinkvmail )
prerequesite=( inkvmailbox )
usedby=(  )
useserfs=(  )
useconfigs=( servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/inkvmailonbox.replace" ]; then . /opt/verb/mods/inkvmailonbox.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/inkvmailonbox.before" ]; then . /opt/verb/mods/inkvmailonbox.before; fi # Precedes this script


# Check to see if inkvmail is installed
. /opt/verb/conf/servermailpath
if [ "$ServerMailStatus" != "VMAIL_SERVER" ]; then
  /bin/echo "Vmail not installed, not adding $domain to PFA"
  exit 0; fi

address="$1"

# Run the update
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqldb.vmail.cnf -e "UPDATE mailbox SET active=1, modified=CURRENT_TIMESTAMP WHERE username='$address';"

# Finish
/bin/echo "Email address $address set to active"




if [ -e "/opt/verb/mods/inkvmailonbox.after" ]; then . /opt/verb/mods/inkvmailonbox.after; fi # Follows this script
