#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs MediaWiki from the inkisaverb.com repository and links it to wiki.your-name.verb.ink

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installmediawiki [ dbase ] [ dbuser ] [ dbpassword ]


usagenotes="This downloads and installs MediaWiki from the inkisaverb.com repository and links it to wiki.your-name.verb.ink"
usageformat="installmediawiki [ dbase ] [ dbuser ] [ dbpassword ]"
usageexample="installmediawiki
installmediawiki [ dbase ] [ dbuser ] [ dbpassword ]"
hierarchy=( primary )
vsetnames=( "Database" "Database user" "Database password" )
vsettypes=( isSQLDatabasename isSQLDatabasename isSQLDatabasename )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( inkget setvapplinkon setvappconfig )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installmediawiki.replace" ]; then . /opt/verb/mods/installmediawiki.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installmediawiki.before" ]; then . /opt/verb/mods/installmediawiki.before; fi # Precedes this script


cVappName=mediawiki

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

dBase=$1
dBaseUser=$2
dBPassword=$3
cleanName=$(/bin/echo $cVappName | /usr/bin/sed -e 's/\.//g')

# Check if already installed
. /opt/verb/donjon/vappinstall.sh
if ! vappinst_clear_partial \
  "/opt/verb/conf/vapps/vapp.${cVappName}" \
  "/srv/www/vapps/${cVappName}" \
  "/srv/www/vapps/${cVappName}/index.php"; then
/bin/echo "This is already installed."
exit 0; fi

vappinst_begin

# Download and establish mediawiki from the inkVerb repo
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"
vappinst_note dir "/srv/www/vapps/${cVappName}"

/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/chown -R www:www /srv/www/verb/ink.wiki; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Auto database
if [ -z ${3} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
dBase=${cleanName}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
dBaseUser=${dBase}; fi

# Create the database and credentials
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"
e="$?"; [[ "$e" = "0" ]] || exit "$e"
vappinst_note mysql "${dBase}" "${dBaseUser}"

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}
vappinst_note conf "/opt/verb/conf/vapps/vapp.${cVappName}"
/opt/verb/serfs/setvappconfig "vapp.${cVappName}" "/srv/www/vapps/${cVappName}/LocalSettings.php"

vappinst_commit
/bin/echo "These are setup:

Host: localhost
Database name: ${dBase}
Database username: ${dBaseUser} (NOT root)
Database password: ${dBPassword}
Storage engine: InnoDB
Character Set: UTF-8
Return email address: use anything real, maybe yourname@${inkURI}, NOT something@wiki.${inkURI}

Go to http://wiki.${inkURI} to install.

After installing, download the LocalSettings.php file, then upload it to the \"vip\" web folder, then run postinstallmediawiki to complete in installation.
"




if [ -e "/opt/verb/mods/installmediawiki.after" ]; then . /opt/verb/mods/installmediawiki.after; fi # Follows this script
