#!/bin/bash
#inkVerbSerf! verb.ink

# This installs Docker, which is used by various apps, including Collabora Online for Nextcloud
## Instructions per VPS service for advanced connections: https://docs.docker.com/engine/installation/#docker-cloud

# How to use:
## ./installdocker

usagenotes="This installs Docker, which is used by various apps, including Collabora Online for Nextcloud"
usageformat="installdocker"
usageexample="installdocker"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installdocker.replace" ]; then . /opt/verb/mods/installdocker.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installdocker.before" ]; then . /opt/verb/mods/installdocker.before; fi # Precedes this script


# Check if already installed
if [ -f /opt/verb/conf/dockerinstalled ]; then
/usr/bin/echo "Docker is already installed."
exit 0; fi

# Install Docker
/usr/bin/pacman -Syy docker --needed --noconfirm

# Record config
/usr/bin/touch /opt/verb/conf/dockerinstalled

# Finish
/usr/bin/echo "Docker installed."





if [ -e "/opt/verb/mods/installdocker.after" ]; then . /opt/verb/mods/installdocker.after; fi # Follows this script
