#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs net2ftp manually from inkisaverb.com/repo and linnks it to net2ftp....verb.vip
# Prereq: vsftp and an ftpvip or ftpfiler for login

# How to use:
## ./installvsftpd


usagenotes="This downloads and installs net2ftp manually from inkisaverb.com/repo and linnks it to net2ftp....verb.vip"
usageformat="installnet2ftp installvsftpd"
usageexample="installnet2ftp"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( inkget setvapplinkon setvappconfig )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installnet2ftp.replace" ]; then . /opt/verb/mods/installnet2ftp.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installnet2ftp.before" ]; then . /opt/verb/mods/installnet2ftp.before; fi # Precedes this script


cVappName=net2ftp

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# IP4?
if [ "${ServerIPv4}" = "NOIP4" ]; then
  /usr/bin/echo "IPv4 is disabled on this server, so net2ftp cannot be installed."
  exit 0
fi

# Download and unpack
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check; wait
e="$?"; [[ "$e" = "0" ]] || exit "$e"

/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait
/bin/chown -R www:www /srv/www/verb/vip.net2ftp; wait

# Settings
cd net2ftp || exit 6
/bin/cp settings.inc.php settings.inc.php.dist
/bin/cp settings_authorizations.inc.php settings_authorizations.inc.php.dist
/bin/cp settings_screens.inc.php settings_screens.inc.php.dist
/bin/sed -i "s/\$net2ftp_settings\[\"email_feedback\"\] = \"webmaster@enter-your-domain-here.com\";/\$net2ftp_settings\[\"email_feedback\"\] = \"postmaster@${inkURI}\";/g" settings.inc.php
/bin/sed -i "s/462E16CB7C3F369BD9F4DBEE0A926F8F14FFB3/462E16CB7C3F369HD9F4DAEE0A926FLF14F9B3/g" settings.inc.php
/bin/sed -i "s/\$net2ftp_settings\[\"max_filesize\"\]  = \"10000000\";/\$net2ftp_settings\[\"max_filesize\"\]  = \"1000000000\";/g" settings.inc.php
/bin/sed -i "s/\$net2ftp_settings\[\"allowed_ftpservers\"\]\[1\] = \"ALL\";/\/\/\$net2ftp_settings\[\"allowed_ftpservers\"\]\[1\] = \"ALL\";/g" settings_authorizations.inc.php
/bin/sed -i "s/\/\/\$net2ftp_settings\[\"allowed_ftpservers\"\]\[3\] = \"ftp.mydomain2.org\";/\$net2ftp_settings\[\"allowed_ftpservers\"\]\[1\] = \"${ServerIPv4}\";/g" settings_authorizations.inc.php
/bin/sed -i "s/\$net2ftp_settings\[\"allowed_ftpserverport\"\] = \"ALL\";/\/\/\$net2ftp_settings\[\"allowed_ftpserverport\"\] = "ALL";/g" settings_authorizations.inc.php
/bin/sed -i "s/\/\/\$net2ftp_settings\[\"allowed_ftpserverport\"\] = \"21\";/\$net2ftp_settings\[\"allowed_ftpserverport\"\] = "2121";/g" settings_authorizations.inc.php

/opt/verb/serfs/setvappconfig "vapp.${cVappName}" "/srv/www/vapps/${cVappName}/settings.inc.php"

# Finish
/bin/echo "net2ftp is enabled and clipping along!

After creating an FTP VIP (or FTP Filer for private file access also)

Login at http://net2ftp.${vipURI}
"




if [ -e "/opt/verb/mods/installnet2ftp.after" ]; then . /opt/verb/mods/installnet2ftp.after; fi # Follows this script
