#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs WordPress to blog.NAME.verb.ink
## WordPress actually resides in www/vapps/wp.inkblog

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installwpinkblog [dbase] [dbuser] [dbpassword]


cVappName=wp.inkblog
# "wp" is the normal app, so it must be specified when retrieving from the repo

# Include the config
. /opt/verb/conf/siteurilist

dBase=$1
dBaseUser=$2
dBPassword=$3
cleanName=$(/bin/echo $cVappName | sed -e 's/\.//g')

# Check for existing inkblog
. /opt/verb/conf/inkinksiteinstallstatus
if [ "${INKblog}" != "NOT_YET" ]; then
/bin/echo "Um... How do I say this...
Your blog at blog.${inkURI} already has ${INKblog} installed. This just isn't going to work.
"
exit 0
fi

# Download and establish wordpress in the server to pre-created domain
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget wp check
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Auto database
if [ -z ${4} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${2} ]; then
dBase=${cleanName}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${3} ]; then
dBaseUser=${dBase}; fi

/bin/mv wp ${cVappName}; wait
/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/ln -sfn /srv/www/vapps/${cVappName} /srv/vip/_webapps/; wait
/bin/chown -R www:www /srv/www/verb/ink.i/blog; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Create the database and credentials
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}

# VIP domain
/bin/ln -s /srv/www/verb/ink.i/blog /srv/vip/_domains/

# Put the settings in the WordPress config file
cd ${cVappName} || exit 6
/bin/cp wp-config-sample.php wp-config.php
/bin/sed -i "s/database_name_here/${dBase}/g" wp-config.php
/bin/sed -i "s/username_here/${dBaseUser}/g" wp-config.php
/bin/sed -i "s/password_here/${dBPassword}/g" wp-config.php

# Add the secure salt and key strings
AUTH_KEY=$(/usr/bin/pwgen -s -1 27)
SECURE_AUTH_KEY=$(/usr/bin/pwgen -s -1 27)
LOGGED_IN_KEY=$(/usr/bin/pwgen -s -1 27)
NONCE_KEY=$(/usr/bin/pwgen -s -1 27)
AUTH_SALT=$(/usr/bin/pwgen -s -1 27)
SECURE_AUTH_SALT=$(/usr/bin/pwgen -s -1 27)
LOGGED_IN_SALT=$(/usr/bin/pwgen -s -1 27)
NONCE_SALT=$(/usr/bin/pwgen -s -1 27)
/bin/sed -i "s/define( 'AUTH_KEY',         .*/define( 'AUTH_KEY',         '${AUTH_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'SECURE_AUTH_KEY',  .*/define( 'SECURE_AUTH_KEY',  '${SECURE_AUTH_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'LOGGED_IN_KEY',    .*/define( 'LOGGED_IN_KEY',    '${LOGGED_IN_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'NONCE_KEY',        .*/define( 'NONCE_KEY',        '${NONCE_KEY}' );/g" wp-config.php
/bin/sed -i "s/define( 'AUTH_SALT',        .*/define( 'AUTH_SALT',        '${AUTH_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'SECURE_AUTH_SALT', .*/define( 'SECURE_AUTH_SALT', '${SECURE_AUTH_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'LOGGED_IN_SALT',   .*/define( 'LOGGED_IN_SALT',   '${LOGGED_IN_SALT}' );/g" wp-config.php
/bin/sed -i "s/define( 'NONCE_SALT',       .*/define( 'NONCE_SALT',       '${NONCE_SALT}' );/g" wp-config.php

#### fixhttps already done?
if /bin/grep -q '##INKHTTPSFIX=fixed' /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
/bin/sed -i "/WP_SITEURL/d" /srv/www/vapps/wp.${domain}/wp-config.php
/bin/sed -i "/WP_HOME/d" /srv/www/vapps/wp.${domain}/wp-config.php
/bin/echo "define( 'WP_SITEURL', 'https://${domain}' );
define( 'WP_HOME', 'https://${domain}' );" >> /srv/www/vapps/wp.${domain}/wp-config.php
fi

# Reset all permissions
/bin/chmod -R 440 wp-config.php
/bin/chown -R www:www /srv/www/vapps/${cVappName}


# Set the site-wide inkblog config
/bin/sed -i "s/INKblog=.*/INKblog=\"WordPress\"/g" /opt/verb/conf/inkinksiteinstallstatus

# Reset all permissions
/bin/chown -R www:www /srv/www/vapps/${cVappName}

# Finish
/bin/echo "These are setup:

Database: ${dBase}
Database user: ${dBaseUser}
Database password: ${dBPassword}

Go to http://blog.${inkURI}/wp-admin/index.php to install.
"




if [ -e "/opt/verb/mods/installwpinkblog.after" ]; then . /opt/verb/mods/installwpinkblog.after; fi # Follows this script
