#!/bin/bash
#inkVerbSerf! verb.ink

# This installs the NVM package manager for Node.js
##DEV may be depreciated since pacman has a simple package for this

# How to use:
## ./installnvm

/usr/bin/su worker -c '/usr/bin/yay -S --noconfirm --needed nvm'
#/usr/local/bin/yeo -S --noconfirm --needed nvm
if [ "$?" != "0" ]; then /usr/bin/echo 'Failed: !!'; exit 4; fi

echo 'source /usr/share/nvm/init-nvm.sh' >> /etc/bash.bashrc
echo 'source /usr/share/nvm/init-nvm.sh' >> ~/.bashrc




if [ -e "/opt/verb/mods/installnvm.after" ]; then . /opt/verb/mods/installnvm.after; fi # Follows this script
