#!/bin/bash
#inkVerbSerf! verb.ink

# This installs Postfix as the email server wtih Dovecot and OpenDKIM
## This creates a database accessed by PostfixAdmin as a web tool, but PFA is not a requirement for the database and inkvmail to work
## Prerequisite: sertupverb
## This only performs basic back-end server setup and creates no mail accounts
## Once this is done it is set for the server permanently.

# How to use:
## ./installpostfixvmail


usagenotes="This installs Postfix as the email server wtih Dovecot and OpenDKIM"
usageformat="installpostfixvmail"
usageexample="installpostfixvmail"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( "inkCert certs should be installled for at least the nameURI for this verber" )
usedby=( installinkvmail )
useserfs=( installspamassassin setinkcertmailcerts setinkcertmail inkvmailverbaddrs inkdnsaddmail newinkdkim inkdnsaddinkdkim inkvmailsysmailbox )
useconfigs=( servernameip siteurilist servertype servermailpath )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installpostfixvmail.replace" ]; then . /opt/verb/mods/installpostfixvmail.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installpostfixvmail.before" ]; then . /opt/verb/mods/installpostfixvmail.before; fi # Precedes this script


# Include the config files
. /opt/verb/conf/servertype
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath

# Check to see if already installed
if [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
/usr/bin/echo "
Maddy email server is already installed.
"
exit 0; fi
if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
/usr/bin/echo "
Postfix vmail server already installed.
"
exit 0; fi
if [[ "${ServerMailStatus}" =~ "_BACKUP_MX" ]]; then # Backup mail server could use Maddy or Postfix vmail or others, each needing its own, but must contain _BACKUP_MX in its setting
/usr/bin/echo "
Email server is already a backup server.
"
exit 0; fi
if [ "${ServerMailStatus}" != "EMAIL_NOT_INSTALLED" ]; then
/usr/bin/echo "
Email server is already configured and cannot be installed.
"
exit 0; fi
if ! /usr/bin/grep -Fq 'Email Control Records' /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/usr/bin/echo "
Email Control Records not declared in the email domain DNS zone file. This won't work.
"
exit 7; fi
if [ "${EmailAllowed}" != "YES" ]; then
/usr/bin/echo "
Email not allowed on this server.
"
exit 0; fi

# Update Keyring
/usr/bin/pacman -Sy archlinux-keyring --noconfirm

# Update Packages
/usr/bin/pacman -Syyu --noconfirm --needed

# Install Postfix server packages
/usr/bin/pacman -S --noconfirm --needed postfix postfix-mysql postfix-lmdb dovecot pigeonhole mailutils cyrus-sasl opendkim msmtp
e="$?"; [[ "$e" = "0" ]] || ( /usr/bin/echo 'Failed: !!' && exit "$e" )

# Generate the mailpassword appendage
mailpassgen="$(/usr/bin/pwgen -s -1 5)"

## Create the MySQL login .cnf
/usr/bin/echo "[client]
user = mail
password = mailpass${mailpassgen}
database = mail
host = localhost
" > /opt/verb/conf/sql/mysqldb.vmail.cnf
## Set the config for backup
/usr/bin/sed -i "s/ServerMailPassApg.*/ServerMailPassApg=\"${mailpassgen}\"/g" /opt/verb/conf/servermailpass

# Utility directories
/usr/bin/mkdir -p /srv/vip/vmail/customscripts /srv/vip/vmail/nativescripts /srv/vip/vmail/unsubscribe

# Virtual mail user
/usr/bin/mkdir -p /srv/vmail
/usr/bin/groupadd -g 5000 vmail
/usr/bin/useradd -u 5000 -g vmail -s /usr/bin/nologin vmail
/usr/bin/usermod -d /srv/vmail vmail
/usr/bin/chmod -R 770 /srv/vmail
/usr/bin/chown -R vmail:vmail /srv/vmail
## Symlink for legacy support
if [ ! -d "/var/vmail" ]; then
  /usr/bin/ln -sfn /srv/vmail /var/vmail
  /usr/bin/chown -R vmail:vmail /var/vmail
fi

# Postfix
## Copy configs
/usr/bin/touch /etc/postfix/virtual_ssl.map
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/main.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/master.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_alias_domains.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_alias_domains_maps.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_alias_maps.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_mailbox_domains.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_mailbox_domainaliases_maps.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_mailbox_maps.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/virtual_sender_login_maps.cf /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/header_checks /etc/postfix/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfix/smtp_header_checks /etc/postfix/
/usr/bin/rm /etc/postfix/main.cf.default
## Replace configs
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_alias_domains.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_alias_domains_maps.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_alias_maps.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_mailbox_domains.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_mailbox_domainaliases_maps.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_mailbox_maps.cf
/usr/bin/sed -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/postfix/virtual_sender_login_maps.cf
/usr/bin/sed -i "s/hostURI286/${hostURI}/g" /etc/postfix/main.cf
## Permissions
/usr/bin/chmod 644 /etc/postfix/virtual_alias_domains.cf
/usr/bin/chmod 644 /etc/postfix/virtual_alias_domains_maps.cf
/usr/bin/chmod 644 /etc/postfix/virtual_alias_maps.cf
/usr/bin/chmod 644 /etc/postfix/virtual_mailbox_domains.cf
/usr/bin/chmod 644 /etc/postfix/virtual_mailbox_domainaliases_maps.cf
/usr/bin/chmod 644 /etc/postfix/virtual_mailbox_maps.cf
/usr/bin/chmod 644 /etc/postfix/virtual_sender_login_maps.cf
## Unsubscribe framework for verber URI emails (normally done by inkvmailaddscriptfilter for hosted domains)
### Dependent on framework provided by https://serverfault.com/a/1130023/487033
emailaddress="unsubscribe@${nameURI}"
scriptname="unsubscribe$(/usr/bin/echo ${nameURI} | /usr/bin/sed "s/[^[:alnum:]]//g")"
/usr/bin/echo "#!/bin/bash
/usr/bin/echo \$1 >> /srv/vip/vmail/unsubscribe/${nameURI}" > "/srv/vip/vmail/nativescripts/${scriptname}"
/usr/bin/chmod 750 /srv/vip/vmail/nativescripts/${scriptname}
scriptpath="/srv/vip/vmail/nativescripts/${scriptname}"
/usr/bin/echo "
# inkVmail script filters (automatically managed, do not change)
${scriptname} unix -    n    n    -    -     pipe flags=Rq user=vmail argv=${scriptpath} \${sender} # script filter default" >> /etc/postfix/master.cf
/usr/bin/echo "
# inkVmail script filters (automatically managed, do not change)
${emailaddress} FILTER ${scriptname}:dummy # script filter default" >> /etc/postfix/transport
/usr/bin/postmap /etc/postfix/transport
## Service
/usr/bin/systemctl enable postfix
/usr/bin/systemctl start postfix

# SASL
/usr/bin/mkdir -p /etc/sasl2
/usr/bin/cat <<EOF > /etc/sasl2/smtpd.conf
pwcheck_method: saslauthd
mech_list: PLAIN LOGIN
log_level: 7
EOF
/usr/bin/mkdir -p /etc/pam.d
/usr/bin/cat <<EOF > /etc/pam.d/smtp
#%PAM-1.0
auth            required        pam_unix.so
account         required        pam_unix.so
EOF
## Service
/usr/bin/systemctl enable saslauthd
/usr/bin/systemctl start saslauthd

# Dovecot
/usr/bin/mkdir -p /etc/dovecot/sieve.before.d /etc/dovecot/sieve-filter /etc/dovecot/crt.d
/usr/bin/cp -r /usr/share/doc/dovecot/example-config/conf.d /etc/dovecot
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/dovecot.conf /etc/dovecot/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/10-auth.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/10-mail.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/10-master.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/10-ssl.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/15-lda.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/15-mailboxes.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/20-lmtp.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/20-lmtp.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/20-managesieve.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/90-plugin.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/conf.d/90-sieve.conf /etc/dovecot/conf.d/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/dovecot-sql.conf.ext /etc/dovecot/
/usr/bin/cp /opt/verb/conf/lib/vmail/dovecot/dovecot.conf /etc/dovecot/
### Diffie-Hellman Group file (unique & extra large for email server)
/usr/bin/rm -f /etc/dovecot/dh.pem
#/usr/bin/openssl dhparam -out /etc/dovecot/dh.pem 4096
/usr/bin/openssl dhparam -out /etc/dovecot/dh.pem 2048
/usr/bin/chmod 600 /etc/dovecot/dh.pem
## Replace configs
/usr/bin/sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/10-ssl.conf
/usr/bin/sed  -i "s/nameURI286/${nameURI}/g" /etc/dovecot/conf.d/15-lda.conf
/usr/bin/sed  -i "s/mailpassword/mailpass${mailpassgen}/g" /etc/dovecot/dovecot-sql.conf.ext
## Own
/usr/bin/chown -R vmail:dovecot /etc/dovecot
/usr/bin/chmod -R o-rwx /etc/dovecot
## Service
/usr/bin/systemctl enable dovecot
/usr/bin/systemctl start dovecot

# SpamAssassin
/opt/verb/serfs/installspamassassin
#/opt/verb/serfs/installspamassassin clamav # Usee the 'clamav' argument to also install clamav, otherwise you can run the serf later 'installclamav' if you want to install clamav

# Spam filter
. /opt/verb/conf/servermailpath
if [ SpamAssassinStatus = "INSTALLED" ]; then
  ## Dovecot integration
  /usr/bin/mkdir -p /etc/dovecot/sieve-filter
  /usr/bin/cat <<EOF > /var/lib/dovecot/sieve/global_sieves/move_to_spam_folder.sieve
require "spamtestplus";
require "fileinto";
require "relational";
require "comparator-i;ascii-numeric";

if spamtest :value "ge" :comparator "i;ascii-numeric" "5" {
  fileinto "Junk";
}
EOF
  /usr/bin/ln -sfn /usr/bin/vendor_perl/spamc /etc/dovecot/sieve-filter/spamc
  #DEV why is this EOFdoc here?
  /usr/bin/cat <<EOF > /etc/dovecot/sieve.before.d/spamassassin.sieve
require [ "vnd.dovecot.filter" ];
filter "spamc" [ "-d", "127.0.0.1", "--no-safe-fallback" ];
EOF
  ## Compile the SpamAssassin Dovecot Sieve rules
  /usr/bin/sievec /var/lib/dovecot/sieve/global_sieves
  ## Services
  /usr/bin/systemctl enable spamassassin.service; wait
  /usr/bin/systemctl start spamassassin.service; wait
  /usr/bin/systemctl enable spamassassin-update.timer; wait
  /usr/bin/systemctl start spamassassin-update.timer; wait
  /usr/bin/systemctl restart spamassassin.service; wait
  if [ "$?" = "0" ]; then /usr/bin/echo "SpamAssassin installed and enabled."; else /usr/bin/echo "SpamAssassin could not be enabled for some reason."; fi
else
  /usr/bin/echo "SpamAssassin not installed yet for dev reasons."
fi

# Virtual mail SQL database
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE mail DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON mail.* TO 'mail'@'localhost' IDENTIFIED BY 'mailpass${mailpassgen}';
FLUSH PRIVILEGES;"

# SSL certs
## Directory
/usr/bin/mkdir -p /etc/ssl/server/mail
## Snakeoil
if /usr/bin/grep -Fq "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${nameURI}; then
  /usr/bin/rm -f /etc/ssl/server/mail/vmail.crt
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/server.crt?ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/mail/vmail.crt?#ssl_cert = </etc/ssl/server/mail/vmail.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/rm -f /etc/ssl/server/mail/vmail.key
  /usr/bin/sed -i "s?^#smtpd_tls_chain_files = /etc/ssl/server/server.key?smtpd_tls_chain_files = /etc/ssl/server/server.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/server.crt?ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?#smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/mail/vmail.key?#ssl_key = </etc/ssl/server/mail/vmail.key?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_dh = </etc/dovecot/dh.pem?#ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
## inkCert
else
  /opt/verb/serfs/setinkcertmailcerts ${nameURI} inkvmail
  /opt/verb/serfs/setinkcertmail ${nameURI} vmail
fi

# Create the mailbox table
## We want these UNIQUE so we can update/insert appropriately with inkvmailsys* tools
## Note: Use as reference dev/mail-*.sql
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqldb.vmail.cnf -e "DROP TABLE IF EXISTS 'admin';
CREATE TABLE 'admin' (
  'username' varchar(255) NOT NULL,
  'password' varchar(255) NOT NULL,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'modified' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  'superadmin' tinyint(1) NOT NULL DEFAULT 0,
  'phone' varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'email_other' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'token' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'token_validity' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY ('username')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Admins';
DROP TABLE IF EXISTS 'alias';
CREATE TABLE 'alias' (
  'address' varchar(255) NOT NULL,
  'goto' text NOT NULL,
  'domain' varchar(255) NOT NULL,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'modified' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY ('address'),
  KEY 'domain' ('domain')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Aliases';
DROP TABLE IF EXISTS 'alias_domain';
CREATE TABLE 'alias_domain' (
  'alias_domain' varchar(255) NOT NULL DEFAULT '',
  'target_domain' varchar(255) NOT NULL DEFAULT '',
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'modified' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY ('alias_domain'),
  KEY 'active' ('active'),
  KEY 'target_domain' ('target_domain')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Domain Aliases';
DROP TABLE IF EXISTS 'config';
CREATE TABLE 'config' (
  'id' int(11) NOT NULL AUTO_INCREMENT,
  'name' varchar(20) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  'value' varchar(20) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY ('id'),
  UNIQUE KEY 'name' ('name')
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PostfixAdmin settings';
INSERT INTO 'config' VALUES
(1,'version','1847');
DROP TABLE IF EXISTS 'domain';
CREATE TABLE 'domain' (
  'domain' varchar(255) NOT NULL,
  'description' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  'aliases' int(10) NOT NULL DEFAULT 0,
  'mailboxes' int(10) NOT NULL DEFAULT 0,
  'maxquota' bigint(20) NOT NULL DEFAULT 0,
  'quota' bigint(20) NOT NULL DEFAULT 0,
  'transport' varchar(255) NOT NULL,
  'backupmx' tinyint(1) NOT NULL DEFAULT 0,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'modified' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  'password_expiry' int(11) DEFAULT 0,
  PRIMARY KEY ('domain')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Domains';
DROP TABLE IF EXISTS 'domain_admins';
CREATE TABLE 'domain_admins' (
  'username' varchar(255) NOT NULL,
  'domain' varchar(255) NOT NULL,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  'id' int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ('id'),
  KEY 'username' ('username')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Domain Admins';
DROP TABLE IF EXISTS 'fetchmail';
CREATE TABLE 'fetchmail' (
  'id' int(11) unsigned NOT NULL AUTO_INCREMENT,
  'mailbox' varchar(255) NOT NULL,
  'src_server' varchar(255) NOT NULL,
  'src_auth' enum('password','kerberos_v5','kerberos','kerberos_v4','gssapi','cram-md5','otp','ntlm','msn','ssh','any') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  'src_user' varchar(255) NOT NULL,
  'src_password' varchar(255) NOT NULL,
  'src_folder' varchar(255) NOT NULL,
  'poll_time' int(11) unsigned NOT NULL DEFAULT 10,
  'fetchall' tinyint(1) unsigned NOT NULL DEFAULT 0,
  'keep' tinyint(1) unsigned NOT NULL DEFAULT 0,
  'protocol' enum('POP3','IMAP','POP2','ETRN','AUTO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  'usessl' tinyint(1) unsigned NOT NULL DEFAULT 0,
  'extra_options' text DEFAULT NULL,
  'returned_text' text DEFAULT NULL,
  'mda' varchar(255) NOT NULL,
  'date' timestamp NOT NULL DEFAULT '2000-01-01 08:00:00',
  'sslcertck' tinyint(1) NOT NULL DEFAULT 0,
  'sslcertpath' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT '',
  'sslfingerprint' varchar(255) DEFAULT '',
  'domain' varchar(255) DEFAULT '',
  'active' tinyint(1) NOT NULL DEFAULT 0,
  'created' timestamp NOT NULL DEFAULT '2000-01-01 08:00:00',
  'modified' timestamp NOT NULL DEFAULT current_timestamp(),
  'src_port' int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY ('id')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
DROP TABLE IF EXISTS 'log';
CREATE TABLE 'log' (
  'timestamp' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'username' varchar(255) NOT NULL,
  'domain' varchar(255) NOT NULL,
  'action' varchar(255) NOT NULL,
  'data' text NOT NULL,
  'id' int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ('id'),
  KEY 'timestamp' ('timestamp'),
  KEY 'domain_timestamp' ('domain','timestamp')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Log';
DROP TABLE IF EXISTS 'mailbox';
CREATE TABLE 'mailbox' (
  'username' varchar(255) NOT NULL,
  'password' varchar(255) NOT NULL,
  'name' varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  'maildir' varchar(255) NOT NULL,
  'quota' bigint(20) NOT NULL DEFAULT 0,
  'local_part' varchar(255) NOT NULL,
  'domain' varchar(255) NOT NULL,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'modified' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  'phone' varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'email_other' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'token' varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL DEFAULT '',
  'token_validity' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'password_expiry' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  PRIMARY KEY ('username'),
  KEY 'domain' ('domain')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Mailboxes';
DROP TABLE IF EXISTS 'quota';
CREATE TABLE 'quota' (
  'username' varchar(255) NOT NULL,
  'path' varchar(100) NOT NULL,
  'current' bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY ('username','path')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
DROP TABLE IF EXISTS 'quota2';
CREATE TABLE 'quota2' (
  'username' varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  'bytes' bigint(20) NOT NULL DEFAULT 0,
  'messages' int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY ('username')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS 'vacation';
CREATE TABLE 'vacation' (
  'email' varchar(255) NOT NULL,
  'subject' varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  'body' text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  'cache' text NOT NULL,
  'domain' varchar(255) NOT NULL,
  'created' datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  'active' tinyint(1) NOT NULL DEFAULT 1,
  'modified' timestamp NOT NULL DEFAULT current_timestamp(),
  'activefrom' timestamp NOT NULL DEFAULT '2000-01-01 08:00:00',
  'activeuntil' timestamp NOT NULL DEFAULT '2038-01-18 08:00:00',
  'interval_time' int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY ('email'),
  KEY 'email' ('email')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci COMMENT='Postfix Admin - Virtual Vacation';
DROP TABLE IF EXISTS 'vacation_notification';
CREATE TABLE 'vacation_notification' (
  'on_vacation' varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  'notified' varchar(255) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  'notified_at' timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY ('on_vacation','notified'),
  CONSTRAINT 'vacation_notification_pkey' FOREIGN KEY ('on_vacation') REFERENCES 'vacation' ('email') ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci COMMENT='Postfix Admin - Virtual Vacation Notifications';"

# OpenDKIM
## Create/reset OpenDKIM files
/bin/mkdir -p /etc/opendkim/keys
/bin/cp /opt/verb/conf/lib/vmail/default/opendkim /etc/default/
/bin/cp /opt/verb/conf/lib/vmail/opendkim.conf /etc/opendkim/
/bin/echo "127.0.0.1
localhost
${hostURI}" > /etc/opendkim/TrustedHosts
## IP4?
if [ "${ServerIPv4}" != "NOIP4" ]; then
  /bin/echo "${ServerIPv4}" >> /etc/opendkim/TrustedHosts
fi
## IP6?
if [ "${ServerIPv6}" != "NOIP6" ]; then
  /bin/echo "${ServerIPv6}" >> /etc/opendkim/TrustedHosts
fi
/bin/echo "inkdkim._domainkey.${nameURI} ${nameURI}:inkdkim:/etc/opendkim/keys/${nameURI}/inkdkim.private" > /etc/opendkim/KeyTable
/bin/echo "${nameURI} inkdkim._domainkey.${nameURI}" > /etc/opendkim/SigningTable
## OpenDKIM Key for initial site
/bin/mkdir -p /etc/opendkim/keys/${nameURI}
cd /etc/opendkim/keys/${nameURI} || exit 6
/usr/bin/opendkim-genkey -r -S -s inkdkim -d ${nameURI}; wait
cd ${oldPwd} || exit 6
/bin/chmod 660 /etc/opendkim/keys/${nameURI}/inkdkim.private
/bin/chown -R opendkim:opendkim /etc/opendkim
## Start
/usr/bin/systemctl enable opendkim
/usr/bin/systemctl start opendkim

# DNS MX and TXT mail records for this server
/opt/verb/serfs/inkdnsaddmail ${nameURI} verber; wait
## DKIM keys & TXT records
/opt/verb/serfs/newinkdkim ${nameURI}; wait
/opt/verb/serfs/inkdnsaddinkdkim ${nameURI} verber; wait

# UFW (services and ports below them if known)
/usr/bin/ufw allow smtp
/usr/bin/ufw allow 25
/usr/bin/ufw allow 587
#/usr/bin/ufw deny smtps # no such rule profile
/usr/bin/ufw deny 465
/usr/bin/ufw allow pop3s
/usr/bin/ufw allow 995
/usr/bin/ufw deny pop3
/usr/bin/ufw deny 110
/usr/bin/ufw allow imaps
/usr/bin/ufw allow 993
/usr/bin/ufw deny imap
/usr/bin/ufw deny 143

# Close OpenDKIM (validation is through DNS records, not contacting the server)
/usr/bin/ufw deny 8891
/usr/bin/ufw deny 12301

# Monit
#/bin/cp /opt/verb/conf/lib/vmail/monit/monitrc.d/amavis /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lib/vmail/monit/monitrc.d/dovecot /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lib/vmail/monit/monitrc.d/opendkim /etc/monit/monitrc.d/
/bin/cp /opt/verb/conf/lib/vmail/monit/monitrc.d/postfix /etc/monit/monitrc.d/
# /bin/cp /opt/verb/conf/lib/vmail/monit/monitrc.d/spamassassin /etc/monit/monitrc.d/ moved to installspamassassin
/bin/systemctl enable monit
/bin/systemctl start monit

# Config settings to "EMAIL_INSTALLED"
/bin/sed -i "s/ServerMailStatus=.*/ServerMailStatus=\"VMAIL_SERVER\"/g" /opt/verb/conf/servermailpath

# PHP mail log
if ! /usr/bin/grep -q '^mail.log = /var/log/phpmail.log' /opt/verb/conf/php.ini; then
  /bin/sed -i "s/^mail.log = /;mail.log = /" /opt/verb/conf/php.ini
  if /usr/bin/grep -q ';mail.log = /var/log/phpmail.log' /opt/verb/conf/php.ini; then
    /bin/sed -i "s?^;mail.log = /var/log/phpmail.log?mail.log = /var/log/phpmail.log?" /opt/verb/conf/php.ini
  else
    /bin/echo "mail.log = /var/log/phpmail.log" >> /opt/verb/conf/php.ini
  fi
  /usr/bin/systemctl restart httpd
fi
/usr/bin/touch /var/log/phpmail.log
/usr/bin/chown www:www /var/log/phpmail.log

# System domains & addresses
## Note: If the mail database needs to be reset, such as for a PostfixAdmin update, just run this after, then the results of this serf will be up to date
## Add base domains & addresses
/opt/verb/serfs/inkvmailverbaddrs
## Setup system mail
/opt/verb/serfs/inkvmailsysmailboxmsmtp

# Grand Restart
if [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl restart nginx; wait
  /usr/bin/systemctl restart httpd; wait
elif [ ${ServerType} = "lemp" ]; then
  /usr/bin/systemctl restart nginx; wait
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/systemctl restart httpd; wait
fi

# LMDB maps
## We need a database building tool to make these files readable by Postfix
## Per this Arch BBS discussion: https://bbs.archlinux.org/viewtopic.php?pid=2164822#p2164822
## Some of these might not be necessary, but this is what was done to get things working
## This was original
/usr/bin/postmap -F lmdb:/etc/postfix/virtual_ssl.map # -F is to read how we have this file set up
## These are used and had .db files, so we add this
/usr/bin/postalias lmdb:/etc/postfix/aliases # This is declared in main.cf
/usr/bin/postmap lmdb:/etc/postfix/transport # We use this for our unsubscribe sieve plugin
/usr/bin/postmap lmdb:/etc/postfix/virtual # We don't ust this at all, no contents, only comments
## This was done once and recommended, but may not be necessary for our configuration
## This will result in .lmdb files being created, used instead of .db files
##DEV since we aren't using these, but they were done once in a fix, they are here for reference
# /usr/bin/touch /etc/postfix/sni.map # We may not even be using this
# /usr/bin/touch /etc/postfix/rbl_override # We may not even be using this
# /usr/bin/touch /etc/postfix/dnsbl-reply-map # We may not even be using this
# /usr/bin/postmap -F lmdb:/etc/postfix/sni.map # We may not even be using this, we use /etc/postfix/virtual_ssl.map for SNI settings
# /usr/bin/postmap lmdb:/etc/postfix/dnsbl-reply-map # We may not even be using this
# /usr/bin/postmap lmdb:/etc/postfix/rbl_override # We may not even be using this
# /usr/bin/postmap lmdb:/etc/postfix/generic
# /usr/bin/postmap lmdb:/etc/postfix/access
# ## Remove any of these, just to be sure, but without using hash:/etc/postfix/... there shouldn't be any
# /usr/bin/rm /etc/postfix/*.db # Just to be sure, no longer doing hash:/etc/postfix/transport

/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart spamassassin
#/usr/bin/systemctl restart clamav-daemon
/usr/bin/systemctl restart dovecot
/usr/bin/systemctl daemon-reload

# Remove unneeded packages
/usr/bin/pacman -Rsc --noconfirm
/usr/bin/pacman -Scc --noconfirm
#/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm' # We didn't install an AUR packages
#/usr/local/bin/yeo -Scc --noconfirm # We didn't install an AUR packages

# Finish
/bin/echo "The Postfix vmail server for inkVerb has been installed.
The email server is https://${emailTLDURI}
"




if [ -e "/opt/verb/mods/installpostfixvmail.after" ]; then . /opt/verb/mods/installpostfixvmail.after; fi # Follows this script
