#!/bin/bash
#inkVerbSerf! verb.ink

# This installs droids from a git repo.

# How to use:
## installdroid [ http://github.com/clonePathTo/droidRepo - optional to avoid dialogue ]

# Eg:
## installdroid 
## installdroid https://github.com/inkVerb/droids


usagenotes="This installs droids from a git repo."
usageformat="installdroid"
usageexample="installdroid"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installdroid.replace" ]; then . /opt/verb/mods/installdroid.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installdroid.before" ]; then . /opt/verb/mods/installdroid.before; fi # Precedes this script


DROIDRepo=$1

# Sanitize repo
CLNDROIDRepo1=$(/bin/echo $DROIDRepo | cut -d'/' -f5-)
CLNDROIDRepo=$(/bin/echo $CLNDROIDRepo1 | /usr/bin/sed 's/\.git//')

# Clone it
cd /opt/verb/droids || exit 6
git clone ${DROIDRepo}

# Clean up and install
cd ${CLNDROIDRepo} || exit 6
/bin/chmod 750 vd*
/bin/mv vd* ../
cd .. || exit 6
/bin/rm -rf ${CLNDROIDRepo}

# Finish
/bin/echo "The droids from \"${CLNDROIDRepo}\" are installed."





if [ -e "/opt/verb/mods/installdroid.after" ]; then . /opt/verb/mods/installdroid.after; fi # Follows this script
