#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs the current verified version of suiteCRM from inkisaverb.com/repo to crm.your-name.verb.red

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installsuitecrm [dbase] [dbuser] [dbpassword]


cVappName=suitecrm

# Include the config
. /opt/verb/conf/siteurilist

dBase=$1
dBaseUser=$2
dBPassword=$3
cleanName=$(/bin/echo $cVappName | sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/www/vapps/${cVappName} ]; then
/bin/echo "SuiteCRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi

# Include the config file
. /opt/verb/conf/servernameip

# This does not create a database, only an administrator since suiteCRM will create that automatically

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check; wait
e="$?"; [[ "$e" = "0" ]] || exit "$e"

cd /srv/www/html || exit 6
/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/chown -R www:www /srv/www/verb/red.crm; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Auto database
if [ -z ${3} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
dBase=${cleanName}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
dBaseUser=${dBase}; fi

# Create the database user and credentials
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON *.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}' WITH GRANT OPTION;
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}

/bin/echo "These are setup:

Database: ${dBase}
Host Name: localhost (do not use crm....verb.red)
Database user: ${dBaseUser}
Database password: ${dBPassword}

*The SuiteCRM installer can be finicky. Be mindful of all details. Copy-paste into fields whenever possible.

*Choose \"Provide Existing User\" BEFORE entering above information.

Go to the http://crm.${redURI} site to install.
"




if [ -e "/opt/verb/mods/installsuitecrm.after" ]; then . /opt/verb/mods/installsuitecrm.after; fi # Follows this script
