#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs OrangeHRM manually from inkisaverb.com/repo and linnks it to ....verb.blue

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installorangehrm [dbase] [dbuser] [dbpassword]


cVappName=orangehrm

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

dBase=$1
dBaseUser=$2
dBPassword=$3
cleanName=$(/bin/echo $cVappName | /usr/bin/sed -e 's/\.//g')

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/www/vapps/${cVappName} ]; then
/bin/echo "OrangeHRM already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi

# Download and unpack the latest checked version from inkisaverb.com/repo
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check; wait
e="$?"; [[ "$e" = "0" ]] || exit "$e"

/bin/mkdir -p /srv/www/vapps/${cVappName}/lib/logs
/bin/mkdir -p /srv/www/vapps/${cVappName}/symfony/cache
/bin/mkdir -p /srv/www/vapps/${cVappName}/symfony/log
/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/chown -R www:www /srv/www/verb/red.hrm; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Auto database
if [ -z ${3} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
dBase=${cleanName}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
dBaseUser=${dBase}; fi

# Create the database and credentials
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Config files
## Preconfig setup is currently disabled until OrangeHRM installation allows, but this would be a start:
#cp /srv/www/vapps/orangehrm/lib/confs/Conf.php-distribution /srv/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbname   = 'hr_mysql'/dbname   = '${dBase}'/g" /srv/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbuser   = 'root'/dbuser   = '${dBaseUser}'/g" /srv/www/vapps/orangehrm/lib/confs/Conf.php
#sed -i "s/dbpass   = 'orangehrm'/dbpass   = '${dBPassword}'/g" /srv/www/vapps/orangehrm/lib/confs/Conf.php

# Firewall
/usr/bin/ufw allow 3306

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}

/bin/echo "These are setup:

Database Host Name: localhost
Database: ${dBase}
OrangeHRM Database user (and Privileged user if applicable, use the same): ${dBaseUser}
Database user password: ${dBPassword}

*Select \"Existing database\" in setup to make life easier, if you want.
*Enable Data Encryption? - Probably NOT!

Go to http://hrm.${redURI} to install.
"




if [ -e "/opt/verb/mods/installorangehrm.after" ]; then . /opt/verb/mods/installorangehrm.after; fi # Follows this script
