#!/usr/bin/env bash
#inkVerbSerf! verb.ink

# This installs phpMyAdmin to a defiend directory, to become available at mysql.your-name.verb.vip/DEFINED-DIRECTORY

# How to use:
## ./installphpmyadmin [directory] [dbuser] [dbpassword]


cVappName=phpmyadmin

# Options
if [ -z ${1} ]; then
/bin/echo "You must designate a folder."
exit 8; fi

DIRECTRY=${1}

# Auto database
if [ -z ${3} ]; then
dBPassword=$(/usr/bin/pwgen -c -1 20); fi
if [ -z ${2} ]; then
dBaseUser=phpmy$(/usr/bin/pwgen -s -1 15); fi

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapp.${cVappName} ]; then
/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/www/vapps/${cVappName} ]; then
/bin/echo "phpMyAdmin already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi

# Download and establish Drupal in the server to pre-created domain
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check; wait
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Create the boss user
/opt/verb/serfs/mysqlnewboss "${dBaseUser}" "${dBPassword}"

# Write the config for backup
/bin/echo "SUBdir=${DIRECTRY}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapp.${cVappName}

# Prepare the config and web directory
/bin/cp /srv/www/vapps/${cVappName}/config.sample.inc.php /srv/www/vapps/${cVappName}/config.inc.php
BLOWFISH=$(/usr/bin/pwgen -c -1 32)
/bin/sed -i "s/cfg\['blowfish_secret'\] = '';/cfg\['blowfish_secret'\] = '$BLOWFISH';/" /srv/www/vapps/${cVappName}/config.inc.php
/bin/ln -sfn /srv/www/vapps/${cVappName} /srv/www/verb/${itsqlTLD}.sql/${DIRECTRY}; wait
/bin/chown -R www:www /srv/www/verb/${itsqlTLD}.sql; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Restart server
. /opt/verb/conf/servertype
if [ ${ServerType} = "lemp" ]; then
  /usr/bin/systemctl restart nginx
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/systemctl restart httpd
elif [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

/bin/echo "
PHP My Admin now active & this MySQL admin is setup:

Username: ${dBaseUser}
Password: ${dBPassword}

Use these credentials to log in at https://sql.${vipURI}/${DIRECTRY}
"




if [ -e "/opt/verb/mods/installphpmyadmin.after" ]; then . /opt/verb/mods/installphpmyadmin.after; fi # Follows this script
