#!/usr/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs ownCloud (OCIS) manually and runs it on ....verb.blue
## The "cloud" subdomain is intended for heavyweight deployments dedicateing the .blue server to one cloud service, having multiple verb namespaces, with Pydio, OCIS, and Nextcloud all using the same "cloud" subdomsin with the three different namespaces

# An optional database block exists, but needs uncommenting and updates to usage meta and final message at end of script, see instructions all in the commented block
## The database is probably never used, only for External IDP Integration
## The purpose of this new database is to create a blank database that can be imported outside this script
## If used, the usage syntax would be:
### installowncloud [ dbase - optional ] [ dbuser - optional ] [ dbpassword - optional ]
## Eg:
### ./installowncloud bestdbase bestdbuser besteverpass
## Then serf header options would change to:
# usageformat="installowncloud [ cab/clooud ] [ dbase - optional ] [ dbuser - optional ] [dbpassword - optional ]"
# usageexample="installowncloud
# installowncloud bestdbase bestdbuser besteverpass"
# voptnames=( "Database" "Database user" "Database password" )
# vopttypes=( isSQLDatabasename isSQLDatabasename isSQLDatabasename )

# How to use:
## ./installowncloud [ alt subdomain "cloud" - defualt "cab" ]

# Eg:
## ./installowncloud
## ./installowncloud cloud


usagenotes="This downloads and installs ownCloud (OCIS) manually and runs it on ....verb.blue"
usageformat="installowncloud [ alt subdomain "cloud" - defualt "cab" ]"
usageexample="installowncloud
installowncloud cloud"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "Alt subdomain: cloud" )
vopttypes=( isChoice )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( inkget inkemailsysowncloud inkvmailsysowncloud inkcert_ inkdriveapp )
useconfigs=( servernameip siteurilist servertype servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installowncloud.replace" ]; then . /opt/verb/mods/installowncloud.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installowncloud.before" ]; then . /opt/verb/mods/installowncloud.before; fi # Precedes this script


cVappName=owncloud

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype
. /opt/verb/conf/servermailpath

# Check if already installed
## Config
if [ -f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
/usr/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/cloud/${cVappName} ]; then
/usr/bin/echo "ownCloud already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi
## Web server
if [ ${ServerType} = "lamp" ]; then
/usr/bin/echo "Only allowed with Nginx servers, LEMP or LAEMP; LAMP servers with Apache not allowed."
exit 0; fi
# Check prerequesites
if [ ${ServerMailStatus} = "EMAIL_NOT_INSTALLED" ]; then
/usr/bin/echo "
Email server not installed, can't install ownCloud.
"
exit 0; fi

# Subdomain
if [ -n ${1} ] && [ "${1}" = "cloud" ]; then
  subDom="cloud"
else
  subDom="cab"
fi

# # Auto database
# cleanName=$(/usr/bin/echo $cVappName | /usr/bin/sed -e 's/\.//g')
# if [ -z ${4} ]; then
# dBPassword=$(/usr/bin/pwgen -s -1 10)
# else
# dBPassword="$4"
# fi
# if [ -z ${2} ]; then
# dBase=${cleanName}$(/usr/bin/pwgen -s -1 6)
# else
# dBase="$2"
# fi
# if [ -z ${3} ]; then
# dBaseUser=${dBase}
# else
# dBaseUser="$3"
# fi

# Download as vapp
cd /srv/cloud || exit 6
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Install as local/bin
/usr/bin/mkdir -p /usr/local/bin
/usr/bin/mv -f /srv/cloud/owncloud/ocis /usr/local/bin/ocis
/usr/bin/echo "Binary at /usr/local/bin/ocis" > /srv/cloud/owncloud/ocis.bin.installed
/usr/bin/chmod 755 /usr/local/bin/ocis

# User & data directories
/usr/bin/useradd -r -U -s /usr/bin/nologin -d /srv/cloud/ocis ocis
## FSH
#DEV Not using the standard /var/lib/..., we want /srv/... for block storage-readiness
# /usr/bin/mkdir -p /var/lib/ocis
# /usr/bin/chown -R ocis:ocis /var/lib/ocis
## Served data (block storage serve-ready)
/usr/bin/mkdir -p /srv/cloud/ocis
/usr/bin/chown -R ocis:ocis /srv/cloud/ocis

# Configure in the service file
/usr/bin/cat << EOF > /etc/systemd/system/ocis.service
[Unit]
Description=ownCloud Infinite Scale Stack
After=network.target

[Service]
User=ocis
Group=ocis

# Basic Configuration
WorkingDirectory=/srv/cloud/ocis

# Primary data storage location
Environment="OCIS_BASE_DATA_PATH=/srv/cloud/ocis"

# Network
Environment="OCIS_URL=https://${subDom}.${blueURI}"
Environment="PROXY_HTTP_ADDR=0.0.0.0:9200"
Environment="PROXY_TLS=false" # Nginx handles SSL

# Security (Only allow write for base data path)
ReadWritePaths=/srv/cloud/ocis

# Systemctl Commands
ExecStart=/usr/local/bin/ocis server
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# # Optional blank database, ready to import database for External IDP Integration
# ## Uncomment this block to use it, but for most implementations this should never be necessary
# 
# ## New usage meta:
# usageformat="installowncloud  [ cab/clooud ] [dbase] [dbuser] [dbpassword]"
# usageexample="installowncloud
# installowncloud bestdbase bestdbuser besteverpass"
# 
# ## Auto database
# cleanName=$(/usr/bin/echo $cVappName | /usr/bin/sed -e 's/\.//g')
# if [ -z ${3} ]; then
# dBPassword=$(/usr/bin/pwgen -s -1 10)
# else
# dBPassword=$3
# fi
# if [ -z ${1} ]; then
# dBase=${cleanName}$(/usr/bin/pwgen -s -1 6)
# else
# dBase=$1
# fi
# if [ -z ${2} ]; then
# dBaseUser=${dBase}
# else
# dBaseUser=$2
# fi
# 
# ## Create the database and credentials (needed now, before service starts)
# /usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
# CREATE DATABASE ${dBase} DEFAULT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
# GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
# FLUSH PRIVILEGES;"
# ## Write the config for backup
# /usr/bin/echo "appDBase=${dBase}
# appDDBUsr=${dBaseUser}
# appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}
# ## Append database info in the service file
# /usr/bin/cat << EOF >> /etc/systemd/system/ocis.service
#
# ## Database Configuration
# Environment="OCIS_DB_ENGINE=mysql"
# Environment="OCIS_DB_HOST=127.0.0.1"
# Environment="OCIS_DB_PORT=3306"
# Environment="OCIS_DB_NAME=${dBase}"
# Environment="OCIS_DB_USER=${dBaseUser}"
# Environment="OCIS_DB_Password=${dBPassword}"
# EOF
# 
## Add at end
# /usr/bin/echo "
# These are setup:

# Database: ${dBase}
# Database user: ${dBaseUser}
# Database password: ${dBPassword}
# "

# Initialize
##REF /usr/bin/sudo -u ocis ocis init # This is the basic command
## The ocis init command is interactive, so we need to echo-pipe the answer
/usr/bin/echo "no" | /usr/bin/sudo -u ocis OCIS_BASE_DATA_PATH=/srv/cloud/ocis ocis init
## Make sure our config folder exists for our notifications.yaml file for email settings; it should exist after running ocis init
/usr/bin/mkdir -p /srv/cloud/ocis/config
/usr/bin/systemctl daemon-reload
/usr/bin/systemctl enable --now ocis # enable and start in one command

# Webserver setup
if [ ${ServerType} = "laemp" ]; then
  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf.old
  /usr/bin/mv /opt/verb/conf/webserver/sites-available/httpd/${subDom}.${blueURI}.conf /opt/verb/conf/webserver/sites-available/httpd/${subDom}.${blueURI}.conf.old
  /usr/bin/cp /opt/verb/conf/site-files/conf/ocis.conf /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/${subDom}.${blueURI}.conf
  if [ "${subDom}" = "cloud" ]; then
    /usr/bin/sed -i "s?cab\.${blueURI}?cloud.${blueURI}?g" /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
    /usr/bin/sed -i "s?blue\.cab?blue.cloud?g" /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
  fi
elif [ ${ServerType} = "lemp" ]; then
  /usr/bin/mv /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf.old
  /usr/bin/cp /opt/verb/conf/site-files/conf/ocis.conf /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
  if [ "${subDom}" = "cloud" ]; then
    /usr/bin/sed -i "s?cab\.${blueURI}?cloud.${blueURI}?g" /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
    /usr/bin/sed -i "s?blue\.cab?blue.cloud?g" /opt/verb/conf/webserver/sites-available/nginx/${subDom}.${blueURI}.conf
  fi
fi

# Setup for inkCert
. /opt/verb/conf/inkcert/cli-ini/siteinkcert.${blueURI}
case ${InkCerted} in
  DONE_SC)
  /opt/verb/serfs/inkcertaddsc ${subDom}.${blueURI} ${blueURI}
  ;;
  DONE_LE)
  /opt/verb/serfs/inkcertaddle ${subDom}.${blueURI} ${blueURI}
  ;;
  DONE_CBSINGLE)
  /opt/verb/serfs/inkcertaddcbsingle ${subDom}.${blueURI} ${blueURI}
  ;;
  DONE_CB)
  /opt/verb/serfs/inkcertaddcb ${subDom}.${blueURI} ${blueURI}
  ;;
  NO|NOT_YET)
    /usr/bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
  ;;
  *)
    if ! /usr/bin/grep -q "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${domain}; then
      /usr/bin/echo "Something's wrong with the inkCert siteinkcert configs! Aborting"
      exit 6
    else
      /usr/bin/echo "Nextcloud is currently using Snakeoil certs, ready for inkCert"
    fi
  ;;
esac

# Webserver restart
if [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl restart nginx; wait
  /usr/bin/systemctl restart httpd; wait
elif [ ${ServerType} = "lemp" ]; then
  /usr/bin/systemctl restart nginx; wait
fi

# Use msmtp for a real SMTP address
## Postfix vmail?
if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
  /opt/verb/serfs/inkvmailsysowncloud

## Maddy email?
elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
  /opt/verb/serfs/inkemailsysowncloud

## Neither
else
  /usr/bin/echo "No email server detected, so not configuring email settings."
fi

# Monit
/usr/bin/cp /opt/verb/conf/lib/cloud/monit/monitrc.d/ocis /etc/monit/monitrc.d/
/usr/bin/chmod 700 /etc/monit/monitrc.d/*
## Restart or enable, just be safe
if systemctl is-active monit -q; then
  /usr/bin/systemctl restart monit
else 
  /usr/bin/systemctl enable --now monit
fi

# Finish
/usr/bin/echo "
Go to https://${subDom}.${blueURI} to finish installing.

"

# inkDrive? (last so above message shows, even if we need to exit non-zero next)
if [ -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  . /opt/verb/conf/inkdrive/inkdriveinfo
  if [ "${InkDriveCloud}" != "off" ]; then
    /usr/bin/echo "Mounting 'ocis' to a drive..."
    /opt/verb/serfs/inkdriveapp "${cVappName}" "${InkDriveCloud}"
    if [ "$?" = 0 ]; then
      /usr/bin/echo "InkDrive=\"${InkDriveCloud}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}
    else
      /usr/bin/echo "inkDrive hosting is expected, but unable to host ownCloud on the drive. Something is very wrong!"
      exit 6
    fi
  fi
fi




if [ -e "/opt/verb/mods/installowncloud.after" ]; then . /opt/verb/mods/installowncloud.after; fi # Follows this script
