#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs MediaWiki from the inkisaverb.com repository and links it to wiki.your-name.verb.ink

# All options are optional, but must are sequential, omit last options first.

# How to use:
## ./installmediawiki [dbase] [dbuser] [dbpassword]


cVappName=mediawiki

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

dBase=$1
dBaseUser=$2
dBPassword=$3
cleanName=$(/bin/echo $cVappName | sed -e 's/\.//g')

# Check if already installed
if [-f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
/bin/echo "This is already installed. I quit."
exit 0; fi

# Download and establish mediawiki from the inkVerb repo
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"

/opt/verb/serfs/setvapplinkon ${cVappName}; wait
/bin/chown -R www:www /srv/www/verb/ink.wiki; wait
/bin/chown -R www:www /srv/www/vapps/${cVappName}; wait

# Auto database
if [ -z ${3} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${1} ]; then
dBase=${cleanName}$(/usr/bin/pwgen -s -1 6); fi
if [ -z ${2} ]; then
dBaseUser=${dBase}; fi

# Create the database and credentials
/usr/bin/mysql --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}" > /opt/verb/conf/vapps/vapp.${cVappName}

/bin/echo "These are setup:

Host: localhost
Database name: ${dBase}
Database username: ${dBaseUser} (NOT root)
Database password: ${dBPassword}
Storage engine: InnoDB
Character Set: UTF-8
Return email address: use anything real, maybe yourname@${inkURI}, NOT something@wiki.${inkURI}

Go to http://wiki.${inkURI} to install.

After installing, download the LocalSettings.php file, then upload it to the \"vip\" web folder, then run postinstallmediawiki to complete in installation.
"




if [ -e "/opt/verb/mods/installmediawiki.after" ]; then . /opt/verb/mods/installmediawiki.after; fi # Follows this script
