#!/bin/bash
#inkVerbSerf! verb.ink

# Backward-compatible name: installs Go inkMail (agnostic) at po.emailURI
## Roundcube stays webmail. This is not PFA and not RC.

# How to use:
## ./installinkemailadmin [ path folder ]

usagenotes="This installs the Go inkMail control panel (formerly the PHP Maddy admin)"
usageformat="installinkemailadmin [ path folder - optional ]"
usageexample="installinkemailadmin
installinkemailadmin wink822"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "inkMail web path" )
vopttypes=( isazAZ09lines )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( installmaddymail )
useserfs=( installinkmail )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installinkemailadmin.replace" ]; then . /opt/verb/mods/installinkemailadmin.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installinkemailadmin.before" ]; then . /opt/verb/mods/installinkemailadmin.before; fi # Precedes this script


/opt/verb/serfs/installinkmail "$1"
e="$?"
exit "$e"



if [ -e "/opt/verb/mods/installinkemailadmin.after" ]; then . /opt/verb/mods/installinkemailadmin.after; fi # Follows this script
