#!/bin/bash
#inkVerbSerf! verb.ink

# This installs Maddy as the email server
## This creates a PostgreSQL database with blobs in /var/email/maddy/ (rather than /var/lib/maddy/)
## Prerequisite: sertupverb
## This only performs basic back-end server setup and creates no mail accounts
## Once this is done it is set for the server permanently.

# How to use:
## ./installmaddymail


usagenotes="This installs Maddy as the email server"
usageformat="installmaddymail"
usageexample="installmaddymail"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( "inkCert certs should be installled for at least the nameURI for this verber" )
usedby=( installinkemail )
useserfs=( inkget inkemailaddscriptfilter setinkcertmail inkdnsaddmail inkdnsaddinkdkim inkemailbaseaddrs inkemailsysmailboxmsmtp inkdriveapp)
useconfigs=( servernameip siteurilist servertype servermailpath )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installmaddymail.replace" ]; then . /opt/verb/mods/installmaddymail.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installmaddymail.before" ]; then . /opt/verb/mods/installmaddymail.before; fi # Precedes this script


cVappName=maddy

# Include the config files
. /opt/verb/conf/servertype
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath

# Check if vapp already installed
## Config
if [ -f /opt/verb/conf/vapps/vapp.${cVappName} ]; then
/usr/bin/echo "This is already installed."
exit 0; fi
## Directory
if [ -d /srv/email/${cVappName} ]; then
/usr/bin/echo "Maddy already exists in the system. If it isn't working, look deeper on the server. For now, doing nothing."
exit 8; fi
## Web server
if [ ${ServerType} = "lamp" ]; then
/usr/bin/echo "Only allowed with Nginx servers, LEMP or LAEMP; LAMP servers with Apache not allowed."
exit 0; fi

# Check to see if email already installed
if [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
/usr/bin/echo "
Maddy email server is already installed.
"
exit 0; fi
if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
/usr/bin/echo "
Postfix vmail server already installed.
"
exit 0; fi
if [[ "${ServerMailStatus}" =~ "_BACKUP_MX" ]]; then # Backup mail server could use Maddy or Postfix vmail or others, each needing its own, but must contain _BACKUP_MX in its setting
/usr/bin/echo "
Email server is already a backup server.
"
exit 0; fi
if [ "${ServerMailStatus}" != "MADDY_EMAIL_READY" ] && [ "${ServerMailStatus}" != "EMAIL_NOT_INSTALLED" ]; then
/usr/bin/echo "
Email server is already configured and cannot be installed.
"
exit 0; fi
if ! /usr/bin/grep -Fq 'Email Control Records' /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/usr/bin/echo "
Email Control Records not declared in the email domain DNS zone file. This won't work.
"
exit 7; fi
if [ "${EmailAllowed}" != "YES" ]; then
/usr/bin/echo "
Email not allowed on this server.
"
exit 0; fi

# Prepare config for Maddy now
## inkmaildomains and setinkcert* need this
/usr/bin/sed -i "s/ServerMailStatus=.*/ServerMailStatus=\"MADDY_EMAIL_READY\"/g" /opt/verb/conf/servermailpath

# Install Maddy server package
## Considered a cloud service, repo uses /srv/cloud for its vapp folder
cd /srv/cloud || exit 6
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Maddy email directory structure (for everything else, do this first)
/usr/bin/mkdir -p /srv/email/maddy/messages

# Maddy email user
#DEV one line, check which is best
# /usr/bin/useradd -mrU -s /sbin/nologin -d /srv/email/maddy -c "maddy mail server" maddy
/usr/bin/groupadd -g 5000 maddy
/usr/bin/useradd -u 5000 -g maddy -s /usr/bin/nologin maddy
/usr/bin/usermod -d /srv/email/maddy maddy
/usr/bin/chmod -R 770 /srv/email
/usr/bin/chown -R maddy:maddy /srv/email/maddy

# Install as local/bin
/usr/bin/mkdir -p /usr/local/bin
/usr/bin/mv /srv/cloud/maddy/maddy /usr/local/bin/
/usr/bin/echo "Binary at /usr/local/bin/maddy" > /srv/cloud/maddy/maddy.bin.installed
/usr/bin/chmod 755 /usr/local/bin/maddy

# Own everything
/usr/bin/chown -R maddy:maddy /srv/email/maddy
/usr/bin/chmod -R 755 /srv/email
/usr/bin/chmod -R 750 /srv/email/maddy

## Symlink for legacy support
if [ ! -d "/var/email/maddy" ]; then
  /usr/bin/ln -sfn /srv/email /var/email
  /usr/bin/chown -R maddy:maddy /var/email/maddy
fi

# Generate the mailpassword appendage
mailpassgen="$(/usr/bin/pwgen -s -1 5)"

# Create the PostgreSQL login .pgpass
/usr/bin/echo "localhost:5432:email:email:emailpass${mailpassgen}" > /opt/verb/conf/sql/pgsqldb.email.pgpass
/usr/bin/chmod 0600 /opt/verb/conf/sql/pgsqldb.email.pgpass

## Set the config for backup
/usr/bin/sed -i "s/ServerMailPassApg.*/ServerMailPassApg=\"${mailpassgen}\"/g" /opt/verb/conf/servermailpass

# Create the SQL items
## Make sure Postgres is running because it can take a while after system reboot, and it doesn't use systemctl
if ! /usr/bin/pg_isready --quiet; then /usr/bin/echo "Waiting for PostgreSQL..."; until /usr/bin/pg_isready --quiet; do /usr/bin/sleep 1; done; fi
/usr/bin/sudo -u postgres psql -c "CREATE USER email WITH PASSWORD 'emailpass${mailpassgen}';"
/usr/bin/sudo -u postgres psql -c "CREATE DATABASE email OWNER email;"

# Utility directories
/usr/bin/mkdir -p /srv/email/pass /srv/vip/email/customscripts /srv/vip/email/nativescripts /srv/vip/email/unsubscribe
## ACL
/usr/bin/setfacl -m u:maddy:rx /srv/vip/email/customscripts/
/usr/bin/setfacl -m u:maddy:rx /srv/vip/email/nativescripts/
/usr/bin/setfacl -m u:maddy:rx /srv/vip/email/unsubscribe/

# Config
/usr/bin/mkdir -p /etc/maddy/conf.d/unsubscribe /etc/maddy/conf.d/customscripts
/usr/bin/chmod 0755 /etc/maddy /etc/maddy/conf.d
/usr/bin/cp /opt/verb/conf/lib/cloud/maddy/maddy.conf /etc/maddy/

## Settings
/usr/bin/sed -i "s/domain286/${nameURI}/g" /etc/maddy/maddy.conf
/usr/bin/sed -i "s/emaildbpass286/emailpass${mailpassgen}/g" /etc/maddy/maddy.conf
## Domains framework
/usr/bin/cp /opt/verb/conf/lib/cloud/maddy/conf.d/domains.conf /etc/maddy/conf.d/domains.conf
#DEV Now obsolete, replaced by rspamd infrastructure
# # Unsubscribe header listings
# /usr/bin/cp /opt/verb/conf/lib/cloud/maddy/conf.d/unsub_domains.conf /etc/maddy/conf.d/unsub_domains.conf
## Aliases framework
/usr/bin/cp /opt/verb/conf/lib/cloud/maddy/conf.d/aliases.conf /etc/maddy/conf.d/aliases.conf
## Unsubscribe framework
/usr/bin/cp /opt/verb/conf/lib/cloud/maddy/conf.d/unsubscribe.conf /etc/maddy/conf.d/unsubscribe.conf
/usr/bin/sed -i "s/domain286/${nameURI}/g" /etc/maddy/maddy.conf
## Custom scripts framework
/usr/bin/echo "# This file is maintained automatically by inkemailaddscriptfilter, edits could break the file and other structure
## No tab syntax, each entry on one line for single-line entry and deletion" > /etc/maddy/conf.d/customscripts.conf
## Ownership
/usr/bin/chown root:maddy /etc/maddy/*.conf /etc/maddy/conf.d/*.conf
/usr/bin/chmod 0644 /etc/maddy/*.conf /etc/maddy/conf.d/*.conf

# Mail Domain DNS & SSL
## Directory
/usr/bin/mkdir -p /etc/ssl/server/mail
## Snakeoil?
if /usr/bin/grep -Fq "InkCerted=NO" /opt/verb/conf/inkcert/cli-ini/siteinkcert.${nameURI}; then
  /usr/bin/rm -f /etc/ssl/server/mail/email.crt
  /usr/bin/echo "InkCert not set up. No certs available for Maddy. It might not work."
## inkCert
else
  ### Certificates & structure
  #/opt/verb/serfs/setinkcertmailcerts ${nameURI} inkemail #DEV this is redundant, run right away in serfs/setinkcertmail
  #### We don't actually need these, but let's keep our framework in place
  /opt/verb/serfs/setinkcertmail ${nameURI} inkmail
  if [ -d "/etc/letsencrypt" ]; then
    ##### Maddy requires this or it cannot read the certs and will fail
    /usr/bin/setfacl -R -m u:maddy:rX /etc/letsencrypt/{live,archive}
    ##### Maddy specifically loves this
    /usr/bin/ln -sfn /etc/letsencrypt/live /etc/maddy/certs
    #/usr/bin/ln -sfn /etc/inkcert/le/live /etc/maddy/certs # viable alternative compatible with inkcert
  else
    /usr/bin/echo "Can't find certs for Maddy. It might not work."
  fi
fi
## Maddy wants at least one extra domain in /etc/maddy/conf.d/domains.conf BEFORE it can start (so we won't use inkemaildomain)
/usr/bin/sed -i "/^\$(extra_domains) =/ s/$/ ${emailTLDURI}/" /etc/maddy/conf.d/domains.conf # Rather than using serfs/inkemaildomain

# UFW (services and ports below them if known)
/usr/bin/ufw allow smtp
/usr/bin/ufw allow 25
/usr/bin/ufw allow 587
/usr/bin/ufw deny 465
/usr/bin/ufw allow imaps
/usr/bin/ufw allow 993
/usr/bin/ufw deny imap
/usr/bin/ufw deny 143
## Close DKIM ports (Maddy doesn't need them, and validation is through DNS records, not contacting the server)
/usr/bin/ufw deny 8891
/usr/bin/ufw deny 12301

# PHP mail log (Maddy can't work on LAMP, PHP not needed on LEMP)
if [ ${ServerType} = "laemp" ]; then
  if ! /usr/bin/grep -q '^mail.log = /var/log/phpmail.log' /opt/verb/conf/php.ini; then
    /bin/sed -i "s/^mail.log = /;mail.log = /" /opt/verb/conf/php.ini
    if /usr/bin/grep -q ';mail.log = /var/log/phpmail.log' /opt/verb/conf/php.ini; then
      /bin/sed -i "s?^;mail.log = /var/log/phpmail.log?mail.log = /var/log/phpmail.log?" /opt/verb/conf/php.ini
    else
      /bin/echo "mail.log = /var/log/phpmail.log" >> /opt/verb/conf/php.ini
    fi
    /usr/bin/systemctl restart httpd
  fi
  /usr/bin/touch /var/log/phpmail.log
  /usr/bin/chown www:www /var/log/phpmail.log
fi

# Service
/usr/bin/cat <<EOF > /etc/systemd/system/maddy.service
[Unit]
Description=maddy mail server
After=network-online.target
After=postgresql.service
Wants=network-online.target

[Service]
Type=exec
User=maddy
Group=maddy
WorkingDirectory=/srv/email/maddy
BindPaths=/srv/email/maddy
ExecStart=
ExecStart=/usr/local/bin/maddy run
ExecReload=/bin/kill -HUP \$MAINPID
KillMode=mixed
Restart=on-failure

# Security and Sandboxing
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

# Storage and funtime directories
RuntimeDirectory=maddy
RuntimeDirectoryMode=0755
ConfigurationDirectory=maddy
ConfigurationDirectoryMode=0755

# File system & database
ReadWritePaths=/srv/email/maddy
ReadOnlyPaths=/etc/maddy/certs/ /etc/letsencrypt/archive/ /etc/letsencrypt/live/ /run/postgresql/

# Restrict access to system directories
ProtectSystem=full
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
## Own
/usr/bin/chown root:root /etc/systemd/system/maddy.service
/usr/bin/sudo chmod 0644 /etc/systemd/system/maddy.service

# Rspamd
## Universal
/usr/bin/cat <<EOF > /etc/rspamd/local.d/milter_headers.conf
use = ["custom"];
EOF

/usr/bin/mkdir -p /etc/rspamd/local.d/unsubscribe-domains

/usr/bin/cat <<EOF > /etc/rspamd/local.d/settings.conf
.include(try=true,priority=1,duplicate=merge) "\$LOCAL_CONFDIR/local.d/unsubscribe-domains/*.conf"
EOF

## Unsubscribe header listings (default domains)
### nameURI
filename_domain="$(/usr/bin/echo "${nameURI}" | /usr/bin/sed 's/\./_/g')"
domain="${nameURI}"
/usr/bin/cat <<EOF > /etc/rspamd/local.d/unsubscribe-domains/${filename_domain}.conf
verb_ink {
  priority = 10;
  from = "@${domain}";
  apply {
    milter_headers {
      custom {
        "List-Unsubscribe-Post" = "List-Unsubscribe=One-Click";
        "List-Unsubscribe" = "<mailto:unsubscribe@${domain}>";
      }
    }
  }
}
EOF
### emailTLDURI
filename_domain="$(/usr/bin/echo "${emailTLDURI}" | /usr/bin/sed 's/\./_/g')"
domain="${emailTLDURI}"
/usr/bin/cat <<EOF > /etc/rspamd/local.d/unsubscribe-domains/${filename_domain}.conf
verb_email {
  priority = 10;
  from = "@${domain}";
  apply {
    milter_headers {
      custom {
        "List-Unsubscribe-Post" = "List-Unsubscribe=One-Click";
        "List-Unsubscribe" = "<mailto:unsubscribe@${domain}>";
      }
    }
  }
}
EOF

#BUG
/usr/bin/echo "1"
## First unsubscribe entry
/opt/verb/serfs/inkemailaddscriptfilter unsubscribe ${nameURI}

#BUG
/usr/bin/echo "2"
/opt/verb/serfs/inkemailaddscriptfilter unsubscribe ${emailTLDURI}

#BUG
/usr/bin/echo "3"
# Start the services
/usr/bin/systemctl daemon-reload; wait
/usr/bin/systemctl enable --now rspamd; wait # get our rspamd service for maddy to use
/usr/bin/systemctl enable --now maddy; wait # enable and start in one command
# Monit
/usr/bin/cp /opt/verb/conf/lib/cloud/monit/monitrc.d/maddy /etc/monit/monitrc.d/
/usr/bin/chmod 700 /etc/monit/monitrc.d/*
## Restart or enable, just be safe
if systemctl is-active monit -q; then
  /usr/bin/systemctl restart monit
else 
  /usr/bin/systemctl enable --now monit # enable and start in one command
fi

#BUG
/usr/bin/echo "4"
# Grand Restart
if [ ${ServerType} = "laemp" ]; then
  /usr/bin/systemctl restart nginx; wait
  /usr/bin/systemctl restart httpd; wait
elif [ ${ServerType} = "lemp" ]; then
  /usr/bin/systemctl restart nginx; wait
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/systemctl restart httpd; wait
fi


# Config settings to Maddy's version of "EMAIL_INSTALLED"
/usr/bin/sed -i "s/ServerMailStatus=.*/ServerMailStatus=\"MADDY_EMAIL_SERVER\"/g" /opt/verb/conf/servermailpath
## PFA not allowed for Maddy
/usr/bin/sed -i "s/PFA_NOT_INSTALLED/PFA_NOT_ALLOWED/g" /opt/verb/conf/servermailpath

# Maddy must be running for everything after this

#BUG
/usr/bin/echo "5"
# System domains & addresses (Requires ServerMailStatus="MADDY_EMAIL_SERVER")
## Add base domains & addresses
/opt/verb/serfs/inkemailbaseaddrs

#BUG
/usr/bin/echo "6"
## Setup system mail
/opt/verb/serfs/inkemailsysmailboxmsmtp

#BUG
/usr/bin/echo "7"

# DKIM keys & TXT records
# /opt/verb/serfs/newinkdkim ${nameURI}; wait # Handled by Maddy
#NOTE Maddy or Postfix must be installed for this to work:
/opt/verb/serfs/inkdnsaddinkdkim ${nameURI} verber; wait
## Add the DNS records for the mail server TLD itself
/opt/verb/serfs/inkdnsaddmail ${emailTLDURI} verber ; wait
/opt/verb/serfs/inkdnsaddinkdkim ${emailTLDURI} verber; wait


# Finish
/usr/bin/echo "The Maddy email server for inkVerb has been installed.
The email server is https://${emailTLDURI}
"

# inkDrive? (last so above message shows, even if we need to exit non-zero next)
if [ -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
  . /opt/verb/conf/inkdrive/inkdriveinfo
  if [ "${InkDriveCloud}" != "off" ]; then
    /usr/bin/echo "Mounting 'messages' to a drive..."
    /opt/verb/serfs/inkdriveapp "${cVappName}" "${InkDriveCloud}"
    if [ "$?" = 0 ]; then
      /usr/bin/echo "InkDrive=\"${InkDriveCloud}\"" >> /opt/verb/conf/vapps/vapp.${cVappName}
    else
      /usr/bin/echo "inkDrive hosting is expected, but unable to host Nextcloud on the drive. Something is very wrong!"
      exit 6
    fi
  fi
fi




if [ -e "/opt/verb/mods/installmaddymail.after" ]; then . /opt/verb/mods/installmaddymail.after; fi # Follows this script
