#!/bin/bash
#inkVerbSerf! verb.ink

# This installs postfix admin
## PostfixAdmin setup secure option: use "secure" for a password required, otherwise anything else including empty
## If using 'secure', you must set the hash via setpfapass
## Prerequisite: verbemail IF using a verb domain other than verb.email
## Prerequisite: installinkvmail, installrc

# How to use:
## ./installpfa [ path folder ] [ setup password option ]

# Eg: (To use at po.NAME.verb.email/mysecretpath do:)
## ./installpfa mysecretpath
## ./installpfa mysecretpath somepassword

usagenotes="This installs Roundcube"
usageformat="installpfa [ path folder ]"
usageexample="installpfa myrcpath
installpfa wink822"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=( "PostfixAdmin web path" "PostfixAdmin setup password" )
vopttypes=( isazAZ09lines isazAZ09 )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( "inkCert certs should be installled for at least the emailTLDURI for this verber" )
usedby=( installinkvmail )
useserfs=(  )
useconfigs=( servertype servernameip siteurilist servermailpass servermailpath )	# List config files of any kind used in this serf, please preserve order of appearance
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/installpfa.replace" ]; then . /opt/verb/mods/installpfa.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/installpfa.before" ]; then . /opt/verb/mods/installpfa.before; fi # Precedes this script

cVappName="postfixadmin"

# Include the config files
. /opt/verb/conf/servertype
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpass
. /opt/verb/conf/servermailpath

# Check dependencies and to see if already installed
if [ "${ServerMailStatus}" != "VMAIL_SERVER" ]; then
/usr/bin/echo "
The email server must be installed first. Run: installpostfix
"
exit 8; fi
if [ "${ServerPFAPath}" = "PFA_NOT_ALLOWED" ]; then
/usr/bin/echo "
This is a backup email server and PostfixAdmin is not allowed.
"
exit 0; fi
if [ "${ServerPFAPath}" != "PFA_NOT_INSTALLED" ]; then
/usr/bin/echo "
PostfixAdmin is already installed.
"
exit 0; fi
if /usr/bin/grep -Fq "Email Control Records" /opt/verb/conf/inkdns/inkzones/db.${emailTLDURI}; then
/usr/bin/echo "Proceeding..."; else
/usr/bin/echo "
Email Control Records not declared in the email domain DNS zone file. This won't work.
"
exit 8; fi

# Options & secure path
if [ -n "$1" ]; then
  pfaFolder=$1 # We need this variable in our Finish echo statement when running via installinkvmail
else
  pfaFolder="$(/usr/bin/pwgen -0 5 1)" # We need this variable in our Finish echo statement when running via installinkvmail
fi
if [ -n "$2" ]; then
  pfaPass=$2 # We need this variable in our Finish echo statement when running via installinkvmail
else
  pfaPass="$(pwgen -1Bcn 10)" # We need this variable in our Finish echo statement when running via installinkvmail
fi

# Download from repo
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"
if [ "$?" = 4 ]; then
  /usr/bin/echo "Repo failed to retrieve the file."
  exit 4
fi

## Fix a bug
/usr/bin/mkdir -p /srv/www/email/postfixadmin/templates_c

# Copy the branding files
/usr/bin/cp /opt/verb/conf/lib/vmail/postfixadmin/pfapics/images/logo-ink.png /srv/www/email/postfixadmin/public/images/

# Settings
/usr/bin/cp /opt/verb/conf/lib/vmail/postfixadmin/postfixadmin286-config.local.php /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/mailpassword/mailpass${ServerMailPassApg}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/pfafolder286/${pfaFolder}/g" /srv/www/email/postfixadmin/config.local.php
if [ "${ServerRCPath}" != "RC_NOT_INSTALLED" ]; then
  /usr/bin/sed -i "s/rcfolder286/${ServerRCPath}/g" /srv/www/email/postfixadmin/config.local.php
else
  /usr/bin/sed -i "s/\$CONF\['show_footer_text'\] = 'YES';/\$CONF\['show_footer_text'\] = 'NO';/" /srv/www/email/postfixadmin/config.local.php
fi
## Whether web-generated (secure) or auto-generated password
/opt/verb/serfs/setpfapass ${pfaPass}

# Replace
/usr/bin/sed -i "s/emailTLDURI286/${emailTLDURI}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/nameURI286/${nameURI}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/mailpassword/mailpass${ServerMailPassApg}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/rcfolder286/${ServerRCPath}/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "s/pfafolder286/${pfaFolder}/g" /srv/www/email/postfixadmin/config.local.php

# Copy the branding files
/usr/bin/cp /opt/verb/conf/lib/vmail/postfixadmin/pfapics/images/logo-ink.png /srv/www/email/postfixadmin/public/images/
/usr/bin/cp /opt/verb/conf/lib/vmail/postfixadmin/pfapics/images/favicon-ink.ico /srv/www/email/postfixadmin/public/images/

# Webserver
/usr/bin/mkdir -p /srv/www/verb/${ServerEmailTLD}.po
/usr/bin/ln -sfn /srv/www/email/postfixadmin/public /srv/www/verb/${ServerEmailTLD}.po/${pfaFolder}
/usr/bin/chown -R www:www /srv/www/verb/${ServerEmailTLD}.po; wait
/usr/bin/chown -R www:www /srv/www/email/postfixadmin; wait

# Write the config
/usr/bin/sed -i "s/ServerPFAPath.*/ServerPFAPath=\"${pfaFolder}\"/g" /opt/verb/conf/servermailpath

# Finish
/usr/bin/echo "
Postfix Admin is installed and ready to be set up at: https://po.${emailTLDURI}/${pfaFolder}/setup.php
Use the Setup password: '${pfaPass}'
(It may be using self-signed SSL certificates until the production certificates are installed.)
When finished, run ./postinstallpfa
"




if [ -e "/opt/verb/mods/installpfa.after" ]; then . /opt/verb/mods/installpfa.after; fi # Follows this script
