#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and installs the InfiniteWP Server to a new directory to an existing domain in the .../html/ folder
## For security, this does NOT install to a pre-defined inkVerb subdomain, ie iwp.name.verb.ink. The site has too much control and must be set differently.
## This does not interfere at all with the contents of the domain.
## This should be installed AFTER any installations to the domain, such as WordPress

# All options after the email are optional, but are sequential

# How to use:
## ./installiwpadmin [sub.domain.tld or domain.tld] [email for registration] [directory of domain.tld/directory] [dbase] [dbuser] [dbpassword]


cVappName=iwpadmin

domain=$1
remail=$2
directory=$3
dBase=$4
dBaseUser=$5
dBPassword=$6
cleanName=$(/bin/echo ${domain} | sed -e 's/\.//g')

# Check that the directory doesn't already exist
if [ -d /srv/www/html/${domain}/${directory} ]; then
/bin/echo "That directory already exists for that domain. Choose a different directory."
exit 8; fi

# Options
if [ -z ${1} ]; then
/bin/echo "You must designate a domain."
exit 8; fi

# Check email is set
if [ -z ${2} ]; then
/bin/echo "You must set an email for the repo package in InfiniteWP-Admin."
exit 8; fi


# Include the config file
. /opt/verb/conf/servernameip

# Download and establish IWPAdmin in the server to pre-created domain
cd /srv/www/vapps || exit 6
/opt/verb/serfs/inkget ${cVappName} check
e="$?"; [[ "$e" = "0" ]] || exit "$e"

## Auto options
if [ -z ${3} ]; then
directory=iwp$(/usr/bin/pwgen -s -1 1); fi
if [ -z ${6} ]; then
dBPassword=$(/usr/bin/pwgen -s -1 10); fi
if [ -z ${4} ]; then
dBase=iwp$(/bin/echo $CLEANNAME | cut -c1-23)$(/usr/bin/pwgen -s -1 5); fi
if [ -z ${5} ]; then
dBaseUser=${dBase}; fi

/bin/mv ${cVappName} ${domain}
/bin/mv ${cVappName} ${cVappName}.${domain}
/bin/ln -sfn /srv/www/vapps/${cVappName}.${domain} /srv/www/html/${domain}/${directory}

# Create the database and credentials
/usr/bin/mysql --login-path=local -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Write the config for backup
/bin/echo "#!/bin/bash
appDBase=${dBase}
appDDBUsr=${dBaseUser}
appDDBPass=${dBPassword}
IWPADMIN_directory=\"${directory}\"" > /opt/verb/conf/vapps/vapp.${cVappName}.${domain}

# Reset all permissions
/bin/chown -R www:www /srv/www/html/${domain}/${directory}; wait

/bin/echo "${domain} now has the InfiniteWP Admin Panel.
These are setup:

Database: ${dBase}
Database user: ${dBaseUser}
Database password: ${dBPassword}
Database port / prefix: DO NOT CHANGE

Go to http://${domain}/${directory} to install.
"




if [ -e "/opt/verb/mods/installiwpadmin.after" ]; then . /opt/verb/mods/installiwpadmin.after; fi # Follows this script
