#!/usr/bin/bash
#inkVerbSerf! verb.ink

# This installs ghost as an app to permanently replace a pre-created domain, such as domain.com or sub.domain.com

# How to use:
## ./installghostsite [domain]


cVappName=ghost

domain=$1

# Basic credential check
if [ -z ${1} ]; then
/usr/bin/echo "You need to set a domain. See \"How to use\" in the serf."
exit 5
fi

# Include settings
. /opt/verb/conf/servernameip
. /opt/verb/conf/servertype

# Check if the domain exists
## Nginx
if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
	if [ ! -e "/opt/verb/conf/webserver/sites-available/nginx/${domain}.conf" ]; then
		/usr/bin/echo "${domain} not found."
		exit 8
	fi
## No Apache
elif [ ${ServerType} = "lamp" ]; then
	/usr/bin/echo "Ghost requires Nginx. Can't be installed on LAMP server."
	exit 5
fi

# Install nvm & Node.js
/usr/bin/pacman -Syy nodejs npm --needed --noconfirm

# Make the installer happy
/usr/bin/mkdir -p /home/www
/usr/bin/chown -R www:www /home/www

# Create app directory
/usr/bin/mkdir /srv/ghost/${domain}
/usr/bin/chown -R worker:worker /srv/ghost/${domain}
# cd /srv/ghost/${domain} || exit 6 #DEV delete if everything works (directory should be an argument and cd not needed)

# Install Ghost CLI tool package from nvm
/usr/bin/npm install ghost-cli@latest -g

# Auto database
cleanName=$(echo ${domain} | /usr/bin/sed -e 's/\.//g')
dBPassword=$(/usr/bin/pwgen -s -1 10)
dBase=gst$(/usr/bin/echo ${cleanName} | cut -c1-23)$(/usr/bin/pwgen -s -1 6)
dBaseUser=${dBase}

# Create the database and credentials
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE  ${dBase};
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Mail account (100M)
emailPassword=$(/usr/bin/pwgen -s 15)
/opt/verb/serfs/inkvmailbox web ${domain} 'Ghost' 104857600 ${emailPassword}

# Determin port 
ghostport=2368
while /usr/bin/netstat -tulpn | /usr/bin/grep LISTEN | /usr/bin/grep -q ${ghostport}; do
  ghostport=$(/usr/bin/expr ${ghostport} + 1)
done

# Email variable
emailUser="web@${domain}"

# Write the config for backup
/usr/bin/echo "appDBase=\"${dBase}\"
appDDBUsr=\"${dBaseUser}\"
appDDBPass=\"${dBPassword}\"
ghostdomain=\"${domain}\"
ghostport=\"${ghostport}\"
ghostemail=\"${emailUser}\"
ghostemailpas=\"${emailPassword}\"
" > /opt/verb/conf/vapps/vapp.${cVappName}.${domain}

# Record the port in the Ghost port inklist
/usr/bin/echo "${domain} ${ghostport}" >> /opt/verb/conf/inklists/ghostserverports

# Set UFW to allow the Ghost port
/usr/bin/ufw allow ${ghostport}

# Remove domain web folder link
/usr/bin/rm -f /srv/www/html/${domain}

#DEv what should we do here for the site configuration?
# Remove Apache site
if [ ${ServerType} = "laemp" ]; then
#   /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
fi
/usr/bin/systemctl restart nginx httpd

# Install ghost
## Help https://ghost.org/docs/ghost-cli/
## User dependency
/usr/bin/id -u ghost &>/dev/null || /usr/bin/useradd --system --user-group ghost
## Can't use ghost as root
/usr/bin/su worker -c "export GHOST_NODE_VERSION_CHECK=false; /usr/bin/ghost install --dir '/srv/ghost/${domain}' --url '${domain}' --port '${ghostport}' --ip '127.0.0.1' --mail 'SMTP' --mailport '465' --mailhost 'smtp.${domain}' --mailuser '${emailUser}' --mailpass '${emailPassword}' --db 'mysql' --dbhost 'localhost' --dbuser '${dBaseUser} ' --dbpass '${dBPassword}' --dbname '${dBase}' --production --start --setup-nginx --no-setup-ssl --no-setup-linux-user --no-setup-migrate --setup-systemd"
if [ "$?" != "0" ]; then /usr/bin/echo 'Ghost install failed: !!'; exit 4; fi


# Dev arguments
# --no-setup-nginx --no-setup-systemd
#    --setup-nginx    --setup-systemd --no-setup-ssl --no-setup-linux-user --no-setup-migrate

# --setup-ssl --setup-mysql
#  --no-setup-mysql --no-setup-ssl --no-setup-linux-user --no-setup-migrate
#  --no-setup-nginx --no-setup-systemd




# Finish
/usr/bin/echo "Ghost is setup.
Go to https://${domain}/ghost to install."

# Optional server restart
#/usr/bin/echo "But first, wait two minutes for the server to restart."
#sleep 3
#reboot




if [ -e "/opt/verb/mods/installghostsite.after" ]; then . /opt/verb/mods/installghostsite.after; fi # Follows this script
