#!/bin/bash
#inkVerbKnight! verb.ink

# This removes the config for a domain served on this DNS as a slave record based on a given rink user config

# How to use:
## ./killinkdnsslavedns [ rink user ] [ domain.tld ] [ -n - optional flag for no inkdnsrefreshbind ]

# Eg:
## ./killinkdnsslavedns inkisaverb.com
## ./killinkdnsslavedns sub.inkisaverb.com
## ./killinkdnsslavedns inkisaverb.com -n

usagenotes="This removes the config for a domain served on this DNS as a slave record"
usageformat="killinkdnsslavedns [ rink user ] [ domain.tld ]"
usageexample="killinkdnsslavedns john.ink inkisaverb.com
killinkdnsslavedns vern.blue sub.inkisaverb.com
killinkdnsslavedns inkisaverb.com -n"
hierarchy=( primary )
vsetnames=( "Existing rink user in /srv/sns/" "Domain" )
vsettypes=( NAME.VTLD isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=( n )
voptflagpurpose=( "No refresh Bind" )
dependencyinstall=( inkdnsinstall make-dns )
prerequesite=( inkdnsaddslave )
usedby=( killinkdnsslavednsallverbs )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdnsslavedns.replace" ]; then . /opt/verb/mods/killinkdnsslavedns.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killinkdnsslavedns.before" ]; then . /opt/verb/mods/killinkdnsslavedns.before; fi # Precedes this script


# Config check
if [ ! -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
  /bin/echo "This server is not a DNS, I quit."; exit 0
fi

# Argument check
if [ -z "$1" ]; then
  /bin/echo "You must specify a domain."; exit 0
fi

# Rink
rink="$1"
# Domain
domain="$2"

# Rink user check
if [ ! -d "/srv/sns/${rink}" ]; then
  /bin/echo "This server does not supply rink user ${rink}, I quit."; exit 0
fi

# Rink user settings check
if [ ! -f "/srv/sns/${rink}/servertldstatus" ] || [ ! -f "/srv/sns/${rink}/conf" ] || [ ! -f "/srv/sns/${rink}/siteurilist" ]; then
  /bin/echo "Rink user ${rink} not properly configured, this shouldn't be possible. I quit."; exit 0
fi

# Does the rink user own the domain?
if [ ! -f "/srv/sns/${rink}/domains/${domain}" ]; then
  /bin/echo "This rink user ${rink} does not own domain ${domain}, I quit."; exit 0
fi

. /srv/sns/${rink}/servertldstatus
. /srv/sns/${rink}/siteurilist
. /srv/sns/${rink}/conf

# Already existing check
if [ ! -f "/opt/verb/conf/inkdns/sdns/s.${domain}" ]; then
  /bin/echo "No SDNS configuration for ${domain}, I quit."; exit 0
fi

# Remove the config
/usr/bin/rm -f /opt/verb/conf/inkdns/sdns/s.${domain}

# Refresh Bind?
## When run repeatedly, such as in some rink or "allverb" serfs, this creates systemctl errors "Start request repeated too quickly." & "Failed with result 'start-limit-hit'."
if [ -z "$3" ] || [ "$3" != "-n" ]; then
  /opt/verb/serfs/inkdnsrefreshbind
fi

# Finish
/bin/echo "${domain} removed from this DNS server."




if [ -e "/opt/verb/mods/killinkdnsslavedns.after" ]; then . /opt/verb/mods/killinkdnsslavedns.after; fi # Follows this script
