#!/bin/bash
#inkVerbSerf! verb.ink

# This kills a subdomain Apache/Nginx .conf file, Letsencrypt cli-ini entry, and DNS Zone entry after it has been added with addsubdomain

## This DOES NOT:
### Removes the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove OpekDKIM/inkDKIM keys.

# How to use:
## ./killonesub [ subdomain ]

usagenotes="This removes a subdomain Apache/Nginx .conf file, Letsencrypt cli-ini entry, and DNS Zone entry for a subdomain at SUBDOMAIN.NAME.verb.one"
usageformat="killonesub [ subdomain ]"
usageexample="killonesub subdom"
hierarchy=( primary )
vsetnames=( "Subdomain" )
vsettypes=( isDomainPart )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newonesub )
usedby=(  )
useserfs=( killinkdnsonesub )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killonesub.replace" ]; then . /opt/verb/mods/killonesub.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killonesub.before" ]; then . /opt/verb/mods/killonesub.before; fi # Precedes this script


killsub=$1

# Include the configs
. /opt/verb/conf/siteurilist

killsubdomain=${killsub}.${oneURI}

# Remove server configs and restart
. /opt/verb/conf/servertype
if [ ${ServerType} = "lemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/${killsubdomain}.conf
  /usr/bin/systemctl restart nginx
elif [ ${ServerType} = "lamp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/${killsubdomain}.conf
  /usr/bin/systemctl restart httpd
elif [ ${ServerType} = "laemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/${killsubdomain}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove from inkCert
/bin/sed -i "s/, ${killsubdomain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${oneURI}.ini

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${killsubdomain}

# inkDNS entry
/opt/verb/serfs/killinkdnsonesub ${killsub}

# Finish
/bin/echo "${killsubdomain} has been removed. But, the folder in www/one/ still exists for a FTP to access."




if [ -e "/opt/verb/mods/killonesub.after" ]; then . /opt/verb/mods/killonesub.after; fi # Follows this script
