#!/bin/bash
#inkVerbSerf! verb.ink

# This completely removes a domain's inkCert, Letsencrypt, inkDNS, and inkDKIM (OpenDKIM) profiles
## This does NOT:
### Remove any subdomains
### Remove any web or Apache folders or configs
### Remove the mail entry in the database used by Postfix and the mail folder at /srv/vmail/

# How to use:
## ./killdomainshell [ domain.tld ]

usagenotes="This completely removes a domain's inkCert, Letsencrypt, inkDNS, and inkDKIM (OpenDKIM) profiles"
usageformat="killdomainshell [ domain.tld ]"
usageexample="killdomainshell inkisaverb.com"
hierarchy=( tertiary killdomainhard/killdomainsoft )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( adddomain )
usedby=( killdomainsoft killdomainhard )
useserfs=( killinkcertdomain inkvmailkillscriptfilter killinkcertmail killinkdkim rinkkilldomain )
useconfigs=( servertype servermailpath inkdnsconf inkcertstatus siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killdomainshell.replace" ]; then . /opt/verb/mods/killdomainshell.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killdomainshell.before" ]; then . /opt/verb/mods/killdomainshell.before; fi # Precedes this script


killdomain=$1

# Include the config files
. /opt/verb/conf/servertype

# Dependencies
if [ ! -f "/opt/verb/conf/inkcertstatus" ]; then
  /usr/bin/echo "No inkCert, there may be nothing more to do."; exit 8
fi
if [ ! -f "/opt/verb/conf/inkdnsconf" ]; then
  /usr/bin/echo "No inkDNS, there may be nothing more to do."; exit 8
fi
if [ ! -f "/opt/verb/conf/servermailpath" ]; then
  /usr/bin/echo "No Postfix Vmail, there may be nothing more to do."; exit 8
fi

# Make sure we don't kill a verb domain
if /bin/grep -q "${killdomain}" /opt/verb/conf/siteurilist; then
  /usr/bin/echo "Can't kill a verber domain, I quit."; exit 9
fi

# Remove all config files, symlinks, and directories
if [ ${ServerType} = "lemp" ]; then
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/*${killdomain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/*${killdomain}.conf
  /usr/bin/systemctl restart nginx
elif [ ${ServerType} = "lamp" ]; then
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/*${killdomain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/*${killdomain}.conf
  /usr/bin/systemctl restart httpd
elif [ ${ServerType} = "laemp" ]; then
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/*${killdomain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/*${killdomain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/*${killdomain}.conf
  /usr/bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/*${killdomain}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove inkCert (including Letsencrypt) configs
/opt/verb/serfs/killinkcertdomain ${killdomain}; wait

# Remove the unsubscribe mail recipient filter
/opt/verb/serfs/inkvmailkillscriptfilter unsubscribe ${killdomain}; wait

# Remove inkCert mail entries
/opt/verb/serfs/killinkcertmail ${killdomain}; wait

# Remove inkDKIM entries
/opt/verb/serfs/killinkdkim ${killdomain}; wait

# Notify the NS slave servers
/opt/verb/serfs/rinkkilldomain ${killdomain}; wait

# Finish
/bin/echo "
The DNS entries and SSL and DKIM profiles for ${killdomain} have been deleted.
"


if [ -e "/opt/verb/mods/killdomainshell.after" ]; then . /opt/verb/mods/killdomainshell.after; fi # Follows this script
