#!/bin/bash
#inkVerbKnight! verb.ink

# This removes the config for a domain served on this DNS as a slave record if running a custom verber, not controlled by the control rink

# How to use:
## ./killinkdnslocalslavedns [ rink user ] [ domain.tld ] [ -n - optional flag for no inkdnsrefreshbind ]

# Eg:
## ./killinkdnslocalslavedns john-ink inkisaverb.com
## ./killinkdnslocalslavedns vern-blue sub.inkisaverb.com
## ./killinkdnslocalslavedns john-ink inkisaverb.com -n

usagenotes="This removes the config for a domain served on this DNS as a slave record if running a custom verber, not controlled by the control rink"
usageformat="killinkdnslocalslavedns [ domain.tld ]"
usageexample="killinkdnslocalslavedns john.ink inkisaverb.com
killinkdnslocalslavedns vern.blue sub.inkisaverb.com
killinkdnslocalslavedns vern.blue sub.inkisaverb.com -n"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( inkdnsinstall make-dns )
prerequesite=( inkdnsaddlocalslave )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdnslocalslavedns.replace" ]; then . /opt/verb/mods/killinkdnslocalslavedns.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killinkdnslocalslavedns.before" ]; then . /opt/verb/mods/killinkdnslocalslavedns.before; fi # Precedes this script


# Config check
if [ ! -f "/opt/verb/conf/inkdns/sdns/dnshost" ]; then
  /bin/echo "This server is not a DNS, I quit."; exit 0
fi

# Argument check
if [ -z "$2" ]; then
  /bin/echo "You must specify a domain."; exit 0
fi

# Verber
verber="$1"
# Domain
domain="$2"

# Already existing check
if [ ! -f "/srv/sns/${verber}/domains/${domain}" ]; then
  /bin/echo "No SDNS configuration for ${domain}, I quit."; exit 0
fi

# Remove the config
#/usr/bin/rm -f /opt/verb/conf/inkdns/sdns/s.${domain}
/usr/bin/rm -f /srv/sns/${verber}/domains/${domain}

# Refresh Bind?
## When run repeatedly, such as in some rink or "allverb" serfs, this creates systemctl errors "Start request repeated too quickly." & "Failed with result 'start-limit-hit'."
if [ -z "$3" ] || [ "$3" != "-n" ]; then
  /opt/verb/serfs/inkdnsrefreshbind
  # Finish
  /bin/echo "${domain} added to this DNS slave server and live."
else
  # Finish
  /bin/echo "${domain} added to this DNS slave server. Changes will not be effective until you run inkdnsrefreshbind"
fi

# Finish
/bin/echo "${domain} removed from this DNS server."




if [ -e "/opt/verb/mods/killinkdnslocalslavedns.after" ]; then . /opt/verb/mods/killinkdnslocalslavedns.after; fi # Follows this script
