#!/bin/bash
#inkVerbSerf! verb.ink

# This removes a subdomain Apache/Nginx .conf file, Letsencrypt cli-ini entry, and DNS Zone entry after it has been added with addsubdomain

## This DOES NOT:
### Removes the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove OpekDKIM/inkDKIM keys.

# How to use:
## ./killsubdomain [ subdomain ] [ domain.tld ]

usagenotes="This removes a subdomain Apache/Nginx .conf file, Letsencrypt cli-ini entry, and DNS Zone entry after it has been added with addsubdomain"
usageformat="killsubdomain [ subdomain ] [ domain.tld ]"
usageexample="killsubdomain subdom inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Subdomain" "Domain" )
vsettypes=( isDomainPart isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( addsubdomain )
usedby=(  )
useserfs=( killinkdnssub )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killsubdomain.replace" ]; then . /opt/verb/mods/killsubdomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killsubdomain.before" ]; then . /opt/verb/mods/killsubdomain.before; fi # Precedes this script


killsub=$1
killdomain=$2
killsubdomain=${killsub}.${killdomain}

# Remove server configs and restart
. /opt/verb/conf/servertype
if [ ${ServerType} = "lemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/${killsubdomain}.conf
  /usr/bin/systemctl restart nginx
elif [ ${ServerType} = "lamp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/${killsubdomain}.conf
  /usr/bin/systemctl restart httpd
elif [ ${ServerType} = "laemp" ]; then
  /bin/rm -f /opt/verb/conf/webserver/sites-available/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/httpd/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-available/nginx/${killsubdomain}.conf
  /bin/rm -f /opt/verb/conf/webserver/sites-enabled/nginx/${killsubdomain}.conf
  /usr/bin/systemctl restart httpd
  /usr/bin/systemctl restart nginx
fi

# Remove from inkCert
/bin/sed -i "s/, ${killsubdomain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${killdomain}.ini

# Remove http folder symlinks
/bin/rm -f /srv/www/html/${killsubdomain}

# inkDNS entry
/opt/verb/serfs/killinkdnssub ${killsub} ${killdomain}

# Finish
/bin/echo "${killsubdomain} has been removed. But, the folder in www/domains still exists for a VIP to access."




if [ -e "/opt/verb/mods/killsubdomain.after" ]; then . /opt/verb/mods/killsubdomain.after; fi # Follows this script
