#!/bin/bash
#inkVerbSerf! verb.ink

# This removes all inkDKIM (OpenDKIM) records for a specific domain

# How to use:
## ./killinkdkim [ domain.tld or subdomain.domain.tld etc ]

usagenotes="This removes all inkDKIM (OpenDKIM) records for a specific domain"
usageformat="killinkdkim [ domain.tld or subdomain.domain.tld etc ]"
usageexample="killinkdkim inkisaverb.com"
hierarchy=( tertiary killdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newinkdkim inkdnsaddinkdkim )
usedby=( killinkcertmail )
useserfs=(  )
useconfigs=( inkcertstatus inkdnsconf servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdkim.replace" ]; then . /opt/verb/mods/killinkdkim.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killinkdkim.before" ]; then . /opt/verb/mods/killinkdkim.before; fi # Precedes this script


killdkimdomain=$1

# Delete domain key from the config files
/bin/sed -i "/inkdkim\._domainkey\.${killdkimdomain} ${killdkimdomain}:inkdkim:\/etc\/opendkim\/keys\/${killdkimdomain}\/inkdkim\.private/d" /etc/opendkim/KeyTable
/bin/sed -i "/${killdkimdomain} inkdkim\._domainkey\.${killdkimdomain}/d" /etc/opendkim/SigningTable
/bin/sed -i "/${killdkimdomain}/d" /etc/opendkim/TrustedHosts

# Delete the declared domain key
/bin/rm -rf /etc/opendkim/keys/${killdkimdomain}

# Restart
/usr/bin/systemctl restart opendkim
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot




if [ -e "/opt/verb/mods/killinkdkim.after" ]; then . /opt/verb/mods/killinkdkim.after; fi # Follows this script
