#!/bin/bash
#inkVerbSerf! verb.ink

# This removes the mail subdomain A & AAAA records in the inkDNS zone file added by inkdnsaddmail
## This is used by killinkcertmail and should not be run independently

# How to use:
## ./killinkdnsmail [ domain.tld ]

usagenotes="This removes the mail subdomain A & AAAA records in the inkDNS zone file added by inkdnsaddmail"
usageformat="killinkdnsmail [ domain.tld ]"
usageexample="killinkdnsmail inkisaverb.com"
hierarchy=( tertiary killdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdnsaddinkdkim )
usedby=( killinkcertmail )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( servernameip inkcertstatus inkdnsconf servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdnsmail.replace" ]; then . /opt/verb/mods/killinkdnsmail.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killinkdnsmail.before" ]; then . /opt/verb/mods/killinkdnsmail.before; fi # Precedes this script


dnsDomain="$1"

# Make sure we don't kill a verb domain
if /usr/bin/grep -q "${dnsDomain}" /opt/verb/conf/siteurilist; then
  /usr/bin/echo "Can't kill a verber domain, I quit."; exit 9
fi

# Include the configs
. /opt/verb/conf/servernameip

# Check if already added
if ! /usr/bin/grep -Fq "; Hostname Mail Record Defaults" /opt/verb/conf/inkdns/zones/db.${dnsDomain}; then
/usr/bin/echo "Mail Record Defaults don't exist for ${dnsDomain}. Use inkdnsaddmail to add them."
exit 0; fi

# Remove the records
/usr/bin/sed -i "/; Hostname Mail Record Defaults/,/;; End Mail Defaults/d" /opt/verb/conf/inkdns/zones/db.${dnsDomain}
/usr/bin/sed -i "/; PTR Hostname Mail Record Defaults/,/;; End Mail Defaults/d" /opt/verb/conf/inkdns/zones/nv.${dnsDomain}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${dnsDomain}

# Refresh zones
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/usr/bin/echo "The Mail Record Defaults have been removed from the ${dnsDomain} DNS zone file."




if [ -e "/opt/verb/mods/killinkdnsmail.after" ]; then . /opt/verb/mods/killinkdnsmail.after; fi # Follows this script
