#!/bin/bash
#inkVerbSerf! verb.ink

# This removes a subdomain A & AAAA records from an existing VIP DNS record in the inkDNS zone file on the server

# How to use:
## ./killinkdnsvipsub [ subdomain ]

usagenotes="This removes a subdomain A & AAAA records from an existing VIP DNS record in the inkDNS zone file on the server"
usageformat="killinkdnsvipsub [ subdomain ]"
usageexample="killinkdnsvipsub me"
hierarchy=( tertiary killvipsub )
vsetnames=( "Subdomain" )
vsettypes=( isDomainPart )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( inkdnsaddvipsub )
usedby=( killvipsub )
useserfs=( inkdnsserial inkdnsrefreshbind )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killinkdnsvipsub.replace" ]; then . /opt/verb/mods/killinkdnsvipsub.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killinkdnsvipsub.before" ]; then . /opt/verb/mods/killinkdnsvipsub.before; fi # Precedes this script


dnsSubDom="$1"
ZONEdir="inkzones"

# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

# Check if already added
if ! /bin/grep -Fq "${dnsSubDom}.${vipURI}" /opt/verb/conf/inkdns/${zonedir}/db.${vipURI}; then
/bin/echo "The subdomain ${dnsSubDom} has not been added to ${vipURI}. Use inkdnsaddsub to add it."
exit 0; fi

# Remove the records
/bin/sed -i "/; Subdomain Records Added by inkDNS ${dnsSubDom}\.${vipURI}/,+2d" /opt/verb/conf/inkdns/${zonedir}/db.${vipURI}
/bin/sed -i "/; PTR Subdomain Records Added by inkDNS ${dnsSubDom}\.${vipURI}/,+2d" /opt/verb/conf/inkdns/${zonedir}/nv.${vipURI}

# Set the Serial No
/opt/verb/serfs/inkdnsserial ${vipURI} verber

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi

# Finish
/bin/echo "The VIP subdomain ${dnsSubDom} has been removed from the DNS zone file."




if [ -e "/opt/verb/mods/killinkdnsvipsub.after" ]; then . /opt/verb/mods/killinkdnsvipsub.after; fi # Follows this script
