#!/bin/bash
#inkVerbSerf! verb.ink

# This "hard" kills a domain added with adddomain
## This removes everything. The server probably wouldn't even know that the domain existed, except for any connected vapp

## This DOES NOT:
### Remove any connected vapp

## This DOES:
### Remove the SSL certificate for the domain and all subdomains thereof.
### Remove files formerly in the domain from the server, which are retained in the domains folder that an ftpvip can access
### Remove files for subdomains in the domains folder, just the same.
### Remove any subdomain folders belonging to the domain.
### Remove opekDKIM/inkDKIM keys.
### Remove the inkDNS zone file

# How to use:
## ./killdomainhard [ domaintokill.tld ]

usagenotes="This 'hard' kills a domain added with adddomain, removing every trace of the domain except a connected vapp"
usageformat="killdomainhard [ domaintokill.tld ]"
usageexample="killdomainhard inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( adddomain )
usedby=(  )
useserfs=( inkvmaildeldomain killinkdnsdomain inkvmailpurgedomain killdomainshell )
useconfigs=( servermailpath inkdnsconf inkcertstatus )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/killdomainhard.replace" ]; then . /opt/verb/mods/killdomainhard.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/killdomainhard.before" ]; then . /opt/verb/mods/killdomainhard.before; fi # Precedes this script


killdomain=$1

# Web folders
/bin/rm -rf /srv/www/html/${killdomain}
/bin/rm -rf /srv/www/html/*${killdomain}
/bin/rm -rf /srv/www/domains/${killdomain}
/bin/rm -rf /srv/www/domains/*${killdomain}

# Remove any mailboxes
/opt/verb/serfs/inkvmaildeldomain ${killdomain}; wait

# Remove inkDNS zone file
/opt/verb/serfs/killinkdnsdomain ${killdomain}; wait

# Finish
/bin/echo "
All web contents and DNS records for ${killdomain} have been deleted.
Mailboxes, apps, and original web folders should remain available for the SysAdmin.
"

# Purge mailboxes
/opt/verb/serfs/inkvmailpurgedomain ${killdomain}; wait

# Remaining services
/opt/verb/serfs/killdomainshell ${killdomain}; wait



if [ -e "/opt/verb/mods/killdomainhard.after" ]; then . /opt/verb/mods/killdomainhard.after; fi # Follows this script
