#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a new MySQL/MariaDB database and a limited-permissions (client: data & structure) user with password

# How to use:
## ./mysqlnewdb [ database name ] [ database userename ] [ database user password - optional ]

usagenotes="This creates a new MySQL/MariaDB database and a limited-permissions (client: data & structure) user with password"
usageformat="mysqlnewdb [ database ename ] [ database userename ] [ database user password - optional ]"
usageexample="mysqlnewdb myGreat99DB myGreat99DBuser"
hierarchy=( primary )
vsetnames=( "Database name" "Database username" )
vsettypes=( isSQLDatabasename isSQLUserCredential )
voptnames=( "Database user password" )
vopttypes=( isSQLUserCredential )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( mysqlinstall )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/mysqlnewdb.replace" ]; then . /opt/verb/mods/mysqlnewdb.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/mysqlnewdb.before" ]; then . /opt/verb/mods/mysqlnewdb.before; fi # Precedes this script


dBase="${1}"
dBaseUser="${2}"

# Auto password
if [ -z ${3} ]; then
  dBPassword="$(/usr/bin/pwgen -s -1 32)"
  serfOUT="New Password: ${dBPassword}"
else
  dBPassword="${3}"
fi

# Create the SQL items
/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/sql/mysqlboss.cnf -e "
CREATE DATABASE ${dBase} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON ${dBase}.* TO '${dBaseUser}'@'localhost' IDENTIFIED BY '${dBPassword}';
FLUSH PRIVILEGES;"

# Create a Verber record
echo "dBase=\"${dBase}\"
dBaseUser=\"${dBaseUser}\"
dBPassword=\"${dBPassword}\"
UTYPE=\"CLIENT\"" > /opt/verb/conf/sql/mysqldb.${dBase}

# Create the MySQL login .cnf
echo "[client]
user = ${dBaseUser}
password = ${dBPassword}
database = ${dBase}
host = localhost
" > /opt/verb/conf/sql/mysqldb.${dBase}.cnf




if [ -e "/opt/verb/mods/mysqlnewdb.after" ]; then . /opt/verb/mods/mysqlnewdb.after; fi # Follows this script
