#!/bin/bash
#inkVerbSerf! verb.ink

# This script creates a new boss user that is a sudoer who can can run serfs

# How to use:
## ./newboss [ new boss user ] [ boss password ]

usagenotes="This script creates a new boss user that is a sudoer who can can run serfs"
usageformat="newboss [ new boss user ] [ boss password ]"
usageexample="newboss managerjohn NotSecure125"
hierarchy=( primary )
vsetnames=( "Username" "Password" )
vsettypes=( isUsername string_quote )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newftpvip 'or' newftpfiler )
usedby=(  )
useserfs=( ensiteapache ensitenginx inkdnsaddvipsub inkcertaddcb )
useconfigs=( servernameip serverport )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newboss.replace" ]; then . /opt/verb/mods/newboss.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/newboss.before" ]; then . /opt/verb/mods/newboss.before; fi # Precedes this script


# Include the config file
. /opt/verb/conf/servernameip
. /opt/verb/conf/serverport

newBoss=$1
NEWBossPASS=$2

# Old create new boss user
# /usr/sbin/adduser ${newBoss} --gecos ",,," --disabled-password
# /bin/echo "${newBoss}:${NEWBossPASS}" | chpasswd
# usermod -a -G sudo ${newBoss}
# usermod -a -G www-data ${newBoss}
# /bin/ln -s /opt/verb/boss /home/${newBoss}/

# Create the new boss user
/usr/bin/groupadd ${newBoss}
/usr/bin/useradd -g ${newBoss} ${newBoss}
/bin/echo "${newBoss}:${NEWBossPASS}" | chpasswd
/usr/bin/usermod -a -G sudo ${newBoss}
/usr/bin/usermod -a -G www ${newBoss}
/usr/bin/mkdir -p /home/${newBoss}
/bin/ln -sfn /opt/verb/boss /home/${newBoss}/
## User privilege specification
/usr/bin/setfacl -R -m user:${newBoss}:rwx /home/${newBoss}  # DEV see if this line works
/bin/echo '# Added by newboss inkVerb serf' >> /etc/sudoers.d/${newBoss}
/bin/echo "${newBoss}  ALL=(ALL:ALL) ALL" >> /etc/sudoers.d/${newBoss}
## Vim preferences
echo 'nnoremap <C-c> "+y
vnoremap <C-c> "+y
nnoremap <C-p> "+p
vnoremap <C-p> "+p' > /home/${newBoss}/.vimrc
## BASH settings
/opt/verb/serfs/setbashrc ${newBoss}
## Own
/usr/bin/chown -R ${newBoss}:${newBoss} /home/${newBoss}

# Finished
  if [ "${ServerIPv4}" != "NOIP4" ] && [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="'ssh ${newBoss}@${ServerIPv4} -p ${ServerPort} 'or 'ssh ${newBoss}@${ServerIPv6} -p ${ServerPort}'"
  ## IP4?
  elif [ "${ServerIPv4}" != "NOIP4" ]; then
    ipAddrBlock="'ssh ${newBoss}@${ServerIPv4} -p ${ServerPort}'"
  ## IP6?
  elif [ "${ServerIPv6}" != "NOIP6" ]; then
    ipAddrBlock="'ssh ${newBoss}@${ServerIPv6} -p ${ServerPort}'"
  fi
/bin/echo "The boss user ${newBoss} has been created.
Log in using ${ipAddrBlock}'
"




if [ -e "/opt/verb/mods/newboss.after" ]; then . /opt/verb/mods/newboss.after; fi # Follows this script
