#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a new fossil user for an existing fossile available at fossil.NAME.verb.vip/FOSSIL-NAME.cgi
## Prereq: fossil

# How to use:
## ./newfossiluser [ existing-fossil-name ] [ username ] [ user-email ] [ userpassword ]

# Example:
## ./newfossiluser dinosaur adam adam@verb.ink Adamp4$$w0RD

usagenotes="This creates a new fossil user for an existing fossile available at fossil.NAME.verb.vip/FOSSIL-NAME.cgi"
usageformat="newfossiluser [ existing-fossil-name ] [ username ] [ user-email ] [ userpassword ]"
usageexample="newfossiluser dinosaur adam NotSecure125"
hierarchy=( primary )
vsetnames=( "Existing fossil name" "Username" "Email" "Password" )
vsettypes=( isPathname isUsername isEmail string_quote )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( newfossil )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newfossiluser.replace" ]; then . /opt/verb/mods/newfossiluser.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/newfossiluser.before" ]; then . /opt/verb/mods/newfossiluser.before; fi # Precedes this script


# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

oldFossil=$1
NEWuser=$2
newEmail=$3
newPass=$4

# Add the user
/srv/www/vip/fossil user new ${newUser} ${newEmail} ${newPass} --repository ${oldFossil}.fossil

/bin/echo "New user ${newUser} added to ${oldFossil}.fossil.
Available on web at fossil.${vipURI}/${oldFossil}.cgi"




if [ -e "/opt/verb/mods/newfossiluser.after" ]; then . /opt/verb/mods/newfossiluser.after; fi # Follows this script
