#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a new fossil available at fossil.NAME.verb.vip/FOSSIL-NAME.cgi
## Prereq: fossil

# How to use:
## ./newfossil [ new-fossil-name ] [ username ] [ user-email ] [ userpassword ]

# Example:
## ./newfossil dinosaur adam adam@verb.ink Adamp4$$w0RD


usagenotes="This creates a new fossil available at fossil.NAME.verb.vip/FOSSIL-NAME.cgi"
usageformat="newfossil [ new-fossil-name ] [ username ] [ user-email ] [ userpassword ]"
usageexample="newfossil dinosaur adam adam@verb.ink NotSecure125"
hierarchy=( primary )
vsetnames=( "Fossil name" "Username" "Email" "Password" )
vsettypes=( isPathname isUsername isEmail string_quote )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( installfossil )
usedby=( adddomain addsubdomain )
useserfs=(  )
useconfigs=( servernameip siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newfossil.replace" ]; then . /opt/verb/mods/newfossil.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/newfossil.before" ]; then . /opt/verb/mods/newfossil.before; fi # Precedes this script


# Include the configs
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist

newFossil=$1
NEWuser=$2
newEmail=$3
newPass=$4

# Create the fossil with user
/srv/www/vip/fossil new ${newFossil}.fossil --admin-user ${newUser}

# Change the user's password
/srv/www/vip/fossil user password ${newUser} ${newPass} --repository ${newFossil}.fossil

# Write the .cgi file
/bin/echo "#!/usr/bin/fossil
repository: /fossil/${newFossil}.fossil" > ${newFossil}.cgi
/bin/chmod 750 ${newFossil}.cgi

# Final chown to allow database to be writable
/bin/chown -R www:www /srv/www/vip/fossil

/bin/echo "${newFossil}.fossil created.
Available on web at fossil.${vipURI}/${newFossil}.cgi"





if [ -e "/opt/verb/mods/newfossil.after" ]; then . /opt/verb/mods/newfossil.after; fi # Follows this script
