#!/bin/bash
#inkVerbSerf! verb.ink

# This creates a user who can read everything on the server and has a www/vip symlink in the home folder

# How to use:
## ./newservervip [ new user ] [ new user password ]


usagenotes="This creates a user who can read everything on the server and has a www/vip symlink in the home folder"
usageformat="newservervip [ new user ] [ new user password ]"
usageexample="newservervip userjohn NotSecure125"
hierarchy=( primary )
vsetnames=( "Username" "Password" )
vsettypes=( isUsername string_quote )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/newservervip.replace" ]; then . /opt/verb/mods/newservervip.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/newservervip.before" ]; then . /opt/verb/mods/newservervip.before; fi # Precedes this script


newFileUser=$1
appDBase=$2

# Create the user with password
/usr/bin/groupadd ${newFileUser}
/usr/bin/useradd -g ${newFileUser} ${newFileUser}
/bin/echo "${newFileUser}:${newUserPass}" | chpasswd
/usr/bin/usermod -a -G sudo ${newFileUser}
/usr/bin/usermod -a -G www ${newFileUser}
/usr/bin/mkdir -p /home/${newFileUser}
/bin/ln -sfn /opt/verb/boss /home/${newFileUser}/
## User privilege specification
/usr/bin/setfacl -R -m user:${newFileUser}:rwx /home/${newFileUser}  # DEV see if this line works

## This was created with the following base script
# sudo /usr/sbin/adduser myuser --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
# /bin/echo "myuser:password" | sudo chpasswd

# Create the www symlink
/bin/ln -s /srv/www/vip /home/${newFileUser}/vip





if [ -e "/opt/verb/mods/newservervip.after" ]; then . /opt/verb/mods/newservervip.after; fi # Follows this script
