#!/bin/bash
#inkVerbSerf! verb.ink

# This "wildly" forwards an already-created domain to another domain
## All subdomains and paths after the domain will be forwarded, useful for forwarding after WP subdomain Multisite migrations
## The destination must be only a domain

# How to use:
## ./pointwilddomain [forwarded domain] [destination]

# Eg:
## ./pointwilddomain inkisaverb.com poetryiscode.com



fwdDom=$1
dest=$2
origDest="$(find /srv/www/html/${fwdDom} -prune -printf "%l\n")"

# Prepare
/bin/mkdir -p /srv/www/forwards/${fwdDom}
/bin/rm -f /srv/www/html/${fwdDom}
/bin/ln -sfn /srv/www/forwards/${fwdDom} /srv/www/html/

# Set and own
/bin/cat <<EOF | cat > /srv/www/forwards/${fwdDom}/.htaccess
RewriteEngine On
RewriteCond %{HTTP_HOST} ^(.+\.)?${fwdDom}$ [NC]
RewriteRule ^ http://%1${dest}%{REQUEST_URI} [R=301,L]
EOF

/bin/echo "forward=\"${dest}\"" > /srv/www/forwards/${fwdDom}/config
/bin/echo "oldDest=\"${origDest}\"" >> /srv/www/forwards/${fwdDom}/config
/bin/chown -R www:www /srv/www/forwards/${fwdDom}

# Finish
/bin/echo "${fwdDom} now wildly forwarding subdomains and paths to *.${dest}/*"




if [ -e "/opt/verb/mods/pointwilddomain.after" ]; then . /opt/verb/mods/pointwilddomain.after; fi # Follows this script
