#!/bin/bash
#inkVerbSerf! verb.ink

# This removes the forwarding for a domain forwarded via pointdomain

# How to use:
## ./pointdomainrm [ forwarded domain ]

## The forwarded domain can be any domain or subdomain created with adddomain or addsubdomain (and -cgi)


usagenotes="This removes the forwarding for a domain forwarded via pointdomain"
usageformat="pointdomainrm [ forwarded domain ]"
usageexample="pointdomainrm
pointdomainrm [ forwarded domain ]"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/pointdomainrm.replace" ]; then . /opt/verb/mods/pointdomainrm.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/pointdomainrm.before" ]; then . /opt/verb/mods/pointdomainrm.before; fi # Precedes this script


fwdDom=$1

# Verify it was created by the pointdomain serf
if [ ! -f /srv/www/forwards/${fwdDom}/config ]; then
/bin/echo "This domain's destination is not forwarded by pointdomain. Doing nothing."
exit 0
else
. /srv/www/forwards/${fwdDom}/config
fi

# Check for wild forwarding
if [ "${forward}" = "${oldDest}" ] && [ -f "/srv/www/forwards/${forward}/.htaccess" ] && [ -f "/srv/www/forwards/${forward}/index.php" ]; then
  /bin/rm -f /srv/www/forwards/${forward}/.htaccess
  /bin/echo "${fwdDom} is no longer forwarding wildly to ${oldDest}, back to normal forwarding to ${oldDest}."
else

# Unset and own
/bin/rm -f /srv/www/html/${fwdDom}
/bin/ln -sfn "${oldDest}" /srv/www/html/${fwdDom}
/bin/chown -R www:www "${oldDest}"
/bin/rm -rf /srv/www/forwards/${fwdDom}

# Finish
/bin/echo "${fwdDom} is no longer forwarding to ${forward}, back to ${oldDest}."

fi




if [ -e "/opt/verb/mods/pointdomainrm.after" ]; then . /opt/verb/mods/pointdomainrm.after; fi # Follows this script
