#!/bin/bash
#inkVerbSerf! verb.ink

# This script points your-name.verb.one to custom-made subdomains, 

# How to use:
## ./pointone [ subdomain only ]

# Eg: (This will point your-name.verb.one to lucky.your-name.verb.one)
## ./pointone lucky

usagenotes="This script points your-name.verb.one to custom-made subdomains,"
usageformat="pointone [ subdomain only ]"
usageexample="pointone lucky"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/pointone.replace" ]; then . /opt/verb/mods/pointone.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/pointone.before" ]; then . /opt/verb/mods/pointone.before; fi # Precedes this script


# Type ./pointone -h for help


# Include the config
. /opt/verb/conf/siteurilist

if [ "$1" = "-h" ]; then
    /bin/echo "Usage: ./pointone [subdomain only]
Examples:
 ./pointone lucky (points ${oneURI} to lucky.${oneURI}
 ./pointone verb.one (resets ${oneURI} to point to itself)

 Make sure the .${oneURI} subdomain exists
 Then, you may use any subdomain you want except
 verb.one
 which will reset ${oneURI}"
exit 0
fi

if [ "$1" = "verb.one" ]; then
    cp /srv/www/verb/one/index-one.php /srv/www/html/one/index.php
    /bin/echo "Reset, done."
exit 0
fi

newONEsub=$1

    cp /srv/www/verb/one/index-newonesub.php /srv/www/html/one/index.php
    /usr/bin/sed -i "s/newonesub/${newONEsub}/g" /srv/www/verb/one/index.php
    /bin/echo "Pointing to http://${newONEsub}.${oneURI}, done."
exit 0





if [ -e "/opt/verb/mods/pointone.after" ]; then . /opt/verb/mods/pointone.after; fi # Follows this script
