#!/bin/bash
#inkVerbSerf! verb.ink

# This forwards an already-created domain to another URI

# How to use:
## ./pointdomain [forwarded domain] [destination]

## The destination may include 'http://' or 'https://'

## The forwarded domain can be any domain or subdomain created with adddomain or addsubdomain (and -cgi)


fwdDom=$1
dest=$2
origDest="$(find /srv/www/html/${fwdDom} -prune -printf "%l\n")"

# Prepare
/bin/mkdir -p /srv/www/forwards/${fwdDom}
/bin/rm -f /srv/www/html/${fwdDom}
/bin/ln -sfn /srv/www/forwards/${fwdDom} /srv/www/html/

# Set and own
/bin/echo "<?php header(\"Location: ${dest}\"); die(); ?>" > /srv/www/forwards/${fwdDom}/index.php
/bin/echo "forward=\"${dest}\"" > /srv/www/forwards/${fwdDom}/config
/bin/echo "oldDest=\"${origDest}\"" >> /srv/www/forwards/${fwdDom}/config
/bin/chown -R www:www /srv/www/forwards/${fwdDom}

# Finish
/bin/echo "${fwdDom} now forwarding to ${dest}"




if [ -e "/opt/verb/mods/pointdomain.after" ]; then . /opt/verb/mods/pointdomain.after; fi # Follows this script
