#!/bin/bash
#inkVerbSerf! verb.ink

# This finalizes branding changes after the LocalSettings.php file has been uploaded to the mediawiki folder

# How to use:
## ./postinstallmediawiki


usagenotes="This finalizes branding changes after the LocalSettings.php file has been uploaded to the mediawiki folder"
usageformat="postinstallmediawiki"
usageexample="postinstallmediawiki"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( setvappconfig )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/postinstallmediawiki.replace" ]; then . /opt/verb/mods/postinstallmediawiki.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/postinstallmediawiki.before" ]; then . /opt/verb/mods/postinstallmediawiki.before; fi # Precedes this script


# Include the config file
. /opt/verb/conf/servernameip

# Download and establish wordpress in the server to pre-created domain
/bin/cp /opt/verb/conf/lib/mediawiki/resources/assets/verbwiki.png /srv/www/vapps/mediawiki/resources/assets/
/bin/sed -i "s/wiki.png/verbwiki.png/g" /srv/www/vapps/mediawiki/LocalSettings.php
# Move from vip/MediaWiki to the settings file
/bin/mv /srv/www/vip/LocalSettings.php /srv/www/vapps/mediawiki/
/bin/rm -rf /srv/www/vapps/mediawiki/mw-config
/opt/verb/serfs/setvappconfig "vapp.mediawiki" "/srv/www/vapps/mediawiki/LocalSettings.php"


/bin/echo "
Post install finished."




if [ -e "/opt/verb/mods/postinstallmediawiki.after" ]; then . /opt/verb/mods/postinstallmediawiki.after; fi # Follows this script
