#!/bin/bash
#inkVerbSerf! verb.ink

# This revokes MySQL users' boss permissions for web apps that require boss access upon install
## Current intended apps include Ampache, SuiteCRM

# How to use:
## ./postinstallmysqlfix [app namespace]

# Eg:
## ./postinstallmysqlfix ampache

appName=$1

# Include the config
. /opt/verb/conf/vapps/vapp.${appName}

/usr/bin/mariadb --defaults-extra-file=/opt/verb/conf/mysqlboss.cnf -e "
REVOKE ALL PRIVILEGES ON *.* FROM '${appDDBUsr}'@'localhost';
REVOKE GRANT OPTION ON *.* FROM '${appDDBUsr}'@'localhost';
GRANT ALL PRIVILEGES ON ${appDBase}.* TO '${appDDBUsr}'@'localhost' IDENTIFIED BY '${appDDBPass}';
FLUSH PRIVILEGES;"

# Finish
/bin/echo "Finished. Database user now has normal permissions."




if [ -e "/opt/verb/mods/postinstallmysqlweb.after" ]; then . /opt/verb/mods/postinstallmysqlweb.after; fi # Follows this script
