#!/bin/bash
#inkVerbSerf! verb.ink

# This should be run after PostfixAdmin has been setup through the web interface

# How to use:
## ./postinstallpfa


usagenotes="This should be run after PostfixAdmin has been setup through the web interface"
usageformat="postinstallpfa"
usageexample="postinstallpfa"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/postinstallpfa.replace" ]; then . /opt/verb/mods/postinstallpfa.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/postinstallpfa.before" ]; then . /opt/verb/mods/postinstallpfa.before; fi # Precedes this script


# Deny http access to the setup file
/bin/echo "<Files "setup.php">
deny from all
</Files>" > /srv/www/email/postfixadmin/public/.htaccess
/bin/chown -R www:www /srv/www/email/postfixadmin/public/.htaccess

# Set the setup password so it can't work until setpfapass runs agian
/bin/sed -i "/setup_password/d" /srv/www/email/postfixadmin/config.local.php
/bin/sed -i "/setup_password/d" /srv/www/email/postfixadmin/config.inc.php

# Delete the old setup password record
/usr/bin/rm /opt/verb/conf/pfasetuppass

# Finish
/bin/echo "Finished. PostfixAdmin Setup disallowed and the setup password disabled."





if [ -e "/opt/verb/mods/postinstallpfa.after" ]; then . /opt/verb/mods/postinstallpfa.after; fi # Follows this script
