#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs killinkdnsslavednsallverbs

# How to use:
## ./rinkkillallverbs

usagenotes="This remote runs killinkdnsslavednsallverbs"
usageformat="rinkkillallverbs"
usageexample="rinkkillallverbs"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( rink::addvps )
useserfs=(  )
useconfigs=( servernameip )

if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkkillallverbs.replace" ]; then . /opt/verb/mods/rinkkillallverbs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/rinkkillallverbs.before" ]; then . /opt/verb/mods/rinkkillallverbs.before; fi # Precedes this script


# Configs
. /opt/verb/conf/servernameip

# Already configured?
if [ "$RinkConfigured" != "true" ]; then
	/usr/bin/echo "Rink NS server keys not configured, this won't work"
	exit 0
fi

# Add the active verb domains, wait so we don't congest the server
if [ $VERBemail=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${emailURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${emailURI}"
fi
wait
if [ $VERBone=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${oneURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${oneURI}"
fi
wait
if [ $VERBink=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${inkURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${inkURI}"
fi
wait
if [ $VERBblue=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${blueURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${blueURI}"
fi
wait
if [ $VERBvip=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${vipURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${vipURI}"
fi
wait
if [ $VERBkiwi=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${kiwiURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${kiwiURI}"
fi
wait
if [ $VERBred=true ]; then
/usr/bin/ssh ns1 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${redURI}"
/usr/bin/ssh ns2 "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/${redURI}"
fi


if [ -e "/opt/verb/mods/rinkkillallverbs.after" ]; then . /opt/verb/mods/rinkkillallverbs.after; fi # Follows this script
