#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs killinkdnsslavednsallverbs

# How to use:
## ./rinkkillallverbs

usagenotes="This remote runs killinkdnsslavednsallverbs"
usageformat="rinkkillallverbs"
usageexample="rinkkillallverbs"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( rink::addvps )
useserfs=(  )
useconfigs=( servernameip )

if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkkillallverbs.replace" ]; then . /opt/verb/mods/rinkkillallverbs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/rinkkillallverbs.before" ]; then . /opt/verb/mods/rinkkillallverbs.before; fi # Precedes this script


# Configs
. /opt/verb/conf/servernameip

# Already configured?
if [ "$RinkConfigured" != "true" ]; then
	/usr/bin/echo "Rink NS server keys not configured, this won't work"
	exit 0
fi

# Check for conflicts
/opt/verb/serfs/rinkcheck inkdnsaddslaveallverbs
/opt/verb/serfs/rinkcheck killinkdnsslavednsallverbs

# Insert the function statements
/usr/bin/ssh ns1 "/usr/bin/echo 'killinkdnsslavednsallverbs ${ServerName}-${ServerTLD} -n' > /srv/sns/${ServerName}-${ServerTLD}/calls/killinkdnsslavednsallverbs"
/usr/bin/ssh ns2 "/usr/bin/echo 'killinkdnsslavednsallverbs ${ServerName}-${ServerTLD} -n' > /srv/sns/${ServerName}-${ServerTLD}/calls/killinkdnsslavednsallverbs"


if [ -e "/opt/verb/mods/rinkkillallverbs.after" ]; then . /opt/verb/mods/rinkkillallverbs.after; fi # Follows this script
