#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs killinkdnsslavednsallverbs

# How to use:
## ./rinkkillallverbs

usagenotes="This remote runs killinkdnsslavednsallverbs"
usageformat="rinkkillallverbs"
usageexample="rinkkillallverbs"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( rink::addvps )
useserfs=(  )
useconfigs=( servernameip )

if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkkillallverbs.replace" ]; then . /opt/verb/mods/rinkkillallverbs.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/rinkkillallverbs.before" ]; then . /opt/verb/mods/rinkkillallverbs.before; fi # Precedes this script


# Configs
. /opt/verb/conf/servernameip

# Already configured or allowed rink?
if [ "$RinkConfigured" = "rink" ] && [ -f "/opt/rink/rinknames" ]; then
  . /opt/rink/rinknames
  ns1="${RinkNS1Name}.${RinkVerbTLD}"
  ns2="${RinkNS2Name}.${RinkVerbTLD}"
elif [ "$RinkConfigured" != "true" ]; then
	/usr/bin/echo "Rink NS server keys not configured, this won't work"
	exit 0
else
  ns1="ns1"
  ns2="ns1"
fi

# Add the active verb domains/served, wait so we don't congest the server
if [ $VERBemail=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${emailURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${emailURI}"
fi
wait
if [ $VERBone=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${oneURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${oneURI}"
fi
wait
if [ $VERBink=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${inkURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${inkURI}"
fi
wait
if [ $VERBblue=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${blueURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${blueURI}"
fi
wait
if [ $VERBvip=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${vipURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${vipURI}"
fi
wait
if [ $VERBkiwi=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${kiwiURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${kiwiURI}"
fi
wait
if [ $VERBred=true ]; then
/usr/bin/ssh ${ns1} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${redURI}"
/usr/bin/ssh ${ns2} "/usr/bin/rm -f /srv/sns/${ServerName}-${ServerTLD}/domains/served/${redURI}"
fi


if [ -e "/opt/verb/mods/rinkkillallverbs.after" ]; then . /opt/verb/mods/rinkkillallverbs.after; fi # Follows this script
