#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs killinkdnsslavedns on both NS rink slave servers
## This is run automatically by killdomainshell and normally should not be run independently

# How to use:
## ./rinkkilldomain [ domain.tld ]

usagenotes="This remote runs killinkdnsslavedns on both NS rink slave servers"
usageformat="rinkkilldomain [ domain.tld ]"
usageexample="rinkkilldomain inkisaverb.com"
hierarchy=( tertiary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=( rinkadddomain )
usedby=( killdomainshell )
useserfs=(  )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkkilldomain.replace" ]; then . /opt/verb/mods/rinkkilldomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/rinkkilldomain.before" ]; then . /opt/verb/mods/rinkkilldomain.before; fi # Precedes this script


servedomain=$1

# Configs
. /opt/verb/conf/servernameip

# Already configured or allowed rink?
if [ "$RinkConfigured" = "rink" ] && [ -f "/opt/rink/rinknames" ]; then
  . /opt/rink/rinknames
  ns1="${RinkNS1Name}.${RinkVerbTLD}"
  ns2="${RinkNS2Name}.${RinkVerbTLD}"
elif [ "$RinkConfigured" != "true" ]; then
	/usr/bin/echo "Rink NS server keys not configured, this won't work"
	exit 0
else
  ns1="ns1"
  ns2="ns1"
fi

# Served or parked?
if [ -f "/opt/verb/conf/inkdns/zones/db.${servedomain}" ]; then
  parkserve="served"
elif [ -f "/opt/verb/conf/inkdns/parked/db.${servedomain}" ]; then
  parkserve="parked"
else
  /usr/bin/echo "${servedomain} is neither served nor parked here; nothing to do"
  exit 8
fi

# Update the NS servers
/usr/bin/ssh -T ns1 <<EOS
/usr/bin/mkdir -p /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh
/usr/bin/mv /srv/sns/${ServerName}-${ServerTLD}/domains/${parkserve}/${servedomain} /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh/
/usr/bin/echo "verber-killed at $(date +'%Y-%m-%d_%H:%M:%S')" >> /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh/${servedomain}
EOS
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/echo "Killed ${servedomain} as on NS1"
/usr/bin/ssh -T ns2 <<EOS
/usr/bin/mkdir -p /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh
/usr/bin/mv /srv/sns/${ServerName}-${ServerTLD}/domains/${parkserve}/${servedomain} /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh/
/usr/bin/echo "verber-killed at $(date +'%Y-%m-%d_%H:%M:%S')" >> /srv/sns/${ServerName}-${ServerTLD}/domains/killed/fresh/${servedomain}
EOS
e="$?"; [[ "$e" = "0" ]] || exit "$e"
/usr/bin/echo "Killed ${servedomain} as on NS2"


if [ -e "/opt/verb/mods/rinkkilldomain.after" ]; then . /opt/verb/mods/rinkkilldomain.after; fi # Follows this script
