#!/bin/bash
#inkVerbSerf! verb.ink

# This remote runs inkdnsaddslave on both NS rink slave servers
## This is run automatically by newdomainshell and rinkimportme; it normally should not be run independently

# How to use:
## ./rinkadddomain [ domain.tld ]

usagenotes="This remote runs inkdnsaddslave on both NS rink slave servers"
usageformat="rinkadddomain [ domain.tld ]"
usageexample="rinkadddomain inkisaverb.com"
hierarchy=( tertiary newdomainshell )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=( "Controlled by Rink" )
prerequesite=(  )
usedby=( newdomainshell rinkimportme )
useserfs=(  )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/rinkadddomain.replace" ]; then . /opt/verb/mods/rinkadddomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/rinkadddomain.before" ]; then . /opt/verb/mods/rinkadddomain.before; fi # Precedes this script


slavedomain=$1

# Configs
. /opt/verb/conf/servernameip

# Already configured?
if [ "$RinkConfigured" != "true" ]; then
	echo "Rink NS nameserver keys not configured, DNS nameserver zone files will need to be updated manually"
	exit 0
elif [ "$RinkConfigured" = "rink" ] && [ -f "/opt/rink/run/addmasterdomain" ]; then
	/opt/rink/run/addmasterdomain ${slavedomain}
	exit 0
fi

# Add the configs to the domains/ folder on the NS nameservers
/usr/bin/ssh ns1 <<EOS
/usr/bin/cat <<EOF > /srv/sns/${ServerName}-${ServerTLD}/domains/${slavedomain}
sdnsDomain="${slavedomain}"
sdnsIPv4="${ServerIPv4}"
sdnsIPv4ARPA="${ServerARPAIPv4}"
sdnsIPv6Exp="${ServerExpIPv6}"
sdnsIPv6Cmp="${ServerIPv6}"
sdnsIPv6ARPA="${ServerARPAIPv6}"
EOF
EOS
/usr/bin/ssh ns2 <<EOS
/usr/bin/cat <<EOF > /srv/sns/${ServerName}-${ServerTLD}/domains/${slavedomain}
sdnsDomain="${slavedomain}"
sdnsIPv4="${ServerIPv4}"
sdnsIPv4ARPA="${ServerARPAIPv4}"
sdnsIPv6Exp="${ServerExpIPv6}"
sdnsIPv6Cmp="${ServerIPv6}"
sdnsIPv6ARPA="${ServerARPAIPv6}"
EOF
EOS

if [ -e "/opt/verb/mods/rinkadddomain.after" ]; then . /opt/verb/mods/rinkadddomain.after; fi # Follows this script
