#!/bin/bash
#inkVerbSerf! verb.ink

# This activates and deactivates the podcast feature in Ampache

# How to use:
## ./setampachepodcast [ on/off ]

# Eg:
## ./setampachepodcast on
## ./setampachepodcast off


usagenotes="This activates and deactivates the podcast feature in Ampache"
usageformat="setampachepodcast [ on/off ]"
usageexample="setampachepodcast on
setampachepodcast off"
hierarchy=( primary )
vsetnames=( "On or off" )
vsettypes=( isChoice )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setampachepodcast.replace" ]; then . /opt/verb/mods/setampachepodcast.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setampachepodcast.before" ]; then . /opt/verb/mods/setampachepodcast.before; fi # Precedes this script


if [ "$1" = "-h" ]
then
    /bin/echo "Usage: ./activatepodcast [on/off]

Examples:
 ./activatepodcast on
 ./activatepodcast off"

exit 0
fi

if [ "$1" = "on" ]
then
    /usr/bin/sed -i "s/;podcast = \"false\"/podcast = \"true\"/g" /srv/www/vapps/ampache/config/ampache.cfg.php
    /bin/echo "Ampcache podcast on.

1. Configure Podcast settings in: Admin > Server Config > System.
2. Add a new Podcast local Catalog in: Admin > Catalogs > Add Catalog.
3. Add your podcast url in: Home > Browse Music > Podcasts.
"
exit 0
fi

if [ "$1" = "off" ]
then
    /usr/bin/sed -i "s/podcast = \"true\"/;podcast = \"false\"/g" /srv/www/vapps/ampache/config/ampache.cfg.php
    /bin/echo "Ampcache podcast off."
exit 0
fi




if [ -e "/opt/verb/mods/setampachepodcast.after" ]; then . /opt/verb/mods/setampachepodcast.after; fi # Follows this script
