#!/bin/bash
#inkVerbSerf! verb.ink

# This sets up basic mail DNS and inkCert entries
## This is run automatically by setup and setinkcertmail (used in installinkvmail and newdomainshell) and normally should not be run independently

# How to use:
## ./setinkcertmailsubdomains somedomain.tld

domain="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# inkCert
## Ensure that you don't get double entries
/bin/sed -i "s/, mail.${domain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
/bin/sed -i "s/, smtp.${domain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
/bin/sed -i "s/, imap.${domain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
/bin/sed -i "s/, pop3.${domain}//g" /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini
## Add it to the cli-ini
/bin/sed -i "/^domains =/ s/$/, mail.${domain}, smtp.${domain}, imap.${domain}, pop3.${domain}/" /opt/verb/conf/inkcert/cli-ini/cli.${domain}.ini




if [ -e "/opt/verb/mods/setinkcertmailsubdomains.after" ]; then . /opt/verb/mods/setinkcertmailsubdomains.after; fi # Follows this script
