#!/bin/bash
#inkVerbSerf! verb.ink

# This sets new site-wide SSL CA for inkNet
## Theoretically, this should not be necessary unless inkVerb makes changes to their own domain.

# How to use:
## ./setinknetsslca [ inkNet SSL CA ]

# Eg:
## ./setinknetsslca sslca.inkisaverb.com


usagenotes="This sets new site-wide SSL CA for inkNet"
usageformat="setinknetsslca [ inkNet SSL CA ]"
usageexample="setinknetsslca sslca.inkisaverb.com"
hierarchy=( secondary )
vsetnames=( "InkNet SSL CA" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inknetmakeverberclient )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setinknetsslca.replace" ]; then . /opt/verb/mods/setinknetsslca.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setinknetsslca.before" ]; then . /opt/verb/mods/setinknetsslca.before; fi # Precedes this script


INKSSLCA=$1

/bin/sed -i "s/InkNetSSLCA=.*/InkNetSSLCA=\"${INKSSLCA}\"/g" /opt/verb/conf/inknet/inknetinfo





if [ -e "/opt/verb/mods/setinknetsslca.after" ]; then . /opt/verb/mods/setinknetsslca.after; fi # Follows this script
