#!/bin/bash
#inkVerbSerf! verb.ink

# This links the mail certs defined by setinkcertmail to the location used by the mail server
## This is run automatically by installpostfixvmail, setinkcertmail, and inkcertdo* and normally should not be run independently

# How to use:
## ./setinkcertmailcerts [ domain.tld ] [ switch 'inkvmail', optional for system email certs, used by installpostfixvmail ]


# Dependencies
if ! /bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

# Include the config
. /opt/verb/conf/siteurilist

DOMAIN="$1"

if [ -n "$2" ] && [ "$2" = "inkvmail" ]; then
  DEST="vmail"
else
  DEST="$1"
fi

# Link the inkCert-LE certs if they exist, otherwise use Snakeoil
if [ -f "/etc/inkcert/le/live/${DOMAIN}/fullchain.pem" ] && [ -f "/etc/inkcert/le/live/${DOMAIN}/privkey.pem" ]; then
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/fullchain.pem /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/chmod 0444 /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/sed -i "s?^#smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#smtp_sender_dependent_authentication = yes?smtp_sender_dependent_authentication = yes?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/mail/vmail.crt?ssl_cert = </etc/ssl/server/mail/vmail.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^#ssl_dh = </etc/dovecot/dh.pem?ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_chain_files = /etc/ssl/server/server.key?#smtpd_tls_chain_files = /etc/ssl/server/server.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/server.crt?#ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/ln -sfn /etc/inkcert/le/live/${DOMAIN}/privkey.pem /etc/ssl/server/mail/${DEST}.key
  /usr/bin/chmod 0400 /etc/ssl/server/mail/${DEST}.key
  /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/mail/vmail.key?ssl_key = </etc/ssl/server/mail/vmail.key?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/server.key?#ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
else
  /usr/bin/rm -f /etc/ssl/server/mail/${DEST}.crt
  /usr/bin/sed -i "s?^#smtpd_tls_chain_files = /etc/ssl/server/server.key?smtpd_tls_chain_files = /etc/ssl/server/server.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/server.crt?ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?#smtpd_tls_chain_files = /etc/ssl/server/mail/vmail.key?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^smtp_sender_dependent_authentication = yes?#smtp_sender_dependent_authentication = yes?" /etc/postfix/main.cf
  /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/mail/vmail.crt?#ssl_cert = </etc/ssl/server/mail/vmail.crt?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_dh = </etc/dovecot/dh.pem?#ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/rm -f /etc/ssl/server/mail/${DEST}.key
  /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/server.key?ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
  /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/mail/vmail.key?#ssl_key = </etc/ssl/server/mail/vmail.key?" /etc/dovecot/conf.d/10-ssl.conf
fi

# Restart Postfix
/usr/bin/systemctl restart postfix
/usr/bin/systemctl restart dovecot




if [ -e "/opt/verb/mods/setinkcertmailcerts.after" ]; then . /opt/verb/mods/setinkcertmailcerts.after; fi # Follows this script
