#!/bin/bash
#inkVerbSerf! verb.ink

# This sets up basic mail certificates and subdomain dummy sites for inkCert-LE
## This is run automatically by setup, installpostfixvmail, and newdomainshell, and normally should not be run independently

# How to use:
## ./setinkcertmail [ domain.tld ] [ switch 'verber', optional skip inkCert cli.ini, used by installpostfixvmail ]

# Eg:
## ./setinkcertmail somedomain.tld
## ./setinkcertmail name.verb.ink verber


# Dependencies
if ! /bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /bin/grep -q 'ServerMailStatus="VMAIL_SERVER"' /opt/verb/conf/servermailpath; then
  /usr/bin/echo "Install Postfix Vmail first, I quit."; exit 8
fi

domain="$1"

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servertype

# inkCert
if [ "$2" != "verber" ]; then
  /opt/verb/serfs/setinkcertmailsubdomains ${domain}
fi

# Webserver directory (remake it everytime)
/usr/bin/mkdir -p /srv/www/mailcatch
/usr/bin/cat <<'EOF' > /srv/www/mailcatch/index.htm
<!DOCTYPE html>
<html>
<head><title>Hey, Boo!</title></head>
<body><h1 style="text-align:center">Hey, Boo!</h1><hr></body>
</html>
EOF
/usr/bin/chown -R www:www /srv/www/mailcatch

# Mail cert links
if [ "$2" = "verber" ]; then
  /opt/verb/serfs/setinkcertmailcerts ${domain} inkvmail
else
  /opt/verb/serfs/setinkcertmailcerts ${domain}
fi

# Only make the Dovecot & Postfix entries if the keys exist
if [ -e "$(/usr/bin/readlink /etc/ssl/server/mail/${domain}.crt)" ] && [ -e "$(/usr/bin/readlink /etc/ssl/server/mail/${domain}.key)" ]; then
  # Dovecot
  /usr/bin/cat <<EOF > /etc/dovecot/crt.d/${domain}.conf
local_name mail.${domain} {
  ssl_cert = </etc/ssl/server/mail/${domain}.crt
  ssl_key = </etc/ssl/server/mail/${domain}.key
}

local_name imap.${domain} {
  ssl_cert = </etc/ssl/server/mail/${domain}.crt
  ssl_key = </etc/ssl/server/mail/${domain}.key
}

local_name pop3.${domain} {
  ssl_cert = </etc/ssl/server/mail/${domain}.crt
  ssl_key = </etc/ssl/server/mail/${domain}.key
}

local_name pop2.${domain} {
  ssl_cert = </etc/ssl/server/mail/${domain}.crt
  ssl_key = </etc/ssl/server/mail/${domain}.key
}

local_name pop.${domain} {
  ssl_cert = </etc/ssl/server/mail/${domain}.crt
  ssl_key = </etc/ssl/server/mail/${domain}.key
}
EOF
  ## Own
  /bin/chown vmail:dovecot /etc/dovecot/crt.d/${domain}.conf
  /bin/chmod o-rwx /etc/dovecot/crt.d/${domain}.conf

  # Postfix
  if ! /bin/grep -q "mail.${domain} /etc/ssl/server/mail/${domain}.key /etc/ssl/server/mail/${domain}.crt" /etc/postfix/virtual_ssl.map; then
    /usr/bin/cat <<EOF >> /etc/postfix/virtual_ssl.map
mail.${domain} /etc/ssl/server/mail/${domain}.key /etc/ssl/server/mail/${domain}.crt
smtp.${domain} /etc/ssl/server/mail/${domain}.key /etc/ssl/server/mail/${domain}.crt
EOF
  fi
  /usr/bin/postmap -F lmdb:/etc/postfix/virtual_ssl.map # Because we made an entry in this file and this is the only way to refresh that
fi

# Webserver files so inkCert-LE checks work
if [ ${ServerType} = "laemp" ] || [ ${ServerType} = "lemp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/mail.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/smtp.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/imap.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/pop3.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/pop2.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnginxmailcatch.conf /opt/verb/conf/webserver/sites-available/nginx/pop.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/mail.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/smtp.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/imap.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/pop3.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/pop2.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${domain}/g" /opt/verb/conf/webserver/sites-available/nginx/pop.${domain}.conf
  /opt/verb/serfs/ensitenginx mail.${domain} smtp.${domain} imap.${domain} pop3.${domain} pop2.${domain} pop.${domain}

elif [ ${ServerType} = "lamp" ]; then

  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/mail.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/smtp.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/imap.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/pop3.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/pop2.${domain}.conf
  /usr/bin/cp /opt/verb/conf/site-files/conf/newnapachemailcatch.conf /opt/verb/conf/webserver/sites-available/httpd/pop.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/mail.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/mail.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/smtp.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/smtp.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/imap.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/imap.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop3.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/pop3.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop2.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/pop2.${domain}.conf
  /bin/sed -i "s/mailcatchdomain/pop.${domain}/g" /opt/verb/conf/webserver/sites-available/httpd/pop.${domain}.conf
  /opt/verb/serfs/ensiteapache mail.${domain} smtp.${domain} imap.${domain} pop3.${domain} pop2.${domain} pop.${domain}

fi




if [ -e "/opt/verb/mods/setinkcertmail.after" ]; then . /opt/verb/mods/setinkcertmail.after; fi # Follows this script
