#!/bin/bash
#inkVerbSerf! verb.ink

# This sets new site-wide repo for Verber app installs, used primarily or solely by the inkget serf
## This should generally not be necessary unless new repos have been added and the current repo is distant or has high traffic.

# How to use:
## ./setinkgetrepo [ inkget repo ]

# Eg:
## ./setinkgetrepo toronto.verb.ink


usagenotes="This sets new site-wide repo for Verber app installs, used primarily or solely by the inkget serf"
usageformat="setinkgetrepo [ inkget repo ]"
usageexample="setinkgetrepo toronto.verb.ink"
hierarchy=( secondary )
vsetnames=( "Inkget repo" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inknetmakeverberclient )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setinkgetrepo.replace" ]; then . /opt/verb/mods/setinkgetrepo.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setinkgetrepo.before" ]; then . /opt/verb/mods/setinkgetrepo.before; fi # Precedes this script


NEWINKRepo=$1

/bin/sed -i "s/InkGet_Repo=.*/InkGet_Repo=\"${NEWINKRepo}\"/g" /opt/verb/conf/serverinkget





if [ -e "/opt/verb/mods/setinkgetrepo.after" ]; then . /opt/verb/mods/setinkgetrepo.after; fi # Follows this script
