#!/bin/bash
#inkVerbSerf! verb.ink

# This links the mail certs defined by setinkcertmail to the location used by the mail server
## This is run automatically by installpostfixvmail, setinkcertmail, inkmaildomains, and inkcertdo* and normally should not be run independently

# How to use:
## ./setinkcertmailcerts [ domain.tld ] [ switch 'inkmail', optional for system email certs, used by installpostfixvmail installmaddymail ]


# Dependencies
if ! /usr/bin/grep -q 'InkCertInstalled="DONE"' /opt/verb/conf/inkcertstatus; then
  /usr/bin/echo "Install inkCert first, I quit."; exit 8
fi
if ! /usr/bin/grep -q 'InkDNSStat="INSTALLED"' /opt/verb/conf/inkdnsconf; then
  /usr/bin/echo "Install inkDNS first, I quit."; exit 8
fi
if ! /usr/bin/grep -q 'ServerMailStatus="VMAIL_"' /opt/verb/conf/servermailpath && ! /usr/bin/grep -q 'ServerMailStatus="MADDY_EMAIL_"' /opt/verb/conf/servermailpath; then
  /usr/bin/echo "Install either Maddy Email or Postfix Vmail first, I quit."; exit 8
fi
if ! /usr/bin/grep -q 'EmailAllowed="YES"' /opt/verb/conf/servernameip; then
  /usr/bin/echo "Email not allowed. Do you know what you are doing?"; exit 8
fi

# Include the config
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath

domain="$1"

if [ -n "$2" ] && [ "$2" = "inkmail" ]; then
  if [ "${ServerMailStatus}" = "VMAIL_SERVER" ] || [ "${ServerMailStatus}" = "VMAIL_READY" ]; then
    dest="vmail"
  elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ] || [ "${ServerMailStatus}" = "MADDY_EMAIL_READY" ]; then # OR if [[ "${ServerMailStatus}" == "MADDY_EMAIL_"* ]]; then # For serfs inside installmaddymail

    dest="email"
  fi
else
  dest="$1"
fi

# Link the inkCert-LE certs if they exist, otherwise use Snakeoil
## Postfix vmail?
if [ "${ServerMailStatus}" = "VMAIL_SERVER" ] || [ "${ServerMailStatus}" = "VMAIL_READY" ]; then
  if [ -f "/etc/inkcert/le/live/${domain}/fullchain.pem" ] && [ -f "/etc/inkcert/le/live/${domain}/privkey.pem" ]; then
    /usr/bin/ln -sfn /etc/inkcert/le/live/${domain}/fullchain.pem /etc/ssl/server/mail/${dest}.crt
    /usr/bin/chmod 0444 /etc/ssl/server/mail/${dest}.crt
    /usr/bin/sed -i "s?^#smtpd_tls_chain_files = /etc/ssl/server/mail/${dest}.key?smtpd_tls_chain_files = /etc/ssl/server/mail/${dest}.key?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^#smtp_sender_dependent_authentication = yes?smtp_sender_dependent_authentication = yes?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/mail/${dest}.crt?ssl_cert = </etc/ssl/server/mail/${dest}.crt?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^#ssl_dh = </etc/dovecot/dh.pem?ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^smtpd_tls_chain_files = /etc/ssl/server/server.key?#smtpd_tls_chain_files = /etc/ssl/server/server.key?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/server.crt?#ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/ln -sfn /etc/inkcert/le/live/${domain}/privkey.pem /etc/ssl/server/mail/${dest}.key
    /usr/bin/chmod 0400 /etc/ssl/server/mail/${dest}.key
    /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/mail/${dest}.key?ssl_key = </etc/ssl/server/mail/${dest}.key?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/server.key?#ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
  else
    /usr/bin/rm -f /etc/ssl/server/mail/${dest}.crt
    /usr/bin/sed -i "s?^#smtpd_tls_chain_files = /etc/ssl/server/server.key?smtpd_tls_chain_files = /etc/ssl/server/server.key?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^#ssl_cert = </etc/ssl/server/server.crt?ssl_cert = </etc/ssl/server/server.crt?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^smtpd_tls_chain_files = /etc/ssl/server/mail/${dest}.key?#smtpd_tls_chain_files = /etc/ssl/server/mail/${dest}.key?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^smtp_sender_dependent_authentication = yes?#smtp_sender_dependent_authentication = yes?" /etc/postfix/main.cf
    /usr/bin/sed -i "s?^ssl_cert = </etc/ssl/server/mail/${dest}.crt?#ssl_cert = </etc/ssl/server/mail/${dest}.crt?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^ssl_dh = </etc/dovecot/dh.pem?#ssl_dh = </etc/dovecot/dh.pem?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/rm -f /etc/ssl/server/mail/${dest}.key
    /usr/bin/sed -i "s?^#ssl_key = </etc/ssl/server/server.key?ssl_key = </etc/ssl/server/server.key?" /etc/dovecot/conf.d/10-ssl.conf
    /usr/bin/sed -i "s?^ssl_key = </etc/ssl/server/mail/${dest}.key?#ssl_key = </etc/ssl/server/mail/${dest}.key?" /etc/dovecot/conf.d/10-ssl.conf
  fi
  ## Restart Postfix
  /usr/bin/systemctl restart postfix
  /usr/bin/systemctl restart dovecot

## Maddy email?
elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ] || [ "${ServerMailStatus}" = "MADDY_EMAIL_READY" ]; then
  if [ -f "/etc/inkcert/le/live/${domain}/fullchain.pem" ] && [ -f "/etc/inkcert/le/live/${domain}/privkey.pem" ]; then
    #DEV This didn't make maddy work, just keep it as it is
    # /usr/bin/chown -R root:maddy /etc/ssl/server/mail/
    # /usr/bin/chmod 0750 /etc/ssl/server/ /etc/ssl/server/mail/
    # /usr/bin/chmod 0644 /etc/ssl/server/mail/${dest}.crt
    # /usr/bin/chmod 0640 /etc/ssl/server/mail/${dest}.key
    # /usr/bin/setfacl -R -m u:maddy:rX /etc/ssl/server/mail/{${dest}.crt,${dest}.key}
    ### Maddy doesn't use this, but they are still here for cuz
    /usr/bin/ln -sfn /etc/inkcert/le/live/${domain}/fullchain.pem /etc/ssl/server/mail/${dest}.crt
    /usr/bin/chmod 0444 /etc/ssl/server/mail/${dest}.crt
    /usr/bin/ln -sfn /etc/inkcert/le/live/${domain}/privkey.pem /etc/ssl/server/mail/${dest}.key
    /usr/bin/chmod 0400 /etc/ssl/server/mail/${dest}.key
  else
    /usr/bin/rm -f /etc/ssl/server/mail/${dest}.crt
    /usr/bin/rm -f /etc/ssl/server/mail/${dest}.key
  fi
  ## Restart Maddy
  /usr/bin/systemctl restart maddy
fi






if [ -e "/opt/verb/mods/setinkcertmailcerts.after" ]; then . /opt/verb/mods/setinkcertmailcerts.after; fi # Follows this script
