#!/bin/bash
#inkVerbSerf! verb.ink

# This sets a new IPv4 address on the server

# How to use:
## ./setipv4 [IPv4 number]


# Include the config file
. /opt/verb/conf/servernameip

# IP4?
if [ "${ServerIPv4}" = "NOIP4" ]; then
  /usr/bin/echo "IPv4 is disabled on this server. Nothing to do."
  exit 0
fi

NEWIP4="$1"

# Normal IP
/bin/sed -i "s:ServerIPv4=.*:ServerIPv4=\"${NEWIP4}\":" /opt/verb/conf/servernameip
/bin/sed -i "s:${ServerIPv4}:${NEWIP4}:" /etc/hosts

# ARPA & inverse IP
## THANKS https://unix.stackexchange.com/a/132806/315069
NEWARPAIP4=$(/bin/echo ${NEWIP4} | /usr/bin/sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
/bin/sed -i "s:ServerARPAIPv4.*:ServerARPAIPv4=\"${NEWARPAIP4}\":" /opt/verb/conf/servernameip

# Finish
/bin/echo "IPv4 now set to: ${NEWIP4}"




if [ -e "/opt/verb/mods/setipv4.after" ]; then . /opt/verb/mods/setipv4.after; fi # Follows this script
