#!/bin/bash
#inkVerbSerf! verb.ink

# This turns on bruteforce protection for nextcloud

# How to use:
## ./setnextcloudbfdon


usagenotes="This turns on bruteforce protection for nextcloud"
usageformat="setnextcloudbfdon"
usageexample="setnextcloudbfdon"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setnextcloudbfdon.replace" ]; then . /opt/verb/mods/setnextcloudbfdon.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setnextcloudbfdon.before" ]; then . /opt/verb/mods/setnextcloudbfdon.before; fi # Precedes this script


# Fix the setting in basic.config.php, searching for both true and false
/bin/sed -i "s/'auth\.bruteforce\.protection\.enabled' => false/'auth\.bruteforce\.protection\.enabled' => true/" /srv/www/vapps/nextcloud/config/basic.config.php




if [ -e "/opt/verb/mods/setnextcloudbfdon.after" ]; then . /opt/verb/mods/setnextcloudbfdon.after; fi # Follows this script
