#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the PostfixAdmin password hash for installation
## The hash is retrieved from the setup.php page

# How to use:
## ./setpfapass [ rawpassword ]


usagenotes="This sets the PostfixAdmin password hash for installation"
usageformat="setpfapass [ rawpassword ]"
usageexample="setpfapass
setpfapass [ rawpassword ]"
hierarchy=( tertiary installpfa )
vsetnames=( "Password" )
vsettypes=( isPassword )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( installpfa )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setpfapass.replace" ]; then . /opt/verb/mods/setpfapass.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setpfapass.before" ]; then . /opt/verb/mods/setpfapass.before; fi # Precedes this script


pfaPass=$1

# Replace whatever current hash settings with the hash
instHash="$(/usr/bin/php -r "echo password_hash('${pfaPass}', PASSWORD_DEFAULT);")"
/usr/bin/sed -i "s/\$CONF\['configured'\] = .*/\$CONF\['configured'\] = true;/g" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "/setup_password/d" /srv/www/email/postfixadmin/config.local.php
/usr/bin/sed -i "/setup_password/d" /srv/www/email/postfixadmin/config.inc.php
/usr/bin/cat <<EOF >> /srv/www/email/postfixadmin/config.local.php
\$CONF['setup_password'] = '${instHash}';
EOF

# Make a record so it can be called
/usr/bin/echo "pfaSetupTPass=\"${pfaPass}\"" > /opt/verb/conf/pfasetuppass




if [ -e "/opt/verb/mods/setpfapass.after" ]; then . /opt/verb/mods/setpfapass.after; fi # Follows this script
