#!/bin/bash
#inkVerbSerf! verb.ink
# Compatibility: setpw99 is now setwinston99

usagenotes="This modifies Winston 99 settings (was setpw99)"
usageformat="setpw99 [ domain.tld ] [ key=value ] ..."
usageexample="setpw99 99.write.pink allow_create_super=false"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=( installwinston99 )
usedby=(  )
useserfs=( setwinston99 )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi
if [ -e "/opt/verb/mods/setpw99.replace" ]; then . /opt/verb/mods/setpw99.replace; return 0; fi

exec /opt/verb/serfs/setwinston99 "$@"
