#!/bin/bash
#inkVerbSerf! verb.ink

# This changes the path of the PostfixAdmin web path
## This changes the path already set by installfpa

# How to use:
## ./setpfapath [ folder ]

# Eg:
## To use at po.NAME.verb.email/mysecretpath do: ./installpfa easy mysecretpath


usagenotes="This changes the path of the PostfixAdmin web path"
usageformat="setpfapath [ folder ]"
usageexample="setpfapath
setpfapath [ folder ]"
hierarchy=( primary )
vsetnames=( "Folder" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setpfapath.replace" ]; then . /opt/verb/mods/setpfapath.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setpfapath.before" ]; then . /opt/verb/mods/setpfapath.before; fi # Precedes this script


# Include the config files
. /opt/verb/conf/servernameip
. /opt/verb/conf/servermailpath

pfaFolder=$1

/bin/rm -rf /srv/www/html/${ServerEmailTLD}.pfa
/bin/cp -R /srv/www/html/0ne /srv/www/html/${ServerEmailTLD}.pfa
/bin/ln -s /srv/www/email/postfixadmin /srv/www/html/${ServerEmailTLD}.pfa/${pfaFolder}
/bin/chown -R www:www /srv/www/html/${ServerEmailTLD}.pfa
/bin/sed -i "s/ServerPFAPath=.*/ServerPFAPath=\"${pfaFolder}\"/g" /opt/verb/conf/servermailpass
/bin/sed -i "s/\$CONF\['postfix_admin_url'\] = 'https:\/\/.*/\$CONF\['postfix_admin_url'\] = 'https:\/\/pfa\.${ServerName}\.verb\.${ServerEmailTLD}\/${pfaFolder}';/g" /srv/www/email/postfixadmin/config.inc.php





if [ -e "/opt/verb/mods/setpfapath.after" ]; then . /opt/verb/mods/setpfapath.after; fi # Follows this script
