#!/bin/bash
#inkVerbSerf! verb.ink

# This changes the path of the RoundCube web path
## This changes the path already set by installrc

# How to use:
## ./setrcpath [ folder ]

# Eg:
## (To use at box.NAME.verb.email/mysecretpath do:)
## ./setrcpath mysecretpath


usagenotes="This changes the path of the RoundCube web path"
usageformat="setrcpath [ folder ]"
usageexample="setrcpath mysecretpath"
hierarchy=( primary )
vsetnames=( "Folder" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip servermailpath )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setrcpath.replace" ]; then . /opt/verb/mods/setrcpath.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setrcpath.before" ]; then . /opt/verb/mods/setrcpath.before; fi # Precedes this script


# Include the config file
. /opt/verb/conf/servernameip
. /opt/verb/conf/servermailpath

rcFolder=$1

if [ "${ServerBoxPath}" = "${rcFolder}" ]; then
  echo "Folder already taken by box."
  exit 7
fi

/bin/rm -rf /srv/www/html/${ServerEmailTLD}.box
/bin/cp -R /srv/www/html/0ne /srv/www/html/${ServerEmailTLD}.box
/bin/ln -s /srv/www/email/roundcube /srv/www/html/${ServerEmailTLD}.box/${rcFolder}
/bin/chown -R www:www /srv/www/html/${ServerEmailTLD}.box
/bin/sed -i "s/ServerRCPath=.*/ServerRCPath=\"${rcFolder}\"/g" /opt/verb/conf/servermailpass
/bin/sed -i "s/\$Conf\['footer_link'\] = 'https:\/\/.*/\$Conf\['footer_link'\] = 'https:\/\/box\.${ServerName}\.verb\.${ServerEmailTLD}\/${rcFolder}';/g" /srv/www/email/postfixadmin/config.inc.php




if [ -e "/opt/verb/mods/setrcpath.after" ]; then . /opt/verb/mods/setrcpath.after; fi # Follows this script
