#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the inkGet repo version list so that it will automatically update when the Verber is updated

# How to use:
## ./setrepoauto


usagenotes="This sets the inkGet repo version list so that it will automatically update when the Verber is updated"
usageformat="setrepoauto"
usageexample="setrepoauto"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setrepoauto.replace" ]; then . /opt/verb/mods/setrepoauto.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setrepoauto.before" ]; then . /opt/verb/mods/setrepoauto.before; fi # Precedes this script


/bin/sed -i "s/InkGet_List=.*/InkGet_List=\"AUTO_UPDATE\"/g" /opt/verb/conf/serverinkget





if [ -e "/opt/verb/mods/setrepoauto.after" ]; then . /opt/verb/mods/setrepoauto.after; fi # Follows this script
