#!/bin/bash
#inkVerbSerf! verb.ink


# This runs the delete of the "serve" download directory rather than waiting for the 30 minute cron

# How to use:
## ./setserveclear


usagenotes="This runs the delete of the \"serve\" download directory rather than waiting for the 30 minute cron"
usageformat="setserveclear"
usageexample="setserveclear"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setserveclear.replace" ]; then . /opt/verb/mods/setserveclear.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setserveclear.before" ]; then . /opt/verb/mods/setserveclear.before; fi # Precedes this script


/opt/verb/donjon/rmdldirs.sh




if [ -e "/opt/verb/mods/setserveclear.after" ]; then . /opt/verb/mods/setserveclear.after; fi # Follows this script
