#!/bin/bash
#inkVerbSerf! verb.ink

# This adds/updates the secure salts to owa-config.php files of a pre-installed (or installing) OWA site
## This does not normally need to be run on fresh OWA installations since the same functions and behavior are embedded in the installwp serfs.

# How to use:
## ./setsecureowa


usagenotes="This adds/updates the secure salts to owa-config.php files of a pre-installed (or installing) OWA site"
usageformat="setsecureowa"
usageexample="setsecureowa"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setsecureowa.replace" ]; then . /opt/verb/mods/setsecureowa.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setsecureowa.before" ]; then . /opt/verb/mods/setsecureowa.before; fi # Precedes this script


OWA_NONCE_KEY="$(/usr/bin/pwgen -s -1 27)"
OWA_NONCE_SALT="$(/usr/bin/pwgen -s -1 27)"
OWA_AUTH_KEY="$(/usr/bin/pwgen -s -1 27)"
OWA_AUTH_SALT="$(/usr/bin/pwgen -s -1 27)"

# Insert the random pwgen strings
/bin/sed -i "s/define('OWA_NONCE_KEY',.*/define('OWA_NONCE_KEY', '${OWA_NONCE_KEY}');/g" /srv/www/verb/red.owa/owa-config.php
/bin/sed -i "s/define('OWA_NONCE_SALT',.*/define('OWA_NONCE_SALT', '${OWA_NONCE_SALT}');/g" /srv/www/verb/red.owa/owa-config.php
/bin/sed -i "s/define('OWA_AUTH_KEY',.*/define('OWA_AUTH_KEY', '${OWA_AUTH_KEY}');/g" /srv/www/verb/red.owa/owa-config.php
/bin/sed -i "s/define('OWA_AUTH_SALT',.*/define('OWA_AUTH_SALT', '${OWA_AUTH_SALT}');/g" /srv/www/verb/red.owa/owa-config.php

/bin/echo "OWA now has secure strings."




if [ -e "/opt/verb/mods/setsecureowa.after" ]; then . /opt/verb/mods/setsecureowa.after; fi # Follows this script
