#!/bin/bash
#inkVerbSerf! verb.ink

# This sets or activates swap to a set size
## 1GB should display something like:
#. 1000+0 records in
#. 1000+0 records out
#. 1048576000 bytes (1.0 GB) copied, 4.0868896 s, 253 MB/s

# How to use:
## ./setswapsize [swap-size in GB]

# Eg:
## ./setswapsize 4


swapSize=$1

## Use SSD if mounted and system uses btrfs
if /usr/bin/grep -q "^LABEL=" /etc/fstab | /usr/bin/grep -q '\s/\s' | /usr/bin/grep -q 'btrfs' || /usr/bin/grep -q "^UUID=" /etc/fstab | /usr/bin/grep -q '\s/\s' | /usr/bin/grep -q 'btrfs'; then
    if [ -f "/opt/verb/conf/inkdrive/inkdriveinfo" ]; then
        . /opt/verb/conf/inkdrive/inkdriveinfo
        if [ -n "${SSDdefault}" ]; then
            swapDir="mnt/${SSDdefault}"
        else
            /usr/bin/echo "System mounted on btrfs disk with no mounted SSD; swap unavailable!"
            exit 0
        fi
    else
        /usr/bin/echo "System mounted on btrfs disk with no mounted SSD; swap unavailable!"
        exit 0
    fi
else
    swapDir="var"
fi

# Prepare
## Make sure it's off, quietly
/usr/bin/swapoff /${swapDir}/swap.img 2>/dev/null
cd /var || exit 6
/usr/bin/touch /${swapDir}/swap.img
/usr/bin/chmod 600 /${swapDir}/swap.img

# Create the swap file
/usr/bin/dd if=/dev/zero of=/${swapDir}/swap.img bs=${swapSize}M count=1024


## Old example of 2gb
# ## 2GB
# /usr/bin/dd if=/dev/zero of=/${swapDir}/swap.img bs=2048k count=1000
# ### Should display something like:
# #. 1000+0 records in
# #. 1000+0 records out
# #. 2097152000 bytes (2.1 GB) copied, 31.6348 s, 66.3 MB/s
# ###

## Initialize
/usr/bin/mkswap /${swapDir}/swap.img
### Should display something like:
#. no label, UUID=d35552b3-4bbe-42a0-b129-5483a2211cde

## Permissions
/usr/bin/chmod 0600 /${swapDir}/swap.img

# Enable current session
/usr/bin/swapon /${swapDir}/swap.img

# Check that it is running
/usr/bin/free
### Should display something like:
#..
#. Swap:      4094996          0    4094996

# Clear out any swap entries in fstab
/usr/bin/sed -i '/swap.img    none    swap    sw    0    0/d' /etc/fstab

# Set to enable swap at next startup
/usr/bin/echo "/${swapDir}/swap.img    none    swap    sw    0    0" >> /etc/fstab




if [ -e "/opt/verb/mods/setswapsize.after" ]; then . /opt/verb/mods/setswapsize.after; fi # Follows this script
