#!/bin/bash
#inkVerbSerf! verb.ink

# This sets the symlink for a vapp from the html/ folder to the vapps/ folder

# How to use:
## ./setvapplinkon [ vapp name ]


usagenotes="This sets the symlink for a vapp from the html/ folder to the vapps/ folder"
usageformat="setvapplinkon [ vapp name ]"
usageexample="setvapplinkon
setvapplinkon [ vapp name ]"
hierarchy=( tertiary backuprestore )
vsetnames=( "Vapp name" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( backuprestore installampache installfossil installmediawiki installnet2ftp installnextcloud installorangehrm installsuitecrm installwpinkbb installwpinkblog )
useserfs=(  )
useconfigs=( serverport siteurilist )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/setvapplinkon.replace" ]; then . /opt/verb/mods/setvapplinkon.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/setvapplinkon.before" ]; then . /opt/verb/mods/setvapplinkon.before; fi # Precedes this script


# Include the config file
. /opt/verb/conf/serverport
. /opt/verb/conf/siteurilist

vAppName=$1

case ${vAppName} in

fossil)
/bin/rm -rf /srv/www/verb/${itsqlTLD}/fossil
/bin/ln -sfn /srv/www/vip/${vAppName} /srv/www/verb/${itsqlTLD}/fossil
/bin/echo "${vAppName} symlink is set."
;;

net2ftp)
/bin/rm -rf /srv/www/verb/${itsqlTLD}/net2ftp
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/${itsqlTLD}/net2ftp
/bin/echo "${vAppName} symlink is set."
;;

ampache)
/bin/rm -rf /srv/www/verb/kiwi.k/ampache
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/kiwi.k/ampache
/bin/echo "${vAppName} symlink is set."
;;

ldap)
/bin/rm -rf /srv/www/verb/blue.ldap
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/blue.ldap
/bin/echo "${vAppName} symlink is set."
;;

mediawiki)
/bin/rm -rf /srv/www/verb/ink.i/wiki
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/ink.i/wiki
/bin/echo "${vAppName} symlink is set."
;;

nextcloud)
/bin/rm -rf /srv/www/verb/blue.cloud
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/blue.cloud
/bin/echo "${vAppName} symlink is set."
;;

orangehrm)
/bin/rm -rf /srv/www/verb/red.r/hrm
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/red.r/hrm
/bin/echo "${vAppName} symlink is set."
;;

owa)
/bin/rm -rf /srv/www/verb/red.r/owa
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/red.r/owa
/bin/echo "${vAppName} symlink is set."
;;

# We don't need a web link for Go apps running on a port proxy from Nginx
# owncloud)
# /bin/rm -rf /srv/www/verb/blue.cloud
# /bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/blue.cloud
# /bin/echo "${vAppName} symlink is set."
# ;;

suitecrm)
/bin/rm -rf /srv/www/verb/red
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/red
/bin/echo "${vAppName} symlink is set."
;;

october.inkblog)
/bin/rm -rf /srv/www/verb/ink.i/blog
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/ink.i/blog
/bin/echo "${vAppName} symlink is set."
;;

wp.inkbb)
/bin/rm -rf /srv/www/verb/ink.i/bb
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/ink.i/bb
/bin/echo "${vAppName} symlink is set."
;;

wp.inkblog)
/bin/rm -rf /srv/www/verb/ink.i/blog
/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/verb/ink.i/blog
/bin/echo "${vAppName} symlink is set."
;;

*)
vappdomain=$(echo "${vAppName}" | /usr/bin/sed 's/wp.//')
if [ -d "/srv/www/domains/${vappdomain}" ]; then
	/bin/ln -sfn /srv/www/vapps/${vAppName} /srv/www/html/${vappdomain}
	/bin/echo "${vAppName} symlink is set."
else
	/bin/echo "Domain '${vappdomain}' is not yet ready for ${vAppName}. Do that first."
	exit 0
fi
;;

esac





if [ -e "/opt/verb/mods/setvapplinkon.after" ]; then . /opt/verb/mods/setvapplinkon.after; fi # Follows this script
