#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the inkNet Client key
## This is useful for getting the key to have it signed by the rink

# How to use:
## ./showinknetverberclientkey


usagenotes="This displays the inkNet Client key"
usageformat="showinknetverberclientkey"
usageexample="showinknetverberclientkey"
hierarchy=( secondary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( inknetnewverber2clientkey inknetnewverberclientkey )
useserfs=(  )
useconfigs=( inknet/rink.client.cnf )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showinknetverberclientkey.replace" ]; then . /opt/verb/mods/showinknetverberclientkey.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showinknetverberclientkey.before" ]; then . /opt/verb/mods/showinknetverberclientkey.before; fi # Precedes this script


# Check the config
if [ ! -f /opt/verb/conf/inknet/rink.client.cnf ]; then
/bin/echo "This is not yet connected to an Inker via inkNet."
exit 8; fi

# Include the config
. /opt/verb/conf/inknet/rink.client.cnf

# Display info
/bin/echo "Copy and paste the ENTIRE long key below, as is, into the \"Activate Client key\" area on the inkNet CA Inker:
"
/bin/cat /opt/ivapp/inknet/sailor/${clientSailor}/.ssh/in_cli_${clientName}_key.pub





if [ -e "/opt/verb/mods/showinknetverberclientkey.after" ]; then . /opt/verb/mods/showinknetverberclientkey.after; fi # Follows this script
