#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the inkDKIM information in OpenDKIM for a specific domain so it can be added to an opendkim txt record in the DNS file
## inkDKIM is the inkVerb method of handling OpenDKIM keys

# How to use:
## ./showinkdkim [ domain.tld ]


usagenotes="This displays the inkDKIM information in OpenDKIM for a specific domain so it can be added to an opendkim txt record in the DNS file"
usageformat="showinkdkim [ domain.tld ]"
usageexample="showinkdkim
showinkdkim [ domain.tld ]"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showinkdkim.replace" ]; then . /opt/verb/mods/showinkdkim.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showinkdkim.before" ]; then . /opt/verb/mods/showinkdkim.before; fi # Precedes this script


domain=$1


## Postfix vmail?
if [ "${ServerMailStatus}" = "VMAIL_SERVER" ]; then
  /usr/bin/echo $(/bin/cat /etc/opendkim/keys/${domain}/inkdkim.txt)

## Maddy email?
  elif [ "${ServerMailStatus}" = "MADDY_EMAIL_SERVER" ]; then
  /usr/bin/echo "default._domainkey IN TXT \"v=DKIM1; k=rsa; p=$(/usr/bin/cat /srv/email/maddy/dkim_keys/${domain}_default.dns | /usr/bin/grep -oP 'p=\K[^"]+')\""
fi



if [ -e "/opt/verb/mods/showinkdkim.after" ]; then . /opt/verb/mods/showinkdkim.after; fi # Follows this script
