#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the inkNet CA info to be used by a Client by inknetmakeverberclient

# How to use:
## ./showinknetcainfo


usagenotes="This displays the inkNet CA info to be used by a Client by inknetmakeverberclient"
usageformat="showinknetcainfo"
usageexample="showinknetcainfo"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( inknet/ca.verber.cnf servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showinknetcainfo.replace" ]; then . /opt/verb/mods/showinknetcainfo.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showinknetcainfo.before" ]; then . /opt/verb/mods/showinknetcainfo.before; fi # Precedes this script


# Check & include the config
if [ -f /opt/verb/conf/inknet/ca.verber.cnf ]; then
. /opt/verb/conf/inknet/ca.verber.cnf
 if [ -n "${iamCAhost}" ]; then
 /bin/echo "Here's the info for this CA Verber..."
 else
 /bin/echo "This is not a CA. No info to show.
First run: inknetmakeca
"
 exit 8
 fi
else
/bin/echo "This is not a CA. No info to show.
First run: inknetmakeca
"
exit 8
fi

# Include the config
. /opt/verb/conf/servernameip

# Display info
/bin/echo "
Host: ${iamCAhost}
URI:  ${IAMCAURI}
Name: ${iamCAname}
IPv4: ${ServerIPv4}
IPv6: ${ServerIPv6}
"





if [ -e "/opt/verb/mods/showinknetcainfo.after" ]; then . /opt/verb/mods/showinknetcainfo.after; fi # Follows this script
