#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the settings and info for this Verber
## This is useful for many things, including Clients that need name and IP to connect to it

# How to use:
## ./showverber


usagenotes="This displays the settings and info for this Verber"
usageformat="showverber"
usageexample="showverber"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip siteurilist servermailpath inklists/verberverno )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showverber.replace" ]; then . /opt/verb/mods/showverber.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showverber.before" ]; then . /opt/verb/mods/showverber.before; fi # Precedes this script


# Include the config
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath
. /opt/verb/conf/inklists/verberverno

# Display info
/bin/echo "IPv4: ${ServerIPv4}
IPv6: ${ServerIPv6}
Namespace: ${ServerName}
Primary TLD: ${ServerTLD}
Primary URI: ${nameURI}
Host: ${ServerTLD}
FQDN: ${hostURI}
Timezone: ${ServerTimeCity}, ${ServerTimeCity}
Update channel: ${ServerUpdateRepo}
Version: ${Verno}
Type: ${Vtype}

IT/SQL URL: ${itsqlTLD}
Email main domain URI: ${emailURI}
Email server URI: ${emailTLDURI}
Email Status: ${ServerMailStatus}
PFA path: ${ServerPFAPath}
inkMail path: ${ServerPOPath}"





if [ -e "/opt/verb/mods/showverber.after" ]; then . /opt/verb/mods/showverber.after; fi # Follows this script
