#! /bin/bash
#inkVerbSerf! verb.ink

# This displays the PHP vrsion
# Dependencies: vsftpd and ftpvip or ftpfiler, run: installvsftpd, and newftpvip and/or newftpfiler

# How to use:
## ./showphpver [ subdomain ]

usagenotes="This displays the PHP vrsion"
usageformat="showphpver [ subdomain ]"
usageexample="showphpver
showphpver [ subdomain ]"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showphpver.replace" ]; then . /opt/verb/mods/showphpver.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showphpver.before" ]; then . /opt/verb/mods/showphpver.before; fi # Precedes this script


phpDir=$(ls /etc/php)
phpVers=(${phpDir})
IFS=$'\n'
/bin/echo "${phpVers[*]}" | sort -nr | head -n1




if [ -e "/opt/verb/mods/showphpver.after" ]; then . /opt/verb/mods/showphpver.after; fi # Follows this script
