#!/bin/bash
#inkVerbSerf! verb.ink

# This displays the Verber service download URL

# How to use:
## ./showservepath


usagenotes="This displays the Verber service download URL"
usageformat="showservepath"
usageexample="showservepath"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/showservepath.replace" ]; then . /opt/verb/mods/showservepath.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/showservepath.before" ]; then . /opt/verb/mods/showservepath.before; fi # Precedes this script


. /opt/verb/conf/servernameip

/bin/echo "${ServerServePath}"





if [ -e "/opt/verb/mods/showservepath.after" ]; then . /opt/verb/mods/showservepath.after; fi # Follows this script
