#!/bin/bash
#inkVerbSerf! verb.ink

# This creates original verb folders to www/verb if they don't exist
## This does not remove any www/verb/ folders that should not be there; it only enforces that what webdirs should be there are so the server won't break
## This is used by setup and killvapp

# How to use:
## ./updatehtmlverbs


# Include the config
. /opt/verb/conf/servernameip
. /opt/verb/conf/siteurilist
. /opt/verb/conf/servermailpath

# Make the commute to where we will work
/bin/mkdir -p /srv/www/verb
cd /srv/www/verb || exit 6

# Remove broken links
/usr/bin/find -L . -name . -o -type d -prune -o -type l -exec rm {} +

# Initial sites
/bin/rm -rf 0sitedefaultInProgress
/bin/cp -r /opt/verb/conf/lib/www/0sitedefaultInProgress .
/bin/chmod -R 750 0sitedefaultInProgress
/bin/rm -rf vsslsitedefault
/bin/cp -r 0sitedefaultInProgress vsslsitedefault
/bin/rm -rf 0ne
/bin/mkdir 0ne
/bin/echo "<?php header(\"Location: http://${inkURI}\"); die(); ?>" > /srv/www/verb/0ne/index.php
/bin/chmod -R 750 0ne

# Block web folder listing
/bin/echo "Options -Indexes" >> /srv/www/verb/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/verb/0ne/.htaccess
/bin/echo "Options -Indexes" >> /srv/www/verb/0sitedefaultInProgress/.htaccess

# Verb sites
if [ ! -e "${itsqlTLD}.sql" ]; then /bin/cp -r 0ne ${itsqlTLD}.sql; fi
if [ ! -e "email" ]; then /bin/cp -r 0ne email; fi
if [ ! -e "email.e" ]; then /bin/cp -r 0ne email.e; fi
if [ ! -e "one" ]; then /bin/cp -r 0ne one; fi
if [ ! -e "one.o" ]; then /bin/cp -r 0ne one.o; fi
if [ ! -e "ink" ]; then /bin/cp -r 0sitedefaultInProgress ink; fi
if [ ! -e "ink.i" ]; then /bin/cp -r 0ne ink.i; fi
if [ ! -e "blue" ]; then /bin/cp -r 0ne blue; fi
if [ ! -e "blue.b" ]; then /bin/cp -r 0ne blue.b; fi
if [ ! -e "blue.cloud" ]; then /bin/cp -r 0ne blue.cloud; fi
if [ ! -e "blue.base" ]; then /bin/cp -r 0ne blue.base; fi
if [ ! -e "blue.cab" ]; then /bin/cp -r 0ne blue.cab; fi
if [ ! -e "blue.kit" ]; then /bin/cp -r 0ne blue.kit; fi
if [ ! -e "blue.ldap" ]; then /bin/cp -r 0ne blue.ldap; fi
if [ ! -e "vip" ]; then /bin/cp -r 0ne vip; fi
if [ ! -e "vip.v" ]; then /bin/cp -r 0ne vip.v; fi
if [ ! -e "vip.files" ]; then /bin/cp -r 0ne vip.files; fi
if [ ! -e "kiwi" ]; then /bin/cp -r 0ne kiwi; fi
if [ ! -e "kiwi.k" ]; then /bin/cp -r 0ne kiwi.k; fi
if [ ! -e "kiwi.sound" ]; then /bin/cp -r 0ne kiwi.sound; fi
if [ ! -e "red" ]; then /bin/cp -r 0ne red; fi
if [ ! -e "red.r" ]; then /bin/cp -r 0ne red.r; fi
if [ ! -e "red.crm" ]; then /bin/cp -r 0ne red.crm; fi
if [ ! -e "red.hrm" ]; then /bin/cp -r 0ne red.hrm; fi

# Serve URI
/bin/rm -rf /srv/www/verb/${ServerServeTLD}.serve
/bin/mkdir -p /srv/www/verb/${ServerServeTLD}.serve/${ServerServeDir}
/bin/echo "Options -Indexes" >> /srv/www/verb/${ServerServeTLD}.serve/${ServerServeDir}/.htaccess
/bin/echo "<?php header(\"HTTP/1.1 301 Moved Permanently\"); header(\"Location: http://${nameURI}\"); die(); ?>" > /srv/www/verb/${ServerServeTLD}.serve/index.php

# Email
## Roundcube
if [ "${ServerRCPath}" != "RC_NOT_INSTALLED " ] && [ -d "/srv/www/email/roundcube" ]; then
  if [ ! -e "/srv/www/verb/${emailTLD}.box/${ServerRCPath}" ]; then
    /bin/mkdir -p /srv/www/verb/${emailTLD}.box
    /bin/echo "Options -Indexes" >> /srv/www/verb/${emailTLD}.box/.htaccess
    /usr/bin/ln -sfn /srv/www/email/roundcube "/srv/www/verb/${emailTLD}.box/${ServerRCPath}"
    /bin/chmod -R 750 /srv/www/verb/${emailTLD}.box
  fi
fi
## PFA
 if [ "${ServerPFAPath}" != "PFA_NOT_INSTALLED " ] && [ -d "/srv/www/email/postfixadmin" ]; then
  if [ ! -e "/srv/www/verb/${emailTLD}.po/${ServerPFAPath}" ]; then
    /bin/mkdir -p /srv/www/verb/${emailTLD}.po
    /bin/echo "Options -Indexes" >> /srv/www/verb/${emailTLD}.po/.htaccess
    /usr/bin/ln -sfn /srv/www/email/postfixadmin "/srv/www/verb/${emailTLD}.po/${ServerPFAPath}"
    /bin/chmod -R 750 /srv/www/verb/${emailTLD}.po
  fi
fi
## Box
 if [ "${ServerBoxPath}" != "BOX_NOT_INSTALLED " ] && [ -d "/srv/www/email/box" ]; then
  if [ ! -e "/srv/www/verb/${emailTLD}.box/${ServerBoxPath}" ]; then
    /bin/mkdir -p /srv/www/verb/${emailTLD}.box
    /bin/echo "Options -Indexes" >> /srv/www/verb/${emailTLD}.box/.htaccess
    /usr/bin/ln -sfn /srv/www/email/box "/srv/www/verb/${emailTLD}.po/${ServerBoxPath}"
    /bin/chmod -R 750 /srv/www/verb/${emailTLD}.box
  fi
fi

# Own
/bin/chown -R www:www /srv/www/verb
/bin/chmod -R 750 ${itsqlTLD}.sql
/bin/chmod -R 750 ${ServerServeTLD}.serve
/bin/chmod -R 750 email
/bin/chmod -R 750 email.e
/bin/chmod -R 750 one
/bin/chmod -R 750 one.o
/bin/chmod -R 750 ink
/bin/chmod -R 750 ink.i
/bin/chmod -R 750 blue
/bin/chmod -R 750 blue.b
/bin/chmod -R 750 blue.cloud
/bin/chmod -R 750 blue.base
/bin/chmod -R 750 blue.cab
/bin/chmod -R 750 blue.kit
/bin/chmod -R 750 blue.ldap
/bin/chmod -R 750 vip
/bin/chmod -R 750 vip.v
/bin/chmod -R 750 vip.files
/bin/chmod -R 750 kiwi
/bin/chmod -R 750 kiwi.k
/bin/chmod -R 750 kiwi.sound
/bin/chmod -R 750 red
/bin/chmod -R 750 red.r
/bin/chmod -R 750 red.crm
/bin/chmod -R 750 red.hrm

# Finish
/bin/echo "Done. Except for any installed apps, any missing Verber html folders have been set to original setup state."




if [ -e "/opt/verb/mods/updatehtmlverbs.after" ]; then . /opt/verb/mods/updatehtmlverbs.after; fi # Follows this script
