#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and updates the Verber™ core files, including serfs and inklists
## This also runs scripts that make other changes that may affect the Verber

# How to use:
## ./updateverber


usagenotes="This downloads and updates the Verber™ core files, including serfs and inklists"
usageformat="updateverber"
usageexample="updateverber"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=( servernameip )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/updateverber.replace" ]; then . /opt/verb/mods/updateverber.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/updateverber.before" ]; then . /opt/verb/mods/updateverber.before; fi # Precedes this script


# Include the config
if [ -d "/opt/verb/inst" ]; then
  ## This allows updates on a -premade or -made verber
  ServerUpdateOrg="inkverb"
  ServerUpdateRepo="verb-update"
else
  ## This is for updates on a setup verber
  . /opt/verb/conf/servernameip
fi

# Download the latest checked version from GitHub
cd /opt/verb/ || exit 6
/usr/bin/git clone https://github.com/${ServerUpdateOrg}/${ServerUpdateRepo}

# Run the update script
/bin/chmod 750 /opt/verb/${ServerUpdateRepo}/update
/opt/verb/${ServerUpdateRepo}/update
wait

# Remove the entire updater
/bin/rm -rf /opt/verb/${ServerUpdateRepo}





if [ -e "/opt/verb/mods/updateverber.after" ]; then . /opt/verb/mods/updateverber.after; fi # Follows this script
