#!/bin/bash
#inkVerbSerf! verb.ink

# This downloads and updates the Verber™ core files, including serfs and inklists
## If the verbdomain mod is in effect, it will automatically run again at the end of this update
## This also runs scripts that make other changes that may affect the Verber
## This is intended for updates for versions retired from the main updater

# How to use:
## ./updateverberlegacy


usagenotes="This downloads and updates the Verber™ core files, including serfs and inklists"
usageformat="updateverberlegacy"
usageexample="updateverberlegacy"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( inkget vtxzout )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/updateverberlegacy.replace" ]; then . /opt/verb/mods/updateverberlegacy.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/updateverberlegacy.before" ]; then . /opt/verb/mods/updateverberlegacy.before; fi # Precedes this script


# Download and unpack the latest checked version from the Inkver repo
cd /opt/verb/ || exit 6
/opt/verb/serfs/inkget verber.update.legacy; wait
/opt/verb/serfs/vtxzout verber.update.legacy; wait

# Run the update script
/opt/verb/verber.update.legacy/update; wait

# Remove the entire updater
/bin/rm -rf /opt/verb/verber.update.legacy





if [ -e "/opt/verb/mods/updateverberlegacy.after" ]; then . /opt/verb/mods/updateverberlegacy.after; fi # Follows this script
