#!/bin/bash
#inkVerbSerf! verb.ink

# This compresses a directory into a .tar.xz file, renamed as a .txz file, all in the PWD
## The resulting .txz file can simply be renamed to .tar.xz and be used accordingly
## This alternate extention name is intended to prevent tampering and to maintain consistency within inkVerb deployment

# The directory MUST be in the PWD!
# This will OVERWRITE any .txz destination file by the same name!

# How to use:
## ./vtxzin [directory]

# Eg:
## ./vtxzin mystuff

if [ -e "/opt/verb/mods/vtxzin.replace" ]; then . /opt/verb/mods/vtxzin.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/vtxzin.before" ]; then . /opt/verb/mods/vtxzin.before; fi # Precedes this script


dir=$1

/usr/bin/echo "Creating .txz archive file..."
/bin/tar c ${dir} | /usr/bin/xz -v > ${dir}.tar.xz
/bin/mv ${dir}.tar.xz ${dir}.txz
/usr/bin/echo "Done."




if [ -e "/opt/verb/mods/vtxzin.after" ]; then . /opt/verb/mods/vtxzin.after; fi # Follows this script
