#!/bin/bash
#inkVerbSerf! verb.ink

# This compresses a directory into a .tar.xz file, renamed as a .txz file, all in the PWD
## The resulting .txz file can simply be renamed to .tar.xz and be used accordingly
## This alternate extention name is intended to prevent tampering and to maintain consistency within inkVerb deployment

# The directory MUST be in the PWD!
# This will OVERWRITE any .txz destination file by the same name!

# How to use:
## ./vtxzin [ directory ] [ outfile - optional, default DIR.txz ]

# Eg:
## ./vtxzin mystuff
## ./vtxzin mystuff /mnt/hdd/vip/mystuff.txz



usagenotes="This compresses a directory into a .tar.xz file, renamed as a .txz file, all in the PWD"
usageformat="vtxzin [ directory ]"
usageexample="vtxzin mystuff"
hierarchy=( secondary )
vsetnames=( "Directory" )
vsettypes=( isazAZ09lines )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=( backup backupnextcloud backupnextcloudrestore backuprestore backupvmail inknetpackclientpkg )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/vtxzin.replace" ]; then . /opt/verb/mods/vtxzin.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/vtxzin.before" ]; then . /opt/verb/mods/vtxzin.before; fi # Precedes this script


dir=$1
out="${2:-${dir}.txz}"

/usr/bin/echo "Creating .txz archive file..."
# -h: store symlink (and inkDrive /mnt/{h|s}dd) targets as real files in the archive tree
set -o pipefail
/bin/tar -h -c "${dir}" | /usr/bin/xz -v > "${out}.part"
e="$?"
set +o pipefail
if [ "$e" != "0" ]; then
  /usr/bin/rm -f "${out}.part"
  exit "$e"
fi
/bin/mv "${out}.part" "${out}"
/usr/bin/echo "Done."




if [ -e "/opt/verb/mods/vtxzin.after" ]; then . /opt/verb/mods/vtxzin.after; fi # Follows this script
