#!/bin/bash
#inkVerbSerf! verb.ink

# This enables cgi for a domain

# How to use:
## ./webcgi on [domain.tld or subdomain.domain.tld]
## ./webcgi off [domain.tld or subdomain.domain.tld]


domain=$2

. /opt/verb/conf/servertype

# Check if it exists
if [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then
	if [ ! -e "/opt/verb/conf/webserver/sites-available/httpd/${domain}.conf" ]; then
		/usr/bin/echo "${domain} not found."
		exit 8
	fi
fi

if [ ${ServerType} = "lemp" ]; then
	/bin/echo "CGI not allowed on LEMP servers."
	exit 9

elif [ ${ServerType} = "lamp" ] || [ ${ServerType} = "laemp" ]; then

	if [ "$1" = "on" ]; then

		# Apache
		## Check to see if "fixhttps" has already been added
		if /bin/grep -q "Options Indexes FollowSymLinks MultiViews Execcgi" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
			/bin/systemctl restart httpd; wait
			/bin/echo "${domain} already has the CGI enabled. The server was just reloaded so the site should work."
		else
			/bin/sed -i "s/Options Indexes FollowSymLinks MultiViews/Options Indexes FollowSymLinks MultiViews Execcgi\nAddHandler cgi-script .cgi/" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
			/bin/systemctl restart httpd; wait
			/bin/echo "CGI enabled for ${domain}."
		fi

	elif [ "$1" = "off" ]; then

		# Apache
		## Check to see if "fixhttps" has already been added
		if ! /bin/grep -q "Options Indexes FollowSymLinks MultiViews Execcgi" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
			/bin/systemctl restart httpd; wait
			/bin/echo "${domain} already has the CGI disabled. The server was just reloaded so the site should work."
		else
			/bin/sed -i "s/Options Indexes FollowSymLinks MultiViews Execcgi/Options Indexes FollowSymLinks MultiViews/" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
			/bin/sed -i "/AddHandler cgi-script .cgi/d" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
			/bin/systemctl restart httpd; wait
			/bin/echo "CGI disabled for ${domain}."
		fi

	fi

fi




if [ -e "/opt/verb/mods/webcgi.after" ]; then . /opt/verb/mods/webcgi.after; fi # Follows this script
