#!/bin/bash
#inkVerbSerf! verb.ink

# This adds the www subdomain prefix to a domain's Apache config.
## This could be set to run automatically at some point, so may not be necessary independently.
## This may eventually be depreciated altogether
## This serf is kept in service because the www fix may not be necessary, especially on secure-based domains or subdomains and an untested possibility remains of breaking other serfs if it is not run deliberately. Besides, needing "www" in front of domains ended in the year 2000. It could also be fixed via a DNS cname.

# How to use:
## ./webwww on [domain.tld or subdomain.domain.tld]
## ./webwww off [domain.tld or subdomain.domain.tld]


domain=$2

. /opt/verb/conf/servertype

if [ "$1" = "on" ]; then

	if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
		# Nginx
		## Check to see if "fixwww" has already been added
		if /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf; then
			/bin/systemctl restart nginx; wait
			/bin/echo "${domain} already has the www subdomain fix. The server was just reloaded so the site should work."
		else

			## Then add the config lines if it doesn't.
			/bin/echo "##INKWWWFIX=fixed
	# Fixes www
	server {
	  server_name www.${domain};
	  return 301 \$scheme://${domain}\$request_uri;
	}
	##verbFIXwww" >> /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf
			/bin/systemctl restart nginx; wait

			/bin/echo "${domain} now has the www subdomain fix and is ready to go."
		fi

	elif [ ${ServerType} = "lamp" ]; then
		# Check to see if "fixwww" has already been added
		if /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
			/usr/bin/systemctl restart httpd
			/bin/echo "${domain} already has the www subdomain fix. The server was just reloaded so the site should work."
		else

			## Then add the config lines if it doesn't.
			/bin/echo "##INKWWWFIX=fixed
	# Fixes www
	<VirtualHost *:80>
	  ServerName www.${domain}
	  Redirect permanent / http://${domain}/
	</VirtualHost>
	<IfModule mod_ssl.c>
	  <VirtualHost _default_:443>
	    ServerName www.${domain}
	    Redirect permanent / https://${domain}/
	  </VirtualHost>
	</IfModule>
	##verbFIXwww" >> /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
			/usr/bin/systemctl restart httpd

			/bin/echo "${domain} now has the www subdomain fix and is ready to go."
		fi

	fi

elif [ "$1" = "off" ]; then

	if [ ${ServerType} = "lemp" ] || [ ${ServerType} = "laemp" ]; then
		# Nginx
		## Verify that the "fixwww" has been added
		if ! /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf; then
			/bin/echo "${domain} doesn't have the www subdomain fix. Nothing to do."
		fi

		## Remove the old settings
		/bin/sed -i '/^##INKWWWFIX=fixed/,/^##verbFIXwww/{/^##INKWWWFIX=fixed/!{/^##verbFIXwww/!d}}' /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf
		/bin/sed -i '/##INKWWWFIX=fixed/d' /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf
		/bin/sed -i '/##verbFIXwww/d' /opt/verb/conf/webserver/sites-available/nginx/${domain}.conf
		/bin/systemctl restart nginx; wait

		# Finish
		/bin/echo "${domain} the www subdomain fix has been removed."


	elif [ ${ServerType} = "lamp" ]; then
		# Verify that the "fixwww" has been added
		if ! /bin/grep -q "##INKWWWFIX=fixed" /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf; then
			/bin/echo "${domain} doesn't have the www subdomain fix. Nothing to do."
		fi

		## Remove the old settings
		/bin/sed -i '/^##INKWWWFIX=fixed/,/^##verbFIXwww/{/^##INKWWWFIX=fixed/!{/^##verbFIXwww/!d}}' /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
		/bin/sed -i '/##INKWWWFIX=fixed/d' /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
		/bin/sed -i '/##verbFIXwww/d' /opt/verb/conf/webserver/sites-available/httpd/${domain}.conf
		/usr/bin/systemctl restart httpd

		# Finish
		/bin/echo "${domain} the www subdomain fix has been removed."

	fi

fi




if [ -e "/opt/verb/mods/webwww.after" ]; then . /opt/verb/mods/webwww.after; fi # Follows this script
