#!/bin/bash
#inkVerbSerf! verb.ink

# This sets up a WordPress vapp .htaccess file to be "normal", NOT for multisite

# How to use:
## ./wphtaccess [ domain.tld ]

# Eg:
## ./wphtaccess inkisaverb.com
## ./wphtaccess mysubsite.inkisaverb.com


usagenotes="This sets up a WordPress vapp .htaccess file to be \"normal\", NOT for multisite"
usageformat="wphtaccess [ domain.tld ]"
usageexample="wphtaccess inkisaverb.com
wphtaccess mysubsite.inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/wphtaccess.replace" ]; then . /opt/verb/mods/wphtaccess.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/wphtaccess.before" ]; then . /opt/verb/mods/wphtaccess.before; fi # Precedes this script


wpdomain=$1

# Remove the old WordPress declarations
/bin/sed -i '/^# BEGIN WordPress*/,/^# END WordPress/d' /srv/www/vapps/wp.${wpdomain}/.htaccess

# Put in the new .htaccess settings
/bin/echo "# BEGIN WordPress ##inkVerb
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress" >> /srv/www/vapps/wp.${wpdomain}/.htaccess

# Finish
/bin/echo ".htaccess file for http://${wpdomain} is set to normal, NOT WP Multisite, use."





if [ -e "/opt/verb/mods/wphtaccess.after" ]; then . /opt/verb/mods/wphtaccess.after; fi # Follows this script
