#!/bin/bash
#inkVerbSerf! verb.ink

# This unsets up a WordPress vapp for multisite after it has been setup

# How to use:
## ./wpmuunsetconfig [ domain.tld ]

# Eg:
## ./wpmusetconfig inkisaverb.com
## ./wpmusetconfig mysubsite.inkisaverb.com


usagenotes="This unsets up a WordPress vapp for multisite after it has been setup"
usageformat="wpmuunsetconfig [ domain.tld ]"
usageexample="wpmusetconfig inkisaverb.com
wpmusetconfig mysubsite.inkisaverb.com"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/wpmuunsetconfig.replace" ]; then . /opt/verb/mods/wpmuunsetconfig.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/wpmuunsetconfig.before" ]; then . /opt/verb/mods/wpmuunsetconfig.before; fi # Precedes this script


wpdomain=$1

# Check the configs are ready
if /bin/grep -Fq "define( 'WP_ALLOW_MULTISITE', true );" /srv/www/html/${wpdomain}/wp-config.php; then
/bin/echo "Proceeding..."; else
/bin/echo "Multisite isn't even setup, dufis. Run: wpmuseton"
exit 8; fi

# Check if already set
if /bin/grep -Fq "define('MULTISITE', true);" /srv/www/html/${wpdomain}/wp-config.php; then
/bin/echo "Proceeding..."; else
/bin/echo "Multisite is ready to install, but hasn't been setup. To set it up use: wpmusetconfig"
exit 8; fi

# Delete the settings
## Subdomain install
/bin/sed -i "/* Multisite Settings via inkVerb */d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('MULTISITE', true);/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('MULTISITE', false);/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('SUBDOMAIN_INSTALL', true);/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('DOMAIN_CURRENT_SITE', '${wpdomain}');/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('PATH_CURRENT_SITE', '\/');/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('SITE_ID_CURRENT_SITE', 1);/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/define('BLOG_ID_CURRENT_SITE', 1);/d" /srv/www/html/${wpdomain}/wp-config.php
/bin/sed -i "/* Multisite inkVerb End */d" /srv/www/html/${wpdomain}/wp-config.php

## Finish
/bin/echo "WP Multisite for http://${wpdomain} is now off. You may need to log in again."





if [ -e "/opt/verb/mods/wpmuunsetconfig.after" ]; then . /opt/verb/mods/wpmuunsetconfig.after; fi # Follows this script
