#!/bin/bash
#inkVerbSerf! verb.ink

# This adds/updates the Ryuki child theme of Ryu to an existing WordPress installation

# How to use:
## ./wpthemeryuki [ domain.tld or folder ]


usagenotes="This adds/updates the Ryuki child theme of Ryu to an existing WordPress installation"
usageformat="wpthemeryuki [ domain.tld or folder ]"
usageexample="wpthemeryuki
wpthemeryuki [ domain.tld or folder ]"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/wpthemeryuki.replace" ]; then . /opt/verb/mods/wpthemeryuki.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/wpthemeryuki.before" ]; then . /opt/verb/mods/wpthemeryuki.before; fi # Precedes this script


domain=$1


# Check if installed
if [ ! -d /srv/www/html/${domain}/wp-content ]; then
 if [ ! -d /srv/www/html/${domain} ]; then
 /bin/echo "${domain} is not even installed. That domain needs to be installed and have WordPress. Do those, then try again."
 exit 8
 else
 /bin/echo "${domain} is installed, but does not have WordPress. Install WordPress to that domain, then try again."
 exit 8
 fi
fi

# Do the Git clone
cd /srv/www/html/${domain}/wp-content/themes || exit 6
git clone https://github.com/cfinke/Ryuki.git

# Finish
/bin/echo "Ryuki theme installed and updated."





if [ -e "/opt/verb/mods/wpthemeryuki.after" ]; then . /opt/verb/mods/wpthemeryuki.after; fi # Follows this script
