#!/bin/bash
#inkVerbSerf! verb.ink

# This unlinks a domain to it's wp location in vapps
## It is useful to return a domain to its www/domains space when turning off or no longer using a wordpress installation
## This does NOT turn off or uninstall wordpress from the domain

# How to use:
## ./wpunlinkdomain [ full domain of WP site ]


usagenotes="This unlinks a domain to it's wp location in vapps"
usageformat="wpunlinkdomain [ full domain of WP site ]"
usageexample="wpunlinkdomain
wpunlinkdomain [ full domain of WP site ]"
hierarchy=( primary )
vsetnames=( "Domain" )
vsettypes=( isDomain )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=(  )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/wpunlinkdomain.replace" ]; then . /opt/verb/mods/wpunlinkdomain.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/wpunlinkdomain.before" ]; then . /opt/verb/mods/wpunlinkdomain.before; fi # Precedes this script


domain=$1

/bin/rm -f /srv/www/html/${domain}
/bin/ln -s /srv/www/domains/${domain} /srv/www/html/${domain}
/bin/chown -R www:www /srv/www/html/${domain}





if [ -e "/opt/verb/mods/wpunlinkdomain.after" ]; then . /opt/verb/mods/wpunlinkdomain.after; fi # Follows this script
