#!/bin/bash
#inkVerbSerf! verb.ink

# This unlinks a domain to it's wp location in vapps
## It is useful to return a domain to its www/domains space when turning off or no longer using a wordpress installation
## This does NOT turn off or uninstall wordpress from the domain

# How to use:
## ./wpunlinkdomain [full domain of WP site]


domain=$1

/bin/rm -f /srv/www/html/${domain}
/bin/ln -s /srv/www/domains/${domain} /srv/www/html/${domain}
/bin/chown -R www:www /srv/www/html/${domain}





if [ -e "/opt/verb/mods/wpunlinkdomain.after" ]; then . /opt/verb/mods/wpunlinkdomain.after; fi # Follows this script
