#!/bin/bash
#inkVerbSerf! verb.ink

# This backs up all wordpress vapps into the vip folder

# How to use:
## ./wpvappbackupall


usagenotes="This backs up all wordpress vapps into the vip folder"
usageformat="wpvappbackupall"
usageexample="wpvappbackupall"
hierarchy=( primary )
vsetnames=(  )
vsettypes=(  )
voptnames=(  )
vopttypes=(  )
voptflags=(  )
voptflagpurpose=(  )
dependencyinstall=(  )
prerequesite=(  )
usedby=(  )
useserfs=( backup )
useconfigs=(  )
if [ -n "$infoINKonly" ] && [ "$infoINKonly" = "true" ]; then return 0; fi # Must have for proper usage to not run the full serf
if [ -e "/opt/verb/mods/wpvappbackupall.replace" ]; then . /opt/verb/mods/wpvappbackupall.replace; return 0; fi # Replaces this script
if [ -e "/opt/verb/mods/wpvappbackupall.before" ]; then . /opt/verb/mods/wpvappbackupall.before; fi # Precedes this script


cd /srv/www/vapps || exit 6
for vapp in wp.*; do
/opt/verb/serfs/backup $vapp 123 -nl
done





if [ -e "/opt/verb/mods/wpvappbackupall.after" ]; then . /opt/verb/mods/wpvappbackupall.after; fi # Follows this script
