#!/bin/sh
## This is a config file for other verb scripts

ServerName="ink"
ServerHost="1verb"
ServerTLD="ink"
SITEIP="104.248.208.98"
ServerIPv6="2604:a880:2:d0:53:1001::"
ServerTimeCity="America/Phoenix"
ServerUpdateRepo="verb-dev-update"

ServerServeTLD="ink"
ServerServeDir="Ion9yg"
ServerServePath="serve.ink.verb.ink/Ion9yg"
ServerExpIPv6="2604:a880:0002:00d0:0000:0000:0053:1001"
ServerARPAIPv4="98.208.248.104.in-addr.arpa"
ServerARPAIPv6="1.0.0.1.3.5.0.0.0.0.0.0.0.0.0.0.0.d.0.0.2.0.0.0.0.8.8.a.4.0.6.2.ip6.arpa"
SITEINKERDNS="ns0.ink.verb.ink"
SITEINKERIP4="NOT_SET"
SITEINKERIP6="NOT_SET"
SITE2INKERDNS="ns1.inkisaverb.com"
SITE2INKERIP4="NOT_SET"
SITE2INKERIP6="NOT_SET"

