#!/bin/bash
#inkVerbMaker! verb.ink

# This updates:
## Linux & packages via pacman
## AUR Packages via yay
## Verber scripts via verb/inst/update-pre-setup

# Eg:
## ./update-snapshot
## ./update-snapshot inkverb # Default
## ./update-snapshot otherorg


if [ -z "$1" ]; then
  ServerUpdateOrg="inkverb"
else
  ServerUpdateOrg="$1"
fi

/opt/verb/inst/update-pre-setup ${ServerUpdateOrg}
/usr/bin/pacman -Sy archlinux-keyring --noconfirm
/usr/bin/pacman -Syyu --noconfirm --needed
/usr/bin/pacman -Qdt --noconfirm
/usr/bin/pacman -Scc --noconfirm
/usr/bin/su worker -c '/usr/bin/yay -Syyu --noconfirm --needed'
/usr/bin/su worker -c '/usr/bin/yay -Scc --noconfirm'
