#!/bin/bash
#inkVerbInk! verb.ink
if [ "$(id -u)" -ne 0 ]; then echo "The 'ink' command must be run with sudo or as root."; exit 0; fi

# This is the "Inkman" who manages a Verber by interacting with "Serfs", "Knights", the "Donjon", et cetera.
## This uses "ink" to execute commands relevant to a Verber, similarly to how "apt", "yum", and "pacman" manage packages.
## ink streamlines help queries, checks for required parameters, and provides a production-worthy layer of "fool-proofing".
## ink retrieves available options, tools, settings, notes, parameter requirements, et cetera from the Verber assets themselves using functions & tools like grep and occasionally a central index. This is partially why formatting Serfs is important.

# How to use:
## ink action schema setting1 setting2 setting3 setting4 -o option1 option2 option3

# Put the path to the setting file here
export InkSet=/opt/verb/ink/ink.set
## Include the settings & functions
. ${InkSet}
. ${iDir}/ink.functions

# Settings, Options, and input variables
## Parse arguments
export action="${1}"
export schema="${2}"
export helpopt="${3}"
shift 2
allargs="$*"

# Help?
## Ink
if [ "${action}" == "-h" ] || [ "${action}" == "--help" ]; then
usageInk
exit 0; fi

## Action help
if [ "${schema}" == "-h" ] || [ "${schema}" == "--help" ]; then
usageSur "${action}"
exit 0; fi

## Schema help
if [ "${helpopt}" == "-h" ] || [ "${helpopt}" == "--help" ]; then
${Felt}/${action}${schema}.ink ${allargs} # for .ink flag help
usageSur "${action}${schema}" # for .md extended help
exit 0; fi

# Lists
## Ink
if [ "${action}" == "-a" ] || [ "${action}" == "--actions" ]; then
getActions
exit 0; fi

## Action
if [ "${schema}" == "-s" ] || [ "${schema}" == "--schemas" ]; then
getSchemas "${action}"
exit 0; fi

# Run the .ink file
if [ -f "${Felt}/${action}${schema}.ink" ]; then
  ${Felt}/${action}${schema}.ink ${allargs}
else
  echo "Action and schema unknown. Use: ink -h"
fi
